### ISSUE TITLE
Create Russian readme/FAQ

### ISSUE THREAD

**Issue by buybackoff** [finsight/QUIKSharp#100]
Label `question` - собрать самые простые вещи: как подключиться, как отправить заявку, как получить поток и историю котировок...

**Comment by Pr0phet1c** [comment]
Я вроде как раз для этого демонстрационное приложение сделал. Там все это есть.

**Comment by buybackoff** [comment]
Нужно кратко написать текстом хотя бы путь от запуска до сделки. Дополнительно FAQ по всем issues, помеченным тагом question. Потом все эти issues закрою, а сейчас они служам как документация.

**Comment by buybackoff** [comment]
https://github.com/finsight/QUIKSharp/blob/master/README.RU.md
