### ISSUE TITLE
Во многих таблицах числа в формате строк

### ISSUE THREAD

**Issue by buybackoff** [finsight/QUIKSharp#102]
Например Portfolio, PortfolioEx. Посмотрел в QLUA документации, они правда так возвращают. Но это так неудобно везде использовать `decimal.TryParse` если там всегда нормальные числа. Если там особый формат, можно добавить специальный JsonConverter. А так на стороне Lua можно умножить каждое значение на 1, и на стороне C# просто сменить тип (хотя это муторно в Луа, конвертор с TryParse и одинаковый для всех полей аттрибут в C# проще).

**Comment by Pr0phet1c** [comment]
Да, я тоже обратил на это внимание, и в целом согласен с Вашей позицией, но нет уверенности, что это правильно с точки зрения ссылок на QLua. Ведь человек, привыкший к QLua и часто обращающийся к соответствующей справке в квике, будет думать, что там ДОЛЖНО быть текстовое значение. Не внесет ли это путаницу для понимания потенциальными пользователями?

**Comment by buybackoff** [comment]
Согласен, надо придерживаться изначальной цели "повторить API Lua" без дополнительных вещей.
