### ISSUE TITLE
Python 

### ISSUE THREAD

**Issue by sm00vik** [finsight/QUIKSharp#103]
Доброго дня. 
У кого-нибудь есть опыт связки библиотеки с Python?
Вообще, это принципиально возможно?
Спасибо.

**Comment by Pr0phet1c** [comment]
-

**Comment by buybackoff** [comment]
Можете посмотреть мой проект https://github.com/buybackoff/Ractor
Там показано, как можно вызывать любой код на Питоне через Редис.

Без Редиса есть закоментированный пример на этой [строке](https://github.com/buybackoff/Ractor/blob/master/src/Ractor/PythonActor.cs#L36). Идея - запускать процесс Питона и давать ему данные через shell. [Здесь](https://github.com/mbraceproject/MBrace.StarterKit/blob/b994f09c03fe87e98ea8b8515033d01f7cc9456e/HandsOnTutorial.FSharp/examples/200-launching-python-example.fsx) и [тут](http://stackoverflow.com/questions/11779143/how-to-run-a-python-script-from-c/41320876#41320876) дополнительные примеры.

**Comment by sm00vik** [comment]
Спасибо еще раз, посмотрю.

**Comment by buybackoff** [comment]
Кстати, не знаю для чего Вам это нужно - но если для сложного анализа данных, то история с R гораздо гораздо проще и надежнее: https://github.com/jmp75/rdotnet

**Comment by buybackoff** [comment]
Закрываю, так как не связано непосредственно с Q#
