### ISSUE TITLE
Не получается реализовать linked StopOrder. В чем засада?   (Сделал...)

### ISSUE THREAD

**Issue by tangous** [finsight/QUIKSharp#104]
Добавил в Datastructures

` private  StopOrderType  GetStopOrderType(int code)
       {

            switch   (code)
            {
                case 1:
                    return StopOrderType.StopLimit;
                case 3:
                    return StopOrderType.StopLimitWithLinkedOrder;
                case 6:
                    return StopOrderType.TakeProfit;
                default:
                    return StopOrderType.NotImplemented;
            }
        }
`
Добавил в функции

` private StopOrderKind ConvertStopOrderType(StopOrderType stopOrderType)

        {
            switch (stopOrderType)
            {
                case StopOrderType.StopLimit:
                    return StopOrderKind.SIMPLE_STOP_ORDER;
                case StopOrderType.StopLimitWithLinkedOrder:
                    return StopOrderKind.WITH_LINKED_LIMIT_ORDER;
                case StopOrderType.TakeProfit:
                    return StopOrderKind.TAKE_PROFIT_STOP_ORDER;
                default:
                    throw new Exception("Not implemented stop order type: " + stopOrderType);
            }
        }
`
Ну и, соответственно в типы....
Все равно неопознанная ошибка. Связанный СтопОрдер делать не желает.

**Comment by tangous** [comment]
Вопрос снят. Просто не хватало полей в
`
 public async Task<long> CreateStopOrder(StopOrder stopOrder)
        {

            Transaction newStopOrderTransaction = new Transaction
            {
                ACTION = TransactionAction.NEW_STOP_ORDER,
                ACCOUNT = stopOrder.Account,
                CLASSCODE = stopOrder.ClassCode,
                CLIENT_CODE = stopOrder.ClientCode,
                SECCODE = stopOrder.SecCode,
                EXPIRY_DATE = "GTC",//до отмены
                STOPPRICE = stopOrder.ConditionPrice,
                PRICE = stopOrder.Price,
                **LINKED_ORDER_PRICE = stopOrder.coOrderPrice,**
                QUANTITY = stopOrder.Quantity,
                STOP_ORDER_KIND = ConvertStopOrderType(stopOrder.StopOrderType),
                OPERATION = stopOrder.Operation == Operation.Buy?TransactionOperation.B : TransactionOperation.S,
                **KILL_IF_LINKED_ORDER_PARTLY_FILLED = stopOrder.StopFlags**
            };
`
И соответственно описания stopOrder.coOrderPrice, 
stopOrder.StopFlags (пришлось сделать YesNo, хотя это не совсем верно...)

**Comment by buybackoff** [comment]
А зачем переоткрыли, если вопрос решен?

**Comment by tangous** [comment]
Да просто в кнопках запутался.

**Comment by buybackoff** [comment]
Что значит "пришлось сделать YesNo"? Что-то у нас не соответствует докам?

**Comment by tangous** [comment]
По документации это набор флагов, а не бит.

22 февр. 2017 г. 20:34 пользователь "Victor Baybekov" <
notifications@github.com> написал:

Что значит "пришлось сделать YesNo"? Что-то у нас не соответствует докам?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/finsight/QUIKSharp/issues/104#issuecomment-281742312>,
or mute the thread
