### ISSUE TITLE
Ну очень хочется примера со Spreads

### ISSUE THREAD

**Issue by tangous** [finsight/QUIKSharp#105]
Когда то было обещано, что пример со Spreads  появится.
Очень нужный пример будет.

**Comment by buybackoff** [comment]
Суть проста: http://hotforknowledge.com/2015/12/29/how-to-write-the-simplest-trading-strategy-using-spreads/

Данные хранить можно с помощью https://github.com/Spreads/SpreadsDB

**Comment by buybackoff** [comment]
Кстати, сегодня добавил простую оптимизацию по решетке, из которой очевидным (пока что для меня) образом вытекает оптимизация стратегий. Не связано с Вашим сообщением напрямую, но как раз перерабатываю walk-forward оптимизацию из костыля в composable functional решение, не привязанное к коробочкам. Поставье что ли звездочку в Spreads, я уже несколько дней ~~плохое слово~~ наблюдаю, когда же будет 100 :) И в QUIK# тоже можно, раз пользуетесь. Не то, чтобы я кармо~~плохое слово~~наблюдатель, но приятно и немного мотивирует :)
