### ISSUE TITLE
Почему такие строгие условия создания кода?

### ISSUE THREAD

**Issue by tangous** [finsight/QUIKSharp#106]
Глубочайший поклон создателю этого проекта.

Зачем так жестко повторять реализацию luaQuik?
Все очень путанно. Данные плохо структурированы и связаны.
Я говорил о luaQuik выше. :}

В QUIKSharp 
Где можно лучше приводить это к нормальному виду.
Отличную отдушину подкинул в примере робота @sm00vik  - Class Tool.
Что я имею ввиду?
Например. Пусть quik.Orders.CreateOrder(newOrder).Result возвращает не номер транзакции с последующим поиском по нему, а сразу Order с его реальным номером или ошибку.

         `public  static Order NewOrder (this Tool _tool,  Operation operation, decimal price, int qty) 
          {
           var newOrder = new Order
           {
                ClassCode = _tool.ClassCode,
                SecCode = _tool.SecurityCode,
                Operation = operation
              ................
            }
           .........
           quik.Orders.CreateOrder(.....

            var autoEvent = new AutoResetEvent(false);
            var statusChecker = new StatusOrderChecker(10, transactionId, _tool);
            var tim = new Timer(statusChecker.CheckStatus, autoEvent, 1000, 500);
               
                autoEvent.WaitOne();
                tim.Dispose();
                return myNewOrder;         
           }`

И обращаться удобно и все понятно tool.NewOrder(
y Tool, естественно есть свойство Quik. Ну и т.д.

**Comment by buybackoff** [comment]
Об этом было #7, хотелось сделать "по-умному". Но просто повторить, как работает QLUA, гораздо проще, и такая реазизация автоматически задокументирована. В принципе довольно легко использовать TaskCompletionSource и сделать метод, который будет искать в словаре. Однако там всякие тонкости, например ответ по трейду может прийти раньше подтверждения ордера, каждых этих сообщений может быть несколько, и возможно другие тонкости.

**Comment by buybackoff** [comment]
Изначальная цель проекта - точное повторение QLua, чтобы можно было пользоватья их документацией без сюрпризов. Дополнительные фишки/логика будут явным образом обозначены и потребуют явных действий со стороны пользователя (например, дополнительный параметр, или namespace).
