### ISSUE TITLE
Проблемы с загрузкой скриптов в Квик в новой версии

### ISSUE THREAD

**Issue by dasmeer** [finsight/QUIKSharp#107]
Столкнулся со следующей проблемой
1 добавляю и запускаю скрипт QuikSharp.lua в Квик - Сервисы/lua скрипты...
2 запускаю тестовую консоль - все работает хорошо
3 закрываю/открываю Квик (либо выкл/вкл ПК)
4  запускаю тестовую консоль - ошибка при вызове метода
_quik.Class.GetSecurityClass
Additional information: Command not implemented in Lua qsfunctions module: lua_error

в QuikSharp.MessageConverter.Create(Type objectType, JObject jObject) в ...\src\QuikSharp\Serialization.cs:строка 233
в QuikSharp.JsonCreationConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) в ...\src\QuikSharp\Serialization.cs:строка 361

помогает только удаление/добавление lua скрипта в квике (Сервисы/lua скрипты...)

есть какое-нибудь решение? в прошлой версии QuikSharp такого не наблюдалась!

версия Квика 7,2,2,3

**Comment by Pr0phet1c** [comment]
Странно. Я пользуюсь самой последней версией библиотеки. Версия квика 7.6.1.1 - полет нормальный. Каждый день вечером у меня квик закрывается, а по утрам запускается заново. Правда, коннект к серверу и запуск роботов производится вручную. При перезапуске квика, Вы тестовое приложение закрываете, или оно остается открытым?
Есть еще один момент (но это я только за себя говорю) - после РЕконнекта к серверу, у меня квику требуется некоторое время, прежде чем он начинает нормально работать с роботами.

**Comment by dasmeer** [comment]
думаю проблема именно в методе _quik.Class.GetSecurityClass, потому что сам коннект отрабатывает, далее у меня идет обновление данных из квика в БД, где и используется данный метод. можете попробовать его ? 
пример 
var t = __quik.Class.GetSecurityClass("SPBFUT,SPBOPT,TQBR,TQBS,TQNL,TQLV,TQNE,TQOB", "SRZ6").Result;

**Comment by buybackoff** [comment]
SRZ6 уже неактивный инструмент. `Additional information: Command not implemented in Lua qsfunctions module: lua_error` говорит об ошибке на стороне Lua, вероятно из-за несуществующего инструмента.

**Comment by dasmeer** [comment]
спасибо, я в курсе, что он неактивный, но при первом подключении (рабочем) фукция возвращает пустую строку, а не падает! 
пробовал и другие инструменты (активные) - тоже самое

**Comment by buybackoff** [comment]
А C# в это время работает и пытается присоединиться, пока перезапускаете Квик? Эта ошибка выбрасывается при неизвестной команде [тут](https://github.com/finsight/QUIKSharp/blob/9edebdc57e40b13b6a4e7d887cce7d48398d2fbe/src/QuikSharp/lua/qsfunctions.lua#L22), странно что эта команда "lua_error", которая никогда не должна приходить со стороны C# в Луа.

**Comment by dasmeer** [comment]
нет 
1 останавливаю c#, 
2 перезагружаю Квик, 
3 запускаю C#

можете сами попровать в тестовой консоли 
подконнектиться к Квик, и вызвать
var t = __quik.Class.GetSecurityClass("SPBFUT,SPBOPT,TQBR,TQBS,TQNL,TQLV,TQNE,TQOB", "SRZ6").Result;

**Comment by Pr0phet1c** [comment]
А если использовать непросроченный тикер, такая ошибка возникает?

**Comment by dasmeer** [comment]
да, у меня возникает при любом тикере. функция показалась полезной в том числе потому, что возвражает string.Empty если тикер не найден

**Comment by Pr0phet1c** [comment]
Буду пробовать у себя воспроизвести такую ситуацию. Если получится - буду искать причину. Пока подозрение на срабатывание исключения в QLua. Если будут результаты - отпишусь

**Comment by dasmeer** [comment]
спасибо большое!

**Comment by buybackoff** [comment]
Как минимум [эти две строчки](https://github.com/finsight/QUIKSharp/blob/9edebdc57e40b13b6a4e7d887cce7d48398d2fbe/src/QuikSharp/lua/qsfunctions.lua#L21-L22) нужно поменять местами, чтобы видеть в ошибке оригианльную команду, которую Q# не находит. Сейчас мы перезаписываем команду, перед тем как записать её в сообщение и всегда записываем `lua_error`, что неправильно (я вверху тоже неправильно написал, что lua выкидывает эту ошибку, сейчас не видно этой ошибки и логирования в Луа в том месте тоже не хватает). Также все содержимое `msg` можно увидеть в дебаггере на той строчке в сериалайзере, где выкидывается сообщение.

**Comment by buybackoff** [comment]
Добавил логирование, чтобы было видно в чем ошибка (не тестировал, вроде тривиально). @dasmeer можете, пожалуйста, выложить, какую ошибку показывает после этих изменений?

**Comment by dasmeer** [comment]
возникает та же самая ошибка что и выше, как мне перекомпилировать луа скрипты? перебилдить проект QuikSharp и/или удалить/добавить/запустить в квике скрипт QuikSharp.lua 
в логах стали появляться записи "1488221017516.9 LOG 2: Loading values that a client missed during disconnect"

для чистоты эксперимента строки в qsfunctions.lua сделал так

function qsfunctions.dispatch_and_process(msg)
    if qsfunctions[msg.cmd] then
        -- dispatch a command simply by a table lookup
        -- in qsfunctions method names must match commands
        local status, result = pcall(qsfunctions[msg.cmd], msg)
        if status then
            return result
        else
            msg.cmd = "lua_error"
            msg.lua_error = "Lua error: " .. result
            return msg
        end
    else
        **log(to_json(msg), 1)
 		msg.lua_error = "- Command not implemented in Lua qsfunctions module: " .. msg.cmd
        msg.cmd = "lua_error"**
		  
        return msg
    end
end

**Comment by buybackoff** [comment]
Склонировать и ребэйзить новую версию... Сделали все ровно так, как я в своем коммите, повпрос в том, что там на выходе. В том коммите я только поменял порадок строк в Луа скрипте, и добавил логирование так, что по идее ошибку должно быть видно как сообщение в в Квике, так и exception в Q#.

Если это сообщение: "Loading values that a client missed during disconnect" было после того, как Вы запустили новую версию, то я знаю в чем дело... И писал об этом выще - пытались быть умными, но облажались по уши. Сейчас мы пишем ошибки в файл и переигрываем их при реконнекте. Забыл выпилисть эту логику, когда выпиливал Esent :/

**Comment by Pr0phet1c** [comment]
Со своей стороны сообщаю, что воспроизвести ошибку на своей стороне мне НЕ удалось. При попытке указать неработающий тикер - стабильно получаю пустую строку в качестве возвращаемого ответа, как и было задумано (в том числе, после реконнекта и/или перезапуска квика).
Т.е. даже конструкция try-catch по исключению не срабатывает. Все работает в пределах корректной обработки информации.

**Comment by dasmeer** [comment]
1 обновил версию квика - не помогает, мб у меня что-то с ПК..
2 @Pr0phet1c, что значит "Склонировать и ребэйзить новую версию"? скопировать папку с луа и настроить на неё квик?

**Comment by buybackoff** [comment]
2. Возьмите новый скрипт Луа из обновленной версии.

**Comment by buybackoff** [comment]
@dasmeer чтобы убедиться, что дело в логах пропущенных сообщений, не могли бы Вы повторить эксперимент, но перед перезапуском скрипта в Квике удалить в папке Луа всё, что похоже на логи (все текстовые файлы). Если без них не будет ошибки, значит дело точно в этом.

**Comment by dasmeer** [comment]
скачал вашу версию, удалял логи, копировал вашу версию и в папку проекта и в F:\temp - при повторном запуске квика в обозначенной функции по-прежднему ошибка

**Comment by dasmeer** [comment]
переустановил ОС - вин 7 (64), квик не переустанавливал (копировал как есть)
забил на вышеописанную функцию, решил просто проверить выставление заявки для этого, как в примере:
1 инициирую Tool, 
2 вызываю NewOrder
в п1 при вызове 
res.AccountID = **_quik.Class.GetTradeAccount(classCode).Result;** 
возникает вышеописанная ошибка **Command not implemented in Lua qsfunctions module: lua_error** с чем это все же связанно?
стоит переустановить квик?

**Comment by buybackoff** [comment]
Попробуйте сначала установить Lua for Windows:

https://github.com/rjpcomputing/luaforwindows

или

https://github.com/rjpcomputing/luaforwindows

2017-03-14 21:24 GMT+03:00 dasmeer <notifications@github.com>:

**Comment by dasmeer** [comment]
установил , не помогло... разве что ПК перезагрузить

**Comment by buybackoff** [comment]
А что случилось между моментом когда у Вас все работало и потом появилась
эта ошибка? Может обновляли Квик или еще что-то делали с компьютером?

2017-03-14 23:33 GMT+03:00 dasmeer <notifications@github.com>:

**Comment by dasmeer** [comment]
все и работало один день, пока квик не закрывал. я потестил, порадовался. но как только закрыл/открыл квик, библиотека перестала работать... удаляю ссылку на скрипт в квике, добавляю - все снова работает. 
буду пробовать переустановку квика

**Comment by Pr0phet1c** [comment]
Lua for Windows - должен быть просто установлен. Но выполните его установку ПОСЛЕ переустановки квика. После установки Lua for Windows компьютер необходимо перезагрузить.
Еще такой вопрос: Если запустить скрипт в квике и перезагрузить квик, то что Вы видите в диалоговом окне скриптов?
1. Скрипт остается запущенным после перезагрузки терминала, или он "стоит" и его надо снова запускать?
2. До и после перезагрузки терминала, при выделенной строке запущенного скрипта, какие-нибудь ошибки в диалоговом окне скриптов есть?

**Comment by dasmeer** [comment]
ура! переустановка квика помогла! сейчас версия 7,9,1,1 
1 скрипт оставался и остается запущенным
что такое "диалоговое окно скриптов" - окно сообщений в квике? у меня оно выкл. в настройках - сказать не могу

**Comment by Pr0phet1c** [comment]
Диалоговое окно скриптов - это то окно, в котором Вы добавляете и запускаете Lua-скрипты.
Оно, в свою очередь, делится на два окна: в верхнем список скриптов; в нижнем отображаются ошибки (если они есть).

**Comment by buybackoff** [comment]
@dasmeer если всё работает, закройте этот issue пожалуйста. Когда будет FAQ, добавим - в случае если ничего не помогает, обновить Квик :)

**Comment by dasmeer** [comment]
@Pr0phet1c ошибок в диалоговых окнах не замечал
