### ISSUE TITLE
Multiclient support

### ISSUE THREAD

**Issue by buybackoff** [finsight/QUIKSharp#108]
Иногда полезно иметь доступ из нескольких процессов к одному серверу Q#. До этого уже обсуждали возможные варианты с несколькими скриптами на разных портах, но это неудобно.

Самый простой способ - добавить Id клиента в сообщения, на стороне Луа держать словарь с клиентами и отсылать ответы только тому клиенту, который делал запрос. Рыночные данные посылаются всем клиентам.

Проблема с коллбеками, например OnOrder - нужно или запихивать Id клиента в коммент, но он ограничен и полезен для других целей, или же на стороне Луа держать словарь соответствия TransId <-> ClientId.

https://github.com/diegonehab/luasocket/blob/master/samples/tinyirc.lua

ClientId можно задавать на стороне Луа, используя счетчик. В идеале хотелось бы не менять C# часть совсем.

**Comment by Pr0phet1c** [comment]
К сожалению, приведенный код, выше моего уровня знаний, поэтому я только свое видение логики работы с колбэками могу предложить.

Т.к. на колбэки мы обычно сначала подписываемся, то в момент подписки на стороне сервера (Lua) мы попоняем базу ClientId (для каждого колбэка свой список). Соответственно, при поступлении колбэка - рассылаем его всему списку клиентов, которые ранее на него подписались.

Как Вам такой вариант?

**Comment by buybackoff** [comment]
Для каждого колбэка держать свой список клиентов конечно "западло", но по-другому наверное не получится. Но на пример со стаканами, мы должны держать список подписок для каждого клиента, этих списков будет много... Надо еще подумать о функциональщине - прятать клиентов в каком-нибудь замыкании, и подписывать эти замыкания на колбэки.

В ближайшее время не смогу этим заниматься, так что up for grabs.

**Comment by buybackoff** [comment]
Производительность в контектсе Квика - не большая проблема. Важно в этой имплементации оставить hot path - если клиент только один, то не делать дополнительную работу. Можно сделать глобальную переменную isMultiClient, тогда для одного клиента издержки будут только проверка этого флага.

Фильтровать незапрошенные сообщения на стороне клиентов совсем не вариант - двойная работа, загрузка сокетов, а реализация не проще, чем сделать фильтрацию на стороне Луа.

**Comment by buybackoff** [comment]
За пределами проекта - можно сделать свой сервер, к которому подключаются клиенты. Или см. @DataSpreads
