### ISSUE TITLE
Не могу отловить ошибку выставления заявки

### ISSUE THREAD

**Issue by Pr0phet1c** [finsight/QUIKSharp#109]
Столкнулся с неожиданной проблемой.
До сих пор я думал, что в случае отклонения сервером заявки, я получу отрицательное значение Transaction ID, и смогу его обработать. На этом у меня построена логика обработки такой ошибки в роботах.
Недавно столкнулся с неправильной заявкой и обнаружил, что робот не смог обработать отклонение этой заявки сервером.
Загнал процедуру выставления ошибочной (с отрицательной ценой) заявки в отдельный тест и команда CreateOrder, спокойно вернула мне положительное значение Transaction ID (что-то типа номера 42). При этом, в квике есть сообщение о том, что моя заявка была отклонена, т.к. значение цены должно быть положительным.

Что я делаю не так?

**Comment by buybackoff** [comment]
В документации ничего не написано про отрицательный номер. TransactionID [задается пользователем](https://github.com/finsight/QUIKSharp/blob/master/src/QuikSharp/TradingFunctions/TradingFunctions.cs#L325) и используется по сути только как correlation id. В ответе на транзакцию есть поле "статус", наверное по нему можно распознать ошибку.

**Comment by Pr0phet1c** [comment]
Хм.
Я ориентировался на вот эту запись из метода SendTransaction:

            } catch (TransactionException e) {
                transaction.ErrorMessage = e.Message;
                // dirty hack: if transaction was sent we return its id,
                // else we return negative id so the caller will know that
                // the transaction was not sent
                return (-transaction.TRANS_ID.Value);
            }

Видимо как-то неправильно понял смысл.

**Comment by buybackoff** [comment]
надо бы убрать этот "dirty hack"... тут транзакция наверное успешно отправляется, но потом забраковывается сервером. Какой статус у ошибочных транзакций?

**Comment by buybackoff** [comment]
Я предлагаю выбрасывать ошибку там, где сейчас отрицательны ID. Это так нелогично и незадокументировано, что я даже сам забыл про это, хотя сам писал.

**Comment by Pr0phet1c** [comment]
Не знаю как вытащить этот статус.
CreateOrder возвращает только ID транзакции.
Пытался получить из хранилища:
                        string tr = _quik.Storage.Get<Transaction>(transactionID.ToString()).ErrorMessage;
Но видимо что-то не то делаю.

**Comment by Pr0phet1c** [comment]
В общем, пока решил пытаться отлавливать ошибки через OnTransReply. Заложил алгоритм проверки в одного из роботов. Посмотрим что получится.

**Comment by buybackoff** [comment]
Пусть будет открытым - я пока не могу копать глубже, но проблема есть.

**Comment by Pr0phet1c** [comment]
ОК. Хотя куда там копать пока непонятно. Эксперименты показали, что попытка отправить транзакцию с отрицательной ценой НЕ вызывает ошибку, т.е. транзакция отправляется успешно. Однако, после этого срабатывает колбэк OnTransReply, где в поле сообщения (в параметрах транзакции) описана причина невозможности разместить заявку. При этом, в случае успешного размещения заявки обозначенный выше колбэк не срабатывает. Хорошо бы придумать метод типа "NewOrder", куда в качестве параметров мы передаем параметры заявки, а обратно получаем уже непосредственно Order, содержащий в себе всю необходимую информацию по заявке. В случае ошибки, можно возвращать Null. Но как запихнуть в один метод отправку транзакции и проверку ответа я пока не придумал.

**Comment by buybackoff** [comment]
Это тоже часть #7 - чтобы не забыть и там было видно упоминание. Надеюсь не позже конца лета уже разберусь с этим. Консилиум бы тоже не помешал на тему всех тонкостей с ответами на транзакции в Квике. Я в #124 написал об идее, что изначальная цель "тупо" повторять QLua не меняется, но в ответ на транзакцию можно возвращать "умный" объект, который все тонкости будет учитывать. А все расхождения с QLua, типа как отрицательный номер, надо бесжалостно выпиливать - и вместо них должна быть выброшена ошибка.
