### ISSUE TITLE
Нет всех сборок в репозитории

### ISSUE THREAD

**Issue by Sergey-A-Dvortsov** [finsight/QUIKSharp#111]
Здравствуйте! Клонировал ветку repo на свой комп. Не могу найти некоторые сборки, например Esent.Collections. Есть эти сборки в репозитории или эти библиотеки нужно брать другом месте (в этом случае где?)

**Comment by Pr0phet1c** [comment]
1. Это внешние сборки, которые можно установить через диспетчер пакетов NuGet.
2. Вроде Esent полностью "выпилили" из проекта, и он больше не требуется. В каком месте Вы обнаружили необходимость его использования?
3. Из внешних сборок сейчас только Newtonsoft.Json используется. Вот ее точно надо установить.
