### ISSUE TITLE
Не могу подключиться к Quik

### ISSUE THREAD

**Issue by Fr3sto** [finsight/QUIKSharp#112]
Установил библиотеку в своё приложение, всё по гайдам. В тестовом приложении QuikSharpDemo подключение проходит и также могу что-либо вывести на экран. Но, когда создаю своё приложение, копирую первую часть кода с подключением, пишет "Получаем статус соединения с сервером" и всё. Грузит так долго, ничего не происходит. В квике запустил файл луа, сгенерированный под данное приложение. В чем может быть проблема?

В Квике выскакивает окно "Loading values that a client missed during disconnect".

**Comment by buybackoff** [comment]
Firewall? Установили из NuGet или отсюда? Функционал "Loading values that a client missed during disconnect" вроде был выпилен недавно, или скоро будет выпилен. Посмотрите еще, нет ли больших файлов логов в той же папке, где скрипт Луа, и удалите если есть.

**Comment by Fr3sto** [comment]
Firewall выключен. 
Скачиваю паком весь код, далее просто запускаю QuikSharpDemo. Всё работает. Самое интересное, если удалить библиотеку и установить через NuGet, то множество ошибок возникает. Но не суть. 
А так, я создаю приложение консольное, устанавливаю через NuGet QuikSharp 0.3.0 версии, прописываю строчку
`isServerConnected = _quik.Service.IsConnected().Result;`
В квике запускаю Луа. Затем нажимаю, запустить приложение.
И всё. Он просто тупит и ждет.

**Comment by Fr3sto** [comment]
Возможно дело в файле Lua. Просто, когда я скачиваю все проекты, библиотека уже установлена в каждом из них и возможно варианты установки библиотеки у нас различаются. Не через NuGet, а еще через чего мб надо делать.

**Comment by buybackoff** [comment]
В NuGet сейчас нерабочая версия, тем более 0.3. Там есть пре-релиз 1.0-alpha, но не помню были ли значимые изменения после этого здесь. Используйте только master отсюда, в том числе и файл Луа отсюда из репозитория. Из Вашего ответа я не понял, какая из версий не работает. НюГетовская 0.3 не должна работать, надо ее вобще удалить оттуда...

**Comment by Fr3sto** [comment]
Первый раз на GitHub'e. Можете подсказать пожалуйста. Ведь файл Lua прикрепляется к конкретному проекту? И, я думал, он устанавливается вместе с QuikSharp. И последнее, через какой именно Master устанавливать, можете прислать ссылку пожалуйста на сам установщик от сюда.

**Comment by buybackoff** [comment]
Если Вы скачиваете отсюда - то это и есть master branch. Файл Луа надо использовать вот этот: https://github.com/finsight/QUIKSharp/blob/master/src/QuikSharp/lua/QuikSharp.lua, вместе с другими из папки. То есть если Вы скачали архив отсюда, то ничего из NuGet не нужно трогать.

**Comment by Fr3sto** [comment]
Всё, я понял, как всё запускать. Спасибо большое за помощь и за созданную библиотеку!

**Comment by buybackoff** [comment]
Заработало?

**Comment by Fr3sto** [comment]
Да, всё заработало в отдельном проекте.

**Comment by buybackoff** [comment]
Отлично. Удачной торговли! :)

**Comment by buybackoff** [comment]
Отлично. Удачной торговли! Поставье тогда звездочку ;)

**Comment by Fr3sto** [comment]
Хорошо, спасибо :)
