### ISSUE TITLE
Реализация колбэка OnFuturesClientHolding

### ISSUE THREAD

**Issue by Fr3sto** [finsight/QUIKSharp#113]
Здравствуйте. Не нашел в тестах и примерах реализацию событий.
Попробовал сделать сам, не вышло. Можете подсказать пожалуйста, как в вашей библиотеке они реализовываются?
Создаю winforms там же по кнопке проверяю подключение. Затем вывожу значение открытой позиции по данному инструменту, всё хорошо. Далее пытаюсь реализовать событие открытия нового ордера, но не выскакивает MessageBox, когда в квике руками покупаю что-нибудь.
Вот мой код по событию:
`quik.Events.OnAllTrade += Events_OnAllTrade;
 
private void Events_OnAllTrade(AllTrade allTrade)
        {
            MessageBox.Show("Новая сделка");
        }
`
Функция создается автоматически после добавления события.

**Comment by Pr0phet1c** [comment]
Странно. Не знаю в каких примерах Вы смотрели, но в Examples есть реализация колбэков.
В QuikSharpDemo: OnQuote
В RobotDemo: NewCandle

Также не очень понятен ход Ваших мыслей при реализации поставленной задачи.
Вы пишите: "...пытаюсь реализовать событие открытия нового ордера...", а код приводите для колбэка получения обезличенных сделок.
Если Вы хотите отследить выставление "своей" заявки, то используйте "OnOrder", или OnTrade (для сделок). Один из вариантов реализован в "RobotDemo".

**Comment by Fr3sto** [comment]
Да, извините, это я недосмотрел в примерах колбэки и  неправильно выразил мысли. Необходимо в результате реализовать колбэк изменения позиции по срочному рынку, различных фьючерсов. 
По поводу колбэка OnTrade, всё вызывается, всё правильно. А вот на счет колбэка OnFuturesClientHolding - событие возникает при изменении позиции на срочном рынке. Но если в квике покупать\продавать контракты по фьючерсам, колбэк не вызывается.

**Comment by Pr0phet1c** [comment]
С "OnFuturesClientHolding" не помогу. Я его не использую. Возможно, реализация этого колбэка в библиотеке еще не завершена.

**Comment by Fr3sto** [comment]
Просто нужно составить таблицу всех сделок от их открытия, до закрытия. И поэтому OnFuturesClientHolding отличным образом тут поможет. Можно, конечно, и через OnTrade, но немного по-сложнее будет.

**Comment by Fr3sto** [comment]
Просто и колбэк OnTrade, OnOrder вызывается по 2 раза, что бывает лишним. А OnFuturesClientHolding вызывается 1 раз, при изменение позиции по срочному рынку.

**Comment by Pr0phet1c** [comment]
Реализовал колбэк "OnFuturesClientHolding".
Пример использования этого колбэка добавил в "QuikSharpDemo" (проверил - работает).
Пользуйтесь (не забудьте скачать свежую версию библиотеки).

**Comment by Fr3sto** [comment]
Спасибо большое, попробую сейчас запустить в примере.
