### ISSUE TITLE
идентификация заявок и мувы

### ISSUE THREAD

**Issue by traderqq** [finsight/QUIKSharp#114]
Добрый день

1. Есть ли способ при отправке заявки пометить её как то, чтобы по приходу сделки получить эту пометку?
(нужно для создания нескольких роботов внутри QS, чтобы каждый работал со своей логической позицией)

2. Есть ли мувы на фортсе? (куски отдельные есть, но метода не нашел)

**Comment by Pr0phet1c** [comment]
1. А чем не устраивает номер заявки, в качестве идентификатора?
2. Я вопроса не понял. Возможно, кто -то еще ответит.

**Comment by traderqq** [comment]
1. Получать long, который отдает NewOrder, хранить где-то список отправленных заявок, в колбеке сделки смотреть, какому роботу этот long принадлежит?
Наверное можно и так, просто более сложно и потенциально ненадежно, чем написать в комменте t1, и по наличию этого коммента разбирать.

2. На фортсе есть режим "Перестановка заявок", когда мы в существующей заявке меняем цену или объем. Квик это поддерживает, в QS не нашел.

**Comment by buybackoff** [comment]
2. [MOVE_ORDERS](https://github.com/finsight/QUIKSharp/blob/master/src/QuikSharp/DataStructures/TransactionEnums.cs#L74) нужно составить транзакцию с определенными параметрами.

**Comment by Pr0phet1c** [comment]
1. Сам я такую операцию никогда не пробовал выполнять, но в таблице сделок и таблице заявок есть поле "Комментарий". Рискну предположить, что в таблице сделок это поле заполняется из заявки. Так что теоретически, Вы можете при составлении транзакции, заполнить поле комментарий и после того как сделка пройдет, должны увидеть комментарий из соответствующей заявки в строке сделки.

**Comment by traderqq** [comment]
1. Если так сделать, при компиляции появится окошко с сообщением что комментарии используются в качестве correlation_id для сопоставления заявок/сделок, и пользователь их заполнять не может. 
Поэтому собственно и вопрос возник.

2. А готовой C# функции нет, как для NewOrder ? (чтобы на вход брала order и новые цены/объемы)

**Comment by Pr0phet1c** [comment]
1. У меня идеи закончились. :(

**Comment by buybackoff** [comment]
1. Это часть #7 и одна из вещей, которые мещают зарелизить уже наконец как 1.0. Давно пора переработать эту логику, я всё не нахожу время. По идее TRANS_ID должно быть достаточно.

**Comment by traderqq** [comment]
положу сюда мой текущий подход, вдруг пригодится кому

public static IDictionary<long, string> trans_list = new ConcurrentDictionary<long, string>();
public static IDictionary<long, string> orders_list = new ConcurrentDictionary<long, string>();

// при отправке заявки
string comment = "trader_id";
long trans_id = 0;
trans_id = NewOrder();
trans_list.Add(trans_id, comment);

// в OnTransReply
if (reply.Status == 3)
{
    string comment;
    if (trans_list.TryGetValue(reply.TransID, out comment)) orders_list.Add((long)reply.OrderNum, comment);
}

// в OnTrade
string comment;
if (orders_list.TryGetValue(trade.OrderNum, out comment))
{
    trader t; // объект класса трейдер, реализующий торговую логику
    if (traders.TryGetValue(comment, out t))
    {
        t.logical_pos += ((side == Operation.Buy) ? 1 : -1) * trade.Quantity;
    }
}

**Comment by traderqq** [comment]
Дополню - подход имеет недостатки, иногда позиция теряется.

Это происходит, когда ответ от NewOrder(), который отдаст номер транзакции, придет позже, чем придет OnTransReply на поставленную заявку.

Тогда в OnTransReply мы не узнаем, какой робот отправил заявку (номер транзакции с роботом еще не соотнесен), а внутри NewOrder() у нас еще не будет номера заявки (его и не должно там быть).
В итоге логическая позиция становится неправильной.

В общем, ждем 1.0, чтобы можно было использовать комментарии для этих целей - это будет всегда работать, и не зависеть от странностей квика.

**Comment by buybackoff** [comment]
Напишите, как Вы видите должно работать по шагам. Не зря тот issue назывался  transaction callback **hell** :)

**Comment by traderqq** [comment]
То, что квик присылает колбеки в хаотичном порядке - с этим наверное бороться бесполезно.

Я адресовался к этой фразе - "По идее TRANS_ID должно быть достаточно", в том смысле, что в логике связывания заявок и сделок будет использоваться (непонятным для меня образом) trans_id, комментарий освободится и можно будет его использовать.

А как перейти на такой подход, - даже и не знаю)
Чтобы содержательно предлагать шаги, нужно сначала понять, как оно сейчас работает, а я пока внутрь архитектуры не заглядывал глубоко.

**Comment by buybackoff** [comment]
Смотрите #195 если это еще не пофиксили.
