### ISSUE TITLE
как правильно получать позицию?

### ISSUE THREAD

**Issue by traderqq** [finsight/QUIKSharp#116]
Непонятно, как правильнее получать позицию (по фортсу)

Если подписываться на OnFuturesClientHolding, то он не вызывается никогда, хотя позиция меняется.

Если периодически вызывать Trading.GetFuturesHolding, то он иногда возвращает позицию корректно, 
а иногда возвращает ноль, падает в exception, и ругается на LUA

```
Error: 0 : QuikSharp.LuaException: Lua error: c:\QUIK\lua\qsfunctions.lua:349: attempt to perform arithmetic on local 'posType' (a nil value)
   at QuikSharp.MessageConverter.Create(Type objectType, JObject jObject)
   at QuikSharp.JsonCreationConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at QuikSharp.JsonExtensions.FromJson(String json, QuikService service)
   at QuikSharp.QuikService.<Start>b__44_3(Object r)
```

Quik 7.9.1.1, QUIKSharp мастер отсюда

**Comment by buybackoff** [comment]
Тут по ходу дела не реализован колбэк и ошибка в коде Луа. [Здесь](https://github.com/finsight/QUIKSharp/blob/d05b8f5386bf5b7b713dc9b774fc1043fdc8fcf3/tests/Profiler/lua/qsfunctions.lua#L242) мы умножаем на 1 чтобы превратить строку в число, а надо еще проверять на nil.

**Comment by Pr0phet1c** [comment]
OnFuturesClientHolding - был реализован мной вчера (31.05.17). В актуальной версии библиотеки все есть.

**Comment by traderqq** [comment]
**buybackoff**

как то так?
```
function qsfunctions.getFuturesHolding(msg)
    local spl = split(msg.data, "|")
    local firmId, accId, secCode, posType = spl[1], spl[2], spl[3], spl[4]
    if posType == nil then
	posType = 0
    end
	local result, err = getFuturesHolding(firmId, accId, secCode, posType*1)
	if result then
		msg.data = result
	else
		log("Futures holding returns nil", 3)
		msg.data = nil
	end
    return msg
end
```

**Pr0phet1c**
Отлично!

**Comment by buybackoff** [comment]
@traderqq сейчас заметил, что nil приходит со стороны C# а не Квика, надо посмотреть почему...

**Comment by traderqq** [comment]
Проверил с этим фиксом - ошибок не выдает, позиция приходит исправно.

А OnFuturesClientHolding так и не вызывается 
Оновился только что, в QuikService.cs теперь
```
case EventNames.OnFuturesClientHolding:
    Trace.Assert(message is Message<FuturesClientHolding>);
    var futPos = ((Message<FuturesClientHolding>)message).Data;
    Events.OnFuturesClientHoldingCall(futPos);
    break;
```

**Pr0phet1c** - а у вас вызывается по изменению позиций на фортсе?

**Comment by Pr0phet1c** [comment]
Согласно справке Квика:
Функция вызывается терминалом QUIK при изменении позиции по срочному рынку. 
и в качестве параметра мы получаем таблицу "Позиции по клиентским счетам (фьючерсы)".
Если я правильно понимаю логику, то при изменении ЛЮБОГО параметра из данной таблицы происходит вызов обозначенного выше колбэка.
Если Вы посмотрите на пример в QuikSharpDemo, то заметите, что по этому колбэку отслеживается значение вариационной маржи и выводится в соответствующее поле формы. Проверял на инструменте SiM7.

Кусок кода, который Вы привели - это действительно, то что оставалось добавить в общую реализацию, для того чтобы колбэк заработал.

**Comment by traderqq** [comment]
Всё перебрал, - оказалось dll забыл в рабочей папке обновить.
Теперь работает!
