### ISSUE TITLE
Дублирование сделок между квиками

### ISSUE THREAD

**Issue by mkurtm** [finsight/QUIKSharp#117]
Добрый день, можно ли с помощью данной библиотеки реализовать дублирование Мастер квика в 2-3 ведомых квика? С учетом нюансов данного вопроса.

**Comment by buybackoff** [comment]
С ньюансаим наверное сложно, а на честном слове просто сразу посылайте в несколько квиков из кода... Но там правда столько ньюансов будет!

**Comment by mkurtm** [comment]
Не совсем об этом. Задача такая - мне нужно реализовать такую историю, чтобы действия одного квика полностью дублировались в ведомые квики. В мастер квике я могу делать сделки руками или через привод либо как угодно. Потом софт считывает эти действия и передает на исполнение в ведомые квики. Такое возможно?

**Comment by buybackoff** [comment]
Всё возможно в коде, наверное! Еще раз повторю: Q# - это зеркало того, что дает QLUA, только в .NET. Любой дополнитиельный функционал сильно за пределами целей, которые стоят перед этим проектом.
