### ISSUE TITLE
Реализация колбэк OnTransReply

### ISSUE THREAD

**Issue by Fr3sto** [finsight/QUIKSharp#118]
Здравствуйте. Недавно писал по поводу колбэка "OnFuturesClientHolding", в итоге выяснилось, что его просто не реализовали в коде, а вывели лишь обложку. Можете пожалуйста помочь также и с колбэком OnTransReply. Всё остальные колбэки при выставлении ордера вылетают 2-3 раза и нельзя четко отследить всё. А в этом колбэке можно отследить конкретное условие, почему он был вызван, по его типу. 
Заранее большое спасибо.

**Comment by Pr0phet1c** [comment]
Такого колбэка не существует, на сколько мне известно.
Во всяком случае, если верить справке по QLua из квика версии 7.12.0.49.

**Comment by Fr3sto** [comment]
А, я неправильно написал название, прошу прощения, параллельно с MT5 просто работаю. Я на счет колбэка "OnTransReply".

**Comment by Pr0phet1c** [comment]
Этот колбэк реализован.
Вот кусочек кода в моем применении:

        TransactionReply lastTransactionReply = new TransactionReply();
        _quik.Events.OnTransReply += (TransactionReply transReply) =>
        {
            if (transReply.TransID == res) lastTransactionReply = transReply;
        };

**Comment by Fr3sto** [comment]
Странно, но у меня он не вызывался при добавление события. Буду искать, в чем могла быть ошибка. Спасибо за ответ.

**Comment by Pr0phet1c** [comment]
Надеюсь Вы не вручную заявку в квике выставляете.

Вот что написано в справке:
Функция вызывается терминалом QUIK при получении ответа на транзакцию пользователя, отправленную с помощью Trans2quik.dll, QPILE, QLua или динамической загрузки транзакций из файла. **При отправке транзакций вручную через интерфейс Рабочего места QUIK функция не вызывается.**

**Comment by Fr3sto** [comment]
Вручную, да.. Я просто не справку в основном читаю, а саму библиотеку в VS и поэтому не увидел этого. Спасибо за пояснение.

**Comment by Pr0phet1c** [comment]
Возьмите из папки квика файл QLua.chm. Много интересного узнаете.
Данная библиотека по сути и реализовывает функционал, описанный в этой справке.

**Comment by Fr3sto** [comment]
Спасибо, всё работает в итоге, я затупок.
