### ISSUE TITLE
Предложение создать событие изменения GetTrades

### ISSUE THREAD

**Issue by Fr3sto** [finsight/QUIKSharp#121]
Здравствуйте. Можете пожалуйста создать событие изменения количества элементов таблицы GetTrades. Я недавно обращался с событие `OnFuturesClientHolding`, но там нагемороился с ним, что он вызывает много одновременных вызовов потоков, что невозможно с ним работать. И по сути в нем я создаю условие изменения конкретной таблицы сделок, чтобы я мог обрабатывать только при наступлении новой сделки, а не изменении маржи и т п. Поэтому и логичным было бы создать такое событие. Можете пожалуйста добавить данное событие к общую библиотеку. 
Заранее огромная благодарность за труд.

**Comment by buybackoff** [comment]
А такое событие есть в QLua?

Присылайте пулл реквест, с удовольствием заревьюим и примем :) Вряд ли кто-то будет специально этим заниматься сразу по первой просьбе, пока кому-то такое событие самому не понадобится.

Что значит `он вызывает много одновременных вызовов потоков`? И почему не подходит событие `OnTrade` для новых сделок?

**Comment by Fr3sto** [comment]
Данное событие вызывается при изменении любого параметра в таблице. И если у тебя там много инструментов открыто, то это событие будет вызываться много раз и у каждого вызова свой поток. И данные между потоками почему-то пересекаются. Плюс, если тебе нужно событие получения новой сделки без каких-либо левых вызовов, то такого события нету. OnTrade вызывается по несколько раз. Другие событие подобные тоже вызываются много раз. А по факту, главное условие - изменение таблицы сделок, если там ничего не поступало, то и нового трейда нету.

**Comment by traderqq** [comment]
**Fr3sto**
сохраняйте пришедшие номера сделок, и реагируйте только на новые - вот эта реакция и будет только один раз на каждую новую сделку

**Comment by Pr0phet1c** [comment]
На самом деле все не так просто. GetTrades - это функция ПОЛУЧЕНИЯ таблицы сделок из терминала, т.е. вызов данной функции приводит к отправке запроса в квик, с целью получения самой актуальной таблицы сделок.
А событие как Вы пишите "изменения количества элементов таблицы GetTrades" - это и есть колбэк OnTrade, со всеми вытекающими последствиями. То что Вы просите это по сути вызов функции GetTrades при каждом срабатывании OnTrade. В принципе, такое Вы в состоянии написать самостоятельно без внесения изменений в библиотеку. Однако, проблему множественного срабатывания OnTrade на одну и ту же сделку это не решает. В свое время я читал, что такие колбэки должны всегда приходить трижды, и в своей работе просто обрабатываю именно третий по счету колбэк. Но там тоже есть свои особенности и тут я Вам не помогу, т.к. я эту методику применяю для достижения своих специфических целей.
