### ISSUE TITLE
Как можно получить список субсчетов?

### ISSUE THREAD

**Issue by Fr3sto** [finsight/QUIKSharp#122]
Здравствуйте. Необходимо, при открытии программы, пройтись по всем субсчетам и посмотреть их открытые позиции. Я могу получить через функцию GetTradeAccount торговый счет, но если у меня их 10 штук, как можно получить их список?

**Comment by spvik** [comment]
GetTradeAccounts

**Comment by Fr3sto** [comment]
Так это выводит только 1 торговый счет, а у меня их 10. Если я руками ввожу сам торговые счета, то у меня выводит таблицу позиций по клиентским счетам на срочном рынке всё правильно, но необходимо всё это получать из функций без ввода руками
