### ISSUE TITLE
Есть ли функции для подключения и отключения библиотеки квикшарп к квику?

### ISSUE THREAD

**Issue by Andrey87-09** [finsight/QUIKSharp#123]
Приветствую! Есть ли функции для подключения и отключения библиотеки квикшарп к квику? Или она автоматически подключается к квику при инициализации класса Quik? Как разорвать соединение между клиентским приложением и квиком?

**Comment by buybackoff** [comment]
https://github.com/finsight/QUIKSharp/blob/master/src/QuikSharp/QuikService.cs#L115

**Comment by Andrey87-09** [comment]
Спасибо Виктор!
