### ISSUE TITLE
Событие получение новой свечи, как то странно работает

### ISSUE THREAD

**Issue by spvik** [finsight/QUIKSharp#124]
Добрый день, при обработке новых свечей, наткнулся на странное поведение, свечи приходят из разных периодов и не по порядку. скриншот прилагаю 
![screenshot_16](https://user-images.githubusercontent.com/10877253/27677342-f969940e-5cb9-11e7-9a69-20186cb6cdce.png)

**Comment by buybackoff** [comment]
А если просто фильтровать/группировать по периоду и тикеру - внутри каждой такой группы вроде бы по порядку.

**Comment by spvik** [comment]
Еще одна проблема, код пустой только получает по событию новые свечи, после 1 часа работы выпало исключение:
![image](https://user-images.githubusercontent.com/10877253/27681746-dd2be210-5cc8-11e7-8400-917c1738765e.png)

теперь, после каждого запуская после 5-10 минут падает это исключение

**Comment by spvik** [comment]
System.Collections.Generic.KeyNotFoundException произошло
  HResult=0x80131577
  Сообщение = Данный ключ отсутствует в словаре.
  Источник = mscorlib
  Трассировка стека:
   в System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   в QuikSharp.InMemoryStorage.Get[T](String key) в c:\Projects\QuikSharp\src\QuikSharp\IPersistentStorage.cs:строка 53
   в QuikSharp.QuikEvents.OnTradeCall(Trade trade) в c:\Projects\QuikSharp\src\QuikSharp\QuikEvents.cs:строка 358
   в QuikSharp.QuikService.ProcessCallbackMessage(IMessage message) в c:\Projects\QuikSharp\src\QuikSharp\QuikService.cs:строка 516
   в QuikSharp.QuikService.<Start>b__44_5(Object r) в c:\Projects\QuikSharp\src\QuikSharp\QuikService.cs:строка 317
   в System.Threading.Tasks.Task.InnerInvoke()
   в System.Threading.Tasks.Task.Execute()

**Comment by buybackoff** [comment]
а версия отсюда или с Нюгета? Тут как раз параллельное у коллеги это было проблемой, в Нюгете старая версия.

**Comment by spvik** [comment]
Версия с гита

**Comment by spvik** [comment]
Выяснил почему падает исключение, у меня несколько субсчетов, на одном из субсчетов торгует робот в Метатрейдере, и когда там происходит сделка, запрашивается ключ с номером заявки, но метатрейдер номер заявки высылает как #0120120303 и на этом падает исключение, как такое исправить в самой библиотеке пока не понимаю

**Comment by buybackoff** [comment]
Сценарий реагирования на чужие сделки не рассматривался, возможно когда-нибудь это будет частью #108. (по времени - когда у меня будет время на развлечения с Луа just for fun). Также можно считатать это частью пресловутого issue #7, самое простое как-то распознавать свои сделки и игнорировать чужие. Что-то на эту тему так было накодено, но очень давно и через коментарии.

Вы можете сами изменить текущуб логику так, что чужие ответы - не найденные в словаре - просто игнорируются. В вашем частном случае это будет просто, не нужно решать "в общем виде".

**Comment by spvik** [comment]
В том и дело, чтобы игнорировать чужие сделки, нужно чтобы колбек в луа в одном формате все слал, и отсортировать не получится по одному счету и прочие сортировки, сама библиотека падает когда колбек приходит, она просматривает все события.

**Comment by buybackoff** [comment]
Вы можете по каким-то признакам на стороне C# игнорировать чужие сделки -
по формату, коментарию, и т.д.

2017-06-30 12:34 GMT+03:00 spvik <notifications@github.com>:

**Comment by spvik** [comment]
я немного не понимаю как это можно сделать.

_quik.Events.OnOrder += Events_OnOrder;

как мне тут отсортировать какие калбаки получать? потому что дальше не проходит, выпадает исключение

**Comment by buybackoff** [comment]
Просто тупо если нет в словаре – то чужой, свои же всегда там

**Comment by spvik** [comment]
Виктор, нашел проблему,
Данная ошибка происходит, когда сторонняя программа или какой нибудь робот, во время выставления ордера  посылает комментарий к ордеру, тогда в словаре QuikSharp  пытается искать значения, а ключ использует этот комментарий, а не номер ордера и транзакции, поэтому, ТУПО отсортировать не получиться, чтоб решить данную проблему, у себя в репозитории сделал исправление, очищаю все входящие комментарии, после этого все прекрасно работает, и обрабатывает все калбаки от всех программ и разных терминалов и роботов.
Если данное исправление вам подходит, могу выслать ПуллРеквест

**Comment by buybackoff** [comment]
Отрабатывать чужие события я считаю неправильно, опасно. Вся суть бесконечного разговора о #7 в том, чтобы можно было от транзакции проследить всю цепочку событий, вызванных транзакцией. Возможно, в итоговом варианте будут события, которые 1-в-1 повторяют то, что делает QLua, не будут умничать и просто реагировать на всё, что приходит, а SendTransaction будет возвращать объект, в который будут приходить события связанные только с этой транзакцией. Поля будут IAsynEnumerable:

```
struct TransactionResponses {
   IAsynEnumerable<Order> Orders {get; }
   IAsynEnumerable<Trade> Trades {get; }
   ...
}
```

Присылайте пулл реквест, если не сложно, просто чтобы посмотреть, как у Вас работает. Может другим будет полезно - как документация, не обязательно его сразу сливать. Будет напоминанием проблемы.

**Comment by buybackoff** [comment]
Пометил как enhancement, так как различать чужие заявки - за пределами функционала QLua, но полезная вещь.

**Comment by buybackoff** [comment]
Кажется был другой issue на эту тему, который решили. Если нет - пишите в #195
