### ISSUE TITLE
Не могу получить получить _quik.Service.IsConnected().Result; 

### ISSUE THREAD

**Issue by Andrey87-09** [finsight/QUIKSharp#125]
Вечер добрый! Скрипт запущен и коннектится, но не могу получить возвращаемое значение _quik.Service.IsConnected().Result;   Квик пишет следующее:  Loading values that a client missed during disconnect   В чем может быть дело?

**Comment by Andrey87-09** [comment]
тесты и 2-й пример работают

**Comment by buybackoff** [comment]
Может быть старая версия?

**Comment by Andrey87-09** [comment]
Квик обновлял только сегодня и библиотеку сегодня по новой скачивал

**Comment by buybackoff** [comment]
Скачивали отсюда или с NuGet?

**Comment by Andrey87-09** [comment]
Проблема не только с этой задачей а со всеми задачами, пример работает полностью, скачивал NuGet-ом

**Comment by Andrey87-09** [comment]
Даже в консольном приложении попробовал получить значение этой задачи и та же проблема

**Comment by Andrey87-09** [comment]
Нашел различия в версиях с гита и nugeta

**Comment by buybackoff** [comment]
Попробуйте удалить все файлы с расширением .log с папке, где скрипт Луа.

**Comment by Andrey87-09** [comment]
Виктор, проблема оказалась в версии из нугета, скомпилировал версию из гитхаба, засунул в копию консольного приложения и все заработало!

**Comment by Andrey87-09** [comment]
Там и тут однозначно разные версии, в нугет версии нету   _quik.Class.GetSecurityClass()
                                                                                                    _quik.Class.GetClientCode()
                                                                                                    _quik.Trading.GetTrades()
и еще наверняка чегото

**Comment by buybackoff** [comment]
надо наверное большими красными буквами написать в ридми :) и обновить
пакет... уже в который раз это корень проблем...

2017-06-30 0:09 GMT+03:00 Andrey87-09 <notifications@github.com>:

**Comment by Andrey87-09** [comment]
Да уж, потрепала мне эта проблема нервишки)), пакет когда обновлять будете?

**Comment by buybackoff** [comment]
когда отполируем всё до версии 1.0. вопрос с колбэками открыт, и с коментами, и с кучей связанных с этим деталей. залить новый пакет не сложно в принципе, только это не решает главную задачу.

**Comment by Andrey87-09** [comment]
Ясно, спасибо за поддержку!

**Comment by buybackoff** [comment]
написал ЗАГЛАВНЫМИ БУКВАМИ в кратком описании проекта на самом верху по NuGet :)
