### ISSUE TITLE
Где брать paramName для функции GetParamEx?

### ISSUE THREAD

**Issue by Andrey87-09** [finsight/QUIKSharp#128]
День добрый! Собственно возник вопрос, где брать paramName для функции GetParamEx?  
В примерах есть такая строчка:    quik.Trading.GetParamEx(classCode, securityCode, "LOTSIZE").Result.ParamValue.Replace('.', separator))); так вот откуда взято имя параметра "LOTSIZE"?

**Comment by Andrey87-09** [comment]
Нашел здесь список [https://quikluacsharp.ru/quik-qlua/poluchenie-dannyh-iz-tablits-quik-v-qlua-lua/](url)

**Comment by buybackoff** [comment]
Наверное хорошо бы было сделать большой список enums для этого, если они стабильные?

**Comment by Andrey87-09** [comment]
Да, было бы хорошо.

**Comment by buybackoff** [comment]
Вопрос в том, стабильные ли они? Так то можно быстро сгенерировать код, если есть список - мой любимый тул для генерации кода Эксель как раз поможет :)

**Comment by Agremond** [comment]
Стабильно на столько, на сколько стабилен ДНК QUIK :) есть пример что нужно получить на выходе и куда вставить в проекте? Попробую сгенерить.

**Comment by Pr0phet1c** [comment]
Для функции GetParamEx добавлена реализация с использованием enum ParamNames, в котором есть все известные на момент формирования списка имена параметров.
