### ISSUE TITLE
Что требуется для запуска

### ISSUE THREAD

**Issue by coder-ex** [finsight/QUIKSharp#129]
Я новичок в C#, помогите разобраться, что необходимо для запуска тестового проекта. Установил VS, скачал проект, но во всем этом ворохе файлов не могу понять что, куда и зачем укладывать.
Так же не понял, как создавать свои проекты в VS и подключать.

**Comment by buybackoff** [comment]
Кстати Вы правы - до сих пор нет самого простого шаг-за-шагом примера, как запустить с нуля. Фраза в Readme в принципе достаточна тем, кто понимает, но даже она не полна. А просить новичков перелопачивать все issues не очень правильно... Напишу в ближайшее время самый краткий мануал. Хотя где-то в вопросах уже есть ответ, но даже я с ходу не нашёл.

**Comment by coder-ex** [comment]
спс )) но хотелось бы все же сегодня начать разбираться, я пришел с С++ Qt и C# да еще под VS для меня темный лес )) мне бы импульс для старта, дальше думаю разберусь, а то хожу вокруг и облизываюсь, но вкурить не могу как и чего вообще подключать
сделайте для меня исключение, разъясните пожалуйста и это же можно будет выложить как общий мануал для всех

**Comment by coder-ex** [comment]
Не знаю разобрался или нет, но добавив либу QuikSharp.dll в проект, запустил создание:
`using System;
using QuikSharp;

namespace QuikTest
{
   class Program
   {
      static async void TestQuik()
      {
         Console.WriteLine("Start creating Quik");
         Quik _quick = new Quik();
         Console.WriteLine("Created...");
         bool _isQuik = await _quick.Debug.IsQuik();
         Console.WriteLine(_isQuik);
      }
      static void Main(string[] args)
      {
         TestQuik();
         Console.ReadLine();
      }
   }
}`
теперь нужно понять, этот коннект только к QUIK, а как авторизоваться? или сам коннект уже подразумевает, что QUIK запущен и авторизован на сервере брокера?

**Comment by coder-ex** [comment]
не могу понять структуру построения тестовых роботов, можете ее описать?

**Comment by buybackoff** [comment]
Если Вам так сильно "хотелось бы" ночью в выходные или утром понедельника начать - я покажу, куда заносить чемодан денег. Если же у Вас нет ни денег ни чемодана, почитайте например это https://en.wikipedia.org/wiki/Open-source_software

Вы позиционируете себя "программистом" откуда Вы пришли сюда (Смарт-Лаб), давайте не будем обсуждать как построить проекты... Это Вам вместо "импульса для старта".

Давайте все же Вы попробуете прочитать readme и вопросы тут в issues. Мой изначальный ответ был общий на будущее, не для Вас лично.

**Comment by buybackoff** [comment]
Для запуска требуется:
1. Запустить скрипт Луа в Квике
2. Подключиться к нему из C#.

FTW

**Comment by coder-ex** [comment]
не хотите отвечать не отвечайте, сам буду разбираться, но уже вижу, что у многих вопросов много, а задать не знают как, т.к. сидит тут один гуру, который на смарт-лабе хвастает своей разработкой, а в итоге объяснять как пользоваться не хочет т.к. ему чемодан денег не дают за это )) вот он и пытается всех ткнуть носом в опенсорс...

**Comment by Pr0phet1c** [comment]
Добавил краткую инструкцию по началу работы с библиотекой в README.RU

**Comment by buybackoff** [comment]
@coder-ex  удачи! найдете место, где в 4 утра по первому Вашему требованию отвечают на вопросы - расскажите, пожалуйста.

**Comment by coder-ex** [comment]
упс )) мы обиделись?
я и не требовал ни чего, а задал вопрос в том месте куда сами же мне и указали на смартлабе ))
на плюсах все же более дружественная атмосфера, там такой стиль общения как ваш, редкое явление, наоборот всегда рады объяснить, даже по мелочи...

**Comment by mkurtm** [comment]
Скажи откуда пришел юзверь и я скажу кто он.

**Comment by buybackoff** [comment]
@coder-ex я Вам ответил в полтретьего ночи в вск на пн, меньше чем через час, как Вы задали вопрос. Ответил, что в ближайшее время напишу подробно - извините, но ночью я сплю. Вам же нетерпелось и захотелось сразу получить ответы, хотя тут все ответы были и так, просто не собраны в одном месте. Мне кажется это Вы обиделись на мой сарказм, потерли все свои комменты и пошли строить свой коннектор с блэкджеком...

**Comment by coder-ex** [comment]
я не знаю кто такой блекджек )) но ваш сарказм меня действительно задел, т.к. я не спросил ни чего такого где можно было писать про мои знания в кодинге в "", вы меня абсолютно не знаете... к тому же я не заставлял вас подпрыгивать ночью и тут же отвечать на мои сообщения, данная форма общения подразумевает иной стиль...
в общем тему закрыли, я сам как нить без такого стиля общения разберусь, а не разберусь то свое напишу

**Comment by buybackoff** [comment]
https://www.youtube.com/watch?v=5l3ipKcnYlQ

**Comment by buybackoff** [comment]
@coder-ex 

Вы создаете впечатление невнимательного человека, который просит индивидуальную помощь, при этом не попытавшись даже немного разобраться. Вы правы, я Вас не знаю, я говорю о своем впечатлении от общения.

Например, на Смарт-Лабе у меня в профиле написано, что все вопросы обсуждаются тут.

![image](https://user-images.githubusercontent.com/489852/28023726-5778598c-6597-11e7-9d23-959c9d2bee39.png)

Но это не помешало Вам писать личные сообщения, из которых довольно явно следует, что Вы не попытались даже разобраться сами, а сразу пошли за помощью.

![image](https://user-images.githubusercontent.com/489852/28023690-37ba3516-6597-11e7-9805-87ae58357c65.png)

И более того, полностью проигнорировали надпись большими буквами про NuGet на самом видном месте проекта. Об этом также написано в недавних issues.

![image](https://user-images.githubusercontent.com/489852/28023798-975d9a26-6597-11e7-95eb-b10821315b5c.png)

Ваше общение в [оригинальное ветке](https://smart-lab.ru/blog/408487.php#comment7383961) также создает впечатление, что Вы не до конца понимаете, что делаете. 

Например, эта часть подтверждает моё впечатление, что Вы требуете индивидуального внимания, хотя люди просто хотят помочь Вам не наступать на грабли и не изобретать велосипед.
![image](https://user-images.githubusercontent.com/489852/28024429-58cb03b4-6599-11e7-9840-5fe48e004a85.png)

Так что задумайтесь сами о стиле общения и не занимайтесь шапкозакидательством. 

По конкретным техническим вопросам здесь идут продуктивные дискуссии. И Вам добро пожаловать обсуждать детали проекта, а не "у меня ничего не работает".

**Comment by mkurtm** [comment]
Закрывайте вопрос. Время тратите на какую-то ерунду.

**Comment by buybackoff** [comment]
Из полезного, эта ветка - повод сделать issue template

**Comment by mkurtm** [comment]
and iq testing at the gate

**Comment by coder-ex** [comment]
я по привычке кодера всегда смотрю в readmy -> Install
а там указано как ставить по устарвшей методике, извините что не читаю ваши мысли и что у вас так принято информацию раскидывать везде, наверное от этого код у подавляющего большинства прогеров на C# такой пухлый ))
и как бы вы сами закрыли эту ветку много постов назад, объясните невнимательному пользователю mkurtm, ткните как умеете его носом, я вам дорогу что ли перешел что вы тут на меня время свое тратите? будьте мужчиной и если закрыли ветку, то и не пишите сюда больше )) говорю же - закрыли тему, мне не интересно общаться в таком стиле, я вам лично ни чего не должен, забудьте про меня...

**Comment by coder-ex** [comment]
> and iq testing at the gate
извиняюсь за резкость, но вы видимо берега попутали, ветка давно закрыта, чего тут третесь, вас сюда точно ни кто не приглашал

**Comment by mkurtm** [comment]
i'm noob in coding , but at least i dont act like everebody owe me

for all questions - it's an open source project,

so NO SUPPORT. as is.

have questions - pay and get support.

**Comment by coder-ex** [comment]
> Из полезного, эта ветка - повод сделать issue template
из полезного эта ветка еще ни чего не принесла т.к. в вашем readmy файле указана все таже старая инфа

**Comment by mkurtm** [comment]
its been written for future generations of pilgrims

**Comment by coder-ex** [comment]
> i'm noob in coding , but at least i dont act like everebody owe me
> for all questions - it's an open source project,
> so NO SUPPORT. as is.
> have questions - pay and get support.
вроде русский а пишешь на бусурманском )) про свое iq не забудь, а то смотрю блещешь умом

**Comment by mkurtm** [comment]
i dont have homeland keyboard layout ))))

**Comment by coder-ex** [comment]
> its been written for future generations of pilgrims
он был не убран во время и я за это не в обиде и ни от кого ни чего не требую, но обидно становится когда начинают не по делу тыкать носом в свои же не доделки
поинтересуйтесь зачем нужен этот файл вообще в репозиториях, а потом пытайтесь умом блестать, будете выглядеть на много умнее чем сейчас со своим iq

**Comment by buybackoff** [comment]
Мальчики - не ссорьтесь! @mkurtm Вы тут совсем неконструктивны, еще больше, чем остальные участники...

> я по привычке кодера всегда смотрю в readmy -> Install

Это открытый проект, если видите ошибку, исправьте по возможности. Про NuGet написано большими буквами вверху, не было удобно на тот момент создавать коммит. И вообще, Readme в принципе правильный, просто последняя версия на NuGet не работает, и это выяснили пользователи, сообщая в конструктивном ключе об ошибках здесь.

Я закрываю дискуссию - думаю все сказали, что хотели.

**Comment by mkurtm** [comment]
mate, i just wanna say, that you're welcome here, but it's an open source project. it's just like charity )     founders share their files with us. they made it their way. they dont have to explain anything or answer questions. or make docs.

**Comment by coder-ex** [comment]
> mate, i just wanna say, that you're welcome here, but it's an open source project. it's just like charity ) founders share their files with us. they made it their way. they dont have to explain anything or answer questions. or make docs.

вы не правы, проект открытый, и вопросы задают разработчикам, но не требуют а просят, разницу видите?

**Comment by coder-ex** [comment]
> Это открытый проект, если видите ошибку, исправьте по возможности. Про NuGet написано большими буквами вверху, не было удобно на тот момент создавать коммит. И вообще, Readme в принципе правильный, просто последняя версия на NuGet не работает, и это выяснили пользователи, сообщая в конструктивном ключе об ошибках здесь.

я понимаю, что это мелочь, но это главный файл, я не читаю особо заголовки т.к. они предназначены для другого, для установки есть специальный файл в котором есть ошибка допущенная вами же, оттого такие вопросы и возникли, кстати могли вообще не делать ни чего, пусть оставалось бы как есть ))
