### ISSUE TITLE
Update project to VS2017

### ISSUE THREAD

**Issue by buybackoff** [finsight/QUIKSharp#131]
.NET Standard имеет мало смысла, хотя в принципе библиотека может работать на Linux и соединяться c Квиком на Windows (вопрос только - зачем!?).

Но текущая структура с build.fsx/FAKE настолько устарела, что уже проблематично упаковывать NuGet.

**Comment by coder-ex** [comment]
пробовали в Linux работать с QUIK в wine, писали врапер Linux <-> wine, но столкнулись с нестабильностью QUIK под wine в плане визуальных настроек, поэтому наверное mono тут не особо поможет, хотя позже нашли проблему в том, что wine использовали х64, а он там не особо стабилен, но возвращаться к х86 уже не захотелось...

**Comment by buybackoff** [comment]
QUIKSharp может работать на .NET Core без Моно, в нем нет никаких специфических для Windows штук. Речь идет о том, что Q# и Квик могут быть на разных машинах, им только нужно соединение через TCP.

**Comment by coder-ex** [comment]
а где настраивается IP? я на стороне сервера не увидел открытого интерфейса настроек, он ведь в dll зашит наверное?

**Comment by buybackoff** [comment]
Сейчас везде localhost, но ничегло не мешает задать параметр. Сервер - это Квик, к нему подсоединяются клиенты откуда угодно. IP будет адрес той машины, где Квик.

**Comment by coder-ex** [comment]
в принципе так и думал делать на случай удаленного соединения
