### ISSUE TITLE
исключение all task must inish gracefully after cancellation token is cancelled

### ISSUE THREAD

**Issue by coder-ex** [finsight/QUIKSharp#132]
Может кто поможет побороть это исключение ))
Создаю коннект с сервером через делегат, так же делаю разрыв соединения с сервером через делегат, все работает нормально и форма не подвешивается, если что то не то с сервером. Но проблема проявляется если вдруг симулировать отключение скрипта от QUIK, в этом случае выскакивает данное исключение:
![quiksharp](https://user-images.githubusercontent.com/20105948/28054752-685a3ab4-6640-11e7-9c6c-8fb3de82fce2.png)

на всякий случай код:
[FormMain.zip](https://github.com/finsight/QUIKSharp/files/1137910/FormMain.zip)

**Comment by coder-ex** [comment]
судя по исходникам классов Quik и QuikService в моем варианте происходит как раз невозможность остановки описанная в методе Quik.StopService()
т.е. если собрать старт клиента через QuikService.Create, то будет ли это правильным или создать свой класс по образу класса Quik, но с необходимой стартовой обвязкой не в конструкторе класса?

**Comment by buybackoff** [comment]
Вставьте код прямо текстом 
```
выделив его тройными ` сверху и снизу
```
Не понятно как именно вы делаете "симулировать отключение скрипта от QUIK". Этот кусок кода особо не тестирован на все случаи жизни, идея была как раз в том, что если ошибки будут видны, значит нужно доработать чистый выход.

**Comment by coder-ex** [comment]
**_симулировать отключение скрипта_** - делается просто, в QUIK выключаю скрипт и все ))
`''using System;
using System.Windows.Forms;
using QuikSharp;

namespace HistoryData
{
   public partial class FormMain : Form
   {
      private delegate void Answer();                 // делегат для получения ответа
      public static Quik m_client_socket;             // сокет клиент
      bool m_is_serv_conn = false;                    // флаг соединения с сервером

      public FormMain()
      {
         this.InitializeComponent();
         this.Init();
      }

      /*!
         \brief   инициализация
      */
      void Init()
      {
         buttonConnect.Enabled = true;
         buttonDisconnect.Enabled = false;
      }

       private void FormMain_Load(Object sender, EventArgs e)
      {

      }

      /*!
         \brief   тут стартуем объект соединения с QUIK
      */
      private void buttonConnect_Click(Object sender, EventArgs e)
      {
         try
         {
            textBoxOutMsg.AppendText("Подключаемся к терминалу QUIK..." + Environment.NewLine);
            m_client_socket = new Quik(Quik.DefaultPort, new InMemoryStorage());    // инициализируем объект Quik
         }
         catch
         {
            textBoxOutMsg.AppendText("Ошибка инициализации объекта quik_conn..." + Environment.NewLine);
         }

         if(m_client_socket != null)
         {
            textBoxOutMsg.AppendText("Объекта quik_conn проинициализирован успешно..." + Environment.NewLine);
            try
            {
               textBoxOutMsg.AppendText("Получаем статус соединения с сервером..." + Environment.NewLine);
               // ожидание ответа от сервера
               new Answer(delegate () { this.Answ(m_client_socket.Service.IsConnected().Result); }).BeginInvoke(null, null);

               //m_is_serv_conn = quik_conn.Service.IsConnected().Result;
               //this.Answ(m_is_serv_conn);
            }
            catch
            {
               textBoxOutMsg.AppendText("Неудачная попытка получить статус соединения с сервером не установлено..." + Environment.NewLine);
            }
         }
      }

      /*!
         \brief   тут стопим соединение с QUIK
      */
      private void ButtonDisconnect_Click(Object sender, EventArgs e)
      {
         try
         {
            textBoxOutMsg.AppendText("Отключаемся от терминала QUIK..." + Environment.NewLine);
            new Answer(delegate () { m_client_socket.StopService(); }).BeginInvoke(null, null);
            //quik_conn.StopService();
         }
         catch
         {
            textBoxOutMsg.AppendText("Неудачная попытка отключиться от сервера..." + Environment.NewLine);
         }

         buttonConnect.Enabled = true;
         buttonDisconnect.Enabled = false;
      }
      /*!
         \brief   ответ socket от сервера
      */
      private void Answ(bool a_flag)
      {
         if(a_flag)
         {
            textBoxOutMsg.AppendText("Соединение с сервером установлено..." + Environment.NewLine);
            buttonConnect.Enabled = false;
            buttonDisconnect.Enabled = true;
         }
         else
         {
            textBoxOutMsg.AppendText("Соединение с сервером не установлено..." + Environment.NewLine);
            buttonConnect.Enabled = true;
            buttonDisconnect.Enabled = false;
         }
      }
   }
}
''`

**Comment by buybackoff** [comment]
Попробуйте. Во время обрыва связи мы игнорировали команду Stop().

**Comment by coder-ex** [comment]
странный стиль общения, тема интересная всем, вы ее убираете

**Comment by buybackoff** [comment]
что вам опять не нравится!? я сделал фикс, который должен решить проблему.

**Comment by coder-ex** [comment]
где этот фикс?

**Comment by buybackoff** [comment]
> buybackoff closed this in https://github.com/finsight/QUIKSharp/commit/54c95d327f0baa4a3bb3cac75df2a2e77c26bb28 10 minutes ago

внимательнее смотрите, я не просто закрыл issue, а с коммитом, в котором фикс.

**Comment by coder-ex** [comment]
т.е. вся проблема была в EnsureConnectedClient(); на EnsureConnectedClient(_cts.Token); ? и если вставить этот фикс, то исключения не будет?

**Comment by buybackoff** [comment]
ну посмотрите внимательно на логику всех изменений... EnsureConnectedClient пытается переподключиться бесконечно, но до этого токен отмены не проверялся, поэтому после вызова функции Stop() циклы в трех потоках не завершались по-хорошему и продолжали пытаться переподключиться.

**Comment by coder-ex** [comment]
тогда извините за написанное ранее ))
по исправлениям, я писал ранее, что в C# пока новичок, поэтому не могу претендовать на какие то заключения, если по простому, то это решит данную проблему и тогда не нужно будет колдовать с собственной организацией старта обвязки клиента (то что я предполагал во втором сообщении) ?

**Comment by buybackoff** [comment]
Классы Quik и QuikService теперь `sealed`.

**Comment by coder-ex** [comment]
не понимаю если честно (( я же вижу их исходный код на гите

**Comment by buybackoff** [comment]
вы не сможете их унаследовать без изменения исходного кода

**Comment by coder-ex** [comment]
Я видел, что вы изменили в классах )) Но ведь я не говорю о наследовании, я во втором сообщении предположил вариант создания класса по образу Quik, но не наследуясь, и в нем организовать собственную обвязку не в конструкторе класса.
Я ведь правильно понимаю, что sealed предполагает запрет на наследование и вы имеете именно это в виду?

**Comment by buybackoff** [comment]
Идея в том, что если Вы что-то пытаетесь улучшить, делайте пожалуйста это в исходниках и присылайте изменения обратно сюда.

**Comment by coder-ex** [comment]
я поддерживаю такую идею, но по описанным ранее причинам, сделать подобное не в состоянии ))
еще раз задам вопрос на который так и не вижу ответа - теперь описанная проблема устранена или мне нужно самому продумать ее решение?

**Comment by buybackoff** [comment]
Я вам написал в самом начале "попробуйте". Я не тестировал, но изменения тривиальные и понятно, почему процесс не выходил вежливо.

**Comment by coder-ex** [comment]
наконец то добрался до компа )) исключение исчезло, но есть непонятность, при отключении скрипта в QUIK, почему то клиент не выходит на отключение сам, думаю что нужно что в коде у меня добавить, скорее всего какую нить проверку на состояние подключения, я правильно думаю?
PS. где вам тут плюс поставить ?

**Comment by buybackoff** [comment]
Клиент C# будет пытаться переподключиться бесконечно каждые 100 миллисекунд, и выдавать сообщение каждую секунду о том, что он пытается подключиьтся. Это такой дизайн. Вы должны вызвать Stop(), чтобы отключить клиента.

**Comment by coder-ex** [comment]
так вот если остановить работу скрипта в QUIK, то я и не вижу ни какой реакции, по идее должно ведь разорвать соединение и потом пытаться подключить с интервалом как вы пишите в 100 мс, а этого не происходит
