### ISSUE TITLE
Что-то сломалось :(

### ISSUE THREAD

**Issue by Pr0phet1c** [finsight/QUIKSharp#134]
После одного из последних обновлений библиотеки, мой робот перестал работать.
Не возможно инициализировать объект Quik.
Пока не смог залезь достаточно глубоко, но поверхностный анализ показал, что ошибка происходит при попытке подключится по нестандартному порту (разумеется, ранее все работало). Скрипты Lua, запущенные в квике не менял, т.к. вроде не заметил чтобы в них вносились изменения.

Я что-то упустил?

**Comment by Pr0phet1c** [comment]
Обновился до самой последней версии и случился совсем АХТУНГ!
QuikSharp (сбой загрузки).
При попытке перезагрузить проект выдало большое текстовое сообщение типа:
пространство имен XML по умолчанию для этого проекта должно быть пространством имен MSBuild XML... бла-бла-бла... Если проект был создан в старом формате 1.0 или 1.2, преобразуйте его в формат MSBuild 2003.

Что я сделал не так???

**Comment by buybackoff** [comment]
У Вас какая версия Visual Studio? Я перевел проект на формат VS2017 недавно.

**Comment by buybackoff** [comment]
Также я сделал классы Quik и QuikService sealed - если наследовали их зачем-то, то должно перестать работать.

**Comment by Pr0phet1c** [comment]
2015.

Вот удалось полный текст ошибки скопировать:
C:\Users\hohlov_v\Dropbox\C#\Repository\QuikSharp - new\src\QuikSharp\QuikSharp.csproj : error  : пространством имен XML по умолчанию для этого проекта должно быть пространством имен MSBuild XML. Если проект создан в формате MSBuild 2003, добавьте xmlns="http://schemas.microsoft.com/developer/msbuild/2003" в элемент <Project>. Если проект был создан в старом формате 1.0 или 1.2, преобразуйте его в формат MSBuild 2003.  C:\Users\hohlov_v\Dropbox\C#\Repository\QuikSharp - new\src\QuikSharp\QuikSharp.csproj

Попробую обновиться до 2017. По результатам отпишусь.

**Comment by buybackoff** [comment]
А насчет первого соолбщения про подключение - есть детали, stacktrace?

**Comment by Pr0phet1c** [comment]
>>Также я сделал классы Quik и QuikService sealed - если наследовали их зачем-то, то должно перестать работать.

Прошу прощения, но смысл данной фразы для меня сейчас непонятен.

Ранее (да и в демо-приложениях) экземпляр создавался вот так:
        public static Quik _quik;
_quik = new Quik(Quik.DefaultPort, new InMemoryStorage());

в моем случае: _quik = new Quik(34138, new InMemoryStorage());
с соответствующей настройкой скрипта lua.

Если теперь так делать нельзя, то как надо?

**Comment by buybackoff** [comment]
если Вы не делали
```
class MyModifiedQuik : Quik 
{
... cool new features
}
```
то это никак не должно повлиять

**Comment by buybackoff** [comment]
или если в коде использовали функцию получения локального IP - я её удалил https://github.com/finsight/QUIKSharp/commit/768aa5333e39516eef8a372d90c382a632474d31

другие изменения не меняли основной функционал (правда я не тестировал, но @coder-ex вроде запустил с ними)

**Comment by Pr0phet1c** [comment]
ничего перечисленного не делал. Дальше выяснить пока ничего не могу, т.к. я все еще не могу даже просто загрузить проект. (пытаюсь обновиться до 2017)

**Comment by buybackoff** [comment]
> Не возможно инициализировать объект Quik.

а это сообщение откуда? я думал робот Ваш запускается, но выдает ошибку

**Comment by coder-ex** [comment]
парни, я запустил только коннект-дисконнект, другой функционал я не трогал т.к. изучаю C#, тяжеловато в моем возрасте делать переход с другого языка оказалось )) плюс с WPF еще нужно разбираться и определиться как выстраивать структуру программ, не хочется все ложить в кучу, а делать модель по принципу MVVM вообще волосы шевелятся на моей башке ))

**Comment by buybackoff** [comment]
@Pr0phet1c наверное хорошее правило не запускать боевых роботов на последнем коммите мастера, или нам нужно сделать ветку dev, которая сливается с мастером только когда у всех работает. Я еще грешу тем, что пушу в мастер напрямую (иногда с force push, потому что могу 😄 ), хотя проект давно уже не мой личный, и наверное мне стоит делать стандартные PRs. У ГитХаба вроде есть функционал, что как минимум N людей должны одобрить PR. Так как этот проект связан так или иначе с реальными деньгами, нам с Вами нужно быть двумя "одобрятелями" любых изменений после 1.0.

**Comment by buybackoff** [comment]
И кстати, после перехода на проекты VS2017, мне обновить NuGet в пару кликов, просто запустить скрипт. @Pr0phet1c я могу Вас добавить в NuGet, чтобы Вы тоже могли публиковать. VS17 это сделал так удобно, что я уже давно перестал линковать проекты напрямую. У меня есть локальный депозитарий, где я публикую все экпериментальные изменения, и обновить проекты, которые например зависят от Spreads.Core, занимает сильно меньше минуты.

**Comment by Pr0phet1c** [comment]
Итак, по порядку:
1. После обновления VS до 2017, проблема исчезла. Ура!
2. Фишка в том, что свою программу я эксплуатирую одновременно в двух режимах (Release и Debug). В Release крутятся боевые системы, а в Debug пачка тестовых роботов. Так уж случилось, что я случайно выполнил перекомпиляцию в режиме Release, но сбой обнаружил только на следующий день, при попытке запустить роботов перед началом торговой сессии. В качестве временного решения помогло подсовывание в Release старой версии библиотеки из Debug.
3. На счет добавления в NuGet - я не уверен, что стоит это делать. Я даже с GitHub все еще не очень освоился.
4. Так же не уверен на счет утверждения PR несколькими людьми. Может возникнуть ситуация с необходимость внести какие-то исправления бага в срочном порядке, а один из "утверждателей" окажется где-нибудь далеко и без доступа к интернету. А это потенциальная проблема. 

Думаю, пока можно оставить все как есть.

В общем, спасибо за помощь. Тему закрываю.

**Comment by coder-ex** [comment]
Я за утверждение PR несколькими людьми.
1. Если кому то не втерпеж и нужно что то не проверенное и быстро, то для этого пусть берет ветку devel где как раз все находится не утвержденное и на проверке
2. Виктору, как он сам заметил, не делать случайных слияний с веткой master, а все заливать в ветку devel и только после утверждения PR делать слияние

**Comment by buybackoff** [comment]
@Pr0phet1c разумно, я перемудрил. Но пушить в мастер без PR давайте больше не будем. И если есть риск breaking changes, обсуждать их и тестировать до слияния с мастером.
