### ISSUE TITLE
Не срабатывают события OnAccountBalance, OnDepoLimit, OnFuturesLimitChange

### ISSUE THREAD

**Issue by Andrey87-09** [finsight/QUIKSharp#135]
Вечер добрый! Не срабатывают выше описанные события, OnFuturesClientHolding работает. Может где-то надо подключать их?

**Comment by buybackoff** [comment]
Из надо реализовать... https://github.com/finsight/QUIKSharp/blob/6e68d0f61b39e13642e97d2647529f3aab0702bb/src/QuikSharp/QuikService.cs#L514

PR welcome! :)

**Comment by Andrey87-09** [comment]
спасибо, позже будем разбираться)

**Comment by Pr0phet1c** [comment]
Странно. Только что просмотрел код: Вроде все три указанных колбэка реализованы полностью. К сожалению, не имею возможности сейчас заняться тестированием этих функций.
Попробуйте привести пример используемого Вами кода для работы с этими колбэками и по какому фактическому событию Вы отслеживаете срабатывание каждого из них?

**Comment by buybackoff** [comment]
@Pr0phet1c в мастере же нет реализации, по ссылке видно...

**Comment by Pr0phet1c** [comment]
Блин, точно. Забыл один файл проверить.

**Comment by Pr0phet1c** [comment]
Закончил реализацию указанных колбэков, плюс небольшую кучку дополнительных, но не имею возможности протестировать. Текущий вариант можно найти в моей ветке, созданной из последней версии мастера.
Если кто-нибудь сможет проверить и подтвердить работоспособность - солью с мастером.

**Comment by Andrey87-09** [comment]
я протестирую

**Comment by Andrey87-09** [comment]
Вопрос до кучи, как в квикшарпе логирование отключить?

**Comment by Pr0phet1c** [comment]
Если я правильно понял суть вопроса, то вот так:
Quik quik = new Quik(Quik.DefaultPort, new InMemoryStorage());

**Comment by Andrey87-09** [comment]
Получается если вместо 34130 указать Quik.DefaultPort то квикшарп перестанет писать в логи?

**Comment by Pr0phet1c** [comment]
нет. 34130 и Quik.DefaultPort - это одно и то же значение. а вот new InMemoryStorage() указывает на то, что логи нужно писать в оперативную память, а не в файл на диске.

**Comment by Pr0phet1c** [comment]
Хотя.. Я еще в файле "qsutils.lua" закомментил две строчки у себя:
missed_values_file = io.open(missed_values_file_name, "a")
и
missed_values_file:write(callback_string..'\n')

**Comment by Andrey87-09** [comment]
OnFuturesLimitChange - теперь работает, OnFuturesClientHolding работал и до этого, остальные так и не работают.

**Comment by Andrey87-09** [comment]
> нет. 34130 и Quik.DefaultPort - это одно и то же значение. а вот new InMemoryStorage() указывает на то, что логи нужно писать в оперативную память, а не в файл на диске.

Так я изначально использовал new InMemoryStorage() и все равно логов набралось на 14 гигов за месяц )

**Comment by buybackoff** [comment]
Вы точно используете последнюю версию? Вроде логи выпилили уже... При
отсоединении C# клиента в логи пишутся все колбеки - это может быть много,
например стаканы

2017-07-27 14:35 GMT+03:00 Andrey87-09 <notifications@github.com>:

**Comment by Pr0phet1c** [comment]
OnFuturesLimitChange - теперь работает, OnFuturesClientHolding работал и до этого, остальные так и не работают.

Просьба привести пример неработающего колбэка с описанием процесса проверки. Просто, я сталкивался с ситуациями, когда люди пытались поймать колбэк не относящимися к нему событиями.

**Comment by Andrey87-09** [comment]
> Вы точно используете последнюю версию? Вроде логи выпилили уже... При
отсоединении C# клиента в логи пишутся все колбеки - это может быть много,
например стаканы

Сборку скачивал чуть более месяца назад

**Comment by Andrey87-09** [comment]
Да обычная подписка и примитивные методы с точками останова

**Comment by Andrey87-09** [comment]
и манипуляции в квике

**Comment by Pr0phet1c** [comment]
Видимо Вы меня не поняли. Приведу грубый пример:

Хотим протестировать колбэк "OnDepoLimit", подписываемся на него, а для проверки покупаем или продаем какой-нибудь контракт на строчном рынке.
В этом случае колбэк НЕ сработает, т.к. рассчитан на изменения в акциях (условно).

Поэтому я и прошу привести конкретный пример: Что писали в коде и какие конкретно манипуляции совершали в квике, для проверки?

**Comment by Andrey87-09** [comment]
возможно принцип добавления и  удаления лимитов на споте я не так понял, но лимиты по фьючерсам работают так как и предполагалось.

**Comment by Andrey87-09** [comment]
`QuikLua.Events.OnDepoLimit += EventsOnOnDepoLimit;
private void EventsOnOnDepoLimit(DepoLimit dLimit)
        {
            var res = dLimit;
        }
`
покупаю, продаю, ставлю лимитки по акциям

**Comment by Pr0phet1c** [comment]
ОК. Попробую выкроить время на проверку.

**Comment by Andrey87-09** [comment]
OnDepoLimit и OnMoneyLimitDelete срабатывают, но все поля приходящих объектов равны нулям

**Comment by Pr0phet1c** [comment]
Я об этом моменте сразу написал, но пока не готов сделать вывод, что это неправильные данные. В повседневной работе эти колбэки не использую совсем, поэтому доскональной проверки не выполнял, и в ближайшее время не смогу выполнить.
Изначально речь шла о том, что события не срабатывают - проверка показала обратное.
Если сможете показать, что в одной и той же ситуации упомянутые объекты полученные через колбэк и другим способом разные, то это действительно будет поводом для проверки. Но пока я в любом случае не готов занятся этим вопросом.

**Comment by Andrey87-09** [comment]
Ну я просто добавил что объекты приходят пустыми и при совершении сделок, по поводу не рабочих коллбеков моя вина, не перебилдил проект)), ссори.

**Comment by buybackoff** [comment]
Странная тема с пустыми полями. Проверил DataStructures - там `double`, а в QLUA.chm - `number`, так что должно работать (у них местами есть маразм, когда числа как текст возвращают). Lua код тоже ничего не делает с оригинальной таблицей из Квика и напрямую ее сериализирует. Так что не могу сразу помочь с нулями. Главное вам точно понимать, что там должны быть не нули - если это так, то предлагаю @Pr0phet1c слить код, а @Andrey87-09 создать отдельный issue с багом. Так логичнее.

**Comment by buybackoff** [comment]
@Pr0phet1c по поводу недавнего обсуждения про то, что мастер должен быть здоровым - это не совсем так. Многие проекты используют мастер как главную ветку, а release как "рабочую". Еще лучше помечать рабочие срезы [тэгами](https://github.com/finsight/QUIKSharp/releases). Так что лучше  "перепушить" в мастер чем "недопушить" я считаю. И конечно снова огромное спасибо, что снова находите время поддерживать проект! (это гораздо ценнее, чем [это](https://smart-lab.ru/blog/379616.php#comment6831017))

**Comment by Pr0phet1c** [comment]
Слил с основной веткой. По поводу пустых полей: Возможно, на неделе (или на следующей) смогу проверить.

**Comment by Pr0phet1c** [comment]
Вроде пофиксил проблему. Правда, проверил только на одном параметре, но думаю проблем быть не должно. Все остальные колбэки надо тестить.
