### ISSUE TITLE
Таблица обезличенных сделок

### ISSUE THREAD

**Issue by rvkstudent** [finsight/QUIKSharp#139]
Добрый день. 
Хочу воспользоваться вашей библиотекой для своего проекта. Мне нужно получить данные таблицы обезличенных сделок для последующей аналитики. В библиотеке нашел функцию получения истории через TICK - как я понимаю это именно обезличенная сделка. Но в структуре Candle отсутствует уникальный  идентификатор и направление сделки. 
Видел. что есть более подходящая структура AllTrades (там вроде как есть и идентификатор и направление). но получать обезличенные сделки можно только в онлайн режиме через событие OnAllTrades. Мне же нужно получить весь список имеющихся  в квике обезличенных сделок. Может быть я чего-то упустил. можно как-то через существующий функционал?
![2017-08-06_18-20-53](https://user-images.githubusercontent.com/22571784/29004718-f0f5b44a-7ad4-11e7-80be-0bd39f3f95e0.png)

**Comment by Pr0phet1c** [comment]
TICK - это НЕ история обезличенных сделок. Так что для получения нужной Вам таблицы этот вариант не подходит. Сам я с обезличенными сделками не работаю, и проверить ничего не смогу, т.к. у моего брокера отключено получение данной информации. Но если я правильно помню, то никто (в смысле ни биржа, ни брокер, ни квик) никогда и не хранит исторические данные по обезличенным сделкам. Т.е. таблица обезличенных сделок у Вас начинает заполняться с нуля каждый раз после запуска терминала и коннекта к серверу, и если в процессе работы был дисконнект, то пропущенные данные Вам не откуда будет взять. Поэтому, единственный вариант на сегодняшний день это подписка на соответствующее событие и последующее накопление информации. 
Вообще, в QLua есть такая функция как "getItem", и есть таблица "all_trades" (обезличенные сделки). Чисто теоретически можете доработать библиотеку, встроив туда метод для получения всех записей из указанной таблицы. Однако, опять же работать это будет лишь в пределах одной сессии соединения с сервером.

**Comment by buybackoff** [comment]
Вроде бы внутри дня Квик перезагружает пропущенные обезличенные сделки, и есть колбэк OnAllTrade
https://quikluacsharp.ru/quik-qlua/poluchenie-obezlichennyh-sdelok-iz-quik-v-qlua-lua/

**Comment by Pr0phet1c** [comment]
Что-то я не увидел, чтобы там говорилось о прогрузке квиком пропущенных сделок. Но как я уже писал, я глубоко в этом направлении не копал. Пару лет назад задумался было, но после поверхностного изучения вопроса - отказался от этой затеи.

**Comment by rvkstudent** [comment]
Спасибо. Действительно, все сделки можно запросить только с начала предыдущей вечерней сессии. Приспособил как раз через колбэк OnAllTrade. Единственное неудобство - запрашивать историю нужно каждый раз вручную, но другого варианта как я уже понял - нет.

**Comment by Pr0phet1c** [comment]
Можно попробовать реализовать метод типа "GetAllTradeTable()", но для этого надо бы взглянуть как Вы у себя реализовали процесс получения этой таблицы.
