### ISSUE TITLE
Известные пользователи

### ISSUE THREAD

**Issue by buybackoff** [finsight/QUIKSharp#140]
Стоит добавить список известных пользователей. Если Вы используете библиотеку в своем публичном проекте, пожалуйста, оптишитесь здесь.

* TsLab - тот самый пост на СЛ
* OsEngine https://github.com/AlexWan/OsEngine
* Liquid.Pro https://liquid.pro/Connector

**Comment by dav1977** [comment]
Делаю Сервер данных из QUIKSharp в PIPE каналы и SQL базы на WPF GUI
https://github.com/dav1977/DataServer

**Comment by buybackoff** [comment]
Do not personally care any more, actually. This tool solves a concrete problem for real users, hope they send comments & pull requests as necessary. It's ARQA fault they did not do a network API, this library only does that job for them. When ARQA comes to their mind and realize it's a one day job to create a JSON-RPC API (+ maybe a week to stabilize) - this library becomes useless instantly.
