### ISSUE TITLE
Есть предложение делать общий проект. Коммерческий. Но не в паблик. Не могу найти Вашу почту

### ISSUE THREAD

**Issue by AlexWan** [finsight/QUIKSharp#141]
Приветствую. 
Это Алексей, из OsEngine. https://github.com/AlexWan/OsEngine
Напишите мне пожалуйста на почту(alexey@o-s-a.net) или дайте свою.

Есть предложение по сотрудничеству. 

С уважением, Алексей.

**Comment by buybackoff** [comment]
vbaybekov@gmail.com
