### ISSUE TITLE
Таблица текущих параметров

### ISSUE THREAD

**Issue by rvkstudent** [finsight/QUIKSharp#143]
Добрый день,
Как-то можно с помощью библиотеки получить таблицу текущих параметров из квика?
![2017-08-26_09-35-23](https://user-images.githubusercontent.com/22571784/29739258-f796bdb8-8a41-11e7-8eb9-78c9e363f944.png)

**Comment by Agremond** [comment]
Добрый день.
ТТП вы можете получить с помощью функции getParamEx.
Описание параметров и примеры вызова  на LUA есть [здесь](https://quikluacsharp.ru/quik-qlua/poluchenie-dannyh-iz-tablits-quik-v-qlua-lua/).
Пример получения последней цены инструмента (параметр  LAST )на C# есть [здесь](https://github.com/finsight/QUIKSharp/blob/20b4571c54e716cfe2f2e0dd710fcd5908732d4d/Examples/QuikSharpDemo/Tool.cs#L67)
Т.о. образом поледовательным вызовом указанной функции вы сможете составить таблицу текущих параметров.
