### ISSUE TITLE
Большие таблицы

### ISSUE THREAD

**Issue by rvkstudent** [finsight/QUIKSharp#144]
Есть необходимость копить историю (в том числе тиков). Квик дает возможность выгрузить данные за одну торговую сессию + предыдущую вечернюю. В принципе все устраивает - нужно раз в день ее забирать. Но количество строчек только по одному инструменту как выяснилось может быть > 400 тыс.

Код
`_quik.Candles.GetLastCandles(classCode, secCode, CandleInterval.TICK, 200000).Result;`
вешает скрипт ошибка 73: not enought memory. 100 тыс. грузится. 
ПК intel i5 8Гб ОЗУ - по диспетчеру задач не наблюдается нехватка памяти.
GetAllCandles соответственно тоже виснет.

В чем может быть проблема? Вроде бы 400 тыс. записей уж не такой великий объем...

**Comment by buybackoff** [comment]
возможно в 32-битном режиме запускаете приложение

**Comment by rvkstudent** [comment]
Была такая мысль. Приложение QUIK имеется ввиду?

**Comment by buybackoff** [comment]
Ваше приложение

**Comment by rvkstudent** [comment]
Свое пробовал в режиме x64 - тоже самое. Но вроде бы ошибка-то в квике возникает, т.е. в скрипте LUA?
