### ISSUE TITLE
Task QuikSharp.ServiceFunctions.IsConnected() висит

### ISSUE THREAD

**Issue by belesev** [finsight/QUIKSharp#146]
.NET солюшн и lua-скрипты забирал из git - ветки master.

- Lua For Windows установил.
- Запустил в QUIK 7.12.1.10 скрипт QuikSharp.lua
- Пытаюсь выполнить в .NET простейшую команду проверки статуса подключения:
`_quik = new Quik(Quik.DefaultPort, new InMemoryStorage());`
`if (_quik != null)`
`{`
        `     var isServerConnected = _quik.Service.IsConnected().Result;`
`}`
`_quik.StopService();`
- Сообщение в lua\logs\QuikSharp.log гласит, что соединение прошло.
`1505165110284.4 LOG 1: Connecting...`
`1505165140900.3 LOG 1: Connected!`
- Однако поток, выполняющий обращение к методу `IsConnected()`, не заканчивает выполнение. Статус таска - Awaiting.
- Netstat показывает следующую активность по портам 34130, 34131:
`  TCP    127.0.0.1:34130        0.0.0.0:0              LISTENING       3204  (info.exe - quik)`
`  TCP    127.0.0.1:34130        127.0.0.1:17001        ESTABLISHED     3204`
`  TCP    127.0.0.1:34131        0.0.0.0:0              LISTENING       3204`
`  TCP    127.0.0.1:34131        127.0.0.1:17002        ESTABLISHED     3204`
`  TCP    127.0.0.1:17001        127.0.0.1:34130        ESTABLISHED     34916 (моё приложение)`
`  TCP    127.0.0.1:17002        127.0.0.1:34131        ESTABLISHED     34916`

Я что-то делаю не так или проблема в окружении?

**Comment by leendev** [comment]
nuget пакеты обновите. Оно падает на попытке загрузить newtonsoft.json и так по кругу

**Comment by buybackoff** [comment]
NuGet JSON.NET последняя версия в зависимости

Почитайте https://github.com/finsight/QUIKSharp/blob/master/README.RU.md#Решение-проблем 

и https://github.com/finsight/QUIKSharp/issues?utf8=%E2%9C%93&q=is%3Aissue%20%20label%3Aquestion%20

Не надо просто так использовать `.Result` из UI

**Comment by leendev** [comment]
Ну у меня после установки quiksharp из нугета, newtonsoft.json этот прилетел аж версии 3.5 для 2-го фреймворка  :) Хотя возможно он у меня из гака прилетел... При попытке обратиться к IsConnected() повалились эксепшны насчет невозможности загрузить эту ассемблю. А внешне, если эксепшны отключены и в debug не смотреть, выглядит как будто все просто зависло. Обновил зависимости и заработало.
Result и Wait() из ui потока это да, плохая идея.

**Comment by buybackoff** [comment]
Первые пакеты в NuGet были как 0.3, но без alpha/beta, они типа считаются stable, а надо ставить prerelease

**Comment by belesev** [comment]
@leendev, 
Newtonsoft.Json добавлен в мой проект версии 10.0.3

@buybackoff,
я читал все существующие Issues. И поступил в соответствии с рекомендацией из "Решение проблем":
> Если среди них нет решения Вашей проблемы, создайте новый вопрос.

> Не надо просто так использовать .Result из UI
Это обычное однопоточное Console Application.

Btw, я взял за основу код из QuikSharpDemo. Если точнее, из buttonStart_Click().
Не вижу ничего плохого в том, чтобы осваивать стороннюю незнакомую библиотеку (QuikSharp.dll) от простого к сложному.

**Comment by buybackoff** [comment]
Из комментариев непонятно откуда делался вызов, проблема с блокированиеи всегда была из-за .Result в UI, предположил так и есть.

Мы очень рады, что Вы пользуетесь библиотекой, и рады помочь. Но Вы тоже помогите нам деталями.

**Comment by belesev** [comment]
Действительно, из приложенного фрагмента не был понятен контекст вызова.
Проект можно посмотреть в https://github.com/belesev/broker
В директории `Thridparty/lua` - скрипты, которые подложены и используются QUIK'ом.
Буду признателен за подсказку, в чём проблема.

**Comment by dav1977** [comment]
Зачем с нуля начинать проект, берите example удаляйте что не нужно

**Comment by belesev** [comment]
Так и начинал. Example также висит.
Думал, автор сможет ответить, для чего это характерно. Какая ещё информация от меня требуется, чтобы установить причину?
Может, есть гипотезы, которые я проверю?

**Comment by belesev** [comment]
Так и начинал. Example также висит.
Думал, автор сможет ответить, для чего это характерно. Какая ещё информация от меня требуется, чтобы установить причину?
Может, есть гипотезы, которые я проверю?

**Comment by dav1977** [comment]
Если висит Example, то я бы начал с установки заново Windows,  Quik от другого брокера, VS2017 и т.д. рано или поздно висяки прекратяться

**Comment by belesev** [comment]
@dav1977, совет про переустановку Quik **от другого брокера** помог.
Поставил отсюда ftp://ftp.quik.ru/public/updates/7.14/quik_7.14.1_upd.zip чистую версию и демо заработало корректно.
Спасибо!
