### ISSUE TITLE
Открытый интерес

### ISSUE THREAD

**Issue by dav1977** [finsight/QUIKSharp#147]
Подскажите где извлекать открытый интерес по каждому инструменту?
и общий спрос и общее предложение  или не реализовано?

**Comment by buybackoff** [comment]
Раньше работало тут https://github.com/finsight/QUIKSharp/blob/c845962b1b8859e419191afc909bb8c906e90890/src/QuikSharp/DataStructures/AllTrade.cs#L117

**Comment by dav1977** [comment]
Сейчас тоже вроде работает, хоть  тип double, а прилетает Целое число,
а где отдельно еще брать общий спрос и общее предложение - еще 2 целых числа

**Comment by buybackoff** [comment]
вроде бы нет таких данных в Квике

2017-09-25 20:14 GMT+03:00 Andrey <notifications@github.com>:

**Comment by dav1977** [comment]
В текущей таблице параметров есть активно обновляются 
- общий спрос, 
- общее предложение, 
- заявки на покупку
- заявки на продажу

**Comment by buybackoff** [comment]
А, это где-то там же есть, смотри коды в QLUA хелпе, они соотвествуют
аттрибутам в структурах данных. Думал про длинные/короткие в открытом
интересе спрашиваете...

2017-09-25 20:44 GMT+03:00 Andrey <notifications@github.com>:
