### ISSUE TITLE
Не билдится проект в VS2015

### ISSUE THREAD

**Issue by valexhome** [finsight/QUIKSharp#148]
Текущий проект с примерами и тестами от 09/10/2017 не билдится выскакивает 4 ошибки. Скачивал по разному через zip файл и git bash. Предыдущий проект который у меня есть (от января) билдится без проблем.
Использую VS 2015 update 3.
- Сам проект QuikSharp (load failed).
- error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.

**Comment by buybackoff** [comment]
Используйте пожалуйста VS 2017 Update 3 и выше, или dotnetcore SDK. Проект в новом формате https://github.com/finsight/QUIKSharp/blob/master/src/QuikSharp/QuikSharp.csproj
