### ISSUE TITLE
В демо-приложении не работают заявки

### ISSUE THREAD

**Issue by slava-nikulin** [finsight/QUIKSharp#149]
Подскажите, использую версию QUIK 7.14.17, не получается создать заявку, в окне сообщений квика пишет "Неверный код клиента"

**Comment by Pr0phet1c** [comment]
О каком конкретно демо-приложении идет речь? Их там как минимум два (умеющих выставлять заявки)

**Comment by slava-nikulin** [comment]
я запускаю QuikSharpDemo

**Comment by Pr0phet1c** [comment]
1. приложении слева есть поля "AccountID", "ClientCode" , "FirmID". Эти поля заполняются значениями после коннекта и запуска. Если заполняются, то правильные ли значения там указаны?
2. У меня квик 7.12,  и вроде все работает нормально (вечером смогу проверить еще раз). Теоретически, могу допустить, что в 7.14 что-то по другому стало работать.
3. Как вариант, можете попробовать в метод "NewOrder" добавить строку:
            order_new.ClientCode = clientCode;
но в свое время отказ от этой строки не повлиял на работоспособность.
4. Я не тестировал свои приложения для аккаунтов с мультисчетами (разделение между срочкой и фондой не считается), так что тут тоже могут быть нюансы.

**Comment by slava-nikulin** [comment]
1 - да, всё заполняется верно
3 - пробовал, не помогло
Помогло вот что: [тут](https://github.com/finsight/QUIKSharp/blob/c845962b1b8859e419191afc909bb8c906e90890/src/QuikSharp/TradingFunctions/TradingFunctions.cs#L339) если присваивать не `transaction.TRANS_ID`, а реальный код клиента, использующего QUIK, то транзакция проходит.

**Comment by Pr0phet1c** [comment]
Странно. Если это проявляется именно в новой версии квика, то это существенное изменение, которое может потребовать внесение изменений в базовые функции библиотеки. Хорошо бы автору подключиться на данном этапе, т.к. я не помощник в текущей ситуации (как минимум до тех пор, пока мой брокер не переведет меня на такую же версию квика).

**Comment by buybackoff** [comment]
Там с TRANS_ID изначально было замудрено, Квик раньше съедал и как-то работало. Не могу в ближайшее время сам разобраться, но pull requests welcome!

**Comment by slava-nikulin** [comment]
ок. Вопрос вдогонку: как можно получить все данные о, например, бумагах с рынка? Т.е. списком
[GetParamEx](https://github.com/finsight/QUIKSharp/blob/c845962b1b8859e419191afc909bb8c906e90890/src/QuikSharp/TradingFunctions/TradingFunctions.cs#L256)?

**Comment by Pr0phet1c** [comment]
Да, через GetParamEx. Другого способа нет. Но параметров там достаточно много, так что вероятно стоит еще раз подумать на счет получения сразу ВСЕХ параметров.
