### ISSUE TITLE
Не могу воспользоваться методом Quik.Service.IsConnected()

### ISSUE THREAD

**Issue by klmfor** [finsight/QUIKSharp#151]
Через NuGet добавил в проект QuikSharp. Поместил на форму те же элементы что и в QuikSharpDemo, назвал их также, скопировал код из обработчика кнопки “CONNECT”, пробую запустить UI блокируется, статус соединения не выдается. Если запускать из-под VS в окно Output  выводится:
   Connecting on request channel... 
   Connecting on callback channel... 
   Connecting on response channel... 
   Request channel connected
   Response channel connected
   Callback channel connected
   The thread 0x1c10 has exited with code 0 (0x0).
   The thread 0x1fd4 has exited with code 0 (0x0).
   Connecting on request channel... 
   Request channel connected
И далее последние 2 строки выводятся постоянно

Попробовал запустить “RobotDemo” при нажатии кнопки “Connect” тоже происходит блокировка UI, но вывод в Output другой
   Connecting on request/response channel... 
   Connecting on callback channel... 
   Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Последняя строка выводится постоянно.

При этом в “QuikSharpDemo” все работает хорошо связь с сервером проверяется.

Что я не учел при использовании QuikSharp

**Comment by Pr0phet1c** [comment]
У меня только одно предположение: Попытка запустить одновременно два приложения.

**Comment by buybackoff** [comment]
Больше одного клиента не поддерживаются. Если это нужно - то Q# должен быть прослойкой-сервером для других клиентов. Делать мульти-клиетное приложение на уровне Луа не имеет смысла.

**Comment by Kuvalda** [comment]
Столкнулся с той же проблемой. Скачал QuikSharp попробовать, посмотреть. Ось - вынь. Скомпилил и запустил RobotDemo. Не приконнектилось, понял что надо запустить лау скрипт. Запустил. Стало выдавать все то же что описано выше. Думал что чета не доустановил...  Застопил прогу, скрипт, запустил скрипт обратно. Открыл и запустил QuikSharpDemo - о чудо! работает.  Закрыл, Открыл робота, запустил - не работает. Перезапустил скрипт. Все равно ен работает. В общем все как написано в этой ишуе, те же логи и симптомы.

Подскажите как вылечить?

**Comment by Kuvalda** [comment]
Сам нашел :)

      private void buttonConnect_Click(object sender, EventArgs e)
        {
            try
            {
                textBoxLogs.AppendText("Подключаемся к терминалу Quik..." + Environment.NewLine);
                //_quik = new Quik(Quik.DefaultPort, new InMemoryStorage());    // инициализируем объект Quik
                _quik = new Quik(34136, new InMemoryStorage());    // отладочный вариант
            }

Вместо циферок надо Quik.DefaultPort, в общем раскоментить коммент и зкоментить строчку после нее.

**Comment by Pr0phet1c** [comment]
Полезное замечание. Это я видимо забыл после очередного "допиливания" вернуть все в исходное состояние. 
Спасибо.
