### ISSUE TITLE
Доработка, предложения

### ISSUE THREAD

**Issue by mkurtm** [finsight/QUIKSharp#152]
Добрый день, хотел узнать в каком направлении сейчас двигается разработка и двигается ли?
Какие планы по развитию проекта у ключевых владельцев проекта?

Может имеет смысл собрать в этой ветке возможные пути развития и доработки?

**Comment by buybackoff** [comment]
Добрый! Вроде всё стабильно, что касалось изначальной цели повторить API QLua в C# так, чтобы документацию можно было бы читать оригинальную. В первую очередь надо убедиться в этом и зарелизить наконец v1.0.

Со своей стороны я прикручу хранилище, когда будет готово, но это как бы отдельный проект и скорее Q# будет как пример практического применения.

Было бы здорово собирать все предложения в одном месте. Однако сомневаюсь, что гипететические направления "сделать еще один клон Сток Шарпа или Осы" имеют смысл. Только что-то конкретное, что касается Квик, например #7. Из того, что сидит в голове с т.з. программирования, - это заменить события на `IObservable/IAsyncEnumerable`, особенно для цепочки `Tx -> Order -> Trade`, когда в ответ на транзакцию возвращается объект с полем `Trades: IAsyncEnumerable<Trade>`, которое можно просто читать, без подписки/отписки на события для каждой заявки.

**Comment by mkurtm** [comment]
С праздником!)

Я могу со своей точки зрения описать как вижу.
Текущая реализация - это по сути отличный "коннектор" - транслятор. Но если посмотреть на круг пользователей - то это либо программисты 80 левел, либо другие софт проекты, типа ТСлаба или Осы. Что собственно они и сделали, взяв этот проект как коннектор к квику.

Я не отношусь ни к одному ни второму. Кодить умею, но не 80 левел. На рынке работаю. И второй год уже пытаюсь штурмануть и начать пользоваться и никак не могу перепрыгнуть пропасть вхождения в проект.

Что, на мой взгляд, может проложить небольшой мост:
1. Наличие хорошо закоменченого файла - примера. Скажем так - обертка, которая легко читается, разбита на логические блоки, которая может быть легко использована как шаблон для усложнения и написания уже рабочих приложений. Причем, вижу это консольным простым приложением. Потому что задача - понять структуру, работу. В библиотеке есть шикарный пример, уже виндовой и прочее. То есть как приложение очень круто, но с точки зрения "обучающей" функции - ну просто жесть. Возможно, я слаб в программировании и опытные кодеры сразу отсеивают код не относящийся к понимаю работы с библиотекой, но на мой взгляд, там только процентов 5 кода, который реально нужен для понимания. И его нужно найти, отсортировать, понять и прочее. Мне кажется, если вынести тебе 5% в консольный апп и хорошенько прокомментить, то потребуется минут 30 чтобы понять что к чему. Плюс потом от этой обертки оттолкнуться.

2. Как я вижу, опять же с моим уровнем понимания, сейчас библиотека - то по факту "низкоуровневый" язык для построения рабочих алгоритмов. На мой взгляд, поэтому это идеально, если мне нужен коннектор, но практически невозможно работать, если я алготрейдер. Почему? Потому что мне, опираясь на низкоуровневые вещи, должен собрать свои библиотеки более высокого класса и с ними работать. Причем, каждый НЕМИНУЕМО будет это делать, если хочет работать. Самый просто пример: Позиция. У нас есть все ордера, все что угодно. Но каждый вынужден у себя собирать класс Позиция, реализовывать одни и те же методы и свойства, как то закрыть позицию, получить ее размер или направление, средняя цена или время открытия. Так вот, мне кажется, если у нас будут в общем виде сделаны классы, в простейшей реализации (которые вроде в примерах реализованы), самые необходимые и без которых невозможно работать, то это на световые года приблизит к обычным алготрейдерам. Тем более, что этот код у всех так или иначе сейчас есть. Просто его нужно сделать в классы и стандартизировать более менее. И тогда вместо того как сейчас: а именно: я алготрейдер - я хочу просто купить при пересечении скользящих и закрыться при обратном пересечении. Мне нужно начать писать тонну кода, чтобы открыть позицию, послать ордера, проконтролить, запомнить сайз и прочее, с учетом тысячи нюансов с ордер айди и прочим. И в итоге, я трачу 90% времени на инженерную работу, а не на алго-кодинг. И руки опускаются.

3. Оболочка из под которой можно управлять многими алгоритмами. Простейший Шелл, который можно подключить к нескольким квикам, и самое важно загрузить туда на исполнение код. Ну и управлять работой всех роботов. Видеть их статус и так далее. Опять же, в конечном итоге, мы все либо каждый для себя напишем эту штуку, либо, если я не супер про - то я пойму , что мне нужно будет это сделать, пойму, что это очень много работы, и что у меня просто нет ни времени ни компетенций, чтобы это сделать в пределах года. И поэтому я вынужден отвалиться.

Я согласен, что нет имеет смысл делать СтокШапр или Осу или ТСЛаб. Сто процентов. Но если разбить этот софт на составные части - а именно тестер, хранилище данных, оптимизатор, трейдер и так далее, то понятно, что это не единый "софт", это швейцарские ножи с кучей функций. Я согласен, что не нужно делать еще один швейцарский нож - комбайн. Но данная библиотека- это экзекьюшн блок данного софта. Вернее, часть экзекьюш блока. Я предлагаю рассмотреть возможность доделать проект до полноценного экзекьюшн блока. Не супер сложного навороченного. А простого, с базовыми функциями, простым и рабочим как Калашников.

Я пересмотрел и перерыл все проекты которые есть на текущий момент - все они - комбайны. Причем, в которых все части сделаны на среднем уровне. Потому что невозможно сделать везде хорошо. А поскольку все это в одном флаконе - то и стабильность страдает. Некоторые даже опционы добавили и все вообще стало тормозить как не в себя. Один из немногих кто разделил: это softalgotrade (https://softalgotrade.com/programs/trader/). Вот там есть такое отдельное приложение - Трейдер. Он берет скрипты, ставит их в работу и ими управляет. Чтобы можно было делать такие скрипты - нужны элементарные классы + пример-обертка. Что думаете?

**Comment by mkurtm** [comment]
ПС. Хотел еще сказать, что на рынке так и не нашел подобного решения. И, на мой взгляд, это очень востребованная история. Потому что софта, в котором можно что-то оттестировать, оптимизировать, проверить и прочее - очень много. От велса до тс. Но софта куда можно изолированно загрузить код на исполнение, с простым апи, и просто управлять своими роботами - такого просто нет.

**Comment by buybackoff** [comment]
Вопрос к Вам и ко всем - сколько вы готовы платить за набор "швейцарских
ножей"? Этот проект возник из личной надобности, и было понятно, что на
таком не заработать и возможно многим нужен как кирпичик. Копать глубже
просто нет сил, времени и экономических стимулов.

**Comment by mkurtm** [comment]
В том то и дело, что смысла делать большой софт - совершенно точно нет.
Я к тому, что все, используя этот кирпичик, итак сделали одни и те же вещи - которые я описал выше. Я только предлагаю их систематизировать.

**Comment by mkurtm** [comment]
Смотрите, если у меня будет хотя бы небольшая помощь, я готов сделать пример- обертку с комментарием логики работы, а также элементарные классы, необходимые для работы. Не знаю, потяну ли шелл оболочку самостоятельно. Просто мне нужно понимать стоит ли расчитывать на помощь. Потому что без неё я завязну.

**Comment by buybackoff** [comment]
@mkurtm к сожалению не могу двигать этот проект дальше, чем заявленная и много раз повторенная цель "повторить QLUA в C#". Но тут у нас открыты и очень либерально принимаются pull requests (если они не ломают текущий код, все разумные добавления точно примем).

Пишите в #195 если это все еще issue.
