### ISSUE TITLE
Нет подключения скриптов lua в Квик

### ISSUE THREAD

**Issue by cia76** [finsight/QUIKSharp#153]
Пытаюсь запустить скрипт QuikSharp.lua в Квик версии 7.16.1.36.

Ошибок нет, но последнее полученное сообщение: Connecting... Т.е. до сообщения Connected не доходим.

Начал отлаживать скрипты, обнаружил, что из при выполнении local status, client, err = pcall(response_server.accept, response_server ) в функцию обратно возврата нет.

```
local function getResponseServer()
    print('Waiting for a client')
	local i = 0
	if not response_server then
		log("Cannot bind to response_server, probably the port is already in use", 3)
	else
		while true do
			local status, client, err = pcall(response_server.accept, response_server ) -- Отсюда не выходит
			if status and client then
				return client
			else
				log(err, 3)
			end
		end
	end
end
```

**Comment by cia76** [comment]
Начал отладку. При запущенном скрипте в Квик (последнее сообщение Connecting...) запускаю QuikSharpDemo. Когда вызываем статус сервера, то обратно не возвращаемся. Код с моими правками:
`        private void buttonStart_Click(object sender, EventArgs e)
        {
            try
            {
                textBoxLogsWindow.AppendText("Подключаемся к терминалу Quik..." + Environment.NewLine);
                _quik = new Quik(Quik.DefaultPort, new InMemoryStorage());    // инициализируем объект Quik
                //_quik = new Quik(34136, new InMemoryStorage());    // отладочное подключение
            }
            catch (Exception ex) // Нужно понять почему объект Quik не создался, поэтому получаем ошибку для разбора
            {
                textBoxLogsWindow.AppendText($"Ошибка инициализации объекта Quik... {ex.Message}" + Environment.NewLine);
            }
            if (_quik != null)
            {
                textBoxLogsWindow.AppendText("Экземпляр Quik создан." + Environment.NewLine);
                try
                {
                    textBoxLogsWindow.AppendText("Получаем статус соединения с сервером...." + Environment.NewLine);
                    isServerConnected = _quik.Service.IsConnected().Result; // Отсюда не возвращаемся
                    if (isServerConnected)
                    {
                        textBoxLogsWindow.AppendText("Соединение с сервером установлено." + Environment.NewLine);
                        buttonRun.Enabled = true;
                        buttonStart.Enabled = false;
                    }
                    else
                    {
                        textBoxLogsWindow.AppendText("Соединение с сервером НЕ установлено." + Environment.NewLine);
                        buttonRun.Enabled = false;
                        buttonStart.Enabled = true;
                    }
                }
                catch
                {
                    textBoxLogsWindow.AppendText("Неудачная попытка получить статус соединения с сервером." + Environment.NewLine);
                }
            }
        }`

**Comment by buybackoff** [comment]
Из NuGet или мастера?

**Comment by cia76** [comment]
Весь код брал только отсюда, из GitHub

**Comment by buybackoff** [comment]
> pcall(response_server.accept, response_server ) -- Отсюда не выходит
проверьте firewall/антивирус и что порты везде указаны правильные. TCP сервер в Луа не принимает входящее соединение, много может быть причин. Вряд ли связано с кодом, который давно работает.

**Comment by cia76** [comment]
В скрипте qsutils
local port = 34130
local callback_port = port + 1

В строке подключения
_quik = new Quik(Quik.DefaultPort, new InMemoryStorage());    // инициализируем объект Quik
Quik.DefaultPort = 34130

Порты везде совпадают.

**Comment by buybackoff** [comment]
Можем у вас Луа обрезанная идет с Квиком, такое часто бывает. Посмотрите русский ридми, там ссылка как установить Lua for Windows. В любом случае что-то не так с подключением, а не кодом.

**Comment by cia76** [comment]
Firewall отключен. Все поры открыты.

Я согласен, что вряд ли в коде есть ошибка. Тем более, что написан он очень грамотно :-) Просто хочу понять, что нужно настроить, чтобы система заработала.

Луа пользую ту, что идет с Квиком. Сейчас с ней поработаю.

**Comment by cia76** [comment]
Поставил Lua for Windows отсюда: https://github.com/rjpcomputing/luaforwindows/releases

Сразу заработало и подключение и примеры. Вопрос снимается. Благодарю за помощь!
