### ISSUE TITLE
Как получить данные об ОИ

### ISSUE THREAD

**Issue by Prival1** [finsight/QUIKSharp#154]
Необходимо получение следующих данных для фьючерсов
Количество открытых позиций (Открытый интерес)
Количество заявок на покупку /продажу
Суммарный спрос/предложение

--

**Comment by Prival1** [comment]
100% позволяет, т.к. через этот тип соединения данные получает Qscalp, StockSharp...(могу продемонстрировать), но там к сожалению код закрыт.
Где смотреть API QLUA не знаю и что такое Pull Request тоже к сожалению пока не знаю ((

Но могу и готов поддержать проект финансово. И снова не знаю как это можно сделать :-).
Если не затруднит, свяжитесь по скайпу privalov-sv

З.Ы. Наши знания ограничены, лишь незнание безгранично...

**Comment by buybackoff** [comment]
Файл qlua.chm в папке где установлен квик. Документация к Lua API является
и документацией к этому проекту, цель была сделать один к одному
соответствие методов.

**Comment by buybackoff** [comment]
Open Interest получается через структуру данных AllTrade (таблица обезличенных сделок) через метод OnAllTrade, тут пример (закомменченный, но должен работать):

https://github.com/finsight/QUIKSharp/blob/81a7df943a32d30a7de4b9621a51623aab8fcba2/src/QuikSharp/Program.cs#L78

**Comment by Prival1** [comment]
Спасибо ОИ, нашел.... приходит в += Events_OnAllTrade.
А вот это не могу найти
1. Количество заявок на покупку /продажу
2. Суммарный спрос/предложение
![2018-04-21_15-54-09](https://user-images.githubusercontent.com/13386987/39398315-9e94ac18-4b14-11e8-833f-a2977915ff00.png)
![2018-04-21_15-54-56](https://user-images.githubusercontent.com/13386987/39398316-9eb5d334-4b14-11e8-9169-9da969981d3b.png)
В квике это точно есть. Прилагаю скрины. Подскажите как эти данные получить. Заранее спасибо.

**Comment by buybackoff** [comment]
@Prival1 смотрите #195. Это или не возможно, или читайте документацию дальше. @Pr0phet1c недавно добавил много полей для таблицы текущих параметров, может там есть.
