### ISSUE TITLE
connected и сразу после connecting

### ISSUE THREAD

**Issue by Dekanczo** [finsight/QUIKSharp#157]
Привет
Подскажите пожалуйста в чем может быть проблема. 
Поставил quik в wine. Всё хорошо, quik работает. Скачал последнюю версию QuikSharp и запустил скрипт из папки lua QuikSharp.lua . Появляется три окошка, горящие о том,  что все хорошо.  Далее запускаю проект с двумя строчками в main - создаю экземпляр на стандартный порт. Получаю два окошка с сообщениями Connected и Connecting. Почти одновременно. В чем может быть проблема или как можно её отследить?

**Comment by Dekanczo** [comment]
Попробовать их запустить немного проблематично, так как запускаю из под debian в rider

**Comment by Dekanczo** [comment]
Сейчас попробовал на винде в visual studio 2017 запустить QuikSharpDemo и RobotDemo. Первый подключается, второй нет.

**Comment by Pr0phet1c** [comment]
К сожалению, я тут помочь уже не смогу. Возможно, автор проекта сможет что-нибудь подсказать.

**Comment by buybackoff** [comment]
С Wine дел не имел и не хочу. Connected -> Connecting значит обрыв изначально успешного соединения, вероятно тут дело с сетевым стеком или еще с какими-то тонкостями.

Если Wine (или Parallels) позволяют коннектиться к порту с хоста, можно будет подумать сделать основную библиотеку как .NET Standard, чтобы можно было код на C# запускать с Линукса/Мака. Но я большой фанат Windows 10 + WSL, сам это буду делать если вдруг какой-то код работает только из Линукса и мне нужно подсоединиться к Квику из него. В обозримом будущем такого не предвидится.

**Comment by Dekanczo** [comment]
Можете подсказать куда примерно копать?

**Comment by buybackoff** [comment]
`quik в wine` мы даже пытаться не будем разбраться что там может пойти не так. Лучше сами делитесь опытом если смогли запустить в итоге.
