### ISSUE TITLE
Как ловить ошибки транзакций?

### ISSUE THREAD

**Issue by eugene20237** [finsight/QUIKSharp#159]
Отправляю заявки методом _quik.Orders.CreateOrder(...). Если транзакция неудачна, то блок catch не ловит исключение:
      try
      {
        transactionID = await _quik.Orders.CreateOrder(order);
      }
      catch (QuikSharp.TransactionException e)
      {
        // это не работает
      }
Как ловить такие исключения? Например, получаю ошибку "Не указан режим транзакции".

**Comment by Pr0phet1c** [comment]
Попробуйте после отправки заявки обработать результат с помощью TransactionReply.
Что-то вроде этого:
        TransactionReply lastTransactionReply = new TransactionReply();
        _quik.Events.OnTransReply += (TransactionReply transReply) => { if (transReply.TransID == res) lastTransactionReply = transReply; };

Как это работает в подробностях - уже не опишу. Давно этим вопросом занимался, и как только решил его в приемлемом для себя варианте - больше к нему не возвращался.

**Comment by Pr0phet1c** [comment]
В проект добавлены новые функции, умеющие (вроде как) ловить ошибки транзакций:
SendLimitOrder
SendMarketOrder
