### ISSUE TITLE
Бажит функция GetMoney, при определенном наполнении таблицы остатков по денежным средствам

### ISSUE THREAD

**Issue by aBaTaPbl4** [finsight/QUIKSharp#160]
В таблице лимитов по денежным средствам имеем следующие строчки (см картинку)
![image](https://user-images.githubusercontent.com/5055659/43221085-71b8887e-9054-11e8-82f4-dc7ae2e96f69.png)

Проблема в том, что в тесте ниже функция GetMoney всегда получает остаток (T0) 53,92USD, - и при этом нет никакой возможности вытащить остаток (T2) 866,35USD, - который как раз является реальным остатком денежных средств. Не нашел к сожалению метод получения всех записей таблицы.

        [Test]
        public void GetMoneyTest()
        {
            var firmId = _quik.Class.GetClassInfo(_settings.ClassCode).Result.FirmId;
            Currency currency = Currency.CreateByQuikClassCode(_settings.ClassCode);
            MoneyLimit moneyRest = _quik.Trading.GetMoney(clientCode, firmId, _settings.Tag, currency.Name).Result;
        }

Версия QuikSharp 1.0.0-beta2

**Comment by aBaTaPbl4** [comment]
Проблема решается вызовом GetMoneyEx, в моем случае она не работала, из-за того что я передавал параметры clientCode и firmId, не в том порядке, - копи паст вызова GetMoney.

Сделай пж одинаковый порядок параметров у GetMoney и GetMoneyEx

**Comment by Pr0phet1c** [comment]
Дело в том, что в основе данного проекта лежит точное повторение функций QLua, встроенного в квик. Из-за этого и возникают такие несуразности.
Вот так эти две функции выглядят в Qlua:
TABLE getMoney (STRING client_code, STRING firmid, STRING tag, STRING currcode)

TABLE getMoneyEx(STRING firmid, STRING client_code, STRING tag, STRING currcode, NUMBER limit_kind)

Так что, при всем понимании Вашего желания сделать одинаковый порядок записи параметров, этот вариант не рассматривается (во всяком случае пока автор проекта не примет решение о смене концепции.)

**Comment by buybackoff** [comment]
Именно так, как @Pr0phet1c написал.
Мы повторяем документацию Квика, чтобы можно было держать её открытой. Если этого + Intellisense, который четко показывает названия переменных, недостаточно, то это проблема пользователей, которые используют Copy-Paste.

По сути поведение в этом issue четко документировано, поэтому это даже не issue.

**Comment by aBaTaPbl4** [comment]
Всё программисты в том или ином объеме используют копи паст, так как это ускоряет написание нового кода. Значит это общая проблема. В то же время, если вы загляните в CodeStyle Google, Microsoft и т.д., - то увидите озвученную рекомендацию, по соблюдению порядка параметров. 
Также неясно ваше намерение всегда придерживаться такого же порядка параметров, как в QLua? При портировании кода с lua на C#, его так и так переписывать придется, уж слишком различны языки. Возможно, вам известны объективные причины для такого решения, но имхо для библиотеки, было бы лучше, если бы вы в подобных ситуациях отступали от канонов.

**Comment by buybackoff** [comment]
Это не каконы, это life hack - вместо того, чтобы писать документацию к этому проекту, можно всегда открыть QLUA.chm. Если кто-то будет переписывать из Lua в C# на этом проекте, то ожидаемое поведение - как в документации QLUA, и будут WTF почему мы поменяли переменные в методах. Если принципиально - обратись пж к разработчикам QLUA, чтобы они объяснили, почему они так сделали и переделали, тогда мы последуем за ними.
