### ISSUE TITLE
Первый запуск примера.

### ISSUE THREAD

**Issue by IFetisov** [finsight/QUIKSharp#162]
Здравствуйте.
Скомпилировал пример. Запустил. Жму коннект
-----------
Подключаемся к терминалу Quik..
Экземпляр Quik создан.
Получаем статус соединения с сервером....
----------
Далее на этом висим. 
Подскажите пожалуйста какая тут возможна диагностика?

**Comment by Pr0phet1c** [comment]
Интересный вопрос. На этом месте я еще ни разу не сталкивался с проблемами.
Для начала попробуйте проверить, не выдал ли Lua-скрипт в Квике ошибку выполнения.
Терминал не разорвал соединение с сервером? Попробуйте перекомпилировать проект (целиком все решение) еще раз. Перед запуском примера убедитесь, что счетчик времени сервера тикает в соответствии с реальным временем (без фризов по несколько секунд). Если ничего не поможет - запускайтесь из студии в режиме отладки с пытайтесь понять что не так.
Как вариант: кусок кода, который отвечает за проверку статуса коннекта, выделите в отдельный метод, чтобы получить возможность вместо строки 
                    isServerConnected = _quik.Service.IsConnected().Result;

использовать:
                    isServerConnected = await _quik.Service.IsConnected().ConfigureAwait(false);

**Comment by IFetisov** [comment]
Спасибо большое! Получилось соединиться. 
Теперь не получается получить класс инструмента.
Делаю вызов
.ClassCode = Quik.Class.GetSecurityClass("CETS_SWAP,GCRP,EQRP,EQRP_BND", "EUR000TODTOM").Result; 
.ClassCode = Quik.Class.GetSecurityClass("CETS_SWAP,GCRP,EQRP,EQRP_BND", "USD000TODTOM").Result; 
.ClassCode = Quik.Class.GetSecurityClass("CETS_SWAP,GCRP,EQRP,EQRP_BND", "SU26215RMFS2").Result; 
Получаю пустой результат.

**Comment by Pr0phet1c** [comment]
Думаю, у Вас некорректный (неполный) список классов, в которых вы ищете интересующие Вас инструменты. Например для указанной ОФЗ правильный код класса TQOB.

**Comment by IFetisov** [comment]
Добрый день.
Разве существует такое понятие "правильный код класса" для бумаги? Классов может быть много. Я смотрю информацию об инструменте. Пытаюсь понять что не так. По бумаге SBER у меня получается код класса EQRP c вышеуказанными параметрами. А по облигации надеюсь получить EQRP_BND.
![image](https://user-images.githubusercontent.com/40885403/46852554-14dcb600-ce04-11e8-883e-6434f00e06b7.png)

**Comment by IFetisov** [comment]
Спасибо за ответ!
Ну вообщем этот метод работает некорректно для некоторых классов (EQRP_BND, CETS_SWAP). В принципе он и не нужен, видимо разработан для тестовых целей. Если я собираюсь торговать бумажкой то я могу сам посмотреть код класса - это должно быть во входных параметрах к каждой бумаге. Главное что дальше подписка и получение данных работает.

**Comment by Pr0phet1c** [comment]
Где Вы там некорректность увидели?
Я Вам указал на Вашу ошибку в определении класса для конкретного инструмента, и указал какой какой класс для него является правильным. И свою правоту я могу доказать скриншотом из "боевого" терминала QUIK. А Вы, непонятно на чем основываясь, выдвигаете непонятные утверждения о некорректности работы функции. 
Прежде чем делать такие заявления - изучите информацию о том, на чем основан функционал данной библиотеки. Потом загляните в справку по QLua, которая прилагается к программе QUIK, и попробуйте сообщить разработчикам квика о том, что эта функция тестовая и работает некорректно.

**Comment by buybackoff** [comment]
@Pr0phet1c спасибо большое за помощь! Кажется вопрос решен.
@IFetisov если что-то не работает в библиотеке и Вы на 100% уверены, что входные параметры верны и с ними работает в чистом Lua без Q#, пожалуйста откройте отдельный issue со скриптом Lua, в котором то что Вам нужно работает, а в Q# не работает.
