### ISSUE TITLE
Не запускается скрипт QuikSharp.lua

### ISSUE THREAD

**Issue by Andrei78** [finsight/QUIKSharp#163]
Не стартует QuikSharp.lua.
Ошибка: C:\Open_Broker_QUIK\lua\qsutils.lua:41: attempt to index global 'logfile' (a nil value).

**Comment by Andrei78** [comment]
Версия Квика 7.19.0.51

**Comment by Andrei78** [comment]
Это все в директории Квика, верно? Ни папки, ни файла не нашел.

**Comment by Andrei78** [comment]
нет ничего из перечисленного. 
![lua](https://user-images.githubusercontent.com/43968157/46658964-22b0f200-cbde-11e8-8390-90bd585ad47a.jpg)

**Comment by Pr0phet1c** [comment]
Попробуйте в указанной на скриншоте папке создать соответствующую папку "logs" и в ней файл "QuikSharp.log" (обычный текстовый формат).
Еще, на всякий случай уточню, у Вас Lua for Windows на компьютере установлен?

**Comment by Andrei78** [comment]
Да, конечно, Lua for Windows установлен.

**Comment by Andrei78** [comment]
Вроде бы запустился, но выдает сообщение "Connecting...". Вроде как должно быть - Соединение установлено. Получается что скрипт непрерывно устанавливает соединение.

**Comment by Pr0phet1c** [comment]
Точно уже не помню (давно не смотрю что и в какой момент там пишется). Вроде одно сообщение появляется после запуска скрипта (и терминала, если скрипт не останавливали), и другое после соединения робота с терминалом.

**Comment by Pr0phet1c** [comment]
Я не являюсь автором проекта (лишь помогаю ему развиваться), поэтому не знаю как там все изначально было задумано, и не помню пришлось ли мне столкнуться с теми же проблемами, что и у Вас. Однако, другие пользователи на эту проблему вроде как не жаловались, а значит вряд ли она имеет место быть. Скорее всего просто где-то что-то не срослось именно в Вашем случае, и пришлось "дорабатывать напильником", как это часто бывает. Если вопрос решен, закройте тему, плиз. Не сочтите за труд.

**Comment by Andrei78** [comment]
Большое спасибо за помощь!
