### ISSUE TITLE
Получение таблиц с лимитами и рисками

### ISSUE THREAD

**Issue by IFetisov** [finsight/QUIKSharp#164]
Как получить лимиты разобрался.
Вызываем
quik.Trading.GetMoneyEx(firmId, clientCode, "EQTV",  "SUR", 0).Result;
quik.Trading.GetMoneyEx(firmId, clientCode, "EQTV",  "SUR", 1).Result;
quik.Trading.GetMoneyEx(firmId, clientCode, "EQTV",  "SUR", 2).Result;
Используем поле CurrentBal

**Comment by IFetisov** [comment]
И параметры рыночных рисков тоже не знаю как получить :(
![image](https://user-images.githubusercontent.com/40885403/47084071-303c2c80-d21b-11e8-9419-e9042701b9f5.png)

**Comment by Pr0phet1c** [comment]
Как эти параметры получить на QLua Вы знаете?

**Comment by IFetisov** [comment]
Не знаю :( 
Попробывал так - получил 0 записей. 
function qsfunctions.getCCPPriceRange(msg)
   local result = {}
   local tbl = "ccppricerange"
   local n = getNumberOf(tbl)
	for i=0,n-1 do
		local litem = getItem(tbl,i)
		table.insert(result, litem)
	end
   msg.data = result
   return msg
end

**Comment by Pr0phet1c** [comment]
Вопрос: Откуда Вы взяли наименование таблицы "ccppricerange"?

**Comment by IFetisov** [comment]
Из инструкции по квик экспортеру.
6.27 CCPPriceRange – параметры рыночных рисков
на фондовом рынке
Параметр Назначение Тип данных
Функция
API
ClassCode Код класса Varchar(12) AddString
SecCode Код инструмента Varchar(12) AddString
CCPNum Диапазон smallint AddInteger
![image](https://user-images.githubusercontent.com/40885403/47213333-52f94d00-d3a3-11e8-8868-0c2b1a7dea32.png)

**Comment by Pr0phet1c** [comment]
Вы случайно информацию не для серверной части квика подсмотрели? Я больше нигде не нашел упоминания "Модуля экспорта биржевой информации". Пункт 6.27 мне также не удалось разыскать (ни в info, ни в руководстве пользователя).

**Comment by IFetisov** [comment]
Это модуль экспорта из квик в базу данных. Квик-экспортер.
Вообщем понял что сделать это невозможно т.к. в списке таблиц из документации этой таблицы  нет. Задачу можно закрывать.
Спасибо!

**Comment by Pr0phet1c** [comment]
Можно попробовать вместо "ccppricerange", использовать "ccp_price_range", вдруг сожрет?...
Но формально, я тоже так и не смог найти способом программным путем получить данную таблицу.
