### ISSUE TITLE
Некорректная работа getSecurityClass

### ISSUE THREAD

**Issue by IFetisov** [finsight/QUIKSharp#165]
В системе есть классы в которых имеется знак подчеркивания например CETS_SWAP
По ним эта функция работает некорректно.

--- Функция предназначена для определения класса по коду инструмента из заданного списка классов.
function qsfunctions.getSecurityClass(msg)
    local spl = split(msg.data, "|")
    local classes_list, sec_code = spl[1], spl[2]

	for class_code in string.gmatch(classes_list,"%a+") do
		if getSecurityInfo(class_code,sec_code) then
			msg.data = class_code
			return msg
		end
	end
	msg.data = ""
	return msg
end
Потому что gmatch работает не так как требуется
![image](https://user-images.githubusercontent.com/40885403/47090550-d132e380-d22b-11e8-94ef-4e53c57f179c.png)

**Comment by buybackoff** [comment]
Спасибо! В этом был баг #162?

Какой должет быть gmatch? Обычный RegEx `"([A-Za-z0-9_]+)"` работает?

**Comment by Pr0phet1c** [comment]
Можно попробовать такой вариант строки:

for class_code in string.gmatch(classes_list,"%P+") do

но я пока этого сделать не могу

**Comment by IFetisov** [comment]
Да в этом был баг 162
У меня работает  вот с таким паттерном. "([^,]+)" 
Подсмотрел его в реализации функции split.

**Comment by buybackoff** [comment]
Эта штука просто говорит "не запятая". Мы это хотим?

**Comment by IFetisov** [comment]
![image](https://user-images.githubusercontent.com/40885403/47152499-8d9cb000-d2e5-11e8-8c87-fc83aefa9d44.png)

**Comment by Pr0phet1c** [comment]
Ясно. Спасибо. 
Значит придется использовать "([^,]+)".
Когда доберусь - внесу изменения.

**Comment by Pr0phet1c** [comment]
Сделано
