### ISSUE TITLE
Получение стакана.

### ISSUE THREAD

**Issue by IFetisov** [finsight/QUIKSharp#169]
У меня задача проанализировать несколько инструментов и выбрать самый подходящий по цене.
Не могу разобраться с получением стакана. 
1. Subscribe - получается ты подписался на что то и это навсегда остается в квик? Никакого варианта все почистить нет? Только сохранять в массив все сделанные подписки и при выходе из программы вычищать.
2. Вообщем отписался от всего. (В метод OnQoute добавил UnSubscribe для инструментов на которые не подписывались в текущей сессии приложения). Теперь надо скачать текущие данные по 3м бумажкам и их проанализировать. - Подписываюсь, жду 5 минут все пусто. - это значит что в стакане пусто или что нет изменений за 5 минут или что терминалу вообще не до моего стакана - он прокачивает сделки или еще что то?
Вообщем я не пойму в каком направлении надо двигаться.
Может надо сделать Subscribe а потом сразу вызвать функцию getQuoteLevel2? Или можно как-то зафорсить вызов OnQoute или в любом случае пока не будет изменений стакан получить не получится?

**Comment by IFetisov** [comment]
В итоге сделал так 
1.в луа

function qsfunctions.Level_II_Quotes(msg)
    local spl = split(msg.data, "|")
    local class_code, sec_code = spl[1], spl[2]
    local status, ql2 = pcall(getQuoteLevel2, class_code, sec_code)

        if status then
            msg.data = ql2
            msg.data.class_code = class_code
            msg.data.sec_code = sec_code
            msg.data.server_time = server_time
	    return msg
        else
            OnError(ql2)
        end
end

В C#
        public async Task<OrderBook> GetQuotes(string class_code, string sec_code)
        {
            var response = await QuikService.Send<Message<OrderBook>>(
                (new Message<string>(class_code + "|" + sec_code, "Level_II_Quotes"))).ConfigureAwait(false);
            return response.Data;
        }

**Comment by buybackoff** [comment]
Получение стаканов работало с самого начала, повторяя QLUA API. Кажется Вы нашли решение. Если нет, то напишите в #195
