### ISSUE TITLE
не полная структура SecurityInfo

### ISSUE THREAD

**Issue by vsemnado** [finsight/QUIKSharp#170]
в структуре SecurityInfo отсутствует параметр "min_price_step" (минимальный шаг цены), соответственно функцией GetSecurityInfo() получить данный параметр инструмента не возможно

**Comment by Pr0phet1c** [comment]
Действительно не было. Класс старый, но момент его создания такого поля видимо еще не было в квике. Сейчас добавил, но на проверку нет времени. Проверьте самостоятельно, плиз (и сообщиет о результатах по возможности). Для проверки можно воспользоваться демо-приложением из проекта.

**Comment by vsemnado** [comment]
добавлено поле типа "string", а в описании qlua указано "NUMBER", почему именно так? поясните пожалуйста!

**Comment by Pr0phet1c** [comment]
Это моя ошибка. Утром в спешке делал, видимо еще не до конца проснулся.
Переделал на "double", но как это неудивительно может и не заработать, т.к. в квике для некоторых полей присутствует глюк, когда не смотря на наличие NUMBER в описании поля, по факту квик выдает srting. Сможете взять свежую версию (с типом double) и проверить?

**Comment by vsemnado** [comment]
проверить смогу только вечером, отпишусь. Меня смущает то, что я добавлял подобное поле только с типом int - результата не было.

**Comment by buybackoff** [comment]
Можно сделать в Lua "+value", тогда не важно что там возвращается (или как-то так, в JavaScript так). Double ОК для интов меньше 2^53, не теряет точности.

**Comment by Pr0phet1c** [comment]
@vsemnado , минимальный шаг цены может быть НЕ целым числом (как вариант)
@buybackoff , вроде в lua используется "+0" для преобразования в число. Я на досуге попробую посмотреть на сколько это применимо в нашем случае

**Comment by vsemnado** [comment]
я не профессиональный программист, моих навыков скорее всего будет не достаточно, так что вся надежда на Вас, уважаемые авторы проекта.

**Comment by Pr0phet1c** [comment]
В общем, в lua-коде это не сделать. Единственный вариант: перерабатывать метод "get" в свойстве уже внутри класса, приводя значение к интересующему нас, о как-то я не уверен в целесообразности такого усложнения кода, ради очень редких случаев недоработок со стороны разработчиков квика.
Все что остается, это проверить работоспособность с типом double в текущем варианте, и если проблем не возникнет - спокойно юзать.

**Comment by vsemnado** [comment]
меня бы устроил любой тип, хоть string хоть double, главное получить значение (мне очень важно), вечером после окончания сессии на фондовом ММВБ отпишусь о результате проверки.

**Comment by vsemnado** [comment]
Проверил. В варианте с типом double работает (string не проверял). Всем спасибо!
