### ISSUE TITLE
Не удалось найти тип или имя пространства имен "QuikSharp" 

### ISSUE THREAD

**Issue by Nikolaev-Nikolay** [finsight/QUIKSharp#173]
Ошибка	CS0246	Не удалось найти тип или имя пространства имен "QuikSharp" (возможно, отсутствует директива using или ссылка на сборку).	AutoConnector	E:\QM\QUIKSharp-master\Examples\AutoConnector\AutoLogin.cs	
Вылетает  такая ошибка.
Что я делаю не так?!

**Comment by buybackoff** [comment]
Это не проблема QuikSharp. Из ошибки кажется нет Reference на dll quiksharp. Посмотрите тут в руском Readme и тэге Questions и погуглите как восстанавливать/добавлять референсы. Кажется была такая проблема с примером и тут обсуждали.

**Comment by Nikolaev-Nikolay** [comment]
Это вот это?! 
Добавил ссылку, но ошибок стало больше.
https://docs.microsoft.com/ru-ru/visualstudio/ide/managing-references-in-a-project?view=vs-2017
Еще по запуску скрипта луа - добавил ссылки на установленные пакеты - но никакой реакции - что должно быть при запуске скрипта  квике?! Он должен сообщить скрипт запустился или еще что нибудь?!

**Comment by Pr0phet1c** [comment]
Обычно, ошибки компиляции демонстрационных проектов возникают из-за отсутствия скомпилированной библиотеки QuikSharp.dll, на которую ссылаются эти проекты. После скачивания и развертывания решения, эта библиотека еще не скомпилирована, поэтому перед компиляцией приложений, сначала надо скомпилировать саму библиотеку. В подавляющем большинстве случаев достаточно просто дважды подряд пересобрать все решение (при первой попытке возникает ошибка, при второй все проходит гладко). Но бывают и более сложные случаи, когда приходится удалять из проекта и заново скачивать/устанавливать сторонние библиотеки из тех, что использованы в проекте. в остальном, проблем возникать не должно.
При запуске Lua-части в квике, какие-то сообщения типа "Connecting..." выскакивают, но я сейчас уже не вспомню что именно там написано. Кажется там даже два подряд сообщения всплывают.

**Comment by Nikolaev-Nikolay** [comment]
поле "Вставить типы взаимодействия" от True to False и работает  - вот это было.
Вообщем кошмар этот VS :))
http://qaru.site/questions/5230473/error-cs1759-while-building-vsix-project-in-visual-studio-2015

**Comment by Nikolaev-Nikolay** [comment]
все заработало!
Спасибо!
Я попробую на python достучаться.
