### ISSUE TITLE
Подскажите по поводу тикера инструмента.

### ISSUE THREAD

**Issue by Nikolaev-Nikolay** [finsight/QUIKSharp#174]
Вроде все подключил - предлагает ввести тикер инструмента (SecCode)
 Я вообщем то понимаю, что это такое - например для северстали CHMF.
Но когда ввожу - говорит, что не находит.
 Под
![qwick](https://user-images.githubusercontent.com/40342151/49440393-59257a80-f7e5-11e8-9cbc-4bd0112eafb4.png)
скажите что вводить и где искать?!

**Comment by Pr0phet1c** [comment]
Странно. Должно работать. Поняли Вы все правильно, тикер - это код инструмента (он же SecurityCode). Т.е. для Северстали в качестве тикера надо указывать CHMF.
Если будет возможность - проверю у себя.

**Comment by Nikolaev-Nikolay** [comment]
Да пожалуйста проверти у себя.

**Comment by Nikolaev-Nikolay** [comment]
А у Вас какая версия квика?! У меня 7.14.1.7
А вы сможете прислать мне ехе  файл - он же ничего конфидициального не содержит. Может у меня компbлируется не так.
Nikolaev_Nikolay@mail.ru

**Comment by Pr0phet1c** [comment]
Версия квика: 7.19.0.51, но в данном случае это не принципиально. Приложение писалось и тестировалось около года назад. Скомпилированную демку отправил на почту

**Comment by Nikolaev-Nikolay** [comment]
Вообщем  все получилось!
Перекомпилировал проект как в видео реадми   и самое главное - надо открывать lua из папки в проекте (/srs/QuikSharp.lua)- не копировать в квик.
