### ISSUE TITLE
Вызвано исключение: "System.InvalidOperationException" в System.Windows.Forms.dll

### ISSUE THREAD

**Issue by Nikolaev-Nikolay** [finsight/QUIKSharp#175]
Запускаю проект.
Вроде все работает.
Но когда хочу получить исторические данные (да и вообще любые данные из функций в окне)
вылетает 
Получаем таблицу информации...
Вызвано исключение: "System.InvalidOperationException" в System.Windows.Forms.dll

 System.Windows.Forms.dll- что там создает исключение?
Где искать - почему возникает исключение?!

**Comment by buybackoff** [comment]
@Nikolaev-Nikolay , почитайте внимательно второй параграф секции решения проблем в русском ридми: https://github.com/finsight/QUIKSharp/blob/master/README.RU.md#%D1%80%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC

**Comment by Nikolaev-Nikolay** [comment]
Так при чем тут это- вот место:
строчка 270 в Formmain.cs
{
                            textBoxLogsWindow.AppendText("Получаем исторические данные..." + Environment.NewLine);
                            toolCandles = await _quik.Candles.GetAllCandles(tool.ClassCode, tool.SecurityCode, CandleInterval.H1).ConfigureAwait(false);
                            textBoxLogsWindow.AppendText("Выводим исторические данные в таблицу..." + Environment.NewLine);
                            toolCandlesTable = new FormOutputTable(toolCandles);
                            toolCandlesTable.Show();
                        }
Исторические данные получили - а в таблицу вывести не можем. Вот я спрашиваю - что может быть? Код не работает.

**Comment by Pr0phet1c** [comment]
Надо разбираться. Приложение писалось давно, и вывод свечек в таблицу тестировался самым первым. Т.е. работали абсолютно все функции приложения.
Но после недавнего внесения исправлений решил перевести запуск ряда методов на режим async away, результаты не проверял. Постараюсь в ближайшее время проверить.

**Comment by Nikolaev-Nikolay** [comment]
Я нашел что то типа - действие из другого потока 
Нельзя из вторичных потоков обращаться к GUI
http://www.cyberforum.ru/windows-forms/thread1721018.html

**Comment by Nikolaev-Nikolay** [comment]
режим async away - а как было до этого - есть пример кода,  который был раньше?

**Comment by Pr0phet1c** [comment]
В общем, лучшее - враг хорошего. Не было приложение заточено под мультипоточность изначально, и нефиг было пытаться на скорую руку что-то менять. Вернул все к старому варианту реализации (без async/away). Можно забирать.

**Comment by Nikolaev-Nikolay** [comment]
Да да вот я поставил и посмотрел
![2](https://user-images.githubusercontent.com/40342151/49644442-422b9600-fa3a-11e8-88c0-c14c1dc8ffaa.png)

  | Имя | Значение | Тип
-- | -- | -- | --
  | err.Message | "Недопустимая операция в нескольких потоках: попытка доступа к элементу управления 'textBoxLogsWindow' не из того потока, в котором он был создан." | string

**Comment by Nikolaev-Nikolay** [comment]
Вобщем заработало - данные в таблицу выводят - но 
вот значение дата - время почему так - ведь должно быть нормальное время.
![date_time](https://user-images.githubusercontent.com/40342151/49650600-95a7df00-fa4e-11e8-925d-02c74619bafd.png)

У меня вопрос - как такой запрос организовать на python
 - покажите пожалуйста, что отправляется в сокет?!

**Comment by Pr0phet1c** [comment]
С датами как раз все в порядке. Так и должно быть. Таблица выводится исключительно в целях демонстрации получения данных. Преобразование типов не производится, тупо назначается DataSource. "Демка", это все же не полноценный программный продукт. Она призвана продемонстрировать основные возможности библиотеки, на простых примерах реализации некоторых методов. Предполагается, что все тонкости пользователь будет реализовывать самостоятельно.

по python - это уже не ко мне.

**Comment by Nikolaev-Nikolay** [comment]
>           С датами как раз все в порядке. Так и должно быть. Таблица выводится исключительно в целях демонстрации получения данных. Преобразование типов не производится, тупо назначается DataSource. "Демка", это все же не полноценный программный продукт. Она призвана продемонстрировать основные возможности библиотеки, на простых примерах реализации некоторых методов. Предполагается, что все тонкости пользователь будет реализовывать самостоятельно.
> по python - это уже не ко мне.
Покажите пожалуйста где преобразование типов делать - я разберусь с кодом. Данные о времени очень нужны просто.
Заранее спасибо!

**Comment by Pr0phet1c** [comment]
Не понимаю вопроса. Преобразование типов надо делать там, где Вы обрабатываете данные.
В демо-приложении я этого делать не буду, т.к. для этого придется создавать отдельную форму вывода, что выходит за рамки демонстрации базовых возможностей.

**Comment by Pr0phet1c** [comment]
Что касается робота, то там никаких изменений я не делал и он нормально работает (во всяком случае, у меня). Возможно, Вы не учли, что программе требуется некоторое время на запрос и получение таблицы свечей, или недостаточно внимательно прочитали предупреждение.
![2018-12-10](https://user-images.githubusercontent.com/14761254/49718490-4be81000-fc6b-11e8-9e56-7770e04d1c84.png)
![2018-12-10 1](https://user-images.githubusercontent.com/14761254/49718495-50142d80-fc6b-11e8-91ed-a09b8aacf94e.png)

**Comment by euvgub** [comment]
> * покажите пожалуйста, что отправляется в сокет?!
Wireshark показывает, что в qlua socket server приходит, например такое {"data":"","id":269,"cmd":"isConnected","t":1555400409924}
При отсылании точно такого же с помощью python socket клиента - сервер в ответ ничего не присылает,  sock.recv - empty
Что должен отсылать python socket client, чтобы получать response от quiksharp?
`import json
import socket
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server_address = ('127.0.0.1', 34130)
sock.connect(server_address)
a_dict = b'{"data":"","id":269,"cmd":"isConnected","t":1555400409924}'
serialized_dict = json.dumps(a_dict)
sock.sendall(serialized_dict)
while(True):
    data = sock.recv(1024)
    print(data)`
