### ISSUE TITLE
Многопоточная обработка событий OnQuote, OnAllTrade, NewCandle 

### ISSUE THREAD

**Issue by AndrewTimofeev** [finsight/QUIKSharp#177]
Это бага или фича? Поидее мы работаем с данными вида time-series и как-то не понятно получать не по-порядку во времени.  Можно это как то исправить?
![screenshot_2](https://user-images.githubusercontent.com/42830505/50090505-c55aa200-0219-11e9-8cf3-01d4ab28a916.png)

**Comment by AndrewTimofeev** [comment]
Вообщем меня волнует только гарантия последовательности во времени, каким образом ее можно добиться?

**Comment by buybackoff** [comment]
Смотрите #7 и все связанные issues. Если вы думаете, что это баг Q#, а не поведение QLUA, уточните пожалуйста. Я бы не стал полагаться на `LuaTimeStamp`, я сам не помню где оно используется. Конкретно в Вашем примере - гарантирует ли QLUA, что элементы сортированы. Со стороны Q# мы точно ничего не делаем с данными по пути к клиенту - как приходят, так и отправляем. Если Вы пользуетесь расширенной API (за пределами QLUA, добавляли что-то полезное для свечей и прочее), то уточните пожалуйста. Из текста не понятно, в чем именно проблема.
