### ISSUE TITLE
Переработка процедуры получения TransID

### ISSUE THREAD

**Issue by Pr0phet1c** [finsight/QUIKSharp#179]
При разработке процедур формирования заявок столкнулся с проблемой дублирования TransID, если заявки формировались после перезапуска приложения.
Есть предложение переработать строку:
transaction.TRANS_ID = QuikService.GetNewUniqueId();

и представить ее в таком виде:
            transaction.TRANS_ID = Math.Abs(QuikService.GetNewUniqueId() - Convert.ToInt32(DateTime.Now.Hour & DateTime.Now.Minute & DateTime.Now.Second));

Нет ли каких-нибудь противоречий?

**Comment by buybackoff** [comment]
Я бы лучше сделал memory mapped file со счетчиком. Проблема этого TRANS_ID в том, что его размер ограничен, поэтому просто рандом не получалось.

`Convert.ToInt32(DateTime.Now.Hour & DateTime.Now.Minute & DateTime.Now.Second)` - это будет очень часто равно нулю на первый взгляд.

По идее TRANS_ID должны быть persistent, это даже было раньше. Скоро верну надеюсь.

Можно для начала просто текстовый файл, но flush/fsync/ReadAllText/WriteAllText могут быть медленными даже в контексте Квика. Чтение же из mmaped файла как из памяти и данные остаются в сохранности даже если приложение вылетает, главное чтобы операционная система оставалась живой.

Также можно SQLite/LMDB. С точки зрения Quik# можно добавить интерфейс счетчика и дать возвожность инициализировать со внешним инстансом, тогда вопрос persistence останется за пределами.

**Comment by Pr0phet1c** [comment]
Попробую разобраться с MemoryMappedFile. Может найду какое-то решение.

Но я тут поглубже залез в текущий код и обнаружил странность.
У нас есть строка
transaction.TRANS_ID = QuikService.GetNewUniqueId();
Которая ведет нас к строке:
var newId = Interlocked.Increment(ref _correlationId);

_correlationId у нас задается в:

        internal void InitializeCorrelationId(int startCorrelationId)
        {
            _correlationId = startCorrelationId;
        }
где в качестве параметра надо передать startCorrelationId
И дальше (из вразумительного) я нашел только вот это:
        public void InitializeCorrelationId(int startCorrelationId)
        {
            QuikService.InitializeCorrelationId(startCorrelationId);
        }

В результате, я нигде не смог найти присвоения конкретного значения переменной "startCorrelationId", а значит и все остальное вряд ли может работать корректно.

Или я чего-то не учел, в силу недостатка знаний?

И кстати, рандом ведь можно ограничить по размеру (значению):

var rnd = new Random();
var n = rnd.Next(100, 1000000);

Разве такая конструкция неприменима (если не задаваться целью синхронизации значений с другими приложениями, подключенными к тому же самому терминалу)?

**Comment by buybackoff** [comment]
Просто использовался один и тот же счетчик для случаев когда нужны уникальные значения.

`var n = rnd.Next(100, 1000000);` может повторяться. К тому же хотелось, чтобы TRANS_ID были монотонными.

Вот так можно открыть mmaped file и получить поинтер к началу данных:

```
            var mmf = MemoryMappedFile.CreateFromFile(_fileStream,
                null,  // $@"{Path.GetFileName(_filePath)}.{unique}"
                bytesCapacity,
                _isWriteable ? MemoryMappedFileAccess.ReadWrite : MemoryMappedFileAccess.Read, HandleInheritability.None,
                true);
            _mmf = mmf;

            byte* ptr = (byte*)0;
            _va = _mmf.CreateViewAccessor(0, bytesCapacity, _isWriteable ? MemoryMappedFileAccess.ReadWrite : MemoryMappedFileAccess.Read);
            _vaHandle = _va.SafeMemoryMappedViewHandle;
            _vaHandle.AcquirePointer(ref ptr);

            _pointer = ptr;
            _length = checked((int)bytesCapacity);
```

Дальше можно просто через `Interlocked.Increment(ref *(int*) pointer)`.

Или взять полный пример отсюда: https://github.com/AdaptiveConsulting/Aeron.NET/blob/7bdfe9e361323b79641e05505f6086165406248a/src/Adaptive.Agrona/Util/MappedByteBuffer.cs

**Comment by Pr0phet1c** [comment]
Понял. Спасибо.
А мы точно хотим сохранять файл на диске? Просто в памяти держать недостаточно? Или в этом случае он при выгрузке приложения обязательно окажется удален из памяти?

**Comment by buybackoff** [comment]
> Или в этом случае он при выгрузке приложения обязательно окажется удален из памяти?

Именно так. 

Я бы все-таки вынес как интерфейс с возможностью инициализации QuikSharp с ним, как в примере с correlation id. Persistence нужно делать или хорошо для всего или оставлять за пределами проекта.

**Comment by Pr0phet1c** [comment]
Нужна помощь. Моих знаний не хватает.
Пока иду по пути простой реализации (в отдельном проекте работает стабильно вроде):

        internal int GetUniqueId()
        {
            string pathQuik = "D:";
            string diskFileName = pathQuik + "\\" + "UniqueID.QUIKSharp";
            MemoryMappedFile mmf = MemoryMappedFile.CreateFromFile(diskFileName, FileMode.OpenOrCreate, "UniqueID", 1024 * 10);
            MemoryMappedViewAccessor accessor = mmf.CreateViewAccessor();
            int newId = accessor.ReadInt32(1);
            if (newId == 0)
            {
                newId = Convert.ToInt32(DateTime.Now.ToString("ddHHmmss"));
            }
            else
            {
                if (newId >= 2147483638) newId = 100;
                newId++;
            }
            accessor.Write(1, newId);
            accessor.Dispose();
            mmf.Dispose();
            return newId;
        }

Надо в переменную filePath прописать путь к info.exe, но я не понимаю как мне вызвать GetWorkingFolder() внутри QuikService.
Или может быть я совсем неправильно делаю?

**Comment by buybackoff** [comment]
А зачем хранить этот файл со счетчиком в той же папке где info.exe? Почему
бы не в Path.Combine(
Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),
"QuikSharp")?

Или любой другой стабильной папке?

Также стоит держать открытыми MemoryMappedFile и MemoryMappedViewAccessor
внутри счетчика, и только увеличивать значение, так как открытие/закрытие
относительно медленная процедура.

**Comment by Pr0phet1c** [comment]
Начну со второго пункта: Это временно. Потом попробую вынести определение за пределы функции, тогда и оставлю открытыми.

Теперь по info.exe. На своем примере:
У меня на машине запущено два квика и 6 (шесть) различных экземпляров QUIK#. 4 из них работают в одном терминале, еще 2 в другом.
Очевидно, что роботы запущенные под первыми 4-мя экземплярами должны смотреть в один файл, а другие два - в другой.
"С:\" может быть закрыт для доступа пользователей. Диска D может вообще не быть на компе. Нужно:
- место, которое будет гарантировано найдено для всех экземпляров QUIK#, 
- файл должен быть уникальным для каждого терминала. 

На мой взгляд, самое логичное место - это папка с самим квиком. А в Вашем варианте, у меня будут созданы 6 различных файлов, и я не уверен, что в результате мы получим то, чего пытаемся добиться
Я не прав?

**Comment by Pr0phet1c** [comment]
Так в том то и проблема, что "_q" у нас тут нет, а передавать его в качестве параметра, при обращении к данной функции, возможно не очень правильно, если мы потом решим заменить ею старую функцию "GetNewUniqueId()".

Потому что в том же "QuikService.cs" у нас есть строка:

                request.Id = GetNewUniqueId();

Внутри метода "internal async Task<TResponse> Send<TResponse>(IMessage request, int timeout = 0)"

**Comment by buybackoff** [comment]
1. Создаем QuikService как обычно
2. Получаем адрес info.exe для этого сервиса
3. Инициализируем счетчик для TRANS_ID - для этого нужен новый метод и интерфейс, без вызова этого нового метода по умолчанию создается счетчик в памяти.
4. Вызываем новый метод `InitializeTransIdCounter(ITransIdCounter counter)`, этот метод заменяет счетчик по умолчанию: `InitializeTransIdCounter(new MyTransIdPersistentCounter(_q.Service.GetWorkingFolder().Result)`

Без пункта 4 в пункте 1 всегда создается базовый `ITransIdCounter`, имплементацию которого нужно добавить и не связывать его с correlation id.

Id который исопльзовался для correlation id можно оставить как есть - он исплоьзуется для matching-а резальтатов запроса в Квик к TaskCompletoinSource, которые висят в словаре с correlation id как ключь и ждут ответа от Квика. Они никак не связаны с TransId, и если инстанс перезапускается, то все TaskCompletoinSource все равно умирают.

**Comment by Pr0phet1c** [comment]
В общем, предложенный Вами путь оказался для меня сложноватым (сказывается недостаток знаний). Пока реализовал через добавление паблик свойства, с его определением при инициализации. Если будет время - посмотрите в моей ветке как оно сделано. Если скажете, что это плохой вариант - откачу обратно (PR пока не делал)
