### ISSUE TITLE
Использование на терминальном сервере.

### ISSUE THREAD

**Issue by IFetisov** [finsight/QUIKSharp#180]
Подскажите можно ли как то устранить проблему.
Сделал виртуальную машину. Туда коннектятся 2 человека. Каждый под своим логином и каждый запускает свой квик. 
В итоге приконнектится к нему библиотекой Квикшарп получается у того кто первый.
Второй когда пытается приконектиться просто подвисает.

**Comment by Pr0phet1c** [comment]
Скопируйте Lua-часть в отдельную папку, в файле qsutils.lua есть строка:
local port = 34140
Поменяйте в ней порт (например на 34142)
И во втором квике запускайте скрипт из этой папки.

Соответственно, проект, который должен работать во втором квике, надо перестроить на другой порт, при инициализации объекта Quik.
