### ISSUE TITLE
Плавающие QuikSharp.LuaException как отладить и как избавиться

### ISSUE THREAD

**Issue by IFetisov** [finsight/QUIKSharp#186]
QuikSharp.LuaException: 'Lua error: D:\QUIK\lua\qsfunctions.lua:746: attempt to index field '?' (a nil value)'

**Comment by Pr0phet1c** [comment]
У меня встречный вопрос:
Откуда у Вас в этом файле 746 строк взялось?
Я у себя только 733 наблюдаю.

**Comment by buybackoff** [comment]
Пишите в #195 если это все еще issue.
