### ISSUE TITLE
Серии опционов

### ISSUE THREAD

**Issue by petrovvova** [finsight/QUIKSharp#187]
Добрый день! Возможно, я не разобрался, человек в этом новый, прошу простить. 
А как можно запросить доску опционов с определенной датой исполнения? Не нашел нигде в библиотеке QUIKsharp соответствующее поле.

**Comment by Pr0phet1c** [comment]
Никак.
Подробности тут:
https://forum.quik.ru/forum10/topic748/

**Comment by Pr0phet1c** [comment]
Хотя, возможно, я Вас обманул.
Сейчас нашел кем-то реализованную функцию:
GetOptionBoard(string classCode, string secCode);
Попробуйте воспользоваться. НО не забудьте прочитать информацию по ссылке, которую я ранее предоставил. Там есть важная информация о правилах настройки терминала, для того, чтобы эта функция могла работать.

**Comment by buybackoff** [comment]
> Сейчас нашел кем-то реализованную функцию:

@Pr0phet1c  Git Blame говорит что это ты два года назад её добавил :)

https://github.com/finsight/QUIKSharp/blame/7ab40ba9bf93d5b8c4811e94458f457d683c14b2/src/QuikSharp/TradingFunctions/TradingFunctions.cs

**Comment by Pr0phet1c** [comment]
Удивительно. Видимо спер у кого-то, чтобы не пропадало. Я ж сам опционы не торгую...  :)

**Comment by spvik** [comment]
Привет, это метод мной был добавлен пару лет назад, и он возвращает все опционы квартальной экспирации, а там уже дальше сортируешь как тебе надо

**Comment by Pr0phet1c** [comment]
Ну вот, теперь знаем кому спасибо сказать... ;)

**Comment by petrovvova** [comment]
Спасибо вам, добрые люди!
