### ISSUE TITLE
Обработка результат заявки

### ISSUE THREAD

**Issue by IFetisov** [finsight/QUIKSharp#188]
Привет коллеги.
Подскажите как правильно обрабатывать результаты исполнения заявки. В комментариях написано FilledValue - сумма исполнено, но там всегда 0
Пытался написать что то такое. Но это никак не хочет взлетать :(  
не получается узнать сумму.
        void OnOrderDo(Order order)
                        if (order.Balance != WaitOrders[order.TransID].OrderBalance)
                        {
                            ExecutedVolume += (WaitOrders[order.TransID].OrderBalance - order.Balance);
                            if ((order.State == QuikSharp.DataStructures.State.Completed) ||
                                (order.State == QuikSharp.DataStructures.State.Canceled))
                            {
                                OrderedVolume -= order.Balance;
                                if (CleanWaits)
                                    WaitOrders.Remove(order.TransID);
                                else
                                    WaitOrders[order.TransID].OrderBalance = 0;
                                ExecutedVolumeAmount += (order.FilledValue - WaitOrders[order.TransID].BalanceValue);
                                WaitOrders[order.TransID].BalanceValue = order.FilledValue;
                            }
                        }

**Comment by Pr0phet1c** [comment]
Возможно, кто-то делает иначе, но я не пытаюсь получить сведения о сделке из заявки. Наиболее точные данные, по любой заявке, можно получить из таблицы сделок.

**Comment by IFetisov** [comment]
Т.е. после каждой заявки нужно выкачивать таблицу сделок? В итоге так и сделал. Т.к. OnTrade работает не надежно и может прийти уже после того как исполнение заявки зафиксировано и нужно реагировать. Приходится перекачивать сделки.
Кстати в OnTrade периодически приходят сделки у которых TransID = 0 - втыкал такой костыль чтобы обойти и узнать к какой заявке относится сделка
                    while (trade.TransID == 0)
                    {
                        var trds = TradeViewModel.Quik.Trading.GetTrades(trade.ClassCode, trade.SecCode).Result;
                        trade = trds.FirstOrDefault(x => x.TradeNum == trade.TradeNum );
                    }

**Comment by Pr0phet1c** [comment]
Ну, тут каждый сам решает какой путь ему ближе.
Я в свое время вообще отказался от использования этих колбэков внутри робота из-за того, что на одно и тоже событие колбэк может приходить три раза подряд. Разработчики квика назвали это фичей, и сказали, что так оно и останется.
Обычно, я отслеживаю статус заявки, и как только заявка перестает быть активной - лезу в таблицу сделок и вытаскиваю оттуда все сделки по этой заявке. Ну а обработка этих данных уже дело техники.

**Comment by IFetisov** [comment]
Дайте плс подсказку как доработать луа скрипт get_trades - чтобы он принимал на вход дату или время - чтобы смотреть сделки после определенного времени. А то очень жестко все тормозит :(
function qsfunctions.get_trades(msg)

**Comment by Pr0phet1c** [comment]
1. Если работает так как Вам надо - используйте и не заморачивайтесь.
2. У Вас какое количество сделок в день? Сотни или тысячи? Если нет, то тормоза скорее всего связаны НЕ со скоростью работы функции по получению таблицы сделок. (Возможно, Вы пытаетесь получать эту таблицу слишком часто, в то время, когда это не требуется).
3. Вы уверены, что Вам каждый раз надо получать всю таблицу сделок (пусть даже и ограниченную по времени)? На пробовали использовать вот такую функцию: "Quik.Trading.GetTrades_by_OdrerNumber(long orderNum)" ? Мои роботы обычно "знают" какие заявки (с какими номерами) они выставляли, и соответственно, им нет смысла обрабатывать данные каких-либо других заявок.
