### ISSUE TITLE
В продолжении "Что отсылается в сокет"

### ISSUE THREAD

**Issue by Nikolaev-Nikolay** [finsight/QUIKSharp#192]
Всем привет!
Подскажите пожалуйста, хочу начать писать процедуры для python, в сокет необходимо отсылать информацию вида:
{"data":"","id":269,"cmd":"isConnected","t":1555400409924}
Объясните пожалуйста, что за поля:
"data" - что пишется сюда?!
"id" - я так  понял порядковый номер команды - какие требования?!
"cmd" - команда- все ли команды из луа поддерживаются?!
"t"  временная метка - как формировать и что значит "0"?!
При чтении ответа как использовать 
sok_callbacks.connect((host , port_callbacks)) - нужно ли отправлять в этот порт и когда читать оттуда?!
И скажите - если команда неправильно написана - почему скрипт луа зависает насмерть?!
Хочу написать универсальную функцию для оперирования API на Python. Заранее спасибо!

**Comment by buybackoff** [comment]
Чтобы получить ответы на эти вопросы, Вам придется читать код, особенно Lua. Если Вы знакомы с JSON-RPC, бдет легче, принцип примерно такой же. Если нет, то базовая идея:

* cmd - имя функции в Луа, которую нужно вызывать при получении сообщения
* data - параметры для этой функции, зависят от фукнции
* id - это correlation id, чтобы сопоставлять ответы от Луа с ожидающими ответа запросами. Должны быть уникальными, самое простое автоматически увеливичать на 1 при каждом запросе.
* t - время, често не помню используется ли на стороне Луа. Может для таймаутов, надо смотреть код.

Если Вы хотите сделать полноценный коннектор для Питона, я думаю лучше думать в терминах QLua API, сделать Python API, которая повторяет QLua API, сделать структуры данных данных в Питоне как с C#, а по ходу дела разберетесь в протоколе - это нужно сделать один раз для какой-нибудь одной функции, остальные будут просто по наитию/примеру.

**Comment by Nikolaev-Nikolay** [comment]
Спасибо большое за ответ!
Подтверждаю, код на питоне рабочий, я убрал цикл пока в конце считываю один раз.
Команды которые мне удалось накопать проходят. Ну например такая команда:
request ={"data":"TQBR|CHMF|SEC_SCALE","id":"1","cmd":"getParamEx","t":str(int(round(time.time()*100000)))}
Ошибка была в том, что все данные должны быть в кавыках - то есть тип - строка.
В луа скрипте нет стойкой проверки правильности JSON сообщения - это на совести отправителя.

Я хотел спросить у Вас какая команда (или список команд) считывают данные из стакана (таблицы Торговля акции РФ).

Предлагаю всем кто интересуется сделать переход квик - питон - автоматизированный бот - писать сюда команды найденный вами в формате  приведенном выше и кратко их описывать. Так мы быстро сделаем конгломерат необходимых функций. Пока не закрывайте этот вопрос пожалуйста.

**Comment by Nikolaev-Nikolay** [comment]
Итак вот первая команда:
getQuoteLevel2
Функция предназначена для получения стакана по указанному классу и бумаге. 
http://luaq.ru/getQuoteLevel2.html#param_table_35

**Comment by buybackoff** [comment]
Смотрите #195.
