### ISSUE TITLE
Постановка лимитных заявок до заданной даты

### ISSUE THREAD

**Issue by cia76** [finsight/QUIKSharp#193]
Как я понимаю, при постановке лимитной заявки нельзя указать ее время действия GTC как для стоп заявки (поправьте, если ошибаюсь). В Квике есть возможность поставить лимитную заявку до заданной даты. Посмотрел, что в QUIKSharp можно поставить дату в заявку. Но при создании транзакции для LUA поля дат не учитываются. Этот фукнционал не реализован?

**Comment by Pr0phet1c** [comment]
Думаю, Вы ошибаетесь.
Я только что проверил в квике возможность указать дату действия для обычной лимитной заявки, и не нашел там таковой (проверял в терминалах двух брокеров). Дату можно указать в стоп-заявках, но я этот функционал в QUIKSharp никогда не использовал, и корректность его работы не проверял.

**Comment by cia76** [comment]
Скорее всего, действительно, ошибся. Т.е. лимитки ставим только до конца сессии.
