### ISSUE TITLE
Заглушка на ввод кода клиента в транзакции

### ISSUE THREAD

**Issue by IFetisov** [finsight/QUIKSharp#197]
Скажите а с какой целью поставлена эта заглушка.
Я в принципе код поправил у себя как только начал пользоваться библиотекой. Сейчас хотел обновиться - может что нибудь улучшилось за год -). Вообщем у меня все работает в таком исполнении:

        public async Task<long> SendTransaction(Transaction transaction)
        {
            Trace.Assert(!transaction.TRANS_ID.HasValue, "TRANS_ID should be assigned automatically in SendTransaction functions");

            transaction.TRANS_ID = QuikService.GetNewUniqueId();

            //    Console.WriteLine("Trans Id from function = {0}", transaction.TRANS_ID);
            /*
            Trace.Assert(transaction.CLIENT_CODE == null,
                "Currently we use Comment to store correlation id for a transaction, " +
                "its reply, trades and orders. Support for comments will be added later if needed");
             */
            // TODO Comments are useful to kill all orders with a single KILL_ALL_ORDERS
            // But see e.g. this http://www.quik.ru/forum/import/27073/27076/
            //if (transaction.CLIENT_CODE == null)
            transaction.Comment = transaction.TRANS_ID.Value.ToString();

            //this can be longer than 20 chars.
            //transaction.CLIENT_CODE = QuikService.PrependWithSessionId(transaction.TRANS_ID.Value);

            try
            {
                var response = await QuikService.Send<Message<bool>>(
                (new Message<Transaction>(transaction, "sendTransaction"))).ConfigureAwait(false);
                Trace.Assert(response.Data);

                // store transaction
                QuikService.Storage.Set(transaction.Comment, transaction);

                return transaction.TRANS_ID.Value;
            }
            catch (TransactionException e)
            {
                transaction.ErrorMessage = e.Message;
                // dirty hack: if transaction was sent we return its id,
                // else we return negative id so the caller will know that
                // the transaction was not sent
                return (-transaction.TRANS_ID.Value);
            }
        }

**Comment by Pr0phet1c** [comment]
Когда я начинал изучать эту библиотеку, то тоже обратил внимание на этот момент. Однако, в реальной работе я каких-либо сложностей не увидел, и не стал заморачиваться на эту тему (не считая изменения логики формирования transactionID).
А в чем принципиальное влияние Вашей реализации на работу данной функции?
Вы можете привести пример отличия результатов работы вашего варианта и того, который реализован в текущей версии библиотеки?

**Comment by IFetisov** [comment]
Отличие что можно указать код клиента для заявки и заглушка теперь не бросает исключение.
                var orderNew = new Order
                {
                    ClassCode = tradeParam.ClassCode,
                    SecCode = tradeParam.Security,
                    Operation = operation,
                    Price = price,
                    Quantity = qty,
                    Account = tradeLimit.AccountId,
                    ClientCode = tradeLimit.ClientCode
                };

**Comment by Pr0phet1c** [comment]
Я конечно могу ошибаться (все таки уже года два прошло), но вроде у меня исключение не выбрасывало, когда я код клиента указывал в параметрах транзакции.
Собственно, вот код моей старой функции:

    public async static Task<long> NewOrder(Instrument instrument, Operation operation, decimal price, int qty)
    {
        long res = 0;
        Order order_new = new Order
        {
            ClassCode   = instrument.ClassCode,
            SecCode     = instrument.SecurityCode,
            Operation   = operation,
            Price       = price,
            Quantity    = qty,
            Account     = instrument.AccountID,
            ClientCode  = instrument.ClientCode
        };
        try { res = await mainQuik.Orders.CreateOrder(order_new).ConfigureAwait(false); }
        catch { Console.WriteLine("Неудачная попытка отправки заявки"); }
        return res;

Позже, когда я выяснил, что код клиента можно просто не указывать без каких-либо последствий (во всяком случае для меня), плюс я захотел немного доработать процесс, то функция стала такой:

    public async static Task<Order> SendOrder(Instrument instrument, Operation operation, decimal price, int qty)
    {
        long res = 0;
        bool set = false;
        TransactionReply lastTransactionReply = new TransactionReply();
        mainQuik.Events.OnTransReply += (TransactionReply transReply) => { if (transReply.TransID == res) lastTransactionReply = transReply; };
        Order order_result  = new Order();
        Order order_new     = new Order
        {
            ClassCode       = instrument.ClassCode,
            SecCode         = instrument.SecurityCode,
            Operation       = operation,
            Price           = price,
            Quantity        = qty,
            Account         = instrument.AccountID
        };
        try { res = await mainQuik.Orders.CreateOrder(order_new).ConfigureAwait(false); }
        catch { Console.WriteLine("Неудачная попытка отправки заявки"); }

        while (!set)
        {
            if (lastTransactionReply == null || lastTransactionReply.ResultMsg == null || lastTransactionReply.ResultMsg == "")
            {
                try { order_result = await mainQuik.Orders.GetOrder_by_transID(instrument.ClassCode, instrument.SecurityCode, res).ConfigureAwait(false); }
                catch { order_result = new Order(); Console.WriteLine("Неудачная попытка получения заявки по ID-транзакции №" + res); }
                Thread.Sleep(500);
            }
            else
            {
                if (order_result != null) order_result.RejectReason = lastTransactionReply.ResultMsg;
                else order_result = new Order { RejectReason = lastTransactionReply.ResultMsg };
            }
            if (order_result != null && (order_result.RejectReason != "" || order_result.OrderNum > 0)) set = true;
        }

        return order_result;
    }

Но на сегодняшний день обе функции полностью рабочие.

**Comment by IFetisov** [comment]
Я не понимаю как его можно не указывать если его можно указывать в заявке Квика. В одном квике можно торговать от нескольких клиентов.

**Comment by buybackoff** [comment]
Изначально я делал, чтобы у меня на моем терминале работало "здесь и сейчас" от одного клиента от конкретного брокера, а не как правильно в общем виде. Поэтому как скажете должно быть правильно в общем виде, так и стоит изменить.

**Comment by Pr0phet1c** [comment]
Я не сталкивался с ситуациями торговли от лица нескольких клиентов через один терминал (и мои брокеры такой возможности не предоставляют, вроде как). Соответственно, я точно не смогу проверить как на самом деле оно должно работать в такой ситуации. Тут ведь надо не забывать, что кроме функции отправки транзакции, есть еще такая функция как "GetClientCode", и ее реализация точно не рассчитана на получение данных о нескольких клиентах. Так что если перерабатывать в одном месте, то надо это сделать везде, где так или иначе предполагается работа от нескольких клиентов. У меня такой возможности нет.
Ну и плюс к этому надо будет переработать все функции связанные с отправкой заявок, чтобы они начали передавать значение кода клиента в параметры транзакции.

**Comment by Pr0phet1c** [comment]
Из безопасных способов фиксации кода клиента в заявке можно убрать:

 Trace.Assert(transaction.CLIENT_CODE == null,
                "Currently we use Comment to store correlation id for a transaction, " +
                "its reply, trades and orders. Support for comments will be added later if needed");
            // TODO Comments are useful to kill all orders with a single KILL_ALL_ORDERS
            // But see e.g. this http://www.quik.ru/forum/import/27073/27076/

            transaction.CLIENT_CODE = transaction.TRANS_ID.Value.ToString();

И вместо этого сделать так:

            if (transaction.CLIENT_CODE == null) transaction.CLIENT_CODE = transaction.TRANS_ID.Value.ToString();

Но это пока никак не повлияет на результаты работы других функций, отвечающих за отправку заявок. Они по прежнему не будут использовать код клиента в работе. Возможно, позже я их переработаю, но пока не уверен в этом.

Возражения есть?

**Comment by Pr0phet1c** [comment]
Реализовал. Доработкой остальных функций надо будет заниматься отдельно. Пока я не готов выделить на это достаточное количество времени.

**Comment by buybackoff** [comment]
Можно закрыть это? @IFetisov @Pr0phet1c 

Или это bug и может блокировать работу большинства?

@Pr0phet1c кажется внес уже нужные изменения.

**Comment by IFetisov** [comment]
Можно как то так поправить. OrderFunctions
        public async Task<long> CreateOrder(Order order)
        {
            Transaction newOrderTransaction = new Transaction
            {
                ACTION      = TransactionAction.NEW_ORDER,
                TYPE = order.Price == 0 ? TransactionType.M : TransactionType.L,
                ACCOUNT     = order.Account,
                CLASSCODE   = order.ClassCode,
                SECCODE     = order.SecCode,
                QUANTITY    = order.Quantity,
                OPERATION   = order.Operation == Operation.Buy ? TransactionOperation.B : TransactionOperation.S,
                PRICE = order.Price,
                CLIENT_CODE = order.ClientCode
            };
            return await Quik.Trading.SendTransaction(newOrderTransaction).ConfigureAwait(false);
        }

**Comment by Pr0phet1c** [comment]
Сделал. Проверьте, это то, что Вы хотели, или я что-нибудь упустил?

**Comment by IFetisov** [comment]
Да с кодом клиента теперь все хорошо.
Спасибо
