### ISSUE TITLE
Получать все сделки и изменения параметров

### ISSUE THREAD

**Issue by iza88** [finsight/QUIKSharp#198]
Подскажите можно ли через эту библиотеку получать обезличенные сделки и таблицу изменений параметров?

**Comment by Pr0phet1c** [comment]
Обезличенные сделки: колбэк OnAllTrade
Таблица изменения параметров: Целиком таблицу - нельзя, но можно получать отдельные параметры через GetParamEx.
А вообще, рекомендую прочитать справку квика по QLua. Там написано что и в каком виде можно получать программным путем.

**Comment by iza88** [comment]
Понял, спасибо.
Подскажите по OnParam можно получать изменения? У меня этот callback не вызывается

**Comment by Pr0phet1c** [comment]
Да, можно. Но после изменения каких конкретно параметров происходит вызов данного колбэка я не подскажу. Придется экспериментировать самостоятельно. Посмотрите в демонстрационных приложениях организацию вызова колбэков, и проверьте, чтобы у Вас было также сделано.

**Comment by iza88** [comment]
Я так понял чтобы этот OnParam начал срабатывать надо вызвать ParamRequest(...). Но когда я его вызываю вылезает ошибка:
![image](https://user-images.githubusercontent.com/14890699/59598237-644a5300-9104-11e9-962f-d6231553e5b6.png)

**Comment by Pr0phet1c** [comment]
Не уверен, что для работы OnParam обязательно требуется paramRequest.
Эта функция нужна для заказа отдельных параметров , но например при работе функции GetParamEx этого не требуется буквально совсем.
Но я могу ошибаться. Просто я нигде не использую OnParam и подробных экспериментов с этим колбэком не проводил.

**Comment by Pr0phet1c** [comment]
Если Вы решили использовать paramRequest, то я надеюсь Вы не забыли выполнить условие обозначенное в справке по QLua?

---------------
ParamRequest

Функция заказывает получение параметров Таблицы текущих торгов. 

BOOLEAN ParamRequest(STRING class_code, STRING sec_code, STRING db_name)

Для корректной работы функции включите в настройках Рабочего места QUIK признак получения данных «Исходя из настроек открытых пользователем таблиц» (меню Система / Настройки / Основные настройки..., раздел «Программа» / «Получение данных»).

---------------

**Comment by iza88** [comment]
> Не уверен, что для работы OnParam обязательно требуется paramRequest.

мне кажется было бы очень неэффективно, если бы в OnParam приходили бы изменения всех параметров по всем инструментам

> Если Вы решили использовать paramRequest, то я надеюсь Вы не забыли выполнить условие обозначенное в справке по QLua?

не забыл

Есть идея вызывать в цикле GetParamEx по всем интересующим меня инструментам, но их много, и с этим далеко не уеедешь. Подскажите есть ли у вас в планах разбираться с OnParam?

**Comment by Pr0phet1c** [comment]
Ну, на какие события реагирует колбэк - это решение разработчиков квика. Описания они не дали, так что придется только догадываться или проверять самостоятельно.
У меня планов разбираться с paramRequest нету. Мне для моих задач вполне хватает функции GetParamEx, без лишних подписок. OnParam также не использую. И между прочим я пользуюсь именно принудительными циклами. Как показала практика - для моих целей это наиболее эффективный метод, по сравнению с событийной моделью. Наибольшая часть параметров инструмента, которые я использую в своих роботах, не изменяются в течение всего дня, а следовательно их можно запрашивать один раз, а обновление выполнять только по постоянно изменяющимся параметрам и только по тем, которые меня интересуют.
Когда у Вас одновременно запущены несколько десятков роботов/алгоритмов, то вопрос сокращения числа обращений к терминалу начинает играть весьма немаловажную роль (да, и нагрузку на ЦП можно значительно снизить).

**Comment by iza88** [comment]
Если вам будет интересно реализовать ParamRequest за деньги, пишите whatsapp/telegram 7929шестьноль9три305
Спасибо

**Comment by Pr0phet1c** [comment]
Не понял, что значит "реализовать"? ParamRequest или работает, или не работает. В первом случае ничего делать не надо. Во втором - это ошибка, которая подлежит исправлению, но для этого нужны более подробные сведения о методике проверки работоспособности, и условиях проведения этой проверки, для выявления источника проблемы. (Правда, реализовывал этот метод не я, так что не знаю сколько времени может уйти на решение проблемы)

**Comment by Pr0phet1c** [comment]
ParamRequest и CancelParamRequest были реализованы с ошибкой.
Исправлено.
В демо-приложение добавлен пример использования соответствующей связки "ParamRequest + OnParam + GetParamEx2"
