### ISSUE TITLE
Документация

### ISSUE THREAD

**Issue by Vikora** [finsight/QUIKSharp#2]
Здравствуйте! Проект очень интересный, но совершенно не понятно, как им пользоваться. "Из кода должно быть всё ясно" -- это очень громкое заявление, если учесть, что проект содержит 143 файла.
Особенно сложно для тех, кто, как я например, ненавидит эту дурацкую Visual Studio.
Если бы Вы написали несколько коротеньких инструкций. Первую, как написать простейшую программу с использованием QuikSharp. Вторую, как добавлять новые функции. То, я думаю, большое количество людей с энтузиазмом принялось бы развивать ваш проект.
Мне приходится каждый файл отдельно открывать наугад, так как сам проект QuikSharp.sln моей Visual Studio не открывается (пишет, что проект был создан более новой версией программы, привет рабовладельцем из майкрософта).
Очень надеюсь на Вашу помощь, так как проект вызывает интерес, но времени и сил на реверс-инжиниринг сейчас нет.

**Comment by buybackoff** [comment]
Тесты являются документацией (все, что пока есть). Я правда считаю, что код достаточно прост и самодокументирован и тратить время на его описание не могу - мне бы найти время на оставшиеся функции Луа и на удобную логику для транзакции, в том числе связанных транзакций (н.п. закрыть все заявки, объединенные в группу) - это будет следующий шаг.

Обратите внимание, что главный проект содержит файл https://github.com/buybackoff/QuikSharp/blob/master/src/QuikSharp/Program.cs, и если тип проекта изменить с Dll Library на Console Application, то эта программа показывает как получать стаканы и выставлять заявки (что-то из это закомментированно). Также она содержит продвинутую логику закрытия, что актуально для трейдинга (н.п. если почему-то прога неожиданно закрывается, сделать clean-up, отменить заявки и т.д.)

Также обратите внимение, что далеко не вся функциональность lua реализована, сделаны принципиальные вещи, по шаблону которых можно доделать все остальное. То есть, добавлять новые функции можно копированием текущих и изменением чего надо, в соотвествии с документация Quik Lua. Эксель файл используется для быстрой генерации C# классов, соотвествующих Lua таблицам. 

Кроме того, логика объединения транзакций, заявок и сделок сейчас в определенных местах хромает из-за дебилизма реализации этих вещей в Квике (transaction id теряется по пути к сделкам, нужно их объединять по промежуточному order id, но даже callback со сделкой может прийти раньше колбэка транзакции).

Если не нравится VS, используйте Xamarin Studio, он бесплатный и открывает все версии (насколько я знаю). Быстрое решение - открыть .sln в блокноте и на первых строках изменить числа VisualStudioVersion  и MinimumVisualStudioVersion на Ваши.

**Comment by Dmitriy74** [comment]
Вопрос для всех  - может ли кто-нибудь помочь с установкой данной системы? Совершенно непривычно всё здесь и пока не получается даже запустить

**Comment by buybackoff** [comment]
Почитайте все issues с тэгом question, начиная с последних. Я могу здесь помочь с вопросами по QuikSharp, но не с вопросами как пользоваться Visual Studio, собирать проекты и писать на C#.

**Comment by Dmitriy74** [comment]
Разумеется! Я это понимаю и поэтому и обраюсь ко всем - может найдётся кто-нибудь кто поможет мне-новичку и новичкам вроде меня. Ведь порой для решения какого-то препятствия не хватает какого-то пустяка, а по незнанию проводишь перед ним долгие часы или дни.

**Comment by COBRAprogDAV** [comment]
для версии 0.3.0
1  Открываете QuikSharp.sln
2  в нем  3-проекта   QuikSharp;    QuikSharp.Test;  Profiler;
3  при наличии последней версии Nuget в VS  все build-ся кроме последнего,
   в Profiler  в References  я заменил  QuikSharp ссылку  на  файл QuikSharp.dll
4 в свойствах QuikSharp меняите Output ConsoleApplication и StartUp   на Program
5 в Quik запустить скрипт  QuikSharp (лежит в bin/lua)
6 Запускаете QuikSharp  все работает.

**Comment by eugene20237** [comment]
Скажите пожалуйста, проект развивается? Quik версии 7.x поддерживается? Какие планы на будущее?
Ваша библиотека - просто глоток воздуха после S# API! Спасибо за ваш труд!

**Comment by buybackoff** [comment]
Проект точно жив, так как им пользуются. У меня нет цели покрыть 100%
функционала, так как это не коммерческий проект, а открытый код. Все
изменения/дополнения - по мере реальной необходимости, пулл реквесты
принимаются.
На 7й Квик не смотрел, но если там работает Луа, то и КШ должен, возможно с
какими-то изменениями API.
