### ISSUE TITLE
Падает Quik

### ISSUE THREAD

**Issue by martinezdm** [finsight/QUIKSharp#200]
работает работает, торгует торгует несколько дней подряд (или в течении одного дня), и вдруг моя прога показывает сообщение http://prntscr.com/o6tg1s , а самого quik нет в списке задач. Такое повторяется регулярно. Так еще у кого-нибудь бывает? при ручной торговле Quik у меня ни разу не падал, только при автоматической. Возможно ли, что код QUIKSharp как то роняет Quik?

**Comment by buybackoff** [comment]
Quik# толко входная точка во всем stack trace по ссылке. Уверены, что ваш код в порядке с какой-нибудь ламбдой? 

Или я перепутал верх-низ и ошибка именно в Q#? В Visual Studio ошибка (кажется) всегда внизу.  Также обращает на себя внимание самое верхнее сообщение: ошибка или Debug.Assert или Trace.Assert. Пожалуйста, поймайте её если можете и сообщите версию библиотеки, где это происходит. (если меньше 1, то обновитесь на мастер или НюГет).

Также возможно в исходном коде есть какие-то `Debug.Assert`-ы, которые потеряли актуальность. Если вы запускаете библиотеку из исходного кода в Debug режиме, Ваша помощь очень важна найти эти места!

Спасибо!

**Comment by martinezdm** [comment]
у меня из Nuget версии 1.0.0, но и прошлым летом с предыдущей версией было тоже самое - падение после продолжительной и/или интенсивной работы. Я так понимаю, что сама показанная ошибка это просто реакция на упавший quik. А вот почему Quik падает я не понимаю, вроде ничего специфичного, долго вызываются однотипные операции, и вдруг падает. Я пробовал отловить какую функцию последней я вызываю перед падением, но получилось что это разные функции и никакой закономерности. возможно все дело в моем Quik, я не знаю кастомизируют ли брокеры его под себя, скоро у меня будет возможность попробовать Quik у другого брокера.

**Comment by AndruhaE** [comment]
У меня тоже похожая ситуация, сразу уточню что скомпилил под целевую платформу x64. Часть функций работает, две- отваливаются с такой ошибкой.
![Untitled](https://user-images.githubusercontent.com/52831738/61142538-af277280-a4d8-11e9-8731-f71e38dcdebc.png)

Шаги чтобы повторить: тикер RIU9, CONNECT, RUN.
Нормально, быстро, отрабатывают функции Получить исторические данные, Получить клиентский портфель. Пытаюсь получить таблицу заявок или таблицу сделок - пишет в лог "Получаем таблицу...", и ничего не показывает. После этого нормальные функции отрабатывают, и через какое-то время (небольшое) падает Quik, выходит ошибка. Один раз, в перерыве (ок.18:45МСК) получение заявок выкинуло ошибку в строке 193

bid = Convert.ToDecimal(toolOrderBook.bid[toolOrderBook.bid.Count() - 1].price);

Так как toolOrderBook.Bid Была пустой.

**Comment by buybackoff** [comment]
@AndruhaE 
что компилили под x64? какую lua51 (без точки) использовали?

**Comment by AndruhaE** [comment]
компилил quiksharp, lua без точки по-моему просто переименовал ту, которая с точкой. ночью скачал штук пять, какая-то заработала :(
