### ISSUE TITLE
Quik 64 

### ISSUE THREAD

**Issue by IFetisov** [finsight/QUIKSharp#201]
Добрый день. 
Сейчас квик обновляется на версию 64 bit
Не подскажете где взять 
cjson.dll
lua51.dll
socket\core.dll
                 64 бит?
Нужно ли будет переделывать все луа скрипты после этого?

**Comment by buybackoff** [comment]
cjson.dll не используется, нужно удалить его.

Остальные должны работать из любых бинарников Луа для 64 бит. Сами скрипты переделывать в принципе не нужно, если не пытаться автоматически определять битность.

Наверное нужно будет сделать отдельный NuGet для 64-битного квика, или продумать как автоматически определять битность и корректировать пути загрузки этих библиотек.

**Comment by buybackoff** [comment]
На месте разработчиков Квика было бы глупо не добавить новую функцию в Lua, которая возвращает битность. Можете посмотреть в новой документации нет ли там такого?

**Comment by IFetisov** [comment]
Написали, что 32-битных версии больше не будет. 
Будет только 64.  
core.dll подскажите пожалуйста где искать. Можно lua нужно 5.1 64 Bit?

**Comment by buybackoff** [comment]
> Написали, что 32-битных версии больше не будет.

Не будет новых версий с 32, но основная масса пользователей еще долго будет сидеть на 32, многие брокеры возможно будут медленно обновлять свои дефолтные версии.

В Lua for Window x64 (или любом бинарном дистрибутиве) должны быть бинарники для сокетов, это базовая библиотека.

**Comment by RD3BAX** [comment]
Появилось обновление на 64
ftp://ftp.quik.ru/public/updates/8.0/

**Comment by RD3BAX** [comment]
Функция определения версии getInfoParam("VERSION") если 8.* значит х64
А вот core.dll x64 найти не удалось, похоже проект luasocket заглох еще в 2007  http://files.luaforge.net/releases/luasocket/luasocket.

**Comment by buybackoff** [comment]
> А вот core.dll x64 найти не удалось, похоже проект luasocket заглох еще в 2007

Google все еще работает. Если по этой ссылке не работает, то можно построить из исходников.

https://github.com/pkulchenko/ZeroBraneStudio/issues/816#issuecomment-483060602

**Comment by RD3BAX** [comment]
На библиотеку по этой ссылки квик дает следующий ответ:
error loading module 'socket.core' from file 'C:\Users\Magistr\source\repos\RD3BAX\QUIKSharp\src\QuikSharp\lua\clibs\socket\core.dll':
	Не найден указанный модуль.

А исходник библиотеки я пока не нашел, да и опыта построить из кода у меня маловато.

**Comment by buybackoff** [comment]
Думаю в этом скрипте нужно поменять на `5.1` и как-то добиться, чтобы строилось.

https://github.com/diegonehab/luasocket/blob/master/win64.cmd

**Comment by RD3BAX** [comment]
Не справлюсь я с этим, буду ждать пока у кого ни будь руки дойдут.

**Comment by IFetisov** [comment]
У меня все взлетело. Ничего не компилял взял по предоставленным ссылкам
спасибо
https://download.zerobrane.com/misc/luasec-0.6-openssl-1.0.2o-luasocket-3.0-win64.zip  - core.dll
lua5.1 идет с квиком просто переименовал ее и перезаписал старую dll

**Comment by buybackoff** [comment]
lua51.dll (без точки) это обертка вокруг lua5.1.dll (с точкой), потому что кто-то когда-то там сильно накосячил и разные библиотеки зависят от разных имен :)

Нужно также найти такую обертку для x64, иначе что-то может неожиданным образом сломаться. Не хочется переименовывать что-то из папки Квика.

**Comment by IFetisov** [comment]
Думаю если это обертка то найти ее не реально. (
У меня так в принципе все подцепилось но уже понятно, что что то не так.

**Comment by buybackoff** [comment]
Вот тут есть lua51.dll: https://sourceforge.net/projects/luabinaries/files/5.1.5/Tools%20Executables/lua-5.1.5_Win64_bin.zip/download

**Comment by buybackoff** [comment]
@IFetisov у вас работает стабильно с lua51.dll из воследней ссылки?

Нужно бы апдейт выкатить поскорее, но пока не понятно какие бинарники работают.

**Comment by Pr0phet1c** [comment]
Вот тут: https://github.com/moteus/lua-windows-environment/blob/master/Lua/5.1/x64/v140/bin/lua51.dll
Нашел lua51.dll. 
Это не то, что нам нужно?

**Comment by buybackoff** [comment]
Вопрос стабильно ли все работает с этими бинарниками?

**Comment by Pr0phet1c** [comment]
Не знаю, и проверить не смогу. Мне негде тестить x64.

**Comment by SkyQuant** [comment]
Так что в итоге нужно сделать, чтобы на 8-й версии не появлялось сообщение?

> error loading module 'socket.core' from file 'C:\QUIK\lua\clibs\socket\core.dll':
> 	%1 не является приложением Win32.

**Comment by SkyQuant** [comment]
На 32-х семёрке нормально пошло. На неё откатываться пока решение не найдено?

**Comment by solzer13** [comment]
вроде работает но как правильно автор сказал нужно сделать поддержку обоих версий, потому что тестовый квик уже 8 а у брокера 7 нужно чтоб и там и там работало

**Comment by dmitryy** [comment]
Коллеги, проблема и правда решается, как написал выше @IFetisov 
Думаю это можно закрывать и добавьте пожалуйста инструкцию по переходу на главную.

Для тех кто пропусти выше:
- качаем https://download.zerobrane.com/misc/luasec-0.6-openssl-1.0.2o-luasocket-3.0-win64.zip 
- забираем из архива socket/core.dll 
- заменяем его в нашем lua/clibs/socket/core.dll
- берем из папки установленного квика lua5.1.dll 
- вставляем lua5.1.dll в папку lua/clibs/scoket/
- удаляем старый (или переименовываем) и переименовываем новый в lua51.dll

**Comment by Pr0phet1c** [comment]
Выгрузил в мастер универсальный вариант. Вроде бы пока работает. Надо чтобы больше народу у себя погоняли. У меня сначала крашилось все при запуске двух клиентов на одном терминале.

З.Ы.: #dmitryy, у Вас ошибочка в предпоследнем пункте инструкции папка должна быть lua/clibs/, а не lua/clibs/scoket/

**Comment by buybackoff** [comment]
@Pr0phet1c Спасибо большое! Откуда бинарники взяли?

**Comment by Pr0phet1c** [comment]
@buybackoff,
core.dll: https://download.zerobrane.com/misc/luasec-0.6-openssl-1.0.2o-luasocket-3.0-win64.zip.
был еще один вариант из другого источника (уже не помню откуда), но он оказался полностью идентичен.
lua51.dll: Переименованный lua5.1.dll из папки нового квика (8.2). Попытки применения других сборок готового lua51.dll, из различных источников (и версий Lua), желаемого результата не принесли.

В общем, текущий вариант пока остается единственным доступным из работоспособных.

**Comment by buybackoff** [comment]
> lua51.dll: Переименованный lua5.1.dll из папки нового квика (8.2).

История с точкой и без точки была в том, что кто-то когда-то накосячил с именами, и существуют различные зависимости, некоторые хотят `5.1`, другие `51`.

`51` была тонкой оберткой над `5.1` и просто перенаправляля все вызовы. Если просто переименовать, то получается, что могут быть загружены два идентичных модуля.

> желаемого результата не принесли.

Что это значит - падает?

**Comment by buybackoff** [comment]
Что происходит, если убрать 51 полностью?

**Comment by buybackoff** [comment]
Пробовали отсюда? https://sourceforge.net/projects/luabinaries/files/5.1.5/Tools%20Executables/lua-5.1.5_Win64_bin.zip/download

Там есть файл lua51.dll, всего 11кб, как раз та обертка. Еще этот файл есть в версии 5.1.4 уровнем выше, отличается на 500 байт.

Обсуждение этого маразма с точкой тут: http://lua-users.org/lists/lua-l/2008-06/msg00076.html

**Comment by Pr0phet1c** [comment]
1. Да, падало (или вообще выдавало ошибку на этапе загрузки)
2. Полностью убирать не пробовал. Могу вечером попробовать (пока x64 на отдельном компе запускаю)
3. 5.1.5 пробовал из ссылки. если сейчас правильно помню, как раз в этом варианте падение вызывалось после запуска второго клиента. Причем ошибка возникала в разных строках класса QuikService, но это всегда была строка вида: 

                                var response = readLineTask.Result;


Вообще, у меня целая подборка всякого набралась за несколько месяцев:

![screen](https://user-images.githubusercontent.com/14761254/68741554-fba5ca80-05fe-11ea-8c88-10b2d9022247.jpg)

Еще что-то уже успел удалить. 
файлы lua51.dll мне попадались разных размеров, но ни с один из них не получилось наладить стабильную работу роботов.
Допускаю, что я просто успел запутаться в файлах, и что-то не так сделал, но переименование файла из квика - это было самое последнее решение, которое я испробовал.  Однако, именно оно показало себя с наилучшей стороны.

Кроме того, у меня есть скрипт на lua, который постоянно работает внутри квика, для отслеживания и логирования реальных сделок. Так вот он раньше подключал мою собственную библиотеку функций, которая, в свою очередь, подключала библиотеку QL.lua.
При переходе не x64 пришлось полностью выпилить использование загружаемых библиотек, отыскав все используемые функции и продублировав их в скрипте, т.к. мне не удалось избавиться от ошибок, возникающих при подключении QL.lua.

**Comment by Pr0phet1c** [comment]
В общем, не получается избавиться от lua51.dll. Скрипт начинает ругаться на то, что core.dll не является приложением Win32. Не знаю какая тут взаимосвязь, но после восстановления файла и строки на загрузку этой библиотеки, все начинает работать нормально.

**Comment by buybackoff** [comment]
Возник вопрос в #236, посмотрите плиз
