### ISSUE TITLE
Не возвращает ошибку и уходит в бесконечный цикл.  

### ISSUE THREAD

**Issue by RD3BAX** [finsight/QUIKSharp#202]
При создании подключения и отсутствии запущенного скрипта Луа библиотека уходит в бесконечный цикл и не выбрасывает ошибку соединения. При запуске скрипта соединение сразу устанавливается. Это баг либы или я что-то делаю не так?

**Comment by RD3BAX** [comment]
При создании подключения и отсутствии засушенного скрипта Луа библиотека уходит в бесконечный цикл и не выбрасывает ошибку соединения. При запуске скрипта соединение сразу устанавливается. Это баг либы или я что-то делаю не так?

**Comment by IFetisov** [comment]
Я использую timeOut для решения этой проблемы. Чуть чуть исходники поменял там где мне таймаут нужен.
        public const int GetLimitsTimeOut = 20000;
 
        public Quik(int timeOut, int? nport = DefaultPort, IPersistentStorage storage = null )
        {
            var port = nport ?? DefaultPort;
            if (storage == null) { Storage = new InMemoryStorage(); } else { Storage = storage; }
            QuikService = QuikService.Create(port);
            // poor man's DI
            QuikService.Storage         = Storage;
            Events                      = QuikService.Events;
            Debug                       = new DebugFunctions(port);
            Service                     = new ServiceFunctions(port);
            Class                       = new ClassFunctions(port);
            OrderBook                   = new OrderBookFunctions(port);
            Trading                     = new TradingFunctions(port);
            StopOrders                  = new StopOrderFunctions(port, this);
            Orders                      = new OrderFunctions(port, this);
            Candles                     = new CandleFunctions(port);
            QuikService.Candles         = Candles;
            QuikService.StopOrders      = StopOrders;
            QuikService.WorkingFolder   = Service.GetWorkingFolder(timeOut).Result;
        }

**Comment by RD3BAX** [comment]
Он зацикливается на постоянном обращении в метод  QuikService.EnsureConnectedClient  и я там совсем не понял конструкцию

catch
                        {
                            attempt++;
                            Thread.Sleep(100);
                            if (attempt % 10 == 0) Trace.WriteLine($"Trying to connect... {attempt}");
                        }

**Comment by buybackoff** [comment]
По-хорошему нужно сделать async метод `ConnectAsync` с CancellationToken и Timeout.

**Comment by buybackoff** [comment]
скорее всего дело было в #234
