### ISSUE TITLE
Анонс

### ISSUE THREAD

**Issue by buybackoff** [finsight/QUIKSharp#205]
Я собираюсь переехать в организацию [**fiimru**](https://github.com/fiimru). Текущее имя не имеет перспектив использования ни для каких проектов, так как торговая марка зарегистрирована в США и подана заявка на международную регистрацию. Я использовал это название с 2005 года для различных целей, но пора с ним попрощаться.

Также дальнейшее развитие будет с GPL 2.0 лицензией, как было изначально. **Для индивидуальных пользователей, которые используют коннектор для личной торговли, ничего не изменится.** Изменение лицензии не имеет обратной силы, так что все коммиты до того, в котором будет это изменение, можно продложать использовать с лицензией  Apache 2.0.

Пишите тут вопросы/возражения, если они есть.

**Comment by iflash5** [comment]
Привет.

Недавно познакомился с этой библиотекой и она меня заинтересовала. 
В процессе первого запуска возникли небольшие трудности (не работает с тестовым аккаунтом) но они быстро решились. Просмотрел всю библиотеку в т.ч. код на луа.
Сейчас хочу попробовать эту библиотеку для написания робота.

Возникли следующие вопросы:
1. где взять wiki с описанием всех функций и параметров? И если ее нет можно ли мне создать страницу и дополнять ее описанием в данном проекте? (для себя и для других)
Может с описанием архитектуры.

2. какие правила для коммитов? и нужны ли они вообще? можно ли исправлять написанный код: например
....
tool = new Tool..
if (tool!=null ....)
...
такая проверка не имеет смысла
или string.IsNullOrEmpty() вместо str!=null && str!=""
и т.д.
можно ли исправлять увиденные ошибки и можно ли предлагать архитектурные решения и их реализацию. Так, например, для себя я создал DataSourceConnection, DataSourceCommand по аналогии со стандартными .net классами и сейчас оборачиваю вашу библиотеку своим DAL для личного удобства использования. ну и для написания робота использую MVVM + wpf.

3. и простите не совсем понял ваш текст в заголовке. этот проект переместится под другое имя или будет продолжаться здесь и дадите ли знать когда это произойдет или этот проект будет закрыт и исходники нельзя использовать?

**Comment by buybackoff** [comment]
3. Для частного использования вообще ничего не изменится, исходники останутся, с этой страницы будет редирект.

1. QLUA.chm или как-то так, идет с Квиком, API тут идентичный.

2 и прочее: коммиты/PR ради опечаток или изменения тривиальных вещей должны быть или микроскопическими (только одно/два изменения), чтобы с телефона можно было замерджить, или как часть более большого коммита, но тоже пару исправлений, замеченных по ходу дела. Рефакторинг ради рефакторинга не приветствуется (не сломалось - не чини). 

Другие вещи не ограничены, но сначала создайте issue для обсуждения, что вы хотите сделать, как и почему. Просто большой PR с изменением логики/архитектуры без обсуждения вряд ли будет принят.

Только помните, что цель проекта - повторить API QLua. Дополнительный функционал следует делать в других проектах (можно как часть этой репо/solution), и если накопится много, возможно будет отдельный NuGet типа QuikSharp.Contrib и т.п.

**Comment by Pr0phet1c** [comment]
Пока напишу от себя, а Виктор потом дополнит, если сочтет нужным:
1. Изначально библиотека создавалась с целью повторить функционал QLua из терминала QUIK. Соответственно, описание функций и параметров надо искать в справке по QLua (в квике есть отдельный файл QLUA.chm). Есть в библиотеке несколько дополнительных функций, немного расширяющих функционал, но WIiKi для них не делалось (видимо предполагалось, что их описание будет через XML-комменты реализовано)
2. Код конечно можно причесывать, но в большинстве случаев это не имеет большого смысла. Особенно, в отношении демонстрационных приложений. Все демо-приложения создавались на коленке, на быструю руку, только как простейшие примеры реализации. Были частые вопросы о том, с чего начать и как пользоваться этой библиотекой, вот и сделали то, на что времени хватило. Не стоит относится к ним как к "образцам" качественных приложений.
3. не могу прокомментировать. Тут только Виктор сможет что-то внятное сказать.
Процесс получения набора данных по инструменту как раз в демонстрационных приложениях есть. Другое дело, что в коде нет достаточно подробных разъяснений, но такой задачи и не стояло.
4. решарпер - это конечно хорошо, но платно. Я тоже могу порекомендовать передвигаться на мерседесе, а не на метро, потому, что у меня он есть, и мне на нем нравится ездить. Но разве цель проекта в этом?
QuikDateTime - приехал к нам напрямую из QUIK`а, и его появление обусловлено основной задачей проекта (см. пункт №1). Да, для большинства задач этот формат неудобен, и каждый волен делать так, как ему надо, но в квике этот формат есть, а значит будет и тут.
5. Именно этот проект, можно считать скорее завершенным (надо только x64 добить) , и далее разве что небольшие обновления будут. Кардинальных изменений в нем не планировалось. Однако, если кто-то решит приложить свои руки к такому развитию, то наверное это не будет лишним (для того код открытым и делался)

**Comment by iflash5** [comment]
спасибо за ответы.
принял информацию.

pdf + chm нашел/скачал.

позвольте еще вопрос. если ветка не та подскажите куда можно задавать вопросы.

из chm/pdf
AddLabel - добавляет метку с заданными параметрами, 
DelLabel - удаляет метку с заданными параметрами, 
эти методы есть в ServiceFunction.cs

а как на график добавить несколько горизонтальных индикаторов?
из chm
SetRangeValue - устанавливает указанное значение на выбранной линии для определенного интервала индексов свечей индикатора. 

в коде такого не нашел...

подскажите где взять и как использовать? (ну или куда копать)

п.с.
если этой функции нет, могу ли добавить ее везде и предложить коммит?

**Comment by avently** [comment]
@buybackoff 

Возникли несколько вопросов по поводу смены лицензии.

Согласно вот этому описанию лицензии https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.ru.html#NFUseGPLPlugin
GPL обязывает выкладывать исходники любых программ, которые используют что-либо с этой лицензией. 

Возьмём такие исходные условия:
- У меня есть коммерческая программа с закрытыми исходниками - терминал для торговли криптой и торговли через Quik.
- Я буду использовать вашу библиотеку, у которой будет GPL v2.
- Я не собираюсь как либо модифицировать вашу библиотеку, а если соберусь, то просто заапстримлю изменения или могу выложить на гитхаб, если вам эти изменения окажутся не нужны. 

1. Правильно ли я понимаю, что я буду обязан выложить исходники своего терминала просто из-за того, что я использую вашу библиотеку? 
2. Если так, то насколько этот шаг (смена лицензии на GPLv2) стоит того, чтобы его сделать? Ведь это автоматически обяжет всех пользователей библиотеки отказаться от нее и придётся писать свой велосипед. 
3. Какие у меня есть варианты по использованию этой библиотеки в коммерческом продукте без необходимости выкладывания исходников этого продукта?

P.s. я еще даже не приступил к добавлению поддержки Quik'а, так что ещё даже не пытался использовать QuikSharp. Пока ещё на этапе поиска инструмента конвертации QLua в человекоподобный язык и QuikSharp отлично подходит, за исключением этой смены лицензии.

**Comment by buybackoff** [comment]
@avently я даже забыл про этот анонс, не переживайте про лицензию. То, что доступно сейчас здесь останется доступно под такой же лицензией.

Возможно когда я писал этот анонс у меня были ~~планы~~ фантазии что-то серьезно перерабатывать и добавлять функционал поверх QLua API, но сейчас таких планов нет.

Мы уже полгода не можем победить x64 и версию 8.5, это гораздо актуальнее.
