### ISSUE TITLE
new Quik(..) зависает если не запущен терминал

### ISSUE THREAD

**Issue by aBaTaPbl4** [finsight/QUIKSharp#206]
Зависание происходит внутри конструктора класса Quik в 37 строке, - вызов метода Service.GetWorkingFolder. В итоге это приводит к зависанию вызывающего приложения.

Получается, наличие у класса Quik метода IsServiceConnected - становится бессмысленным.

Если не ошибаюсь в бете, зависания в данном случае не было. Конструктор завершался всегда. И посредством метода IsServiceConnected, могли проверить запущен ли терминал

**Comment by buybackoff** [comment]
повтор #202
