### ISSUE TITLE
Направление заявки

### ISSUE THREAD

**Issue by SkyQuant** [finsight/QUIKSharp#21]
Ставлю заявку на продажу. В дебагире вылавливаю событие и вижу поле _Operation = Buy_

**Comment by buybackoff** [comment]
Сегодня утром могло быть все, что угодно. Биржа сломалась. Какой инструмент? Покажите код.

**Comment by SkyQuant** [comment]
Бумага ОФЗ24018. Код обычный, выдаёт в консоль Buy
```
_q.Events.OnOrder += order =>
            {
                Console.WriteLine(order.Operation);
            };
```

**Comment by buybackoff** [comment]
Поле Operation в классе Order используется только для удобного создания транзакции из заявки здесь: https://github.com/buybackoff/QuikSharp/blob/master/src/QuikSharp/OrderFunctions.cs#L31
Квик возвращает статус в поле [flags](https://github.com/buybackoff/QuikSharp/blob/master/src/QuikSharp/DataStructures/Transaction/Order.cs#L23), расшифровка которых [тут](https://github.com/buybackoff/QuikSharp/blob/master/src/QuikSharp/DataStructures/Transaction/OrderTradeFlags.cs#L23) и в документации QLUA.
Нужно добавить обработку флагов в возвращенном ордере для установки свойства, которое сейчас [по умолчанию остается Buy](https://github.com/buybackoff/QuikSharp/blob/master/src/QuikSharp/DataStructures/StopOrder.cs#L216). Это свойство добавил @nubick, я даже не заметил.

**Comment by SkyQuant** [comment]
Flags = Active | IsSell | IsLimit | AllowDiffPrice

Т.е. нужно смотреть, содержит ли (contains) перечисление IsSell или IsBuy?

**Comment by buybackoff** [comment]
Я удалю setter этого свойства в объекте Order, сейчас так:

```
/// <summary>
        /// Тип операции - Buy или Sell
        /// </summary>
        [JsonIgnore]
        [Obsolete("This property will be removed")]
        public Operation Operation {
            get { return this.Flags.HasFlag(OrderTradeFlags.IsSell) ? Operation.Sell : Operation.Buy; }
        }
```

**Comment by SkyQuant** [comment]
Как то пока так
```
_q.Events.OnOrder += order =>
            {
                Console.WriteLine(order.Flags);
                var direction = order.Flags.HasFlag(OrderTradeFlags.IsSell) ?
                     "Продажа" : "Покупка";
                Console.WriteLine(direction);
            };
```
А зачем удалять? Может просто модифицировать?

**Comment by buybackoff** [comment]
Удалю setter, а не свойство целиком. Это производная от другого свойства, у него не должно быть сеттера. А создавать транзакцию из класса ордера не совсем корректно, так как объекты ордера возвращаются только Квиком. У них не должно быть конструктора, не знаю будет ли работать JSON.NET без конструктора.
