### ISSUE TITLE
Блокировка при подключении

### ISSUE THREAD

**Issue by kv-gits** [finsight/QUIKSharp#210]
QUIK 7.19.3.1 (либы запускаются нормально)
Windows 10
.net core 2.0.0
QuikSharp 1.0.0 nuget
При подключении сишарп блокируется.
Подключаю так и пробовал через default port

 `_quik = new Quik(34130, new InMemoryStorage()); `

UPD:
Такое поведение появляется при установке targetframework netcoreapp3.0

**Comment by kv-gits** [comment]
Покопался я. Конект происходит, обмен сообщениями идет, но функция is_connected возвращает ноль, хотя сообщения диспатчатся.

**Comment by kv-gits** [comment]
Скачал проект, демо-примеры работают нормаьно. При подключении к стороннему проекту из nuget qsharp подвисает при new Quik на сообщении "waiting for client responce".

**Comment by iflash5** [comment]
@kv-gits 
https://www.youtube.com/watch?v=DKkCvKeSFoc

либо я не понял вопроса. Блокируется c# означает вызываете команду и она висит?

вот вам сложнее вопрос вышел quick 8.1 64 bit only ктонть пробовал собирать под него полностью все????

**Comment by Prival1** [comment]
Я собрал, все получилось. Работает. Квик 8.2.0.78.
Если нужно еще раз записать видео про это могу сделать.

**Comment by Nikolaev-Nikolay** [comment]
А Вы можете выложить бинарник, что бы не заморачиваться с варкой, а посмотреть поковыряться. Ну и видео не помешало бы :))

**Comment by Prival1** [comment]
Вот видео 
[https://youtu.be/QtMVqgwoPU0](url)
[https://youtu.be/3UeJdL3bUKs](url)
У меня все получилось запустить. Есть мелкие неточности, но я их поправил, на видео. Все есть.
Квик 8.2...
Огромное спасибо автору. Как могу буду поддерживать этот проект.

**Comment by Pr0phet1c** [comment]
@Prival1 , я правильно понимаю, что у Вас видео на демо-счете записано? Есть подозрение что на "игровом" терминале роботы и библиотека в целом могут работать некорректно. По умолчанию, данный робот не должен выставлять множественные заявки на открытие позиции, с таким коротким интервалом. В Вашем примере он должен был открыть позицию ОДИН раз размером в 1 лот, и далее ждать дальнейшего движения. Эту часть я тестировал на боевом счете, и того, что видно у Вас в видео точно не происходило.

**Comment by nikorus** [comment]
Подскажите пожалуйста - где и что  не так или не хватает:
 при попытки подключении к терминалу выдает:
 Вызвано исключение: "System.IO.FileNotFoundException" в QUIKSharp.dll

**Comment by Pr0phet1c** [comment]
Самый очевидный ответ: Неправильно "урезаете" демо-робота. Для более развернутого ответа недостаточно данных.
Попробуйте не "урезать", а создать маленькую программу "с нуля", где будет только инициализация класса. Скорее всего Вы упускаете из виду что-то элементарное.

**Comment by nikorus** [comment]
Все получилось ! Скорее всего ссылка на QUIKSharp.dll у меня была кривая или то, что на терминале был запущен старый скрипт луа из другого источника. Спасибо авторам !
