### ISSUE TITLE
Отписка от стакана не работает

### ISSUE THREAD

**Issue by aBaTaPbl4** [finsight/QUIKSharp#212]
Здравствуйте. 
Получаю содержимое стакана по следующему алгоритму:
1) Подписка на получение стакана
2) Получение стакана
3) Отписка от получения стакана

Столкнулся с тем, что на шаге 3, - отписка от стакана, функционал по факту не работает.
Код отписки выглядит следующим образом:
```
        private void UnsubscribeOrderBook()
        {
            int i = 1;
            while (_isSubscribedToolOrderBook = _quikWrapper.IsSubscribedOnOrderBook(_defaultSec))
            {
                _log.InfoFormat("Попытка отписки от стакана No {0}", i);
                _quikWrapper.UnsubscribeOrderBook(_defaultSec);
                i++;
                if (i > 10)
                {
                    Guard.Throw("Failed to unsubscribe");
                }
                    

            }
            _isSubscribedToolOrderBook = false;
        }
```

В итоге у нас всегда вылетает исключение, в тоже время делегат обработки события "получение стакана" продолжает вызываться.

Подскажите пожалуйста в чем может быть проблема?

Заранее Спасибо.

**Comment by cmcdetonator** [comment]
Всем привет! 
кстати я сейчас как раз учусь писать скрипты на луа и у меня та же проблема, поэтому я думаю, что трабла на в квикшарпе.
У меня условно то же самое но на луа, подписываешься, берешь стакан, отписываешься

Судя по всему отписка занимает какое-то время (как кстати и получение стакана) и если сразу проверить, отписался или нет то выдает, что еще подписан (почти всегда)

**Comment by aBaTaPbl4** [comment]
_quikWrapper - это синхронная обертка над классом Quik. Она дожидается завершения выполнения команды, запущенной квиком.
Но ради полноты эксперимента, я добавил ожидание в процедуру отписки от стакана.
Симптомы, увы..не изменились

```
        private void UnsubscribeOrderBook()
        {
            _quikWrapper.Events.OnQuote -= this.OnOrderBookChanged;
            int i = 1;
            while (_isSubscribedToolOrderBook = _quikWrapper.IsSubscribedOnOrderBook(_defaultSec))
            {
                _log.InfoFormat("Попытка отписки от стакана No {0}", i);
                _quikWrapper.UnsubscribeOrderBook(_defaultSec);
                if (i > 1)
                {
                    Thread.Sleep(1000);
                }
                i++;
                if (i > 10)
                {
                    _log.Error("Failed to unsubscribe on server");
                    break;
                }
            }
            _isSubscribedToolOrderBook = false;
        }
```

**Comment by buybackoff** [comment]
Посмотрите может Lua API изменилась или неправильно вызывается. 

Если @cmcdetonator говорит, что и в Луа так же, то это не проблема Quik#

**Comment by cmcdetonator** [comment]
вроде не важно, синхронная обертка или нет
сам квик-то ответ присылает, т.е. вызов unsubscribe завершен, просто итог его - подписка не отменена
наверно надо на форум квика идти за ответом, но  я простой код  на луа накидал для иллюстрации проблемы. В результате у меня никогда не получается отписаться от стакана.

````
count = 0
IsRun = true 

function main()
	while IsRun do 
		if (count==1) then
			sleep(10000)
			if (Unsubscribe_Level_II_Quotes(class, sec)) then
				message("Successfully unscubscribed")
			else
				message("Unable to unsubscribe")
			end
			sleep(10000)
			if(IsSubscribed_Level_II_Quotes(class, sec)) then
				message("yeah")
			else
				message("still nothing")
			end
			IsRun = false
		end
	end

end;


function OnParam(class, sec)
	if(count == 0) then
		if(Subscribe_Level_II_Quotes(class, sec)) then
			message("subscribed to " .. sec)
			--ql2 = getQuoteLevel2(class, sec)
			count = count + 1
		else
			message("Unable to subscribe to " .. sec)
		end
			
	end 

end

```

**Comment by Pr0phet1c** [comment]
Реализовал отписку от стакана в QuikSharpDemo. У меня вроде как работает (во всяком случае, IsSubscribed возвращает false после отписки). Свежее обновление в мастер-ветке

**Comment by aBaTaPbl4** [comment]
По-моему, в реализованом примере ошибка, из-за этого и работает=)
Обратите внимание на битовое "AND" в первой строчке, полагаю там должно быть логическое (&&)? + счетчик не инкрементируется.

                        while(isSubscribedToolOrderBook & i < 10)
                        {
                            Thread.Sleep(500);
                            isSubscribedToolOrderBook = _quik.OrderBook.IsSubscribed(tool.ClassCode, tool.SecurityCode).Result;
                        }

**Comment by Pr0phet1c** [comment]
Да, Вы правы, это ошибка. Значит "по быстрому" не получилось. Буду разбираться позже.

**Comment by aBaTaPbl4** [comment]
Главная проблема тут в том, что мой торговый робот умирает от стакана, подобно алкоголику. И нет никакой возможности, дать ему боржоми.

**Comment by Pr0phet1c** [comment]
В общем, немного доделал процедуру отписки в QuikSharpDemo. По идее, теперь все правильно сделано, и все работает. Но выложить смогу только завтра.

Что же касается Вашей проблемы, то опишите ее подробнее. На сколько я помню, мое приложение держит подписку минимум на 10 стаканов (но может оказаться и несколько десятков), и проблем не испытывает.
Первое что я рекомендовал бы проверить - сравнить работоспособность днем и вечером. Если вечером Ваш робот работает стабильно, то скорее всего Ваша проблема связана с тем, что Вы по каждому срабатыванию колбэка, на изменения в стакане, запускаете процедуру сложного расчета. При высокой активности на рынке, это легко может приводить к проблемам.

**Comment by aBaTaPbl4** [comment]
В мастер-ветке получается будет фикс?

По проблеме, - подписка идет на один инструмент. Для обработки событий сразу дергаем таску, чтобы не блокировать вызывающий поток:
```
        void OnOrderBookChanged(OrderBook quote)
        {
            Task.Run(() => this.OnOrderChangedImpl(quote));
        }
```
Проблемы начинаются на серверной стороне квик шарпа. 
Проявляются в том, что начинают отваливаться другие вызовы к сервису от робота. 
При этом Квик с роботом, запущены на одной машине.

Пока подписки на получения стакана не было, - всё было ок.
Поэтому и решил что проблема в подписке на стакан.

Завтра еще дополнительно проверю гипотезу о влиянии передачи стакана, на другие команды.

Квик к тестовому серверу от компании БКС.  Версия программы 7.19.0.51.
https://broker.ru/demo

Единственное, что у меня старая версия скриптов QuikSharp-a по терминалом находилась, со времен беты еще наверное. Только сейчас заметил.

**Comment by Pr0phet1c** [comment]
1. мастер-ветку обновил.
2. Если до того, как успеет исполнится Ваша таска, успеет поступить еще пять-шесть колбэков (что вполне вероятное явление в периоды высокой активности), то проблемы могу возникнуть где угодно. Я из-за этого давно отказался от использования полностью событийной модели и перешел на замкнутый цикл опросов по таймеру. Это одновременно решило проблемы множественных колбэков и снизило нагрузку на ЦП. Правда, есть один нюанс - мои алгоритмы даже рядом не стоят с ХФТ, и с тиками я тоже не работаю.
3. Впихните у себя в QuikSharpDemo выполнение какой-нибудь дополнительной таски по колбэку стакана и посмотрите что будет. Может быть найдете решение для своего случая.
4. Скрипты однозначно лучше обновить.
5. дополнительно можете попробовать закомментить строки:

            missed_values_file = io.open(missed_values_file_name, "a")

и

        missed_values_file:write(callback_string..'\n')

В qsutils.lua

**Comment by aBaTaPbl4** [comment]
Дополню пока по своему ресерчу, - скрипты под терминалом обновил и симптомы остались прежними,  - после подписки на стакан, - начинают отваливаться обращения к терминалу. Метод "_quik.IsConnected()"  - возвращает false. Хотя скрипт QuikSharp.lua работает, и терминал также работает без видимых лагов.

PS:
Спасибо за ответ, - гляну сразу как появится время и отпишусь

**Comment by aBaTaPbl4** [comment]
При подключении QuiksharpDemo к моему терминалу, отписка не прошла:

![отписка](https://user-images.githubusercontent.com/5055659/69413540-158f8d80-0d22-11ea-8a7e-a6cc7ee12e09.png)

**Comment by Pr0phet1c** [comment]
Даже не знаю, что Вам на это ответить. Попробуйте, после неудачной попытки, нажать эту кнопочку еще раз.
Вот мой результат:
![2019-11-22](https://user-images.githubusercontent.com/14761254/69416838-8e91e380-0d28-11ea-8d03-419f9d6393bb.jpg)

Правда, я сейчас проверял на 8-й версии квика, но учитывая то обстоятельство, что функция работы со стаканом делалась задолго до появления 8-ки, вряд ли это имеет значение (разве что в 7-ке изначально этот функционал не работал как надо даже на Lua).

И еще: В следующий раз закрашивайте такие поля как ClientCode, AccountID и FirmID

**Comment by buybackoff** [comment]
Удалил картинку с ClientCode, AccountID и FirmID. 

Оффтоп, но мне любопытно, как их можно использовать в злых целях? Реалистичный сценарий?

**Comment by Pr0phet1c** [comment]
Вероятно, у разных брокеров ситуация разная, но у одного из моих, при общении по телефону, сначала спрашивают "код клиента", дополнительно могут уточнить ФИО (а могут и не уточнить), после этого со мной разговаривают как с полноценным клиентом, предоставляя всю информацию по счету или бумагам. Что еще можно сделать, когда тебя воспринимают как 
"своего" клиента, думаю можно придумать. Даже если для совершения каких-то операций будут предусмотрены дополнительные меры защиты - лучше перестраховаться и не "светить" лишний раз такие индивидуальные данные (IMHO)

**Comment by buybackoff** [comment]
У меня всегда спрашивали одноразовый код с карточки с ними при телефонных звонках. Но согласен, не у всех могут быть дополнительные шаги идентификации.

**Comment by aBaTaPbl4** [comment]
Аккаунт тестовый, так что не критично. Но всё равно спасибо=)

**Comment by aBaTaPbl4** [comment]
Причина тормозов заключалась в многократном вызове "_quikWrapper.UnsubscribeOrderBook", - в цикле отписки.  
Если вызов этого метода вынести из цикла, так чтобы он вызывался только один раз, - то вроде всё ок

**Comment by cmcdetonator** [comment]
Я кстати тоже нашел выход и думаю причина общая - после подписки на стакан в реальности надо еще подождать, чтобы и получить этот стакан и даже чтобы отписаться от подписки

в луа я стал делать sleep на 300 мс после подписки(на меньшее у меня не срабатывало) и тогда стакан стал приходить и отписаться стало возможно (что не работало в случае мгновенного запроса стакана и последующей отписки)

так же я заметил, что если после подписки пытаться стакан получить из обработчика OnQuote, то задержку sleep (300) можно не использовать, т.к. после подписки OnQuote сам срабатывает для нужного стакана, когда стакан уже доступен для получения

У Вас судя по всему (т.к. отписку вы вынесли из цикла) теперь подписка реально успевает отработать и квик уже готов принять запрос на отписку

**Comment by aBaTaPbl4** [comment]
В боевой 8-ой версии квика, - отписка работает!
Единственной что у вас косяк в "QuikSharp Demo", - в коде отписки. 

Вместо:

```
                            textBoxBestBid.Text = "-";
                            textBoxBestOffer.Text = "-";
```
Нужно чтоб было
```
                            AppendText2TextBox(textBoxBestBid, "-");
                            AppendText2TextBox(textBoxBestOffer, "-");
```

ЗЫ: (офф топик)
В классе Quik сделайте возможность задавать ip адрес сервера, помимо порта.
А то фича уже есть и работает. А заиспользовать её, не прибегая к изменению кода библиотеки, нельзя8)

**Comment by Pr0phet1c** [comment]
"AppendText2TextBox" туда конечно же не подходит, но в целом замечание верное.
Исправления внесены. Мастер-ветку обновил.

А вот что касается IP-адреса, просьба пояснить, что Вы имеете в виду?
При инициализации класса мы задаем порт, через который наше приложение "общается" с терминалом. Какое отношение к этому процессу имеет IP-адрес? И кстати, о каком "сервере" идет речь?

**Comment by aBaTaPbl4** [comment]
ip-адрес терминала, где запущен QuikSharp.lua. Тут речь о подключению к терминалу запущенному на удаленном хосте.

В скрипте можно поменять ip-адрес, на котором запускается сервис.
А в клиентском коде, задать ip-адрес, отличный от localhost, возможности нет.
Если в квик клиента засетить нужный ip-адрес, подправив библиотеку, - то  всё работает.

**Comment by Pr0phet1c** [comment]
Можете показать куски кода в которые Вы внесли изменения (в части IP-адреса) после которых у вас все заработало как Вы хотели? Я подумаю как это можно организовать в библиотеке, и стоит ли оно того...

**Comment by aBaTaPbl4** [comment]
В классе QuikService, тут прописал нужный ip:
`private readonly IPAddress _host = IPAddress.Parse("127.0.0.1");`
Это собственно всё.

**Comment by Pr0phet1c** [comment]
Ранее Вы писали: "В скрипте можно поменять ip-адрес, на котором запускается сервис."
О каком скрипте шла речь? О том же классе QuikService или о чем-то еще?
Правильно ли я понимаю, что для своих целей Вы в коде вместо 127.0.0.1 прописали интересующий Вас адрес, пересобрали проект, и у вас все работает как надо Вам (т.е. терминал запускается на удаленном компе со статическим IP, а приложение на локальном компе)?

**Comment by aBaTaPbl4** [comment]
+ qsutils.lua
```
local response_server = socket.bind('localhost', port, 1)
local callback_server = socket.bind('localhost', callback_port, 1)
```
Да, ваше демо-приложение подключалось к терминалу запущенному на другой машине.

**Comment by buybackoff** [comment]
Я умышленно сделал 127.0.0.1, а не 0.0.0.0. Кому нужен продвинутый сценарий
легко могут изменить, но по умолчанию не очень хочется иметь торговый
терминал, доступный по сети без авторизации. Возможно имеет смысл добавить
файл конфигурации с ip для bind и портом, чтобы не менять код для этого.

**Comment by Pr0phet1c** [comment]
Понятно. Сделано (вроде бы)!
Но:
1. в qsutils.lua по прежнему придется руками прописывать нужный ip
2. в демо-приложение добавил возможность провести тест с удаленным терминалом. @aBaTaPbl4  проверка работоспособности за Вами. Жду обратную связь.

**Comment by Pr0phet1c** [comment]
@buybackoff , я тоже об этом задумывался, но пока руки как-то не доходят.

**Comment by aBaTaPbl4** [comment]
Поклацал по кнопкам. Вроде ок.
![image](https://user-images.githubusercontent.com/5055659/69939330-ac153900-14f0-11ea-8730-9ad4994b597e.png)

**Comment by Pr0phet1c** [comment]
Хорошо, спасибо.

**Comment by Igor-san** [comment]
Сегодня столкнулся с невозможностью отписаться от пары инструментов - оказалось что именно их стаканы открыты в квике. Закрыл - и все нормализовалось.
