### ISSUE TITLE
Вопрос по OrderTradeFlags

### ISSUE THREAD

**Issue by IFetisov** [finsight/QUIKSharp#213]
Привет.
Не понял можно и нужно ли этими флагами как то пользоваться при выставлении заявки и вообще зачем нужны флаги которые не используются и не работают.
Зачем например флаг из IsSell если у заявки есть Operation  
        private void ParseFlags()
        {
            // (Я закомментил у себя) Operation = Flags.HasFlag(OrderTradeFlags.IsSell) ? Operation.Sell : Operation.Buy;

            State = Flags.HasFlag(OrderTradeFlags.Active)
                ? State.Active
                : (Flags.HasFlag(OrderTradeFlags.Canceled)
                    ? State.Canceled
                    : State.Completed);
        }
При создании заявки если устанавливаешь добавляешь какой то флаг
   orderNew.Flags = orderNew.Flags | OrderTradeFlags.IsMarketMakerOrSent; 
ParseFlags - сразу убивает направление заявки. И в итоге вместо того чтобы продать дорого покупаешь дорого :).
И вообще эти флаги в CreateOrder никак не участвуют. Рыночную заявку поставить тоже нельзя.

**Comment by Pr0phet1c** [comment]
Я этими флагами пользуюсь исключительно для контроля статуса уже выставленной заявки (хотя только сейчас выяснил, что я пошел сложным путем). При выставлении заявки я флаги не использую. Видимо поэтому никогда не сталкивался с проблемой, которую Вы описали.
Зачем нужна закомментированная Вами строчка возможно сможет ответить @buybackoff

**Comment by buybackoff** [comment]
> Зачем нужна закомментированная Вами строчка возможно сможет ответить @buybackoff

Я уже не помню, мне придется читать код с нуля. Но общий принцип был читать документацию QLUA полностью, с примечаниями. Если что-то непонятное/сложное происходит в коде, нужно перечитать документацию. Если это не требуется для корректной работы в каких-то случаях, то значит я что-то переусложнил и можно переписать.

**Comment by Pr0phet1c** [comment]
Постарался самостоятельно изучить вопрос. Мои выводы:
1. В описании QLua в таблице параметров заявки нет такого параметра как "Operation", равно как и "State". Это значит, что данные параметры добавлены разработчиком библиотеки для большего удобства пользования, чтобы пользователю не пришлось забивать себе голову преобразованием флагов.
2. В тех методах, которые используются с библиотеке, нигде не применяется параметр Operation ДО отправки транзакции и получения экземпляра класса Order. Таким образом, при правильном использовании функционала отправки заявок, наличие обсуждаемой строчки никак не должно приводить в проблемам. Выражаясь другими словами, Обсуждаемая строка вызывается только тогда, когда мы обращаемся к набору битовых флагов заявки, а это должно происходить только после размещения заявки на бирже, т.к. этот параметр нельзя устанавливать, а можно только читать.
3. С учетом первых двух пунктов считаю имеющуюся реализацию кода оптимальной, и комментить обсуждаемую строку нет никакого смысла (а в ряде случаев может оказаться даже вредно).
4. В процессе изучения вопроса, обнаружил необходимость немного обновить класс Order (выяснилось в процессе изучения описания параметров таблицы заявок из свежего файла справки по QLua). Обновление выполнено и выгружено в мастер-ветку.
