### ISSUE TITLE
Quik зависает в конструктуре на вызове метода GetWorkingFolder

### ISSUE THREAD

**Issue by aBaTaPbl4** [finsight/QUIKSharp#214]
Помогите пж разобраться.
Квик собран из полседних исходинков.  lua-скрипт в терминале запущен.
Однако происходит зависание на строчке 
            QuikService.WorkingFolder   = Service.GetWorkingFolder().Result;

Еще недавно всё было ок. Код не менялся. Единственное что взял последние исходники квика. Вызов конструктора выглядит так:
                        var quik = new Quik(settings.Port, new InMemoryStorage());
В качестве порта передается Quik.DefaultPort

**Comment by aBaTaPbl4** [comment]
Тут еще возможно причина в том, что сейчас я пытаюсь использовать QuikSharp из .net core 3.1 приложения (раньше был .net framework)

**Comment by aBaTaPbl4** [comment]
В процессе работы метода QuikService.Start() в строке 278: 
`var reader = new StreamReader(stream, Encoding.GetEncoding(1251));`
Возникает ошибка System.NotSupportedException: 'No data is available for encoding 1251. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.'

В итоге из-за этой ошибки вылетаем из цикла обработки сообщений, что и приводит к зависону квика.

Ошибка характерна для .net core приложений. Чтоб её не было, нужно до вызова конструктора класса Quik, вставить магическую строку:
`Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);`

**Comment by ism** [comment]
I can confirm the bug. If target is set to 'netcoreapp3.1' the Quik constructor stalls at

https://github.com/finsight/QUIKSharp/blob/df68004b0c9a41e65373ecba7403921e97434cec/src/QuikSharp/Quik.cs#L41

**Comment by Pr0phet1c** [comment]
попробовал решить проблему изнутри, через вставку указанной строки, но проверить не могу.
Попробуйте использовать свежую версию, и сообщите о результатах.

**Comment by buybackoff** [comment]
#234

**Comment by AgentSmit** [comment]
Спасибо aBaTaPbl4, а то 2 часа голову ломаю почему не работает в net core 3.1. Ни каких сообщений об ошибках, просто зависало на подключении. Терминал в то время писал "client connected", сразу же "client disconnected", Quik продолжает работать, а программа повисла.

> В процессе работы метода QuikService.Start() в строке 278:
> `var reader = new StreamReader(stream, Encoding.GetEncoding(1251));`
> Возникает ошибка System.NotSupportedException: 'No data is available for encoding 1251. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.'
> 
> В итоге из-за этой ошибки вылетаем из цикла обработки сообщений, что и приводит к зависону квика.
> 
> Ошибка характерна для .net core приложений. Чтоб её не было, нужно до вызова конструктора класса Quik, вставить магическую строку:
> `Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);`
