### ISSUE TITLE
getCandlesByIndex

### ISSUE THREAD

**Issue by Prival1** [finsight/QUIKSharp#215]
нужен этот функционал. Не смог его найти.
Идея следующая. Брать показания индикаторов прямо из квика, а не самому рассчитывать.

Функция предназначена для получения информации о свечках по идентификатору (заказ данных для построения графика плагин не осуществляет, поэтому для успешного доступа нужный график должен быть открыт). Возвращаемые значения:
t – таблица, содержащая запрашиваемые свечки,
n – количество свечек в таблице t,
l – легенда (подпись) графика.

**Comment by Pr0phet1c** [comment]
Плохо искали.
_quik.Candles.GetCandles(
