### ISSUE TITLE
OnAllTrade

### ISSUE THREAD

**Issue by Prival1** [finsight/QUIKSharp#216]
иногда тики путаются местами. Скорее всего из-за того что они приходят пачками, насколько я знаю. А в Event передается только 1 тик. Ошибку можно посмотреть на видео с 13 мин.
Тики идут не подряд !
https://youtu.be/aAqmyzLe7DY?t=759

**Comment by Tr0sT** [comment]
Столкнулся с аналогичной проблемой.  

Ещё непонятно - возможно ли подписаться на обезличенные сделки по нужному инструменту аналогично тому, как подписываемся на стакан (Orders.Subscribe)? Или нужно обязательно сначала в quik настраивать фильтр таблицы обезличенных сделок?

**Comment by Prival1** [comment]
Нет не нужно. Скоро покажу на видео как это делать.
--
Отправлено из Mail.ru для Android суббота, 18 января 2020г., 16:03 +03:00 от Sergey Morozov  notifications@github.com :

**Comment by Tr0sT** [comment]
Аналогичная проблема с OnDepoLimit ивентом. Ивенты приходят иногда не в том порядке, то есть последнее присланное значение этим ивентом на самом деле может быть не последним, и это вызывает баги с определением текущей позиций.

**Comment by buybackoff** [comment]
Во всех таких делах нужно чётко понять - это такое поведение Квика, или эта библиотека делает что-то не так. Вспоминая #7 всякое может быть неожиданным

**Comment by Tr0sT** [comment]
Использую QuikSharp, чтобы не иметь удовольствия разрабатывать на quik lua, но очень сомневаюсь что в квике ивенты OnDepoLimit приходят в неправильном порядке. Если он приходит в quik в неправильном порядке - то это просто обесценивает этот ивент, так как в таком случае нельзя доверять его результату и рассчитывать размеры позиций на основании него...

**Comment by Pr0phet1c** [comment]
Зря сомневаетесь. Там еще и не такое бывает. Я например очень хорошо помню, как разработчики квика объясняли приход трех колбэков, с разными значениями отдельных параметров, на одно единственное событие. Но проверить каждую конкретную ситуацию можно только опытным путем. Хочу напомнить, что данная библиотека всего лишь транслирует данные из квика, полученные командами на Lua в С#, и не более того. Если по каким-либо причинам, Вы не можете получить удовлетворяющие Вас данные в колбэках, то библиотека на это скорее всего никак повлиять не сможет. Попробуйте поискать альтернативные пути получения интересующей Вас информации. Я в ряде случаев так и делаю.

**Comment by buybackoff** [comment]
Решение описано в #219
