### ISSUE TITLE
Trading.getFuturesLimit отсутствует

### ISSUE THREAD

**Issue by Tr0sT** [finsight/QUIKSharp#217]
Непонятно как получить информацию по фьючерсным лимитам, так как функция 
`TABLE getFuturesLimit(STRING firmid, STRING trdaccid, NUMBER limit_type, STRING currcode)`
не реализована. Хотя и есть комментарии и упоминания о ней в проекте.

**Comment by Pr0phet1c** [comment]
Вы уверены, что Вам так уж необходима именно эта функция? Какой такой параметр из этой таблицы для Вас на столько важен, что Вы не можете без него обойтись? Я несколько лет работаю с фьючами, и ни разу не столкнулся с необходимостью использовать именно эту функцию.

**Comment by Tr0sT** [comment]
Мне нужно получить баланс срочного рынка сразу после подключения. Для фондовой секции я делаю это с помощью GetMoney. Метод-аналог для срочного рынка я не нашёл, и решил что getFuturesLimit для этого. Возможно, есть другой способ?

**Comment by Pr0phet1c** [comment]
1. Что такое "баланс рынка", в Вашем понимании? Среди параметров таблицы, которую возвращает обозначенная функция, такого нет.
2. Функцию реализовал, но не тестировал. Если хотите - попробуйте и сообщите о результатах. Не забудьте, что для корректной работы, lua-файлы тоже придется обновить в той папке из которой Вы скрипт в квике запускаете.

**Comment by Tr0sT** [comment]
под балансом я имею ввиду количество кэша - деньги, доступные под подкупки и залоченные в заявках

**Comment by Pr0phet1c** [comment]
Ну, тогда пробуйте новую версию библиотеки, и не забудьте сообщить о результатах.

**Comment by Tr0sT** [comment]
Не работает. 
Во-первых, вы обновили lua скрипт только в profiler проекте, а в корневой папке lua их не обновили.
Во-вторых, при получении ответа в 305 строке файла QuikService
'var message = (r as string).FromJson(this);'
ответ не получается преобразовать в List<FuturesLimits>, поэтому получается бесконечный цикл или дедлок - эксепшна нет, но и возврата из функции тоже. Видимо чего-то не хватает в JsonConverter, но я не пойму как это исправить.

**Comment by Tr0sT** [comment]
я использую вот такой тест
       ```
        [Test]
        public void GetFuturesLimit() {
            string targetClass = "SPBFUT";
            var clientCode = _q.Class.GetTradeAccount(targetClass).Result;
            var firmId = _q.Class.GetClassInfo(targetClass).Result.FirmId;
            var res = _q.Trading.GetFuturesLimit(firmId, clientCode, 0, "SUR").Result;
            Console.WriteLine(res);
        }
```

**Comment by Pr0phet1c** [comment]
Тогда придется ждать пока я смогу заняться этим более плотно. Сейчас времени на это нет.

**Comment by Pr0phet1c** [comment]
Поправил, можно пользоваться. Работоспособность можно проверить в демо-приложении.

**Comment by Tr0sT** [comment]
Да, спасибо, всё работает. Когда планируется обновление nuget версии, содержащей эти изменения?

**Comment by Pr0phet1c** [comment]
Надо @buybackoff  попросить. Может он найдет время обновить версию...

**Comment by buybackoff** [comment]
Обновляется в 2 клика скриптами в папке nuget. Сделаю на днях (главное не забыть). И наверное надо дать доступ к NuGet для @Pr0phet1c
