### ISSUE TITLE
Task.Factory.StartNew could reorder callbacks, makes client code multi-threaded

### ISSUE THREAD

**Issue by buybackoff** [finsight/QUIKSharp#219]
#217 

С мая было много изменений, нужно сделать список release notes.

Самое важное - поддержка x64. 

Подтвердите (@Pr0phet1c и другие, кто использует), что бинарники в репо стабильно работают.

**Comment by Prival1** [comment]
Есть ошибки 
1.
...Sharp\QUIKSharp-master\src\QuikSharp\lua\qsutils.lua:177: attempt to index upvalue 'callback_client' (a nil value)
2.
...p\QUIKSharp-master\src\QuikSharp\lua\qscallbacks.lua:139: attempt to index field 'data' (a nil value)
3. В примере для работе на Demo Квике нужно вставить QJSIM

_quik.Class.GetSecurityClass("SPBFUT,TQBR,TQBS,TQNL,TQLV,TQNE,TQOB,**QJSIM**", secCode).Result;

**Comment by Prival1** [comment]
Есть еще 1 проблема.
Код
`        private void Events_OnAllTrade(AllTrade allTrade)
        {   
                var str = $"{allTrade.TradeNum};{allTrade.SecCode};{(DateTime)allTrade.Datetime};{allTrade.Price};{allTrade.Qty};{allTrade.Flags};{allTrade.OpenInterest}";
                _logger.Info(str);            
        }`
Кусок записанного лога
2020-01-29 16:33:10.7272 INFO 25623775782841;SiH0;29.01.2020 16:33:10;63045;19;1026;2463462
2020-01-29 16:33:10.7272 INFO **25623775782844**;SiH0;29.01.2020 16:33:10;63046;1;1026;2463468
2020-01-29 16:33:10.7272 INFO 25623775782843;SiH0;29.01.2020 16:33:10;63046;1;1026;2463466
2020-01-29 16:33:10.7272 INFO 25623775782845;SiH0;29.01.2020 16:33:10;63046;2;1026;2463472
2020-01-29 16:33:10.7272 INFO **25623775782842**;SiH0;29.01.2020 16:33:10;63046;1;1026;2463464
2020-01-29 16:33:10.7372 INFO 25623775782846;SiH0;29.01.2020 16:33:10;63046;3;1026;2463478
2020-01-29 16:33:10.7372 INFO 25623775782847;SiH0;29.01.2020 16:33:10;63047;5;1026;2463478
2020-01-29 16:33:10.7372 INFO 25623775782850;SiH0;29.01.2020 16:33:10;63047;5;1026;2463498
2020-01-29 16:33:10.7372 INFO 25623775782849;SiH0;29.01.2020 16:33:10;63047;2;1026;2463488
2020-01-29 16:33:10.7372 INFO 25623775782848;SiH0;29.01.2020 16:33:10;63047;3;1026;2463484

Как видно сделки идут не по порядку. Мне кажется это из-за того что allTrade - это 1 тик. А по факту там их приходит пачка.... нужно передавать сюда коллекцию, и уже обрабатывать через foreach() ... Я так думаю. В квике все четко, все тики идут по порядку...
Можно ли это исправить ?

**Comment by Pr0phet1c** [comment]
Уточните, каким образом Вы убедились в том, что в квике все в порядке?

**Comment by Prival1** [comment]
я визуально смотрю таблицу всех сделок Квика. Там они все по порядку идут (не замечал что тики местами меняются, это было бы заметно заметно). А в записанном логе сразу обратил внимание, там такое часто происходит.
Я думаю это важно для многих. Попробуйте воспроизвести. Если нужно я могу конечно записать видео экрана, потом найти в логе где переставляються тики, и найти это место на видео. Но если у вас тоже перепутываются местами, то с этим нужно что то делать.

**Comment by buybackoff** [comment]
Заметьте, что номера переставлены в том месте, где одно и то же время и одна и та же цена. Лог показывает одно и то же время с точностью до 100 микросекунд. Вероятно это результат большого рыночного ордера, ударившего по нескольким маленьким. Сделки прошли в один момент, и их порядок имеет мало значения если это так.

Я не помню как приходят трейды в Луа - если пачками, то можно просто сортировать по номеру в пачке. Если по одному, то ничего не поделать.

**Comment by Prival1** [comment]
Я раньше пользовался библиотекой StockSharp там приходит коллекция
        private void _connector_NewTrades(IEnumerable<Trade> trades)
        {
            
        }
Мой уровень программирования не такой высокий, как Ваш. Вряд ли смогу поправить ваш код. Если не затруднит, и у вас будет время посмотрите что можно сделать. Заранее благодарю.

**Comment by buybackoff** [comment]
В Луа приходят по одному http://luaq.ru/OnAllTrade.html

Эта библиотека пересылает всё, что приходит, по TCP, там невозможна перестановка.

Однако проблема тут: https://github.com/finsight/QUIKSharp/blob/a5b6a551f786628958bba69055579fd6c1f8103d/src/QuikSharp/QuikService.cs#L403-L417

Нужно использовать новые System.Threading.Channels, чтобы ставить колбеки в очередь и обрабатывать по одному, а не просто запускать Таски параллельно.

**Comment by buybackoff** [comment]
Можно использовать простую `BlockingCollection<ConcurrentQueue>` вместо каналов. Однако в обоих решениях все колбеки будут обрабатывать по очереди, один за другим. Если какой-то из них будет обрабатываться медленно - все другие будут ждать.

Вариант - разделить на типы сообщений. Например, все AllTrade обрабатываются своим потоком, стаканы - другим (можно сделать канал для каждого инструмента), и т.д. Этот вариант посложнее, но кажется правильнее.

С другой стороны - полностью однопоточное решение избавляет пользователей от необходимости думать о локах и прочей синхронизации потоков. Продвинутые пользователи могут сами разбить общий поток на составные независимые части (например используя Rx).

@Pr0phet1c что думаете?

**Comment by Prival1** [comment]
Мне кажется есть еще 1 решение. Это использовать ObservableCollection
Но я не уверен.

**Comment by Pr0phet1c** [comment]
К сожалению, я в этой области "профан". Единственное, что могу сказать, что меня терзают некоторые сомнения: Не получится ли так, что в моменты высокой активности на рынке, мы не будем успевать обрабатывать весь поток информации в однопоточном режиме, и начнем терять часть колбэков? Если мои опасения напрасны, то вероятно однопоточное решение наверное могло бы подойти. Вот только своими силами я это реализовать не смогу.

**Comment by buybackoff** [comment]
Все колбеки будут в очереди (как сообщения, которые один за другим скармливаются методу ProcessCallback из Invoker thread). Если обработка колбеков медленная, то очередь будет расти. В крайнем случае будет OutOfMemoryException, но вряд ли так много данных, скорее в случае плохого кода.

Нужно решить, какие события можно обрабатывать параллельно, а какие только по очереди.

* AllTrade - один поток, важен порядок сообщений
* Стакан - поток/канал на каждый инструмент, важен порядок сообщений для каждого инструмента, но сообщения для разных инструментов можно обрабатывать параллельно
* Колбеки по состоянию счета и OnOrder/OnTrade/etc - один общий поток. Важно получать их по порядку, чтобы отслеживать состояние счета.

Что еще можно обрабатывать паралелльно?

**Comment by Tr0sT** [comment]
Хотелось бы ещё как-нибудь уйти от стандартной подписки на ивенты, которая вызывает каждый подписанный метод по очереди, чтобы разные методы, подписанные на один и тот же ивент, не блочили друг друга...
Например у меня на OnAllTrade подписан основной алгоритм торговли, и отдельный алгоритм DataCollector, который все поступающие данные записывает в базу данных при достижении их большого количества в памяти. Когда данных накапливается много, то на очередном OnAllTrade мой коллекционер данных решит всё-это задампить на диск, и таким образом своей записью заблочит алгоритм торговли...
То есть хотелось бы, чтобы все ивенты приходили последовательно, но вот каждый обработчик ивента запускался параллельно, при этом блокируя свои (и только свои) следующие запуски до тех пор пока не завершится этот. Вообщем-то это не проблема сделать уже у себя, но может есть какое-то идиоматическое решение параллельных подписок.

**Comment by buybackoff** [comment]
@Tr0sT Это точно на стороне пользователей нужно делать. Много разных подходов для этого может быть.

**Comment by Pr0phet1c** [comment]
@buybackoff , По поводу "OnOrder/OnTrade", учитывая затроенность этих колбэков, мне кажется, что какое бы решение не было реализовано на нашей стороне, это не спасет от проблем, которые изначально заложили разработчики квика.
По остальному выглядит логично.

@Tr0sT , Возможно я как-то неправильно понял Вашу идею, но на мой взгляд отказываться от подписок нельзя, т.к. единственный способ это сделать - пересылать абсолютно ВСЕ колбэки, независимо от их востребованности. Очевидно, что это утопичный вариант.

**Comment by Tr0sT** [comment]
@Pr0phet1c Я имел ввиду, что вместо сигнатуры
```
events.OnAllTrade += OnAllTradeDataCollector;
events.OnAllTrade += OnAllTradeMainAlgorithm;
```
сделать что-то вроде
```
events.RegisterOnAllTrade(OnAllTradeDataCollector);
events.RegisterOnAllTrade(OnAllTradeMainAlgorithm);
```
Я реализую такое апи на своей стороне, но предположил наличие идиоматических способов таких асинхронных подписок в .net core api, может в System.Threading.Channels, про которые я не знал...

**Comment by buybackoff** [comment]
>  учитывая затроенность этих колбэков, мне кажется, что какое бы решение не было реализовано на нашей стороне, это не спасет от проблем, которые изначально заложили разработчики квика.

@Pr0phet1c  по крайне мере мы не будем делать ситуацию хуже.

@Tr0sT, идиоматический способ - это [Disruptor-net](https://github.com/disruptor-net/Disruptor-net) или https://github.com/Spreads/Spreads (библиотека сейчас в большой переработке и нерабочем состоянии).

**Comment by buybackoff** [comment]
Протестируйте плиз. Сделал только однопоточный вызов. По примеру можно разбить на отдельные каналы.

* "Поток" (Task с асинхронным циклом) receiver читает данные и десериализует их, пишет в канал.
* "Поток" Invoker читает из канала и вызывает метод ProcessCallback.

Второй поток можно сделать Dispatcher, который пишет каждый тип сообщения (например AllTrade) в свой канал, и для каждого типа сообщения свой Invoker. Эту часть в ближайшее время вряд ли смогу сделать.

**Comment by Tr0sT** [comment]
моя проблема с OnDepoLimit больше не возникает. Спасибо

**Comment by Prival1** [comment]
Виктор доброго времени суток. Не знаю как с вами связаться другим способом, поэтому пишу сюда.
1. Спасибо вам за библиотеку и Ваш труд.
2. Я начал писать видео на ютубе как пользоваться вашей библиотекой, надеюсь это поможет сделать ваш труд более востребованным. Ссылка на плей лист https://clck.ru/LRGZB
3. Если вас не затруднит, свяжитесь со мной в скайпе -> privalov-sv
Есть некоторые вещи которые нужно запрограммировать, пока они выше моего уровня программирования, я могу показать, как это сделано (что нужно) в других торговых платформах (библиотеках) на C# и показать код.
Для этой задачи дал объявления о поиске программистов на С#... мне кажется будет правильнее если вы откликнитесь.
В принципе любой кто прочтет это пишите буду рад сотрудничеству, условия обговорим в скайпе.

**Comment by buybackoff** [comment]
@Prival1 к сожалению сейчас даже час в неделю на эту библиотеку сложно найти. Могу только следить за багами и вносить небольшие критические изменения, как последний коммит тут, и только в рамках open source и заявленной цели "повторить API QLUA" в .NET.

Связаться со мной можно через личные сообщения в Твиттере. Также мой email видно в истории коммитов на ГитХабе.

**Comment by Prival1** [comment]
> @Prival1 к сожалению сейчас даже час в неделю на эту библиотеку сложно найти. Могу только следить за багами и вносить небольшие критические изменения, как последний коммит тут, и только в рамках open source и заявленной цели "повторить API QLUA" в .NET.
> 
> Связаться со мной можно через личные сообщения в Твиттере. Также мой email видно в истории коммитов на ГитХабе.

Если Вас не затруднит посмотрите вот это видео. Там всего 5 мин https://youtu.be/kn-MvFo5lag

**Comment by buybackoff** [comment]
@Prival1 это так работает QLUA. По OnParam невозможно узнать, какие параметры обновились. В Квике многое нелогично.

![image](https://user-images.githubusercontent.com/489852/74090896-4fff0000-4ab1-11ea-8e85-92a077c1e5ff.png)

**Comment by buybackoff** [comment]
Что бы я сделал:
* Хранить в Луа таблицу с ключем class_code и sec_code и всеми текущими параметрами, которые были запрошены (типа кэш)
* На каждый OnParam проверять значения всех ранее запрошенных параметров через getParamEx и если что-то изменилось, то присылать новые значения измененных параметров вместе с кодами в колбэке OnParam.

Это сэкономит roundtrip в QUIK# и сериализацию, сделает API удобнее. Но фундаметнально ничего не меняется - нужно вызывать getParamEx после OnParam.

**Comment by Pr0phet1c** [comment]
Что-то у меня все сломалось. :(

Connecting on callback channel... 
Callback channel connected
AlgoDriveVH_v2.exe Error: 0 : Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: String. Path '', line 1, position 10.
   в Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   в QuikSharp.JsonCreationConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) в C:\Users\Владислав\Dropbox\C#\Repository\QuikSharp - new\src\QuikSharp\Serialization.cs:строка 402
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   в Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   в Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   в Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   в QuikSharp.JsonExtensions.FromJson(String json, QuikService service) в C:\Users\Владислав\Dropbox\C#\Repository\QuikSharp - new\src\QuikSharp\Serialization.cs:строка 57
   в QuikSharp.QuikService.<<Start>b__53_3>d.MoveNext() в C:\Users\Владислав\Dropbox\C#\Repository\QuikSharp - new\src\QuikSharp\QuikService.cs:строка 417
Response channel disconnected
Callback channel disconnected


Пока не могу понять в чем проблема.

**Comment by buybackoff** [comment]
@Pr0phet1c  Что-то с JSON не то. Обновляли что-нибудь (Квик, JSON.NET) с последнего удачного запуска?

**Comment by Prival1** [comment]
У меня все нормально. такого не возникает. Квик версии разные 8.2 и 8.3 все работает.
Да забыл сообщить 
Тики теперь приходять нормально не путаются местами.
Спасибо.

**Comment by Pr0phet1c** [comment]
Сначала, я тоже подумал, что какие-то проблемы с JSON, но на пустом месте они не могли возникнуть. Ничего такого не делал, только вытянул к себе последний фикс, и пересобрал свои проекты. Как показало дальнейшее разбирательство (за пол часа до полуночи :) ), видимо проблема была в System.Runtime.CompilerServices.Unsafe и System.Text.CodePagesEncodingProvider

У меня были установлены версии 4.5.0, после обновления до 4.7.0 вроде бы все заработало, но пока не уверен, что все работает на 100% корректно.

**Comment by Prival1** [comment]
нашел еще ошибку.
1. var ddd= quik.Trading.GetParamEx(ClassCode, SecurityCode, ParamNames.NUMBIDS).Result;
все приходит за исключением
ddd.LuaTimeStamp - всегда равен 0.

**Comment by Nikolaev-Nikolay** [comment]
Скажите пожалуйста, все то, что Вы делаете, это где то у Вас на компе или выкладывается в общий проект?! Хотел тоже войти в стройные ряды - не могу понять, откуда стартовать?!

**Comment by Pr0phet1c** [comment]
@Prival1, это не столько ошибка, сколько следствие наследственности интерфейса. Я не помню, откуда там взялась привязка к интерфейсу IWithLuaTimeStamp (то ли я копипастом создал, то ли она там уже была до моего вмешательства), но суть в том, что в данной функции, среди возвращаемых параметров LuaTimeStamp быть в общем-то и не должно. Обычно, этот параметр заполняется в колбэках, но лично я его значение все равно никогда не использовал.
Таким образом - можете просто забыть о существовании данного параметра в указанной функции. Это ни на что не влияет.

**Comment by Prival1** [comment]
Очень расстроен (((. Я так надеялся что могу получить время для этих параметров, разработчики Квика тоже говорят https://forum.quik.ru/messages/forum10/message42038/topic734/#message42038
Дело в том что я использую для анализа свои собственные индикаторы. Есть такая наука ЦОС (цифровая обработка сигналов). Одним из фундаментальных понятий в которой является частота дискретизации сигнала (период поступления данных) ....от неё многое зависит. 

Хотя я до сих пор так и не нашел лучшего варианта сбора тиков, стакана и параметров. Дельта очень сильно плавает, имею ввиду разницу между временем когда примеру сделка прошла на бирже и временем когда она ко мне прилетела. 
И последнее время почему то часто стало.
Net error: Удаленный хост принудительно разорвал существующее подключение.
После этого вообще беда ((( сегодня максимальная задержка после этого 140 сек.
Если соединение не рвется то эта дельта все равно плавает от 0 до 9-10 секунд 
Я что то не так делаю наверное. А вот что пока не могу понять.

**Comment by buybackoff** [comment]
LuaTimeStamp - это TimeStamp, который задается Луа. Можно с таким же успехом использовать DateTime.UtcNow.
