### ISSUE TITLE
Реактивная модель

### ISSUE THREAD

**Issue by SkyQuant** [finsight/QuikSharp#22]
Я тут подумал, что может быть было бы неплохо внедрить не событийную модель, а реактивную. Построить коннектор на базе _Akka.NET_ http://getakka.net/ и раздавать приходящие сообщения потребителям. На известном трекере недавно аж три курса было выложено по этому фреймворку.

**Comment by buybackoff** [comment]
Akka точно не подходит сюда. Это для другого, и если тут применять акторов, то я уж свою библиотеку прикручу: https://github.com/buybackoff/Ractor.CLR
Вы скорее говорите об Rx.
Я давно работаю над библиотекой для анализа данных в реальном времени и построения стратегий, она уже используется нами "в производстве" и очень удобно и быстро работает. Я планирую ее в недалеком времени опубликовать с открытым кодом. Ноги растут из Deedle и этого [issue](https://github.com/BlueMountainCapital/Deedle/issues/51)

**Comment by SkyQuant** [comment]
Здорово! Было бы любопытно взглянуть на библиотеку.

Тогда текущая событийная модель, получается, оптимальная? Какую архитектуру приложения выбрать? Делать quik как сервис-singltone и через DI внедрять его во ViewModels? В них же события и обрабатывать.

**Comment by buybackoff** [comment]
Вам для анализа нужно собирать временные ряды, готовой удобной библиотеки для реального времени пока не суещствует. Rx добавляет некоторое удобство, но в целом это те же события. Так что все равно придется дописывать логику самому. Rx позволит внерить IObservables, насколько я знаю они хорошо поддерживаются в GUI, но я далек от форм.

**Comment by SkyQuant** [comment]
Ок, поразбираюсь. Можно только в двух словах уточнить, почему Rx подходит, а Akka и другие акторы нет?

**Comment by SkyQuant** [comment]
Акка, наверное, больше подходит для коммуникации с облаком? Где сферы её применения?

**Comment by buybackoff** [comment]
Акка - это акторы, несколько другая абстракция. Тут она overkill, но можно
взять и ее, если речь идет о какой-то большой системе. Но тогда она не
должна быть частью КвикШарпа, а только использовать его как источник
событий и посылать ему команды.

2015-09-21 18:22 GMT+03:00 SkyQuant <notifications@github.com>:

**Comment by SkyQuant** [comment]
Спасибо!
