### ISSUE TITLE
Зависает вне студии

### ISSUE THREAD

**Issue by iza88** [finsight/QUIKSharp#222]
Из Visual Studio программа работает нормально.
Но когда просто запускаю exe, зависает тут:
`QuikService.WorkingFolder   = Service.GetWorkingFolder().Result;`
посмотрел через Debug > Attach to Process

**Comment by Pr0phet1c** [comment]
попробовал решить проблему, но проверить не могу.
Попробуйте использовать свежую версию, и сообщите о результатах.

**Comment by iza88** [comment]
скачал сегодняшнюю - не помогло
вообще у меня раньше всё работало и вне студии с версией примерно ноября
но вот сейчас решил обновить, и работать перестало

и сорри забыл еще один важный момент - это происходит только на одном компьютере (там win7)
на другом (win10) вне студии всё работает нормально
у меня такое подозрение, что дело в каких-то библиотеках или установленных программах

**Comment by Pr0phet1c** [comment]
Жаль.
Вот тут: https://github.com/finsight/QUIKSharp/issues/214
Описана эта же проблема и метод ее решения. Попробуйте сделать так, как предложил пользователь обнаруживший проблему.

**Comment by Pr0phet1c** [comment]
Я думал у Вас проблема такая же как тут: https://github.com/finsight/QUIKSharp/issues/214
Тогда я пока ничем помочь не могу. Не знаю в чем может быть проблема. На Win7 я уже давно нигде не работаю.

**Comment by iza88** [comment]
решил проблему скачав эту версию
https://github.com/finsight/QUIKSharp/tree/eeac1a2c380f6712d387e1994b99a2af1c1bfcfb

**Comment by Pr0phet1c** [comment]
Сложно назвать такой вариант решением проблемы. Эту версию библиотеки Вы не сможете использовать с квиком версии 8.0 и выше.

**Comment by buybackoff** [comment]
Нужно попробовать везде, где используется `new TaskCompletionSource()`, добавить опцию RunContinuationsAsynchronously, возможно в этом проблема.

**Comment by Pr0phet1c** [comment]
@buybackoff cделал.
@iza88 попробуйте проверить новый вариант.

**Comment by iza88** [comment]
спасибо за оперативность, но не помогло
перейду на win10 всё равно когда-то

**Comment by buybackoff** [comment]
@Pr0phet1c я поторопился, для каждого response уже был свой Task: https://github.com/finsight/QUIKSharp/blob/fc378833227f1ddf159fc0d084cc79d109d552f7/src/QuikSharp/QuikService.cs#L310

Где-то блокируются (deadlock) потоки, надо будет пересмотреть код.

**Comment by Prival1** [comment]
Виктор если это возможно. Покажите пример как получать из квика не один инструмент а несколько. К примету IMOEX, SBER, RIH0. Что бы в 
            _quik.Events.OnQuote += Events_OnQuote;         //Стакан
            _quik.Events.OnAllTrade += Events_OnAllTrade;   //Тики
            _quik.Events.OnParam += Events_OnParam;         //Параметры
Приходите эти инструменты. Никак не получается ((( через некоторое время котировки просто перестают приходить, в чем причина не понимаю. Вот ссылка на код + там есть log файл (2020-03-02.log) где видно что котировки просто перестают приходить (IMOEX вообще не приходит), хотя сам квик работал без проблем никаких разрывов (отсоединений не было)
https://yadi.sk/d/_nQ2ovh6spWeVw

**Comment by Pr0phet1c** [comment]
@buybackoff , откатить обратно как было, или оставить как теперь есть?

**Comment by buybackoff** [comment]
@Pr0phet1c можно оставить, думаю для большинства, кто не сталкивался с багами из-за этого, новое поведение более интуитивное.

**Comment by Pr0phet1c** [comment]
ОК

**Comment by kasumumu** [comment]
Добрый день. У меня такая же проблема когда в решении создаю новый проект к примеру api(консольку тоже пробовал) и просто инициализация new Quik зависает дальше ничего не идет. Там вроде где то цикл бесконечный, но даже если таймауты ставить, то от этого не легче потому что все равно выбрасывает стабильно с ошибкой таймаута. Все накрывается как и выше было указано на методе GetWorkingFolder вроде, по крайней мере от него результат получить не удается. Проверял сам терминал по тысяче раз скрипты запущены и локалхосты работают, и Ваша демо версия отлично подключается к квику и получает Result, но новое приложение с подключенный проектом QuikSharp не может. Там есть какая то завязка на текущий фреймворк?

**Comment by kasumumu** [comment]
Подгрузил 4.7.2 фреймворк все заработало в новом проекте. Получается не работает на Core.

**Comment by kasumumu** [comment]
> Подгрузил 4.7.2 фреймворк все заработало в новом проекте. Получается не работает на Core.

Нет все равно как то странно работало, теперь не работает. Демо стабильно работает, а если делаешь какое то api, которое использует QuikSharp, то даже не подключается.

**Comment by Pr0phet1c** [comment]
На сколько я понимаю, единственным решением (на данный момент) обеспечения работы по .Core, является использование строки:

Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);

перед инициализацией экземпляра Quik. Проблема в том, что если эту строку встроить в библиотеку, то тогда она (библиотека) перестает работать под .net
Попробуйте...

**Comment by kasumumu** [comment]
> На сколько я понимаю, единственным решением (на данный момент) обеспечения работы под .Core, является использование строки:
> 
> Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
> 
> перед инициализацией экземпляра Quik. Проблема в том, что если эту строку встроить в библиотеку, то тогда она (библиотека) перестает работать под .net
> Попробуйте...

как понял проблема не совсем в Core, некоровское api тоже не могло работать с QuikSharp, пока не понял в чем дело, т.к. по сути зависает сам QuikSharp. Сегодня подобрал коммиты с багфиксами в lua, и сейчас проблем в данный момент не наблюдаю. Посмотрим что будет на открытии но проблема похоже пропала

**Comment by iza88** [comment]
прошу прощения, зависание не из-за студии, а из-за windows 7
#233

**Comment by buybackoff** [comment]
Возник вопрос в #236, посмотрите плиз
