### ISSUE TITLE
Missed callBacks Как это работает

### ISSUE THREAD

**Issue by IFetisov** [finsight/QUIKSharp#223]
Всем привет.
Идет запись файл MissedCallBacks Файл очень быстро дорастает до нескольких гигов и комп умирает. Закомментил код в Луа. Это поможет?
    -- we need this break instead of else because we could lose connection inside the previous if
    -- if not is_connected and was_connected then
    --    if not missed_values_file then
    --        missed_values_file_name = script_path .. "/logs/MissedCallbacks."..os.time()..".log"
    --        missed_values_file = io.open(missed_values_file_name, "a")
    --    end
    --    missed_values_file:write(callback_string..'\n')

{"cmd":"OnQuote","t":1583152405597,"data":{"sec_code":"ALRS","offer_count":"20.000000","class_code":"TQBR","offer":[{"price":"71.19","quantity":"398"},{"price":"71.20","quantity":"503"},{"price":"71.21","quantity":"311"},{"price":"71.22","quantity":"350"},{"price":"71.23","quantity":"65"},{"price":"71.24","quantity":"558"},{"price":"71.25","quantity":"165"},{"price":"71.26","quantity":"294"},{"price":"71.27","quantity":"871"},{"price":"71.28","quantity":"2827"},{"price":"71.29","quantity":"350"},{"price":"71.30","quantity":"308"},{"price":"71.31","quantity":"350"},{"price":"71.32","quantity":"1"},{"price":"71.33","quantity":"73"},{"price":"71.34","quantity":"51"},{"price":"71.35","quantity":"1000"},{"price":"71.36","quantity":"208"},{"price":"71.37","quantity":"59"},{"price":"71.38","quantity":"1"}],"bid":[{"price":"70.91","quantity":"1402"},{"price":"70.92","quantity":"207"},{"price":"70.93","quantity":"1202"},{"price":"70.95","quantity":"1095"},{"price":"70.97","quantity":"843"},{"price":"70.98","quantity":"2264"},{"price":"70.99","quantity":"1337"},{"price":"71.00","quantity":"1243"},{"price":"71.01","quantity":"1061"},{"price":"71.02","quantity":"18"},{"price":"71.03","quantity":"958"},{"price":"71.04","quantity":"312"},{"price":"71.05","quantity":"1627"},{"price":"71.06","quantity":"500"},{"price":"71.07","quantity":"1107"},{"price":"71.08","quantity":"19"},{"price":"71.09","quantity":"1055"},{"price":"71.10","quantity":"165"},{"price":"71.11","quantity":"566"},{"price":"71.13","quantity":"162"}],"server_time":"15:33:25","bid_count":"20.000000"}}

**Comment by Pr0phet1c** [comment]
Я у себя уже давно так сделал. С тех пор проблем данного характера не испытываю.

**Comment by buybackoff** [comment]
Да, надо удалить это совсем. Это не часть API QLua.

**Comment by Pr0phet1c** [comment]
@buybackoff , мне выпилить этот кусок из проекта?

**Comment by buybackoff** [comment]
@Pr0phet1c я бы закоментил, чтобы код был под рукой как напоминание, но был выключен по умолчанию. Можно будет потом сделать опциональное логирование и чтение пропущенных сообщений из .NET явным образом, а не автоматически, как сейчас.

**Comment by Pr0phet1c** [comment]
Готово
