### ISSUE TITLE
Update to Lua 5.3 and long ids

### ISSUE THREAD

**Issue by IFetisov** [finsight/QUIKSharp#225]
https://forum.quik.ru/forum10/topic5119/
Уважаемые клиенты!

Московская биржа уведомила участников торгов о важных изменениях в новой версии торговой системы срочного рынка. Ключевым нововведением  является увеличение размерности идентификатора заявок и сделок: после обновления торговой системы идентификатор будет занимать до 19 десятичных знаков. Соответствующее изменение в промышленной системе запланировано на самое ближайшее время: https://www.moex.com/n26656/?nt=107
 
Уведомляем Вас, что старые версии терминалов QUIK не поддерживают полноценную работу с 19-значными номерами.
Наверное с этим надо что то делать ((

**Comment by buybackoff** [comment]
Log(10^19, 2) = 63.11, они перешли на `Int64/long`. Можно превентивно обновить поля на long. Если мы используем Id как число в Луа, наверное надо на всякий случай использовать как строку. Double поддерживает integers 2^53 без потери точности, соответственно Луа и JSON могут работать с числами до этого предела. Надеюсь биржа достаточно адекватна, чтобы не использовать id выше 2^53. Но без гарантии этого - нужно использовать строки. У Квика нет выбора кроме как сделать это поле строкой (если сейчас число, не помню), чтобы поддерживать любой long.

**Comment by Pr0phet1c** [comment]
Когда я впервые увидел эту новость, то первым делом проверил, чтобы у нас в библиотеке для номеров заявок использовался именно тип long. Так что, по моим наблюдениям, мы изначально готовы к такому повороту событий. Правда с lua-часть не залезал. Позже проверю. Я другую проблему обнаружил, но о ней отдельно напишу (я ее уже решил, но пока не выгружал), когда закончу с доделками, которые сейчас начал реализовывать.

**Comment by buybackoff** [comment]
Самое главное в той новости - переход на Lua 5.3. Это хорошо (там вроде бы проще 64 битная история), но потребует работы.

> 2. В связи с необходимостью поддержки 19-значных номеров, в терминале новой версии запланировано изменение версии LUA c 5.1 до 5.3. Это, в свою очередь, означает следующее:
- Выполнение скриптов, скомпилированных под версию Lua 5.1, будет невозможно на новой версии терминала QUIK, для решения проблемы потребуется повторная компиляция под версию Lua 5.3;

**Comment by Pr0phet1c** [comment]
Похоже, на стороне lua проблема все таки есть, но ее не решить, пока разрабы не поменяют что-то на своей стороне. Сейчас там квик выдает и принимает номера заявок именно в формате number. Вряд ли квик нормально проглотит string, без доработок разрабов. Но они об этом кажется предупреждали в своей новости. У меня недавно обновление от брокера прилетело и справка там кажется сильно подросла в размерах. надо будет изучить на досуге. Возможно, они уже что-то сделали для решения данной задачки.

**Comment by buybackoff** [comment]
Тут все ответы есть внизу ветки: https://forum.quik.ru/forum10/topic5119/

API QLUA не изменится, типы останутся как есть.

Нам нужны будут новые бинарники сокетов для 5.3. Танцы с ~~бубнами~~ точками, надеюсь, будут не нужны.

**Comment by Pr0phet1c** [comment]
Если что, у меня есть "lua-5.3.5_Win64_bin.zip". Сохранился с тех пор когда решали проблему перехода на x64.
На сколько помню - скачивал с легитимного ресурса.

**Comment by buybackoff** [comment]
сделано в https://github.com/finsight/QUIKSharp/commit/1dcef193aa948610aba516a2716c4d7645cd879f
