### ISSUE TITLE
не победить System.Text.Encoding.CodePages, Version=4.1.3.0

### ISSUE THREAD

**Issue by iiAlladin** [finsight/QUIKSharp#226]
Добрый день!!

В
![err_QuikSharpDemo](https://user-images.githubusercontent.com/15216754/76634905-a26f8880-6557-11ea-82b2-1e9b10050043.JPG)
опрос по QuikSharp.lua из проекта https://github.com/finsight/QUIKSharp/
Точнее QuikSharp.lua работает а вот пример QuikSharpDemo у меня нет VS community 17 

Я прикрутил вывод описания ошибки.

System.IO.FileNotFoundException: Не удалось загрузить файл или сборку "System.Text.Encoding.CodePages, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" либо одну из их зависимостей. Не удается найти указанный файл.

Имя файла: 'System.Text.Encoding.CodePages, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

   в QuikSharp.Quik..ctor(Int32 port, IPersistentStorage storage, String host)

 

   в QuikSharpDemo.FormMain.ButtonStart_Click(Object sender, EventArgs e) в C:\Users\Pankiv\Documents\examples\QUIKSharp-master\QUIKSharp-master\Examples\QuikSharpDemo\FormMain.cs:строка 84

Не могу победить.

**Comment by Pr0phet1c** [comment]
Если Вы используете самую свежую сборку, то первым делом Вам необходимо в классе Quik, проекта QUIKSharp удалить строки:
using System.Text;
и
Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);

После этого пересоберите все проекты. Должно помочь (при условии, что Вы используете .Net Framework, а не .Net Core).
Я недавно обнаружил, что эта добавка вызывает проблемы, но обновление будет чуть позже, после того как решу парочку смежных проблем.

**Comment by iiAlladin** [comment]
Спасибо! Помогло.
