### ISSUE TITLE
Дублирование кода?

### ISSUE THREAD

**Issue by sergshabal** [finsight/QUIKSharp#228]
https://github.com/finsight/QUIKSharp/blob/e7c5c700b50e9df8a95598f5be05b51c99233fdd/src/QuikSharp/lua/qscallbacks.lua#L215

**Comment by sergshabal** [comment]
https://github.com/finsight/QUIKSharp/blob/e7c5c700b50e9df8a95598f5be05b51c99233fdd/src/QuikSharp/lua/qscallbacks.lua#L62

**Comment by sergshabal** [comment]
И также с function OnDisconnected()
https://github.com/finsight/QUIKSharp/blob/e7c5c700b50e9df8a95598f5be05b51c99233fdd/src/QuikSharp/lua/qscallbacks.lua#L73
и https://github.com/finsight/QUIKSharp/blob/e7c5c700b50e9df8a95598f5be05b51c99233fdd/src/QuikSharp/lua/qscallbacks.lua#L206

**Comment by sergshabal** [comment]
В моем случае вызываются вторые объявления функций. Заметил что там нет проверки is_connected. Но все вроде отрабатывает. Скрипт не падает.

**Comment by Pr0phet1c** [comment]
Действительно были дубли :)
Исправлено.
Проверки is_connected в этих колбэках быть не должно.
