### ISSUE TITLE
Сбой получения котировок и исторических данных

### ISSUE THREAD

**Issue by Pr0phet1c** [finsight/QUIKSharp#229]
Однажды эта тема уже где-то всплывала. В общем подтвердилась проблема сбоя получения котировок и исторических данных. В какой-то (произвольный) момент данные о стакане и/или новых свечах исторических данных просто перестают приходить. Найти причину и устранить ее мне не удалось.
Что мне известно на данный момент:
1. Сбой может произойти в любой момент, но чем выше активность на рынке - тем чаще такие сбои происходят.
2. Переподпиской на получение данных проблема не решается. Данные все равно не идут после первого сбоя. Приходится перезагружать приложение.
3. Сбой где-то в C# или между QLua и C#, т.к. в коде QLua соответствующие колбеки продолжают вызываться, и отрабатывать отправку данных за пределы терминала.
4. Путем экспериментов, последнее место "затыка", которое мне удалось обнаружить (на примере обновления исторических данных) находится в классе QuikService, вот тут:

                    case EventNames.NewCandle:
                        Trace.Assert(message is Message<Candle>);
                        var candle = ((Message<Candle>)message).Data;
                        Candles.RaiseNewCandleEvent(candle);
                        break;

Попробовал отследить что тут происходит, и в какой-то момент произошел сбой с ошибкой типа Null Reference Exception (или что-то вроде того). Возможно, из терминала приехало значение null (хотя в QLua колбэк получил нормальную свечу). С этого момента данный колбэк вообще перестал вызываться. Напоминю, что на стороне QLua все продолжает исправно работать.
5. Самое интересное, что у меня на одном компе работают одновременно два терминала (разных версий) от двух разных брокеров. Так вот сбой получения исторических данных происходит только на одном терминале, на другом все нормально.

**Comment by buybackoff** [comment]
Как первый шаг (если этого еще где-то нет) нужно обернуть все циклы в тасках в try...catch и добавить логгинг непойманных ошибок в тасках.

При не обработанном исключении в тасках/потоках они молча умирают.

Что-то типа:

```
Task.Run(async () => {

while(true)
{
   try
   {
     var message = await .....
     Process(message);
    }
    catch (Exception ex)
    {
       Log(ex);
    }
}

});
```

Но это уже есть в основных циклах в QuickService, и ошибки логируются в Trace. У вас логируются сообщения из Trace?

**Comment by Pr0phet1c** [comment]
Нет, не логируются. Стыдно признаться, но никогда раньше не использовал логирование через Trace, Debug или NLog. Всегда применял собственные методы, из-за недостатка знаний.
Я даже не представляю что и как мне надо сделать в данном конкретном случае, чтобы найти источник проблемы. Предположим, я добавлю в класс QuikService строку типа:

Trace.Listeners.Add(new TextWriterTraceListener("TraceLogging.log"));

Я правильно понимаю, что в этот файл будут записываться все сообщения, которые в данном классе определены в Trace.Assert?
Не получу ли я там кучу мусора, который накопится за пару-тройку часов работы робота?

**Comment by buybackoff** [comment]
TraceListener нужно добавлять не в QuikService, а в конечное приложение. `Trace.TraceXXX` будет записывать логи во все TraceListener в коллекции. В TraceListener можно определить уровень, который записывается (это абстрактный класс, с одним абстрактным методом WriteLine и несколько виртуальных, которые по умолчанию используют абстрактный.)

**Comment by iza88** [comment]
Я кстати переподписываюсь на стаканы постоянно и вроде все норм работает, днями не перезапускаю

**Comment by Pr0phet1c** [comment]
Обновление не помогло. Отловить причину по прежнему не получается.

**Comment by buybackoff** [comment]
> 5. Самое интересное, что у меня на одном компе работают одновременно два терминала (разных версий) от двух разных брокеров. Так вот сбой получения исторических данных происходит только на одном терминале, на другом все нормально.

@Pr0phet1c  Разве это утверждение логически не означает, что дело в терминале? Если бы дело было в Q#, то ошибка была бы в обоих случаях.

**Comment by Pr0phet1c** [comment]
Ну, на самом деле, как выяснилось позже (через пару дней) во втором терминале происходит то же самое, просто гораздо реже. При этом, надо отметить что и нагрузка, которую создают мои роботы в этом терминале также значительно меньше.

**Comment by Pr0phet1c** [comment]
Серия экспериментов с логированием, вывела меня на следующую ошибку:
Вызвано исключение: "System.ArgumentNullException" в System.Core.dll
Проблема в том, что не могу понять где и когда точно эта ошибка  возникает, но именно из-за нее, судя по всему, система перестает обрабатывать какие-либо колбеки на стороне C#.
Попробую дать более подробное описание, может кого натолкнет на идеи.
В код Lua, я встроил сроку с выводом сообщения на экран терминала, при обновлении исторических данных по инструменту. В частности, при появлении новой свечи графика.
Одновременно с этим, я логирую поступление колбэков на стороне C#, исключая из логов такие колбэки как OnParam и OnQuote, т.к. они просто "засирают" лог.
Таким образом, проводя эксперимент с помощью демо-приложения, я имею поток периодических колбэков. В моем случае это: OnFuturesLimitChange, OnFuturesClientHolding - Эти колбэки поступают каждую минуту. И "NewCandle", который поступает каждые 15 минут, т.к. я подписался на получение данных по соответствующему таймфрейму.
Отслеженный сбой скорее произошел в период между 18:45 и 19:00. С 18:30 на стороне Lua есть информация о колбэках NewCandle, которые были обработаны и отправлены во внешнюю среду. Однако, на стороне C# последний поступивший колбэк зарегистрирован 18:44:59 (OnFuturesClientHolding). Время может быть неточным, так указывается системное время на компе. Последний колбэк "NewCandle", на стороне C# получен 18:29:58 (время также системное).
Все. После этого больше никакие колбэки уже не приходят вообще.

Ниже кусок кода, где я впервые ловлю поступление колбэков на стороне C#:
       private void ProcessCallbackMessage(IMessage message)
        {
            /////////////////////
            Trace.WriteLineIf(message == null, "Trace: ProcessCallbackMessage(). message = NULL");
            /////////////////////
            if (message == null) throw new ArgumentNullException("message");
            EventNames eventName;
            var parsed = Enum.TryParse(message.Command, true, out eventName);
            if (parsed)
            {
                /////////////////////
                bool newCand = eventName.ToString() != "OnParam" && eventName.ToString() != "OnQuote" ? true : false;
                if (newCand) Trace.WriteLine(DateTime.Now + ": Trace: ProcessCallbackMessage(). eventName = " + eventName.ToString());
                /////////////////////
                // TODO use as instead of assert+is+cast
                switch (eventName)

А вот скрин из приложения:
![2020-05-05_19-54-40](https://user-images.githubusercontent.com/14761254/81093441-cf626b00-8f0a-11ea-9e62-5fa0a067413e.png)

Есть какие-нибудь идеи, где отловить ошибку?

З.Ы.: Сразу хочу заметить, что вряд ли стоит связывать ошибку с техническим перерывом между сессиями, т.к. это только в демке сбой произошел в этот период времени, в то время как другие роботы, работающие в том же самом терминале, но по другим портам, регистрируют появление проблем в течение всего дня.

**Comment by Pr0phet1c** [comment]
Продолжаю эксперименты с отловом сбоя. Сегодня удалось поймать одну ошибку (не факт, что она единственная виновница):

Вот так сейчас выглядит кусок кода, в котором поймал ошибку:
           _callbackInvokerTask = Task.Factory.StartNew(async () =>
            {
                while (!_cts.IsCancellationRequested)
                {
                    try
                    {
                        var message = await _receivedCallbacksChannel.Reader.ReadAsync(_cts.Token);
                        ProcessCallbackMessage(message);
                    }
                    catch (LuaException e)
                    {
                        Trace.TraceError(e.ToString());
                    }
                    ///////////////
                    catch (ArgumentNullException er)
                    {
                        Trace.WriteLine(DateTime.Now + ": Trace: (_callbackInvokerTask) ArgumentNullException - " + er.Message);
                    }
                    ///////////////
                }
            },

А вот что записалось в файл:
12.05.2020 18:45:00: Trace: (_callbackInvokerTask) ArgumentNullException - Значение не может быть неопределенным.
Имя параметра: source

Судя по времени появления ошибки, и отсутствию в логах записи типа:
07.05.2020 18:29:59: Trace: EventNames.NewCandle
Trace: Получена новая свеча -  'Time' = 07.05.2020 18:29:59, 'TimeCandle' = 07.05.2020 18:15:00, 'Open' = 74343, 'Close' = 74327
Проблема вызвана колбэком "NewCandle"
А вот дальше я немного не понял. Где найти параметр с именем "source"???
И что делать дальше? Встроить проверку на null в этот кусок кода? Если встраивать, то что делать если получили null?

**Comment by buybackoff** [comment]
Полный stack trace был бы полезен.

Это может быть связано с LINQ: https://stackoverflow.com/a/16281298/801189

Возможно где-то коллекция (IEnuemrable), которая может быть пустой, но она вместо этого null.

А что, в той петле `while (!_cts.IsCancellationRequested)` ловятся только два вида ошибок? Если это так, то петля умирает и конечно после этого никакие колбэки не будут работать.

**Comment by Pr0phet1c** [comment]
1. Не знаю как вытащить полный stack trace (не умею)
2. Изначально в петле только один вид ошибок отлавливался. ArgumentNullException - я добавил, в качестве теста. и таких мест в классе несколько.
3. Пока вставил проверку на null, с сообщением об этом. Возможно, завтра что-нибудь увижу.

**Comment by buybackoff** [comment]
@Pr0phet1c попробовал пофиксить. Афтоформатирование добавило много изменений в коммит, идея описана в тексте коммита.

**Comment by Pr0phet1c** [comment]
Забрал. Буду тестировать.

**Comment by Pr0phet1c** [comment]
Ну, пожалуй пришло время отчитаться об итогах тестирования.
1. Ошибки больше не возникают, и таски/потоки больше не умирают.
2. Потеря колбэков перестала носить массовый характер, но все же не пропала полностью.
При этом, есть очень важное замечание: Когда эта проблема возникает, то она НЕ на стороне Q#. Т.е. колбэк не появляется на стороне Lua, Кроме того, из трех инструментов, которыми я сейчас торгую (Si, SR, MM) проблема возникает только с ММ. Проверял на трех разных версиях терминала (в том числе 8.5), на двух брокерах. Соответственно, можно сделать вывод, что в рамках работы библиотеки данный вопрос можно считать закрытым.

З.Ы.: Для себя данную проблему решил путем организации переподписки на исторические данные, в случае возникновения такой ситуации.
Вот кусочек лога:
22.05.2020 19:30:40 : RenewQuotation(MMM0|M15)
22.05.2020 19:30:46 : RenewQuotation(MMM0|M15)
22.05.2020 19:30:46 : RenewQuotation(). LastCandle in List AllCandle - Sec = MMM0, interval = M15, DatreTime = 22.05.2020 19:15:00
22.05.2020 19:30:46 : RenewQuotation(MMM0|M15) - Complete
22.05.2020 19:30:52 : RenewQuotation(). LastCandle in List AllCandle - Sec = MMM0, interval = M15, DatreTime = 22.05.2020 19:15:00
22.05.2020 19:30:53 : RenewQuotation(MMM0|M15) - Complete
22.05.2020 20:00:40 : RenewQuotation(MMM0|M15)
22.05.2020 20:00:46 : RenewQuotation(MMM0|M15)
22.05.2020 20:00:47 : RenewQuotation(). LastCandle in List AllCandle - Sec = MMM0, interval = M15, DatreTime = 22.05.2020 19:45:00
22.05.2020 20:00:47 : RenewQuotation(MMM0|M15) - Complete
22.05.2020 20:00:53 : RenewQuotation(). LastCandle in List AllCandle - Sec = MMM0, interval = M15, DatreTime = 22.05.2020 19:45:00
22.05.2020 20:00:53 : RenewQuotation(MMM0|M15) - Complete
22.05.2020 20:30:40 : RenewQuotation(SRM0|M15)
22.05.2020 20:30:46 : RenewQuotation(SRM0|M15)
22.05.2020 20:30:46 : RenewQuotation(). LastCandle in List AllCandle - Sec = SRM0, interval = M15, DatreTime = 22.05.2020 20:15:00
22.05.2020 20:30:46 : RenewQuotation(SRM0|M15) - Complete
22.05.2020 20:30:52 : RenewQuotation(). LastCandle in List AllCandle - Sec = SRM0, interval = M15, DatreTime = 22.05.2020 20:15:00
22.05.2020 20:30:52 : RenewQuotation(SRM0|M15) - Complete
22.05.2020 20:45:40 : RenewQuotation(MMM0|M15)
22.05.2020 20:45:46 : RenewQuotation(MMM0|M15)
22.05.2020 20:45:47 : RenewQuotation(). LastCandle in List AllCandle - Sec = MMM0, interval = M15, DatreTime = 22.05.2020 20:30:00
22.05.2020 20:45:47 : RenewQuotation(MMM0|M15) - Complete
22.05.2020 20:45:53 : RenewQuotation(). LastCandle in List AllCandle - Sec = MMM0, interval = M15, DatreTime = 22.05.2020 20:30:00
22.05.2020 20:45:53 : RenewQuotation(MMM0|M15) - Complete
22.05.2020 22:00:40 : RenewQuotation(MMM0|M15)
22.05.2020 22:00:46 : RenewQuotation(MMM0|M15)
