### ISSUE TITLE
Модуль core.dll несовместим с Quik 8.5 (Lua 5.3)

### ISSUE THREAD

**Issue by sgolod** [finsight/QUIKSharp#231]
При попытке загрузить последнюю версию QuikSharp.lua выдаётся ошибка:

error loading module 'socket.core' from file 'C:\Quik\LuaScripts\QuikSharp\clibs64\socket\core.dll':
	Не найден указанный модуль.

Файл присутствует. Нужно каким-то образом перекомпилировать для совместимости с 8.5 и Lua 5.3?

**Comment by Pr0phet1c** [comment]
У меня не было и нет (во всяком случае пока) возможности протестировать работу на версии 8.5.
Возможно, Ваше предположение верно. Будем искать пути решения. Если найдете Вы - сообщайте.

**Comment by Pr0phet1c** [comment]
Сделал еще один вариант. Попробуйте.
Изменились три lua-файла + расположение файлов Lua53.dll и core.dll (новый)
Сообщите о результатах, плиз.

**Comment by sgolod** [comment]
> Сделал еще один вариант. Попробуйте.
> Изменились три lua-файла + расположение файлов Lua53.dll и core.dll (новый)
> Сообщите о результатах, плиз.

склонировал репозитарий и заменил весь свой каталог на ваш из src/lua.
Ошибка та же самая:

error loading module 'socket.core' from file 'C:\Quik\LuaScripts\QuikSharp\clibs64\socket\core.dll':
	Не найден указанный модуль.

**Comment by Pr0phet1c** [comment]
Странно выглядит путь. Для квика версии 8.5 он должен был выглядеть так:
C:\Quik\LuaScripts\QuikSharp\clibs64\8.5x\socket\core.dll

Попробуйте из луа вывести сообщение на экран терминала о номере версии. точнее значение переменной "qver"

**Comment by sgolod** [comment]
> Странно выглядит путь. Для квика версии 8.5 он должен был выглядеть так:
> C:\Quik\LuaScripts\QuikSharp\clibs64\8.5x\socket\core.dll
> 
> Попробуйте из луа вывести сообщение на экран терминала о номере версии. точнее значение переменной "qver"

script_path = getScriptPath()
local qver = getInfoParam("VERSION")
message(qver)

8.5.1.18

**Comment by sgolod** [comment]
if qver ~= nil then
	qver = tonumber(qver:match("%d+"))
end

вот в этом месте qver становится равным 8, а не 8.5 И далее в коде сбивается проверка

**Comment by sgolod** [comment]
поменял вручную в коде везде проверку на >= 8.5 (сделал только на >=8), теперь выдаёт ошибку на 42 строку в socket.lua

C:\Quik\LuaScripts\QuikSharp\socket.lua:42: attempt to call a nil value (global 'newtry')

**Comment by Pr0phet1c** [comment]
Да, я тоже нашел эту проблему. Сейчас занимаюсь решением. Возможно, сегодня будет обновление.

**Comment by Pr0phet1c** [comment]
Обновил. Проверяйте

**Comment by sgolod** [comment]
> Обновил. Проверяйте

.\socket.lua:42: attempt to call a nil value (global 'newtry')

**Comment by Pr0phet1c** [comment]
Это уже проблема. У меня нет решения (во всяком случае пока).
Я так понимаю, что в core.dll, которую я нашел под lua 5.3, нет такой функции.
@buybackoff , нет идей?

**Comment by buybackoff** [comment]
помимо core.dll нужна и Lua обертка, ей соответствующая. Может что-то поменялось в C API.

**Comment by sgolod** [comment]
> Это уже проблема. У меня нет решения (во всяком случае пока).
> Я так понимаю, что в core.dll, которую я нашел под lua 5.3, нет такой функции.
> @buybackoff , нет идей?

а старая core.dll не подойдёт? В ней жёстко прописана Lua51?

**Comment by sgolod** [comment]
> помимо core.dll нужна и Lua обертка, ей соответствующая. Может что-то поменялось в C API.

В версии квика на которой проверяю вроде есть какая-то ошибка. Разработчики обещают поправить в след. версии, но я не уверен что та ошибка и данная имеют что-то общее.
https://forum.quik.ru/forum10/topic5317/

И там же я задал свой вопрос про core.dll, на который уже ответили:
https://forum.quik.ru/messages/forum10/message43008/topic4609/#message43008

**Comment by alex912** [comment]
socket.lua нужно обновить на вот эту: https://github.com/diegonehab/luasocket/blob/master/src/socket.lua

Также у меня была спустя какое то время крит ошибка как пишут на форуме

**Comment by Pr0phet1c** [comment]
@alex912, спасибо.
Файл заменил, но на всякий случай пока и старую версию сохранил.
@sgolod, попробуйте как будет возможность.

**Comment by sgolod** [comment]
> @alex912, спасибо.
> Файл заменил, но на всякий случай пока и старую версию сохранил.
> @sgolod, попробуйте как будет возможность.

Та ошибка ушла. Но в новом файле уже другая ошибка:

C:\Quik\LuaScripts\QuikSharp\qsutils.lua:41: attempt to index a nil value (global 'logfile')

создал каталог logs (кстати почему бы скрипту ему самому не создавать при запуске, если каталог не существует?), всё ЗАПУСТИЛОСЬ! Но сегодня торгов нет, так остальное проверю уже в понедельник)

**Comment by sgolod** [comment]
> @alex912, спасибо.
> Файл заменил, но на всякий случай пока и старую версию сохранил.
> @sgolod, попробуйте как будет возможность.

Кстати обнаружил интересную особенность (ошибку?) - без установленного VS2019 возникает аналогичная ошибка загрузки core.dll даже на самой последней версии. Такое ощущение что какая-то библиотека из VS2019(NET*) тянется, которая устанавливается вместе с VS2019.

**Comment by buybackoff** [comment]
Msvcrt, обычное дело

**Comment by buybackoff** [comment]
Msvcrt можно положить в clibs, это самое простое. Можно даже в репо добавить. Хотя эта dll есть в папке Квика, странно что она не подгружается.

**Comment by sgolod** [comment]
> > @alex912, спасибо.
> > Файл заменил, но на всякий случай пока и старую версию сохранил.
> > @sgolod, попробуйте как будет возможность.
> 
> Та ошибка ушла. Но в новом файле уже другая ошибка:
> 
> C:\Quik\LuaScripts\QuikSharp\qsutils.lua:41: attempt to index a nil value (global 'logfile')
> 
> создал каталог logs (кстати почему бы скрипту самому не создавать этот каталог при запуске, если его не существует?), всё ЗАПУСТИЛОСЬ! Но сегодня торгов нет, остальное проверю уже в понедельник)

К сожалению, несмотря что скрипт запустился в квике - другие приложения его не видят. Проверял из OS Engine, в нём есть поддержка подключения через QuikLua. Сейчас просто молчание и пусто в логе при попытке подключения.

**Comment by Pr0phet1c** [comment]
Демо-приложение работает?

**Comment by sgolod** [comment]
> Демо-приложение работает?

это в Visual Studio нужно собрать из QuikSharpDemo и попробовать запустить?

**Comment by sgolod** [comment]
> Демо-приложение работает?

Собрал демо. Тоже не подключается
![Снимок экрана 2020-04-27 в 19 33 22](https://user-images.githubusercontent.com/34815751/80384216-0b1f8400-88be-11ea-8b9a-98f9c9d7b209.png)

**Comment by buybackoff** [comment]
#234

**Comment by buybackoff** [comment]
Возник вопрос в #236, посмотрите плиз

**Comment by vshelest901** [comment]
Для информации, получил аналогичную ошибку на quik 8.4.6.1 и 8.5.2.11 (win10 с установленным vs2019):

Проблема ушла после установки vcredist 2015-2019. Поскольку связь совершенно не очевидна (я считал что установленные vs автоматом ставит и все необходимое для запуска) - пусть будет тут.

**Comment by buybackoff** [comment]
В Луа можно поменять linking option с MD на MT, тогда - по идее - эта зависимость не нужна.

**Comment by aBaTaPbl4** [comment]
Склонирова репозиторий "git clone https://github.com/finsight/QUIKSharp.git"
Скопировал из скачанных исходников папку "P:\QUIKSharp\src\QuikSharp\lua" в корневую папку, - куда установлен квик.
Запустил скрипт QuikShrap.lua
И всё заработло!
Боль ушла. Спасибо8)
