### ISSUE TITLE
Зависает в windows 7

### ISSUE THREAD

**Issue by iza88** [finsight/QUIKSharp#233]
Одна и та же программа (.net 461) с одним и тем же квиком 8.1 работает на Windows 10 и зависает на Win 7 здесь:
`QuikService.WorkingFolder = Service.GetWorkingFolder().Result;`
lua скрипт работает, ошибок не выдает
[этот commit](https://github.com/finsight/QUIKSharp/commit/064f273873784df766a6a9dd152088eca3d08fe4)
могу дать комп с win7 по google remote desktop или teamviewer

**Comment by buybackoff** [comment]
#234
