### ISSUE TITLE
Обновление бинарников luasocket и форсирование IPv4

### ISSUE THREAD

**Issue by buybackoff** [finsight/QUIKSharp#234]
С новыми либами для socket `localhost` слушал на IPv6 адрес.

В этой репо есть тесты. Они не просто так, а полезны иногда. Самый простой тест `Ping.EchoWorks` должен всегда работать. Он всего-то тестирует соединение. Ну или любой другой пример на самом деле. Если бы поймали [ошибку тут](https://github.com/finsight/QUIKSharp/blob/064f273873784df766a6a9dd152088eca3d08fe4/src/QuikSharp/QuikService.cs#L515), то было бы всё сразу понятно. К сожалению, так был голый catch без логирования.

Есть штука https://github.com/lucasg/Dependencies/, которая позволяет видеть, какие зависимости в бинарнике. Если модуль не найден, то Dependencies покажет, какой не найден. Код как был тут не нужен:

```
	if qver >= 8.5 then
		-- Если версия Quik 8.5 или выше будет загружена WIN64 библиотека Lua 5.3, - которую нужно положить в папку clibs64
		-- package.loadlib(getScriptPath()..libPath.."lua53.dll", "main")
	else
		-- Если версия Quik < 8.5 будет загружена WIN64 библиотека Lua 5.1, - которую нужно положить в папку clibs64
		-- package.loadlib(getScriptPath()..libPath.."lua51.dll", "main")
	end
```

мы уже в Луа, зачем загружать её либу второй раз!?

Для 8.5 файл был рабочий, но я пересобрал сам на всякий случай.

В версии <8.5 снова история с точкой и без (lua51 vs lua5.1). Завтра попробую собрать так, чтобы работало без прослоек с x64.

После того, как модули грузятся, запускаем  `netstat -an` в консоли и видим:

![image](https://user-images.githubusercontent.com/489852/80428028-3b304c80-88e9-11ea-9092-c6097005fe20.png)

тогда как C# код рассчитан на IPv4.

Чтобы заставить Lua слушать на IPv4, нужно заменить `localhost` на `127.0.0.1` в файле `qsutils`.

![image](https://user-images.githubusercontent.com/489852/80428235-aa0da580-88e9-11ea-8c1b-1308706a731b.png)

![image](https://user-images.githubusercontent.com/489852/80428306-d75a5380-88e9-11ea-9404-f11c5794331b.png)

Voilà!

![image](https://user-images.githubusercontent.com/489852/80428331-e5a86f80-88e9-11ea-878f-454cc65f02cb.png)

Коммит будет завтра вечером. У кого не коннектится, но модули грузятся, замените localhost на  127.0.0.1

**Comment by sgolod** [comment]
После исправления locahost на 127.0.0.1, стал коннектится. Но дальше при вызове функций происходит глобальный сбой с ошибкой:
Critical error ACCESS_VIOLATION in script C:\Quik\LuaScripts\QuikSharp\QuikSharp.lua

![Снимок экрана 2020-04-28 в 16 11 59](https://user-images.githubusercontent.com/34815751/80481216-7d9a6d80-896b-11ea-80f6-298890b909e4.png)

**Comment by buybackoff** [comment]
@sgolod 8 или 8.5?

**Comment by buybackoff** [comment]
Обновил бинарники и скрипты и проверил на Квиках 7.19, 8.0 и 8.5.

@Pr0phet1c проверьте плиз демо приложение и вообще работоспособность.

Кто-то упоминал, что не работает на машинах без Visual Studio. Я добавил бинарники со статической линковкой (линкованием?) MSVCRT, возможно в этом дело. Однако MSVCRT идет вместе с Квиком и папка с ней влючена в cpath, всё должно находиться и так.

Тут можно переключиться https://github.com/finsight/QUIKSharp/blob/1dcef193aa948610aba516a2716c4d7645cd879f/src/QuikSharp/lua/QuikSharp.lua#L28-L32

**Comment by iza88** [comment]
у меня lua script выдает ошибку после commit'а 28 апреля
![image](https://user-images.githubusercontent.com/14890699/80567157-3fe62500-89fd-11ea-9473-87c7afd70479.png)

**Comment by buybackoff** [comment]
@iza88 
Странно, я специально проверил, что создание папки и файла работает. Создайте папку `logs` там, где QuikSharp.lua

https://github.com/finsight/QUIKSharp/blob/1dcef193aa948610aba516a2716c4d7645cd879f/src/QuikSharp/lua/qsutils.lua#L30-L32

**Comment by sgolod** [comment]
> @sgolod 8 или 8.5?

8.5, сейчас проверю с самой свежей версией QuikSharp и отпишусь

**Comment by buybackoff** [comment]
Обновил логику создания файла для логирования: если папка `logs` не создается, то лог файл будет создан там же, где скрипт. Если и там его не получится создать, то просто не будет логирования в файл, без ошибок скрипта.

**Comment by iza88** [comment]
> @iza88
> Странно, я специально проверил, что создание папки и файла работает. Создайте папку `logs` там, где QuikSharp.lua
> 
> https://github.com/finsight/QUIKSharp/blob/1dcef193aa948610aba516a2716c4d7645cd879f/src/QuikSharp/lua/qsutils.lua#L30-L32

эти строки в скрипте, что я запускаю, есть

> Обновил логику создания файла для логирования: если папка `logs` не создается, то лог файл будет создан там же, где скрипт. Если и там его не получится создать, то просто не будет логирования в файл, без ошибок скрипта.

спасибо, но зависание на win 7 с новым коммитом не решилось

**Comment by sgolod** [comment]
При попытке подключиться выдаётся ACCESS_VIOLATION и ошибка в qsutils.lua
![Снимок экрана 2020-04-29 в 11 57 03](https://user-images.githubusercontent.com/34815751/80568578-b7717f80-8a10-11ea-9931-8144f2d7e446.png)

**Comment by buybackoff** [comment]
Windows 7 больше не поддерживается даже самим Microsoft. 

https://venturebeat.com/2020/01/14/microsoft-ends-support-for-windows-7-what-you-need-to-know/

@sgolod  у вас какая ОС?

**Comment by sgolod** [comment]
> Windows 7 больше не поддерживается даже самим Microsoft.
> 
> https://venturebeat.com/2020/01/14/microsoft-ends-support-for-windows-7-what-you-need-to-know/
> 
> @sgolod у вас какая ОС?

C:\Users\tango>ver
Microsoft Windows [Version 10.0.19041.207]

**Comment by buybackoff** [comment]
@sgolod 

> p.s. Может это socket.dll изменился? Есть ли где-то исходники этой дллки? От 8.1 уже не подходит (там вшито упоминание lua51)

я скомпилировал новые бинарники сам из https://github.com/diegonehab/luasocket

вся папка lua из репо должна быть скопирована, если запускаете из другого места, а не из репо. там новая структура бинарников.

попробуйте также заменить `linkage = "MT"` как указано тут https://github.com/finsight/QUIKSharp/issues/234#issuecomment-620829939

**Comment by Pr0phet1c** [comment]
Работу библиотеки проверил на версиях квика 7.27.2.1 и 8.4.1.6. (Использовал вариант, который был доступен на раннее утро).
На 8.5 пока проверить не могу.
Мои роботы работают. QuikSharpDemo и RobotDemo работают.

С наличием папки "logs" действительно были проблемы (я специально предварительно ее удалил), но я просто создал ее и не стал заострять на этом внимание. Может надо было просто в исходники проекта эту папку включить?

В ближайшее время постараюсь перевести все свои роботы на новую версию библиотеки и посмотреть сохранится ли проблема описанная тут https://github.com/finsight/QUIKSharp/issues/229

**Comment by buybackoff** [comment]
@Pr0phet1c спасибо!

Какая ОС? Не могу понять, почему `os.execute("mkdir "..script_path.."\\logs")` может не работать

**Comment by cmcdetonator** [comment]
всем привет
скачал последнюю версию, собрал ее в VS2019
Запустился под квиком 8.3.2.4 и 7.27.2.1 - все законнектилось (QuikSharpDemo) и подписалось на стакан по SiM0. Глубже не тестировал
8ой квик удалось скачать в какие-то лохматые времена (полгода назад), когда Открытие однажды предложило обновиться до 8го. С тех пор Открытие закрыло эту возможность, а где взять апдейт этого квика не знаю, поэтому у меня есть толкьо эта версия 8.3.2.4

**Comment by buybackoff** [comment]
> Не могу понять, почему os.execute("mkdir "..script_path.."\\logs") может не работать

У кого ошибки те имеют пробелы в пути script_path. Почему никто на это не обратил внимание!? 🤦‍♂️

**Comment by iza88** [comment]
> > Не могу понять, почему os.execute("mkdir "..script_path.."\logs") может не работать
> 
> У кого ошибки с папкой логирования - те имеют пробелы в пути script_path. Почему никто на это не обратил внимание!? 🤦‍♂️
> 
> Решается тривиально [9b2a488](https://github.com/finsight/QUIKSharp/commit/9b2a4888bbeb9f385d06b964f32746a897a763be)

господи Иисуси, у меня на win7 заработало, когда пробелы из пути убрал

**Comment by IFetisov** [comment]
Скачал новые скрипты теперь не запускается lua 
qsutils.lua:52: attempt to index a nil value (global 'logfile')
Комменировал кусок кода чтобы запустилось
--    if not level then level = 0 end
--    local logLine = "LOG "..level..": "..msg
--    print(logLine)
--    local msecs = math.floor(math.fmod(timemsec(), 1000));
--    pcall(logfile.write, logfile, os.date("%Y-%m-%d %H:%M:%S").."."..msecs.." "..logLine.."\n")
--    pcall(logfile.flush, logfile)

**Comment by IFetisov** [comment]
У меня запуститься не получается
netstat -an
  TCP    127.0.0.1:34130        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:34130        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:34131        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:34131        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:50816        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:56893        127.0.0.1:34130        SYN_SENT
  TCP    127.0.0.1:58751        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:58803        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:60861        0.0.0.0:0              LISTENING
telnet 127.0.0.1 34130                                                                                                                                                Подключение к 127.0.0.1...Не удалось открыть подключение к этому узлу, на порт 34130: Сбой подключения
Клиент на Sharp висит

**Comment by buybackoff** [comment]
@IFetisov  Многовато у вас слушателей, как будто два скрипта запущено

**Comment by IFetisov** [comment]
Наверное сбой какой то пока с логом разбирался. до конца не понял
В итоге законнектиться получилось. Пытаюсь вызвать GetDepoLimits (висит и отваливается по таймауту)

**Comment by IFetisov** [comment]
Вообщем все очень странно просто отрубается соединение  через несколько секунд.

2020-04-29 15:06:08.86 LOG 1: QUIK# client disconnected
2020-04-29 15:06:08.88 LOG 1: QUIK# is waiting for client connection...
2020-04-29 15:06:08.89 LOG 0: Waiting for a response client...
2020-04-29 15:06:28.525 LOG 0: Waiting for a callback client...
2020-04-29 15:06:28.540 LOG 1: QUIK# client connected
2020-04-29 15:07:20.97 LOG 1: QUIK# client disconnected
2020-04-29 15:07:20.100 LOG 1: QUIK# is waiting for client connection...
2020-04-29 15:07:20.100 LOG 0: Waiting for a response client...
2020-04-29 15:09:11.75 LOG 0: Waiting for a callback client...
2020-04-29 15:09:11.88 LOG 1: QUIK# client connected
2020-04-29 15:09:16.62 LOG 1: QUIK# client disconnected
2020-04-29 15:09:16.64 LOG 1: QUIK# is waiting for client connection...
2020-04-29 15:09:16.64 LOG 0: Waiting for a response client...

**Comment by IFetisov** [comment]
![image](https://user-images.githubusercontent.com/40885403/80594788-50fa5a80-8a2c-11ea-9e00-0f2e3cfbfaf8.png)

**Comment by Pr0phet1c** [comment]
> @Pr0phet1c спасибо!
> 
> Какая ОС? Не могу понять, почему `os.execute("mkdir "..script_path.."\\logs")` может не работать

Win10. Я так (судя по недавнему фиксу) проблема с указанной строкой решена? (сам я не проверял)

**Comment by IFetisov** [comment]
> > @Pr0phet1c спасибо!
> > Какая ОС? Не могу понять, почему `os.execute("mkdir "..script_path.."\\logs")` может не работать
> 
> Win10. Я так (судя по недавнему фиксу) проблема с указанной строкой решена? (сам я не проверял)

Ну если папка с квиком и содержит пробелы работать команда не будет. Решение убрать эту строку и создать папку logs руками.

**Comment by buybackoff** [comment]
@IFetisov @Pr0phet1c 

> Решается тривиально 9b2a488

Всё уже пофиксено выше в последнем коммите

**Comment by Pr0phet1c** [comment]
Запустил на версии 8.5.1.18
Сначала вроде все запустилось, но через некоторое время начались сбои. Пока не могу досконально вникнуть, но вот одна из странных ошибок:
![2020-04-29_20-33-11](https://user-images.githubusercontent.com/14761254/80628482-15768500-8a5a-11ea-8fc3-ec50e1985181.png)

**Comment by Pr0phet1c** [comment]
Или вот еще вариант ошибки. На этот раз путь ведет к файлу QuikSharp.lua:
![2020-04-29_20-46-14](https://user-images.githubusercontent.com/14761254/80628934-c846e300-8a5a-11ea-8d9e-38a8c9e51689.png)

**Comment by buybackoff** [comment]
@Pr0phet1c это с самым последнием коммитом?

**Comment by buybackoff** [comment]
работает ли с linkage=MT?

**Comment by buybackoff** [comment]
Вообще на форуме пишут, что 8.5.1 - нерабочая версия с т.з. Луа. Если всё работает в более ранних версиях, я больше не буду обращать внимание на ошибки в последней версии.

**Comment by sgolod** [comment]
> Вообще на форуме пишут, что 8.5.1 - нерабочая версия с т.з. Луа. Если всё работает в более ранних версиях, я больше не буду обращать внимание на ошибки в последней версии.

Ну не совсем "нерабочая")). Разработчики признали что там есть ошибки, которые были допущены в процессе сборки. Просто на стандартных луа-скриптах они не вылазят, а вот в случае использования внешних библиотек - появляются. На версиях до 8.5 QuikSharp работал корректно. 

Замена на "MT" ситуацию не исправило. Ошибка во время исполнения (ACCESS VIOLATION...) осталась.

**Comment by sgolod** [comment]
> @sgolod
> 
> > p.s. Может это socket.dll изменился? Есть ли где-то исходники этой дллки? От 8.1 уже не подходит (там вшито упоминание lua51)
> 
> я скомпилировал новые бинарники сам из https://github.com/diegonehab/luasocket
> 
> вся папка lua из репо должна быть скопирована, если запускаете из другого места, а не из репо. там новая структура бинарников.
> 
> попробуйте также заменить `linkage = "MT"` как указано тут [#234 (comment)](https://github.com/finsight/QUIKSharp/issues/234#issuecomment-620829939)

проверил с текщей репой (вариант MD). У меня вообще квик упал))), а приложение которой пыталось через коннектор подключиться выдало ошибку:
![Снимок экрана 2020-04-30 в 00 16 39](https://user-images.githubusercontent.com/34815751/80637528-95abe300-8a78-11ea-8dfc-1e44f7d43114.png)


С вариантом MT квик задумался надолго уйдя в 100% CPU. Пришлось прибить процесс.

**Comment by buybackoff** [comment]
@sgolod это всё 8.5?

Мне важно знать, работает ли стабильно с 8.4 и ниже. 8.5 пока в игнор.

**Comment by sgolod** [comment]
> @sgolod это всё 8.5?
> 
> Мне важно знать, работает ли стабильно с 8.4 и ниже. 8.5 пока в игнор.

да. это всё  8.5, с предыдущими версиями квика к QuikSharp вообще вопросов не было)

**Comment by Pr0phet1c** [comment]
На счет старых версий, у меня пока нет однозначного ответа. Если не считать проблемы с потерей колбэков (https://github.com/finsight/QUIKSharp/issues/229), то в целом переход успешный. Однако, в ряде случаев робот может тупо не стартовать как надо (обычно это связано с невозможностью соединиться с квиком). В логи вроде ничего не вываливается. Часто помогает остановка и новый запуск скрипта в квике.

**Comment by sgolod** [comment]
Вышла новая версия Квика - 8.5.2.11, в ней QuikSharp запустился и даже пока работает (проверял в связке с OS Engine).

**Comment by Pr0phet1c** [comment]
Подтверждаю. На версии 8.5.2.11 проблем с работоспособностью библиотеки пока не наблюдается.
