### ISSUE TITLE
Ошибка подключения к QUIK

### ISSUE THREAD

**Issue by A-bit-st** [finsight/QUIKSharp#235]
Добрый день! Хотел подключить к Quik через Visio, как показывали на видео в категигории Обучающее видео (все делал по аналогии) + пользовался readme, но возникла ошибка: 

`:\QUIKSharp-master\tests\Profiler\Program.cs(4,7,4,16): error CS0246: Не удалось найти тип или имя пространства имен "QuikSharp" (возможно, отсутствует директива using или ссылка на сборку). (QuikSharp и все его функции подсвечиваются красным)`

Удалось решить эту проблему. Заключалось в том, что ссылка на QUIKSharp была построена для платформы ".NETFramework,Version=v4.6.1". Это более поздняя версия по сравнению с текущей целевой платформой ".NETFramework,Version=v4.5". Поменял версию платформы на 4.6.1 - все ошибки были исправлены, но опять не заработало. Не может подключится к QUIK.

![изображение](https://user-images.githubusercontent.com/64482985/80499968-47162000-8976-11ea-9daf-10b69d09fd94.png)
![изображение](https://user-images.githubusercontent.com/64482985/80500089-6b71fc80-8976-11ea-9998-8cff0e837631.png)
![изображение](https://user-images.githubusercontent.com/64482985/80500111-70cf4700-8976-11ea-86d8-dc551eac4105.png)

Менял версии платформы (4.7.2), смотрел форумы по данным ошибкам - ничего не помогло. Можете пожалуйста помочь советом, как в моем случае можно осуществить подключение.

Заранее Спасибо!

**Comment by buybackoff** [comment]
Читайте пожалуйста существующие issues, хотя бы самый последний #234. Пробовали делать то, что там написано?

**Comment by A-bit-st** [comment]
Да пробовал, ничего не вышло

**Comment by IFetisov** [comment]
У меня тоже новая версия не работает совсем
У меня на localhost 34130 телнет заходит но коннекта к Луа нет. А 127.0.0.1 не работает вообще. Безопасность сети настроена так что идешь на localhost порты открыты на 127 опознаешься как чужой и все порты закрыты. Поправил исходники чтобы по имени localhost шло соединение но соединения нет. Не пойму почему у меня на старой версии все хорошо работало

**Comment by buybackoff** [comment]
@IFetisov 

посмотрите/покажите, что показывает `netstat -an` на порты Q#.

**Comment by IFetisov** [comment]
local port = 34130
netstat -an по этому порту вообще не показывает ничего

**Comment by buybackoff** [comment]
значит Луа сервер на заводится. Если 127,0,0,1 не работает из-за настроек сети, то наверное стоит поменять настройки сети.

**Comment by buybackoff** [comment]
обновил бинарники и скрипты.

пожалуйста, без повторения шагов из #234 не создавайте больше issues про ошибки подключения.

* Если скрипт в Квике запускается, `netstat -an` должен показывать, что на этих портах LISTENING с IPv4
* Если это не так, проверьте/отключите firewall

Этот issue пообще не тему, подробно освещенную в FAQ, раздел решение проблем, второй параграф: https://github.com/finsight/QUIKSharp/blob/master/README.RU.md#%D1%80%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC
