### ISSUE TITLE
Опрос: ответьте плиз прямо сейчас

### ISSUE THREAD

**Issue by buybackoff** [finsight/QUIKSharp#236]
Я прямо сейчас (вечер 28 апреля) готовлю коммит с новыми бинарниками и прочие мелкие фиксы.

Пожалуйста, скажите, а бывают ли Квики до 8-й версии включительно, где Луа dll называется `lua51.dll` (без точки), а не `lua5.1.dll`.  Мне кажется, что я таких не встречал, все мне доступные были с точкой.

Я скомпилил либу luasockets, которая зависит от dll с точкой, и собираюсь удалить поддержку без точки, если с Квиком никогда такой либы не поставлялось.

**Comment by iza88** [comment]
У меня на всех квиках с точкой
