### ISSUE TITLE
Получение таблицы money_limits после обновления Квик

### ISSUE THREAD

**Issue by IFetisov** [finsight/QUIKSharp#237]
Помогите разобраться пожалуйста. После обновления поломалось получение таблицы

      LUA
      function qsfunctions.getClientCodes(msg)

	    local ListCodes={}
         	for i=0,getNumberOf("money_limits")-1 do
	        	local clientcodes = getItem("money_limits",i)
		        table.insert(ListCodes,clientcodes)
         	end
	     msg.data=ListCodes
              return msg
      end
    C#
    public class ClientData
    {
        // ReSharper disable InconsistentNaming
        /// <summary>
        /// Код валюты  (STRING)  
        /// </summary>
        [JsonProperty("currcode")]
        public string CurrCode { get; set; }

        /// <summary>
        /// Тэг расчетов  (STRING)  
        /// </summary>
        [JsonProperty("tag")]
        public string Tag { get; set; }

        /// <summary>
        /// Идентификатор фирмы  (STRING)  
        /// </summary>
        [JsonProperty("firmid")]
        public string FirmId { get; set; }

        /// <summary>
        /// Код клиента  (STRING)  
        /// </summary>
        [JsonProperty("client_code")]
        public string ClientCode { get; set; }

        /// <summary>
        /// Входящий остаток по деньгам  (NUMBER)  
        /// </summary>
        [JsonProperty("openbal")]
        public double Openbal { get; set; }

        /// <summary>
        /// Входящий лимит по деньгам  (NUMBER)  
        /// </summary>
        [JsonProperty("currentbal")]
        public double Currentbal { get; set; }

        /// <summary>
        /// Текущий лимит по деньгам  (NUMBER)  
        /// </summary>
        [JsonProperty("currentlimit")]
        public double CurrentLimit { get; set; }

        /// <summary>
        /// Заблокированное количество  (NUMBER)  
        /// </summary>
        [JsonProperty("locked")]
        public double Locked { get; set; }

        /// <summary>
        /// Стоимость активов в заявках на покупку немаржинальных бумаг  (NUMBER)  
        /// </summary>
        [JsonProperty("locked_value_coef")]
        public double LockedValueCoef { get; set; }

        /// <summary>
        /// Стоимость активов в заявках на покупку маржинальных бумаг  (NUMBER)  
        /// </summary>
        [JsonProperty("locked_margin_value")]
        public double LockedMarginValue { get; set; }
        /// <summary>
        /// Плечо  (NUMBER)  
        /// </summary>
        [JsonProperty("leverage")]
        public double Leverage { get; set; }

        /// <summary>
        /// Тип лимита  (NUMBER)  
        /// </summary>
        [JsonProperty("limit_kind")]
        public int LimitKind { get; set; }
    }
        public async Task<List<ClientData>> GetClientData()
        {
            var response = await QuikService.Send<Message<List<ClientData>>>(
                (new Message<string>("", "getClientCodes"))).ConfigureAwait(false);
            return response.Data;
        }

**Comment by IFetisov** [comment]
Вообще нет  при каких то условиях это все работает не знаю при каких пока.
А так валятся случайные ошибки в местах которые раньше работали. И что самое обидное валятся через раз и код который выше минимум 1 раз отработал успешно 
(( Все пропало
ERROR QuikSharp.JsonCreationConverter`1 Error reading JObject from JsonReader. Current JsonReader item is not an object: Undefined. Path '', line 1, position 0. - ,    в Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   в QuikSharp.JsonCreationConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) в D:\Work\Projects\CBExtra\QUIKSharp-master\src\QuikSharp\Serialization.cs:строка 423

**Comment by buybackoff** [comment]
Возможно, что присылаются пустые строки? Должна быть проверка и игнор пустых строк, не помню сделано ли это.

**Comment by buybackoff** [comment]
@IFetisov 

В репо getClientCode, а не getClientCode**s**, и так с 2016-го года. Не знаю, откуда взялась разница

**Comment by IFetisov** [comment]
Еще такое вариант ошибки
<TaskScheduler_UnobservedTaskException>b__8_0
System.IO.IOException: Не удается прочитать данные из транспортного соединения: Доступ к ликвидированному объекту невозможен.
Имя объекта: "System.Net.Sockets.Socket".. ---> System.ObjectDisposedException: Доступ к ликвидированному объекту невозможен.
Имя объекта: "System.Net.Sockets.Socket".
   в System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode, AsyncCallback callback, Object state)
   в System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   в System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   --- Конец трассировки внутреннего стека исключений ---
   в System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   в System.IO.Stream.<>c.<BeginEndReadAsync>b__43_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   в System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   в System.IO.Stream.BeginEndReadAsync(Byte[] buffer, Int32 offset, Int32 count)
   в System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   в System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count)
   в System.IO.StreamReader.<ReadBufferAsync>d__97.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.IO.StreamReader.<ReadLineAsyncInternal>d__60.MoveNext()
