### ISSUE TITLE
Несколько вопросов по скрипту под x64

### ISSUE THREAD

**Issue by QuantFinanceMethod** [finsight/QUIKSharp#239]
Интересный проект. 

Существует ли готовый x64 nuget или просто укороченная установка под x64? Попробовал скачать nuget, оттуда взять папку с lua, но терминал пишет, что первая же dll - win32.

**Comment by Pr0phet1c** [comment]
Текущую последнюю версию отсюда скачивать и использовать пробовали?

**Comment by QuantFinanceMethod** [comment]
Да, всё попробовал. Отсюда отваливалась какая-то зависимость socket.core. 
Поэтому попробовал из Nuget.

Оказалось проще разобрать вложенные таблицы QLua из-под нативной библиотеки. 
C/C++ в итоге отлаживаются на порядок проще. Удивляет размер вложенного объекта таблицы lua (lua_objlen(L, -1) 0, который надо разбирать, несоответствие number и string иногда.

В общем и целом C/C++ и C# друзья-братья. От Lua по максимуму надо отказываться.

По-видимому, наиболее правильный подход - лобовой: брать их интерпретатор из поставки Quik, разобрать экспорт функций, потом собрать .lib файл, прилинковать его к нативной dll и уже отлаживая под Quik, однозначно убедиться в конкретных типах аргументов функций, возвращаемых результатах, которые покажет отладчик. Основные функции 5.1 так и удалось разобрать. 
Что они там насобирали и наделают дальше в 5.3 - хз.

К сожалению, от Quik полностью отказаться нельзя - им даже ЦБ пользуется.

**Comment by buybackoff** [comment]
> Оказалось проще разобрать вложенные таблицы QLua из-под нативной библиотеки.
C/C++ в итоге отлаживаются на порядок проще. Удивляет размер вложенного объекта таблицы lua (lua_objlen(L, -1) 0, который надо разбирать, несоответствие number и string иногда.

> В общем и целом C/C++ и C# друзья-братья. От Lua по максимуму надо отказываться.

> По-видимому, наиболее правильный подход - лобовой: брать их интерпретатор из поставки Quik, разобрать экспорт функций, потом собрать .lib файл, прилинковать его к нативной dll и уже отлаживая под Quik, однозначно убедиться в конкретных типах аргументов функций, возвращаемых результатов, которые покажет отладчик. Основные функции 5.1 так и удалось разобрать.
> Что они там насобирали и наделают дальше в 5.3 - хз.

Забавно, сколько людей из целевой аудитории это смогут понять, не то что сделать. Наверное они всё же работают уже с TWIME и FAST. К сожалению практика показывает, что даже C# с готовой API для многих сложно и затык именно в программировании.

А по поводу несоотвествия параметров число/текс, помогает дословно читать QLUA документацию. А не помню, чтобы она врала. А то, что числа как текст - часто это даже нужно в языках, где кроме float64 ничего больше нет.

NuGet скоро обновлю до 2.0. Или возможно до 8.5.

**Comment by QuantFinanceMethod** [comment]
Без терминала QUIK не обойтись - это точно. Поэтому владеть автоматизацией методами работы с ним ценилось и 20 лет назад - мальчики приходили на автоматизацию, потом через 2 года уходили во всякие Альфа-директы и т.п. и всё равно им все пользуются.
Вероятно, и сейчас всё обстоит также.

В документации QUIK тяпы и ляпы встречались и встречаются повсемеcтно. Объясняется просто - когда разработанный по директиве Центробанка комплекс средств автоматизации продолжает обслуживаться по принципу - без вариантов все будут пользоваться, то и работа от обратного. Поэтому, по-видимому, по такому же принципу взяли lua, добавили от себя кое-как, что получилось. 
За 5 лет не удосужились сделать экспорт новостей : что-то типа OnNews(string news) - просматривая их форум увидел третий раз "Регистрируем пожелание на новости?". Элементарно может оказаться, что автор сего чудного гибрида quik lua уже давно ушел.
В последних версиях макулатуры появился пример модной функции printdebug - из WindowsApi с подхватом сообщения скриптом python, сделали какой-то коннектор к программе тех. анализа из каменного века - WealthLab.
Это всё уровень поделки школьников и студентов.
Ни планов развития - ничего.
Собственно они и не возражают. Лет 5 назад их товарищ из саппорта писал : "да , это атавизм, но мы вынуждены сего шлифовать".

Поэтому, к сожалению, без вариантов придется проверять самостоятельно, что наделают каждый раз эти трудящиеся. Возможно, у вас нестабильность работы различных более или менее отлаженных пакетов lua с этим и связана - каждый раз, то чай прольют на клавиатуру, то еще что-нибудь. Пишут, что колбэки в потоке интерфейса терминала, main в отдельном. Что-то изменили, никому не сказали.
У меня, например, Quik с темной темой на голой виртуальной машине под Hyper-V через полдня работы начинает ломаться - окна начинают дрожать, часть символов не отрисовывается, меню пропадает. В традиционном такого не наблюдается.

**Comment by buybackoff** [comment]
@QuantFinanceMethod да, монополия плохо. Я когда-то хотел зарегиться на форуме и высказаться на тему "доколе", но там после капчи идет нелепый вопрос, например:

![image](https://user-images.githubusercontent.com/489852/82740531-e8ac4980-9d49-11ea-94d6-399815377174.png)

И всё желание пропало с ними общаться. WTF если есть капча, зачем этот вопрос!? Если было время задуматься о такой детали, как безопасность сайта, на котором просто общаются люди, почему они не сделали JSON-RPC хотя бы, новости да... Эта форма регистрации показала/напомнила, что там неадекват с только им видимыми приоритетами.

Даже Тиньков с нуля сделал лучше API на JSON (другой вопрос - работает ли и стабильно/быстро ли). Их целевая аудитория наверное другая. С Квиком все же понятно, что latency порядка 100-150мс из дома, и можно жить с этим, если тип торговли позволяет. Стопы на серверах брокера тоже помогают от отключения интернета. Finam Transaq имеет много минусов, но блин берешь и пользуешься, если этот брокер.

Но как написано тут в РидМе, нужно сводить зависимости к Квику к минимуму и добавлять абстракции между Квиком и своим кодом. Была даже идея сделать такие абстракции, но даже на одной бирже акции и ФОРТС немного отличаются, а универсальная абстракция скорее всего не будет работать или будет что-то типа `Dictionary<dynamic,dynamic>`, что равносильно отсутствию абстракции. Так что это на стороне пользователя.

**Comment by buybackoff** [comment]
> Возможно, у вас нестабильность работы различных более или менее отлаженных пакетов lua с этим и связана - каждый раз, то чай прольют на клавиатуру, то еще что-нибудь.

Серьезная проблема была только с 8 и 8.5, но больше от отсутствия времени разбираться с компиляцией, искали готовые бинарники. В итоге скомпилировал сам и вроде всё работает. Первая версия Квика 8.5 была битой из-за "разлитого на клавиатуру чая" у них, но они исправили.

**Comment by buybackoff** [comment]
Негативить на тему Квика можно очень много, но свою цель от достигает и многим большего не нужно. Если у кого-то накипело, то можно продолжить тут. https://gitter.im/QUIKSharp/community
