### ISSUE TITLE
Лист ордеров

### ISSUE THREAD

**Issue by SkyQuant** [finsight/QUIKSharp#24]
Всё стесняюсь спросить, как получить список заявок / сделок за сессию, до того как подписался на событие _Events.OnOrder_. Метод `public async Task<List<StopOrder>> GetStopOrders()` вижу, а метод возврата простых ордеров - нет.

**Comment by buybackoff** [comment]
Может быть он не реализован... Тут еще очень много методов не сделано и ждут, когда их кто-то добавит и пришлет pull request :)

**Comment by eugene20237** [comment]
Скажите пожалуйста, зачем нужны методы OrderBook.Subscribe и OrderBook.Unsubscribe? Я получаю котировки по всем открытым стаканам любых инструментов вне зависимости от вызова этих методов. Котировки получаю через событие quik.Events.OnQuote.

**Comment by buybackoff** [comment]
чтобы получать, не открывая

2016-03-01 11:50 GMT+03:00 eugene20237 <notifications@github.com>:

**Comment by eugene20237** [comment]
Спасибо! Всё понятно!

**Comment by Pr0phet1c** [comment]
Давно реализовано в текущей версии библиотеки. Наверное можно закрывать.
