### ISSUE TITLE
Ошибка Transaction.OnTransReplyCall

### ISSUE THREAD

**Issue by RosinterTMP** [finsight/QUIKSharp#240]
Уважаемые разработчики,
Пользуюсь вашей библиотекой уже более двух лет. Активно торгую фьючерсами и опционами на ФОРТС. Сделок в течение дня проходит довольно много.
В марте перешел на версию x64 и Quik 8.4.1.6. Также на прошлой неделе скачивал последние обновления из репозитория.
В данной сборке периодически у меня вываливается ошибка, снимок которой прилагаю во вложении. Чаще она появляется в периоды повышенной активности рынка после совершения сделки по опциону и одновременной попытке хеджирования фьючерсом. Сделка по фьючерсу, как раз, не проходит.
В своем коде я отменил подписку на событие "OnTransReply". Также добавил конструкцию "Try / Catch" в строки на которые ссылается текст ошибки. Однако данные меры не решили проблему.
К сожалению, моего уровня в программировании недостаточно для дальнейшего самостоятельного анализа. Подскажите, пожалуйста, как можно было бы решить данную задачу?
![001](https://user-images.githubusercontent.com/30287719/80697347-81e89700-8ae1-11ea-9ade-290902cfa362.JPG)

**Comment by buybackoff** [comment]
Это с самым последним коммитом?

**Comment by RosinterTMP** [comment]
Нет, не с самым последним.
Я где-то в марте обновлял и библиотеку и Quik. С тех пор ошибка и появляется. Два-три раза в течение торгового дня. Сделок, обычно, 100-300. Закономерности возникновения проблемы я не выявил. Кроме того, что при активном рынке это чаще происходит.

**Comment by RosinterTMP** [comment]
Я снова вернулся к версии 32-бит и Quik 7. Однако ошибка повторяется. Видимо что-то локальное.
Хотя и странно, почему проблема в коде, связанном с событием "OnTransReply", если нет подписки на данное событие.

**Comment by Pr0phet1c** [comment]
@RosinterTMP , текущую версию библиотеки так и не попытались использовать? Если попытались, то каковы результаты? Проблема все еще актуальна?

**Comment by RosinterTMP** [comment]
Добрый день!
Давайте в ближайшее время снова попробую обновить у себя библиотеку и протестирую.
Пока сижу на 32-bit (старой) версии. Там эта ошибка ни разу не проскакивала.

**Comment by RosinterTMP** [comment]
В общем, пока ошибка не повторяется. Хотя и рынок сейчас гораздо менее активный, чем в марте-апреле.
Закрою проблему.
