### ISSUE TITLE
Подскажите как должна работать диагностика ping

### ISSUE THREAD

**Issue by IFetisov** [finsight/QUIKSharp#243]
Если зависает на строке 
                   var pong = array[i].Result;
Какую еще дальше провести диагностику чтобы разобраться почему не работает библиотека?

**Comment by buybackoff** [comment]
@IFetisov у вас было много странных проблем, они разрешились? Вижу что закрыли несколько issues.

**Comment by IFetisov** [comment]
После обновления квика (8.7.1.3) + вчера забрал последние версии отсюда старые странные проблемы разрешились.
Появились новые )
