### ISSUE TITLE
Опрос: следующая версия 2.0 или 8.5?

### ISSUE THREAD

**Issue by buybackoff** [finsight/QUIKSharp#246]
Как думаете, имеет смысл делать версии X.Y.zzz так, что X и Y совпадают с Квиком? Точнее с последней версией Квика, на которой библиотека стабильно работает и все API новых версий, если такие есть, реализованы.

Мне кажется, что в истории с переходом на 8.5 такая же версия была бы более говорящей, чем 2.0 или 1.1.

В semantic versioning я не особо верю, пуризмом не занимаюсь, вопрос удобства коммуникации.

Собираюсь наконец обновить NuGet, только немного еще причешу кое-что.

**Comment by Pr0phet1c** [comment]
Как по мне - сугубо фиолетово. В моем восприятии, использоваться должна всегда самая свежая версия. А какой номер она при этом имеет - совершенно неважно.

**Comment by buybackoff** [comment]
@Pr0phet1c OK, пусть будет 8.5. Не будет желания оповестить Смарт-Лаб о новом релизе когда он выйдет?

На неделе постараюсь найти время. Еще надо дорешить вопрос оформления лицензии с теми ребятами, и в этой репо поправить все заголовки и файлы. (речь не идет о смене лицензии, только оформление).

**Comment by Pr0phet1c** [comment]
Да, не вопрос. Оповестим.

**Comment by manuscriptum** [comment]
Имхо лучше привязывать к версии quik, раз уж коннектор к нему

**Comment by buybackoff** [comment]
В итоге 2.0
