### ISSUE TITLE
NuGet release

### ISSUE THREAD

**Issue by buybackoff** [finsight/QUIKSharp#247]
В прошлый раз issue с таким заголовком привел к тому, что в комментариях вскрылись несколько багов, а потом началась чехарда с обновлениями Луа и битности в самом Квике.

Сейчас вроде бы все работает с последней версией 8.5, ориентировочно в один из вечеров на следующей неделе обновлю NuGet.

Если у кого-то что-то все еще не работает, отпишитесь плиз. Было несколько issues в духе: "у меня ничего не работет, что делать" или "у меня localhost заблокирован файрволом", или "я запускаю Квик из Линукса в Wine". С такими мы ничего не можем/будем делать, а конкретно по функционалу/стабильности кода вероятно можно что-то еще докрутить.

Например, запускает ли кто-то код на машине, где не установлена Visual Studio? Действительно ли не хватает каких-то бинарников в комлекте, или в том issue дело было в чем-то другом.

**Comment by IFetisov** [comment]
А какую  диагностику можно прислать
Проверил ping (внутри проекта QuickShar) - не работает.
С файрволом все в порядке.

**Comment by buybackoff** [comment]
@IFetisov у Вас странный случай. Пробовали с чистого листа? Перезагрузиться, клонировать в новую папку, построить и запустить оттуда как C# тест/демо, так и Луа скрипт?

Также чеклист:
* Версия Windows - наверное в 7 должно работать, начинали когда 10й еще не было. Но лучше 10.
* Версия Квика - если 8.5, то должна быть самой последней
* Стоит ли Visual Studio на машине?
* Работают ли какие-то нетипичные сервисы, которые могут блокировать траффик.

В вашем netstat было слишком много слушателей на каждый порт, должно быть по одному.

**Comment by IFetisov** [comment]
Windows 10 - Microsoft Windows [Version 10.0.18363.535]
NetStat до старта тестового приложения
[netstat1.txt](https://github.com/finsight/QUIKSharp/files/4676094/netstat1.txt)
NetStat после зависания тестового приложения
[netstat2.txt](https://github.com/finsight/QUIKSharp/files/4676125/netstat2.txt)
Версия Квик 8.5.2.11. 
Visual Studio установлена я с ней постоянно работаю.
Код теста:

 
         public static void Ping() {
            var _df = new DebugFunctions(Quik.DefaultPort, Quik.DefaultHost);
            var sw = new Stopwatch();
            Console.WriteLine("Started");
            for (int round = 0; round < 10; round++) {
                sw.Reset();
                sw.Start();

                var count = 100;
                var array = new Task<string>[count];
                for (int i = 0; i < array.Length; i++) {
                    array[i] = _df.Ping();
                }
                for (int i = 0; i < array.Length; i++) {
                    Console.Write($"[{round}-{i}] ");
                    var pong = array[i].Result;
                    array[i] = null;
                    Trace.Assert(pong == "Pong");
                }
                sw.Stop();
                Console.WriteLine("MultiPing takes msecs: " + sw.ElapsedMilliseconds);
            }
            Console.WriteLine("Finished");
            Console.ReadKey();
        }

Результат работы тестового приложения: 
[result.txt](https://github.com/finsight/QUIKSharp/files/4676156/result.txt)

По результатам видно что процесс зависает на 3М круге пинга.
Про нетипичные сервисы сказать трудно обычная корпоративная сеть.

**Comment by Pr0phet1c** [comment]
Может я чего-то не понимаю, но почему не создаете экземпляр класса Quik, как все?

**Comment by IFetisov** [comment]
Эта диагностика в проекте есть. Я ее запустил чтобы проверить почему у меня
сбои каждый раз в разном месте. Выяснил что диагностика не работает как
должна.
Теперь хочу выяснить куда копать дальше. И работает ли эта диагностика у
других.
С уважением, Илья

пн, 25 мая 2020 г. в 13:02, Prophetic <notifications@github.com>:

**Comment by buybackoff** [comment]
Сделано. Возможны проблемы с папкой lua на .NET Core, не нашел за 10 минут гугления решения как заставить копировать папку, а не добавлять логические ссылки.
