### ISSUE TITLE
OnParam

### ISSUE THREAD

**Issue by Pr0phet1c** [finsight/QuikSharp#25]
Попытался реализовать подписку на колбэк OnParam.

В файле qscallbacks.lua:
--- Функция вызывается терминалом QUIK при изменении текущих параметров.
````
function OnParam(class_code, sec_code)
    local msg = {}
    msg.cmd = "OnParam"
    msg.t = timemsec()
    msg.data = sec_code
    sendCallback(msg)
end
````
В файле IQuikEvents.cs:
````
        event ParamHandler OnParam;
````
В файле QuikEvents.cs:
````
    /// <summary>
    /// Обработчик события OnParam
    /// </summary>
    /// <param name="sec_code">Код бумаги</param>
    public delegate void ParamHandler(string sec_code);
````
....
в классе: internal class QuikEvents : IQuikEvents
...
````
        public event ParamHandler OnParam;
        internal void OnParamCall(string sec_code) { if (OnParam != null) OnParam(sec_code); }
````
Проект собрал все необходимые файлы перенес в нужные папки (по аналогии с одной из функций, которые мне удалось благополучно реализовать)

В проекте, на котором тестирую подписался на событие:
````
                _quik.Events.OnParam += (param) => OnParamDo(param);
````
...
````
        void OnParamDo(string param)
        {
                Console.WriteLine("Есть колбэк OnParam");
        }
````
После запуска этот колбэк не приходит. (тот же OnQuote например исправно работает)
в логах "MissedCallbacks.1444311584.log"
есть записи типа
{"cmd":"OnParam","t":1444311584417.4,"data":"SBER"}
{"cmd":"OnParam","t":1444311584466.4,"data":"GAZP"}
{"cmd":"OnParam","t":1444311584502.5,"data":"SBER"}
{"cmd":"OnParam","t":1444311584528.5,"data":"SBER"}
{"cmd":"OnParam","t":1444311584549.5,"data":"GAZP"}
{"cmd":"OnParam","t":1444311584570.5,"data":"SBER"}
{"cmd":"OnParam","t":1444311584591.6,"data":"SiZ5"}
{"cmd":"OnParam","t":1444311584612.6,"data":"SRZ5"}

т.е. из квика колбэки отправляются, если я правильно понимаю.

Что я сделал неправильно в реализации колбэка?

**Comment by buybackoff** [comment]
А тут? https://github.com/buybackoff/QuikSharp/blob/master/src/QuikSharp/QuikService.cs#L401

**Comment by Pr0phet1c** [comment]
Неа, ничего не создавал  :)

Спасибо. Буду разбираться. По результатам отпишусь

**Comment by buybackoff** [comment]
В MissedCallbacks.___.log пишется только тогда, когда нет соединения. Значит функция в Луа работает как надо, но сторона C# не принимает и не обрабатывает корректно. Колбэки в виде json призодят сюда: https://github.com/buybackoff/QuikSharp/blob/master/src/QuikSharp/QuikService.cs#L242, оттуда можно проследить их дальнейший путь

**Comment by buybackoff** [comment]
Кстати missed callbacks я наверное скоро уберу как функционал. Он контр-интуитивен и редко нужен, и уже стоил мне нервов и немного денег

**Comment by Pr0phet1c** [comment]
Думаю, это не страшно.
Если я правильно понимаю, туда пишутся колбэки, которые не были приняты( не успели обработаться) в C#. Не знаю как для хфт, но для моих стратегий пропуск ряда колбэков во время выполнения сильно нагруженных операций, которые требуют много времени - вполне нормально.
Собственно, для этого я даже игнорирование колбэков реализовал. что-то типа:
````
        void OnParamDo(string param)
        {
            if (IgnoreTransactions == false)
            {
                IgnoreTransactions = true;
                last_price = Get.last_price(ClassCode, securityCode);
                Invoke(ChangeLabelText, label_LastPrice, last_price);
                IgnoreTransactions = false;
            }
        }
````

**Comment by buybackoff** [comment]
Луа не знает, что обработалось или нет в C#. Она пишет туда при обрыве TCP соединения - это она может понять, а при следующем соединении она отправляет все, что записала. И вот однажды я за четыре секунды надолбил в стакан Си несколько десятков миллионов, благо Си ликвидный с узким спрэдом, потерял всего пару тысяч рублей. Нужно постоянно помнить, что в момент соединения могут отработаться старые колбеки.

**Comment by Pr0phet1c** [comment]
В общем добавил в файл QuikService.cs:
в метод private void ProcessCallbackMessage(IMessage message):
````
                    case EventNames.OnParam:
                        Trace.Assert(message is Message<string>);
                        Events.OnParamCall(((Message<string>)message).Data);
                        break;
````
Не помогло. все равно не работает.
Причем, даже OnDisconnected и OnConnected и те не работают.
Запись вот такая:
````
                _quik.Events.OnConnected += OnConnectedDo;
                _quik.Events.OnDisconnected += OnConnectedDo;
...
        void OnConnectedDo()
        {
            if (IgnoreTransactions == false)
            {
                IgnoreTransactions = true;
                IsConn = Get.IsConnected();
                if (IsConn == true) 
                {
                    Invoke(ChangeLabelText, label_ConServer, "Connected");
                    Invoke(ChangeLabelColor, label_ConServer, Color.Green);
                }
                else 
                {
                    Invoke(ChangeLabelText, label_ConServer, "Disconnected");
                    Invoke(ChangeLabelColor, label_ConServer, Color.Red);
                }

                IgnoreTransactions = false;
            }
        }
````

OnQuote продолжает нормально отрабатывать.

Я снова что-то не так сделал?

**Comment by buybackoff** [comment]
Я написал выше в каком месте приходит сообщение из Квика, проследите его
судьбу оттуда

**Comment by Pr0phet1c** [comment]
Все. Разобрался.
Обнаружил необходимость внести изменения в файл "Serialization.cs":
````
                        case EventNames.OnParam:
                            return new Message<string>();
````
Правда, с OnConnected и OnDisconnected пока не получается.
В "Serialization.cs" обнаружил вот такие строки:
````
                        case EventNames.OnConnected:
                        case EventNames.OnDisconnected:
````
Тут у меня пока знаний не хватает. Так и должно быть для нормальной работы этих колбэков?
Если нет, то подскажите что нужно там прописать, чтобы не тратить время на "научный метод тыка".

**Comment by Pr0phet1c** [comment]
Кстати, запись потерянных колбэков в лог, я тоже отключил (точнее закоментил стро самой записи строки в файл. остальное пока не трогал).
Их подгрузка, после перезапуска приложения, создает массу неудобств.

**Comment by buybackoff** [comment]
Там все должно быть просто, однажды разобравшись. Учитесь асинхронным
потокам и дебагу, пригодится далеко за пределами КШ. К сожалению не могу
сейчас глубоко погружаться в решение проблем. Сделайте форк, чтобы не в
тексте объяснять, а я мог видеть что происходит целиком, тогда больше
шансов что я посмотрю. Сейчас же я вообще могу только на уровне
горячо/холодно и только догадываться

**Comment by zenonofelea** [comment]
А OnConnected в текущей версии должен работать? Мне кажется, что QuikSharp.lua никаких сообщений при разрыве соединения с Брокером не отправляет.
