### ISSUE TITLE
Nuget Package для Quik 64 bit

### ISSUE THREAD

**Issue by xplicit** [finsight/QUIKSharp#257]
Планируется ли выпуск nuget-package для quik 8+? После обновления Win10, 32-битная версия QUIK не работает совершенно, высыпая при запуске ошибки нехватки памяти. БКС, Сбер, ВТБ уже давно предоставляют QUIK 8 для клиентов, возможно и другие брокеры перешли на новую версию. Было бы неплохо иметь nuget-package, который работает с QUIK 8+ (версия 1.0.0, к сожалению, не работает).

**Comment by buybackoff** [comment]
https://github.com/finsight/QUIKSharp/issues/247
