### ISSUE TITLE
Exception thrown: 'System.IO.FileLoadException' in System.Threading.Channels.dll

### ISSUE THREAD

**Issue by vshelest901** [finsight/QUIKSharp#258]
Приветствую. Успешно собрал проект, но при попытке нажать кнопку CONNECT на демке, в консоль вылетают следующие сообщения (в основном окне: "Ошибка инициализации объекта QUIK")

'QuikSharpDemo.exe' (CLR v4.0.30319: QuikSharpDemo.exe): Loaded 'C:\Users\user2\Documents\QUIKSharp\Examples\QuikSharpDemo\bin\Debug\QUIKSharp.dll'. Symbols loaded.
'QuikSharpDemo.exe' (CLR v4.0.30319: QuikSharpDemo.exe): Loaded 'C:\Users\user2\Documents\QUIKSharp\Examples\QuikSharpDemo\bin\Debug\Newtonsoft.Json.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'QuikSharpDemo.exe' (CLR v4.0.30319: QuikSharpDemo.exe): Loaded 'C:\Users\user2\Documents\QUIKSharp\Examples\QuikSharpDemo\bin\Debug\System.Threading.Channels.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Exception thrown: 'System.IO.FileLoadException' in System.Threading.Channels.dll

Результат не зависит от того, нажата галка локального подключения или нет и не зависит от того слушает кто-либо порт или нет (пробовал посадить netcat, входящего соединения никто не пытается установить). VS2019, винда 10я (x64). 

Делал все по уроку https://youtu.be/QtMVqgwoPU0?t=432  , там в окне отладки видно, что у автора данная библиотека вообще не загружается, вместо нее на очереди Microsoft.NET. Винда 10 x64, пробовал на двух разных установках, результат одинаковый.  В какую сторону посмотреть?

**Comment by vshelest901** [comment]
Включил FusionLog. Нашлась ошибка для System.Threading.Tasks.Extensions

Журнал: данная привязка начинается в контексте загрузки default.
Журнал: используется файл конфигурации приложения: C:\Users\vlad\QUIKSharp-master\QUIKSharp-master\Examples\QuikSharpDemo\bin\Debug\QuikSharpDemo.exe.Config.
Журнал: используется файл конфигурации главного узла: 
Журнал: используется файл конфигурации компьютера из C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
Журнал: ссылка после применения политики: System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
Журнал: поиск в GAC выполнен неудачно.
Журнал: попытка скачивания нового URL file:///C:/Users/vlad/QUIKSharp-master/QUIKSharp-master/Examples/QuikSharpDemo/bin/Debug/System.Threading.Tasks.Extensions.DLL.
Журнал: скачивание сборки выполнено успешно. Осуществляется попытка установить файл: C:\Users\vlad\QUIKSharp-master\QUIKSharp-master\Examples\QuikSharpDemo\bin\Debug\System.Threading.Tasks.Extensions.dll
Журнал: вход в фазу установки run-from-source.
Журнал: имя сборки: System.Threading.Tasks.Extensions, Version=4.2.0.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
Предупреждение: при проверке имени сборки обнаружено несовпадение: Revision Number
Ошибка: ссылка на сборку не соответствует найденному определению сборки.
Ошибка: сбой на этапе запуска из исходного кода при установке (hr = 0x80131040).
Ошибка: не удалось завершить установку сборки (hr = 0x80131040). Проверка прекращена.

**Comment by mkashapov** [comment]
Я бы проверил версии сборки System.Threading.Tasks.Extensions - привёл бы их в соответствие или настроил assembly bindingRedirect

**Comment by vshelest901** [comment]
> Я бы проверил версии сборки System.Threading.Tasks.Extensions - привёл бы их в соответствие или настроил assembly bindingRedirect

Спасибо! 

На всякий случай, если кто-то новенький пойдет по этим-же граблям. Открываем QuikSharpDemo -> App.config И приводим его в какой-то такой вид (для моего случая)

`<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5" />
    </startup>
	<runtime>
		<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
			<dependentAssembly>
				<assemblyIdentity name="System.Threading.Tasks.Extensions" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-4.2.0.0" newVersion="4.2.0.1" />
			</dependentAssembly>
		</assemblyBinding>
	</runtime>
</configuration>`
