### ISSUE TITLE
Не выполняется скрипт QuikSharp.lua QUIK# is waiting for client connection...

### ISSUE THREAD

**Issue by MadaraV** [finsight/QUIKSharp#259]
Windows 10
QUIK версия 8.3.1.38. Брокер Сбербанк Последняя версия у данного брокера, в папке QUIK lua5.1.dll
Скачал с git последнюю версию QUIKSharp-master 2.0
Собрал проект без ошибок.

Установлен Lua for Windows v5.1.5-52 Released.
https://github.com/rjpcomputing/luaforwindows/releases
Хотя не уверен нужен ли он уже. Там версия x32

При запуске скрипта QuikSharp.lua через QUIK 
QUIK# is waiting for client connection...
и на этом и висит. 
Файл qsutils.lua Функция getResponseServer() 

Пробовал заменять файл lua5.1.dll на lua5.1.dll
Из http://luabinaries.sourceforge.net/download.html
lua5_1_5_Win64_bin.zip

Ничего не помогает, что еще может быть, просьба помочь.
Брандмауэр и Антивирус выключены.
На другом ПК Windows 8.1 такая же проблема

**Comment by buybackoff** [comment]
> Пробовал заменять файл lua5.1.dll на lua5.1.dll
Из последнего NuGet/master ничего менять не нужно

Изучите issues на эту тему, мне кажется 1/4 от всех на эту тему.

**Comment by MadaraV** [comment]
> Изучите issues на эту тему, мне кажется 1/4 от всех на эту тему.

Изучал там либо QUIK 7 версии в подобных ситуациях и темы старые. Либо если свежая обсуждают версию 8.5, и lua53.dll, но у Сбербанка пока что только 8.3.1

Вы в какой то теме отвечали, что нужно поставить Lua for Windows и автору темы помогло, но там версия Quik была 7.
Но последняя версия Lua for Windows v5.1.5-52 Released, если использовать dll от туда, ругается на разрядность.
Если использовать lua5_1_5_Win64_bin.zip тот же результат сервер не создается. Ну и также если ничего не ставить, а просто использовать lua5.1.dll, которая идет при установке QUIK 8.3.1.38 от брокера, такая же ситуация.

В итоге не понятно, что ставить. Если все равно тот же результат на двух разных ПК

**Comment by buybackoff** [comment]
> но у Сбербанка пока что только 8.3.1

Скажем так, версия `8.3.1` не поддерживается. Слишком много крови попортили версии 8.0 и 8.5, чтобы разбираться с 8.3. Вы можете скачать последнюю или 8.0 версию с сайта ARQA и портировать настройки и ключи со своей версии (давным давно так кажется работало, не знаю как сейчас).

Вообще логика такая:
https://github.com/finsight/QUIKSharp/blob/dbeee4d5a435332477c2938a89aa8a1f1f7e0bf5/src/QuikSharp/lua/QuikSharp.lua#L35-L41

8.3 должен работать как 8.0. 

Посмотрите логи в папке со скриптом. Убедитесь (double check), что используете последнюю версию C# и Lua кода, и что Квик запускает именно последний скрипт. Если вы обновили NuGet на версию 2.0, скрипты Луа возможно не обновились.

**Comment by MadaraV** [comment]
Спасибо за ответ, 
Скачивал проект https://github.com/finsight/QUIKSharp.git
В Readme сказано, что возможно потребуется установить LuaForWindows, может в этом дело и что то тут не так делаю.

1) В данный момент в версии Q# 2.0.0.0 нужно ли устанавливать LuaForWindows для QUIK версий 8+ или достаточно того, что поставляется Брокером вместе с программой? 
2) Если да то какую версию, в установочном варианте есть только Lua for Windows v5.1.5-52 Released. https://github.com/rjpcomputing/luaforwindows/releases, но она уже старая. Достаточно ли просто установить и перезагрузить или нужно какие то манипуляции делать с ней. Либо lua5_1_5_Win64_bin.zip http://luabinaries.sourceforge.net/download.html там чисто dll

**Comment by buybackoff** [comment]
> В данный момент в версии Q# 2.0.0.0 нужно ли устанавливать LuaForWindows для QUIK версий 8+ или достаточно того, что поставляется Брокером вместе с программой?

Это больше не нужно. Тем более, что LuaForWindows кажется не существует для x64.

Посмотрите логи.

> На другом ПК Windows 8.1 такая же проблема

Если логи ОК, скорее всего проблема с этой версией Квика.

**Comment by MadaraV** [comment]
Логи ошибок нет
2020-07-03 15:38:05.238 LOG 0: QUIK# is initialized from D:\! LUA Scripts\lua\QuikSharp.lua
2020-07-03 15:38:05.238 LOG 0: Running from QuikSharp, params: response 127.0.0.1:34130, callback  127.0.0.1:34131
2020-07-03 15:38:05.238 LOG 0: Entered main function
2020-07-03 15:38:05.239 LOG 1: QUIK# is waiting for client connection...
2020-07-03 15:38:05.239 LOG 0: Waiting for a response client...
2020-07-03 15:38:36.558 LOG 1: QUIK# stopped. You could keep script running when closing QUIK and the script will start automatically the next time you start QUIK

**Comment by MadaraV** [comment]
Разобрался
Сообщения 
LOG 0: Waiting for a response client...
LOG 0: Waiting for a callback client...
LOG 1: QUIK# client connected

появляются после соединение через QuikSharpDemo

А соединение не устанавливалось, так как не создавало _quik = new Quik из-за ошибки "Не удалось загрузить файл или сборку "System.Threading.Tasks.Extensions", пока в Свойствах не поставил флажок «Автоматически создавать перенаправления привязок».
