### ISSUE TITLE
Особенности создания приложения Windows Forms

### ISSUE THREAD

**Issue by Pr0phet1c** [finsight/QuikSharp#26]
В процессе тестирования QuikSharp в Windows Forms-приложении, столкнулся с необходимостью все функции, которые получают какие-либо данные из Quik, запускать в отдельных процессах.
Для простоты написания кода в дальнейшем, пришлось создать отдельных класс, дублируя там все реализованные функции QuikSharp.

В результате, строка которая в консольном приложении выглядит так:

```
IsConn = _quik.Service.IsConnected().Result;
```

у меня превращается в:

```
    static class Get
    {
        public static bool IsConnected()
        {
            bool Res = false;
            Thread trCon = new Thread(delegate() { Res = Form1._quik.Service.IsConnected().Result; });
            trCon.Start();
            trCon.Join();
            return Res;
        }
    }
....
                IsConn = Get.IsConnected();
```

Более изящного решения пока не нашел.
Собственно вопрос вот в чем:
А нельзя ли непосредственно в QuikSharp реализовать все эти функции в отдельных потоках?
Попробовал бы сам, но думаю знаний не хватит.

Также, при создании этого приложения столкнулся с проблемой изменения свойств объектов Form из методов вызванных колбэками.
В частности, система ругается на попытку получить доступ к  методу объекта не из того потока, в котором такой объект был создан.
Пока решил задачку через кросспотоковый вызов, типа:

```
    public delegate void ChangerLabels(Label label, object value);
...
        ChangerLabels ChangeLabelText;
...
            ChangeLabelText = new ChangerLabels(ChngLabelTxt);
...
        private void ChngLabelTxt(Label label, object value)
        {
            label.Text = Convert.ToString(value);
        }
...
                    Invoke(ChangeLabelText, label_LastPrice, last_price);
```

Возможно, кому-то эта информация будет полезна.
Если кто-нибудь подскажет более простое решение - буду рад.

**Comment by buybackoff** [comment]
Ой ой ой, что-то тут не так :) Async/await вместе с ConfigureAwait как-то должно работать. Создавать каждый раз поток убийственно медленно. Гугл Вам в помощь, это не прямая проблема QuikSharp. Как-нибудь сделаю пример вызова из потока GUI.

**Comment by Pr0phet1c** [comment]
Буду весьма признателен за помощь. Я с многопоточностью впервые сталкиваюсь, поэтому знания пока минимальные.

**Comment by buybackoff** [comment]
Гугл точно будет быстрее, чем я.

**Comment by Pr0phet1c** [comment]
Да, Вы правы.
на первый взгляд (после нескольких экспериментов) записей вида:
````
        private async void Init()
        {
...
                IsConn = await _quik.Service.IsConnected();
                label_Instrument.Text = (await _quik.Class.GetSecurityInfo(ClassCode, securityCode)).short_name;
...
        }
````
Вполне достаточно.

Если не затруднит, может подскажете идею упрощения доступа в объектам Form из других потоков (та проблема, которая у меня через Invoke в результате делается)?

**Comment by COBRAprogDAV** [comment]
После иницилизации формы можете создать поток, в котором работаете с quiksharp.  
в этом потоке получете ссылку или создаете делегат на форму - для общения потока с формой.
в потоке формы не должно быть вызовов Quiksharp для "чистоты" программирования.

**Comment by buybackoff** [comment]
http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html
