### ISSUE TITLE
Не срабатывают колбэки

### ISSUE THREAD

**Issue by IFetisov** [finsight/QUIKSharp#263]
Скачал последние версии с примерами. Нужно ли что то делать чтобы запустить колбэки?
![image](https://user-images.githubusercontent.com/40885403/87651211-6c3b5300-c75b-11ea-941f-ef214995e577.png)
Добавил в DEMO строки (выделены жирным). Обезличенные сделки сыплются в квик но OnAllTrade не срабатывает.
                        textBoxLogsWindow.AppendText("Подписываемся на колбэк 'OnFuturesClientHolding'..." + Environment.NewLine);
                        _quik.Events.OnFuturesClientHolding += OnFuturesClientHoldingDo;
                        textBoxLogsWindow.AppendText("Подписываемся на колбэк 'OnDepoLimit'..." + Environment.NewLine);
                        _quik.Events.OnDepoLimit += OnDepoLimitDo;
                        **textBoxLogsWindow.AppendText("Подписываемся на колбэк 'OnAllTrade'..." + Environment.NewLine);
                        _quik.Events.OnAllTrade += OnAllTradeDo;**       
         **void OnAllTradeDo(AllTrade alltrade)
         {  
              AppendText2TextBox(textBoxLogsWindow, "Вызвано событие OnAllTradeDo .." + 
                            Environment.NewLine);
          }**

**Comment by Pr0phet1c** [comment]
Не очень понятна фраза "...сыплются в квик но OnAllTrade не срабатывает"
Если OnAllTrade не срабатывает в коде Lua, то проблема вероятно не в библиотеке, а в терминале.
В противном случае, надо смотреть прилетают ли данные в библиотеку.
К сожалению, я помочь в этой части не смогу, т.к. не подписан на получение обезличенных сделок у своих брокеров (и не планирую этого делать).

**Comment by Pr0phet1c** [comment]
Кстати, а OnQuote у Вас отрабатывает нормально, в этой демке? Он по умолчанию всегда запускается и обновляет данные о последней цене, биде и аске.

**Comment by IFetisov** [comment]
Никакие события не отрабатывют в C#.
В квике появляются все сделки
В коде Lua все работает
function OnAllTrade(alltrade)
    if is_connected then
        log("OnAllTrade is activated", 0)
        local msg = {}
        msg.t = timemsec()
        msg.cmd = "OnAllTrade"
        msg.data = alltrade
        sendCallback(msg)
        log("OnAllTrade is sent", 0)
    end
end


2020-07-17 17:46:39.553 LOG 0: OnAllTrade is activated
2020-07-17 17:46:39.554 LOG 0: OnAllTrade is sent
2020-07-17 17:46:39.666 LOG 0: OnAllTrade is activated
2020-07-17 17:46:39.666 LOG 0: OnAllTrade is sent
2020-07-17 17:46:40.105 LOG 0: OnAllTrade is activated
2020-07-17 17:46:40.105 LOG 0: OnAllTrade is sent
2020-07-17 17:46:40.189 LOG 0: OnAllTrade is activated
2020-07-17 17:46:40.189 LOG 0: OnAllTrade is sent
2020-07-17 17:46:40.189 LOG 0: OnAllTrade is activated
2020-07-17 17:46:40.189 LOG 0: OnAllTrade is sent
2020-07-17 17:46:40.189 LOG 0: OnAllTrade is activated
2020-07-17 17:46:40.189 LOG 0: OnAllTrade is sent
2020-07-17 17:46:40.307 LOG 0: OnAllTrade is activated
2020-07-17 17:46:40.307 LOG 0: OnAllTrade is sent
2020-07-17 17:46:40.856 LOG 0: OnAllTrade is activated
2020-07-17 17:46:40.856 LOG 0: OnAllTrade is sent

**Comment by IFetisov** [comment]
Подскажите пожалуйста как отладить pcall.
        local status, res = pcall(callback_client.send, callback_client, callback_string..'\n')
где брейк ставить или лог?

**Comment by Igor-san** [comment]
> Подскажите пожалуйста как отладить pcall.
> local status, res = pcall(callback_client.send, callback_client, callback_string..'\n')
> где брейк ставить или лог?
Попробуй в квике открыть таблицу обезличенных сделок - заработает

**Comment by IFetisov** [comment]
У меня она на скриншоте видно что она открыта. 
Тем более что событие в луа срабатывает, не приходит в C# по каким то причинам.

**Comment by Igor-san** [comment]
> У меня она на скриншоте видно что она открыта.
> Тем более что событие в луа срабатывает, не приходит в C# по каким то причинам.
Ну тогда может действительно что из-за 8.7. У меня только 8.5 
![OnAllTrade](https://user-images.githubusercontent.com/30476065/87920874-7e323400-ca82-11ea-8a44-a68b94451ed4.png)

**Comment by IFetisov** [comment]
Обновился на квик 8.8.0.55
Скомпилял проект на Net 472
Колбэки заработали и вроде все остальное тоже. Тестирую еще пока.

**Comment by ArtemKolesnikov** [comment]
На правах некропоста.
Я вообще не программист (времени нет им становится), поэтому пользуюсь готовыми кодами, лишь чуть редактируя под себя. Так и в этом примере, мне тоже нужен был OnAllTrade для открытого интереса, решил вопрос просто копипастя все, что связано с OnQuote. На форму добавил текстбокс для вывода открытого интереса.
`double oi;
*****
                            _quik.Events.OnQuote += OnQuoteDo;
                            _quik.Events.OnAllTrade += OnAllTradeDo;
*****
void OnAllTradeDo(AllTrade quote)
        {
            if (quote.SecCode == tool.SecurityCode && quote.ClassCode == tool.ClassCode)
                oi = quote.OpenInterest;           
        }
*****
//И вставил в обработчик таймера в то место, где выводится бид и офер.
private void TimerRenewForm_Tick(object sender, EventArgs e)
        {
****
                Text2TextBox(textBoxOI, oi.ToString());`
Все работает.
