### ISSUE TITLE
Не работает колбэк _quik.Events.OnStopOrder

### ISSUE THREAD

**Issue by cia76** [finsight/QUIKSharp#266]
Версия Квика 8.8.0.55

Подключаю обработчик событий стоп-заявок
_quik.Events.OnStopOrder += OnStopOrder;

Передаю в Квик стоп заявку
transactionId = _quik.StopOrders.CreateStopOrder(stopOrder).Result;

На Квике заявка создается корректно. Колбэк не обрабатывается. Другие колбэки подключения, отключения, прихода котировки, рыночных/лимитных заявок работают корректно.

**Comment by buybackoff** [comment]
Было похожее тут #263, это не оно?

**Comment by cia76** [comment]
Нет, не оно. Только событие OnStopOrder не обрабатывается. Остальные события обрабатываются без проблем.

**Comment by avently** [comment]
Надо в Lua сначала проверять, приходят ли коллбэки от самого Квика. Приходят ли?

**Comment by cia76** [comment]
> Надо в Lua сначала проверять, приходят ли коллбэки от самого Квика. Приходят ли?

Верное замечание. Поправил функцию:

```
function OnStopOrder(stop_order)
	log('Stop', 1)
	local msg = {}
    msg.t = timemsec()
    msg.data = stop_order
    msg.cmd = "OnStopOrder"
    sendCallback(msg)
end
```
При постановке стоп заявки в лог Квика пишется Stop. Значит, Квик здесь ни при чем.

**Comment by avently** [comment]
У меня Квик 8.7, OnStopOrder приходит, НО я не использую C#, а только луа сервер. На самом деле, вам вряд ли кто-то поможет, потому как это не получится воспроизвести у себя. Я бы на вашем месте логгировал все места кода, по которым идет сообщение от lua кода до непосредственно вашего обработчика. Благо исходники библиотеки открыты. Начать логи следует еще в луа методе, который пишет в сокет.

**Comment by Pr0phet1c** [comment]
На 8.4 похоже действительно не приходит. Причины пока не смог понять.
В демо-приложение добавил подписку на это событие и его обработку, чтобы можно было проверять, когда решим проблему

**Comment by Pr0phet1c** [comment]
Вроде пофиксил.
![2020-08-05_19-14-36](https://user-images.githubusercontent.com/14761254/89437808-b4450880-d750-11ea-8091-401543099ff1.png)

**Comment by Pr0phet1c** [comment]
А вот срабатывание при ручной отмене заявки:
![2020-08-05_19-21-44](https://user-images.githubusercontent.com/14761254/89438208-36353180-d751-11ea-9feb-da030b9ad578.png)

**Comment by cia76** [comment]
> Вроде пофиксил.

Проверил. Все заработало, благодарю!
