### ISSUE TITLE
Айсберг заявка

### ISSUE THREAD

**Issue by IFetisov** [finsight/QUIKSharp#270]
Всем привет.
Не подскажете как такую поставить?
Или это невозможно через Lua?

**Comment by Pr0phet1c** [comment]
Вы средствами Квика пытались выставить такую заявку?

**Comment by IFetisov** [comment]
Через Квик выставляется. 
По ЛУА нашел вот что https://forum.quik.ru/forum10/topic4846/
вот : 
_Транзакции с ACTION равным NEW_ORDER, NEW_STOP_ORDER, KILL_ORDER и т.д., которые явно прописаны в справке к терминалу - это формат, оставшийся с давних времен и на текущий момент его не развивают, т.к. при добавлении новых полей в транзакциях их нужно будет явно прописывать в коде терминала, в документации и т.д. и выпускать каждый раз новую версию терминала (а таких транзакций очень много). В этот перечень новых транзакций попала транзакция и для Айсберг-заявок, по этой причине для нее и нет зарезервированного ACTION, наподобие NEW_ORDER._

Типа пользуем устаревший интерфейс а новый  оказывается  развивается сверхтемпами и имеет 2 языка

**Comment by IFetisov** [comment]
попробую сейчас вот это запилить transaction['ACTION'] = 'Ввод айсберг заявки'
и отпишусь

**Comment by Pr0phet1c** [comment]
> попробую сейчас вот это запилить transaction['ACTION'] = 'Ввод айсберг заявки'
> и отпишусь

Ну, по идее правильный путь. При условии, что Вы не пытаетесь сделать это в "игровой" версии терминала (Junior).

**Comment by IFetisov** [comment]
Надо как то с кодировкой разобраться. На сайте написано что квик ожидает кодировку 1251 У меня видимо уходит UTF8
{"data":{"CLIENT_CODE":"1","PRICE":"119,05",
"Р’РёРґРёРјРѕРµ РєРѕР»РёС‡РµСЃС‚РІРѕ":"3","OPERATION":"S","QUANTITY":"40",
"ACTION":"Р’РІРѕРґ Р°Р№СЃР±РµСЂРі Р·Р°СЏРІРєРё",
"TRANS_ID":"15109652","TYPE":"L"},"t":1597071402374,"cmd":"sendTransaction","id":128}

**Comment by IFetisov** [comment]
Закрою чтобы зря не висело :) Можно жить и без айсберг заявок.
