### ISSUE TITLE
Предложение: Защита подключения паролем

### ISSUE THREAD

**Issue by Igor-san** [finsight/QUIKSharp#274]
В случае рабочего места в интернете, хотелось бы **дополнительно** обезопасить его через парольную защиту. Т.е. подключаться вроде 

`new Quik(port, new InMemoryStorage(), host, password); `

**Comment by buybackoff** [comment]
Это не имеет смысла при использовании TCP, т.к. траффик может быть виден всем при минимальных усилиях. Нужно использовать TLS. В теории можно сделать прямо из Луа, на практике вряд ли кто-то будет это делать.

Самое простое - запустить любой web server (ASP.NET Core например) и сделать прокси через websocket.

Вариант с Луа кажется простым, но наверняка потребует некоторой (возможно большой на Windows) возни https://github.com/brunoos/luasec/wiki
