### ISSUE TITLE
Платные консультации - Need help

### ISSUE THREAD

**Issue by mr-first** [finsight/QUIKSharp#275]
Хочу разобраться как писать с помощью библиотеки - буду рад если кто-нибудь покажет/объяснит что к чему. 
Если кто-то готов помочь мне за денежку - напишите плиз на ilya-alex@mail.ru.
Спасибо!

**Comment by Pr0phet1c** [comment]
Я конечно могу ошибаться, но мне кажется, что Вы неправильно понимаете суть данного проекта.
Для того, чтобы писать роботов с помощью данной библиотеки, необходимо изучить, хотя бы на начальном уровне, язык программирования C#.
Если вы его не знаете, то за обучением программированию, гораздо эффективнее обратиться на профильные ресурсы.
Если же Вы умеете писать программы на C#, то для понимания того, как пользоваться данной библиотекой, в проекте предусмотрены демонстрационные приложения (в том числе полноценный робот), изучив код которых можно построить собственное приложение.
И все это можно сделать не вложив ни копейки денег.

**Comment by mr-first** [comment]
Я что-то умею на c#, но хочется уменьшить время изучения.  Запустил тестового робота на демо - получил ошибку, может быть все дело в новых заявках (скрин: https://ibb.co/3kDnjmv). 
Поэтому мне и нужна консультация, чтобы понять как быстро реализовать то, что мне нужно силами QuikSharp

**Comment by Mail-png** [comment]
Какой ужас
