### ISSUE TITLE
Добавил метод GetClientCodes

### ISSUE THREAD

**Issue by VsevolodEvdokimov** [finsight/QUIKSharp#278]
У меня в квике несколько клиентских кодов, поэтому нужен список всех. Добавил метод GetClientCodes(). Не могу запушить изменения и сделать пулреквест, поэтому приаттачиваю изменения здесь:
[QuikSharp_GetClienttCodes.zip](https://github.com/finsight/QUIKSharp/files/5554053/QuikSharp_GetClienttCodes.zip)

**Comment by Pr0phet1c** [comment]
Вы же проверили работоспособность этой функции, правда?
По коду я проблем не увидел, и базовый функционал эта функция не ломает, так что функция добавлена в библиотеку. Спасибо.
