### ISSUE TITLE
Добавил пропущенный Result в ParamTable

### ISSUE THREAD

**Issue by usikpavel** [finsight/QUIKSharp#279]
Мне понадобился флаг успеха вызова getParamEx() - например, когда SecurityCode некорректно задан. По документации getParamEx() возвращает result в качестве такого флага: http://luaq.ru/getParamEx.html, однако в ParamTable его не было. Добавил, проверил, все работает. Изменения тут:
[ParamTable.zip](https://github.com/finsight/QUIKSharp/files/5560334/ParamTable.zip)

**Comment by Pr0phet1c** [comment]
Согласен. Добавлено.

З.Ы.: Такое ощущение, что раньше этого свойства не существовало
