### ISSUE TITLE
Trade.SideQualifier всегда ноль

### ISSUE THREAD

**Issue by iza88** [finsight/QUIKSharp#288]
и поэтому не могу определить сделка была продажей или покупкой
вызываю `ITradingFunctions.GetTrades`

**Comment by Pr0phet1c** [comment]
Странный выбор метода определения направления сделки.
Мне кажется Вы не то поле для этих целей выбрали.
Если Вам необходимо определить именно направление сделки, без привязки к заявке - анализируйте поле Flags в классе Trade. Там передается набор битовых флагов. Сам я в эту структуру давно не влезал, но если я правильно понимаю, Вам необходимо получить состояние флага "IsSell", по нему и определите направление.

**Comment by iza88** [comment]
спасибо

**Comment by Pr0phet1c** [comment]
Вот Вам даже подсказка:

bool isSell = _trade.Flags.HasFlag(OrderTradeFlags.IsSell)
