### ISSUE TITLE
Update Readme, NuGet + Add examples

### ISSUE THREAD

**Issue by buybackoff** [finsight/QuikSharp#29]
60 microsecs - throughput, not latency. Latency is closer to 100.

Nice definition what QS is  :smile:  "минимальный базовый рабочий сетап, без перегруза деталями каких-то частных методов анализа данных и включения всех мыслимых нюансов с документации и чей-то практики. Как АК-47, чтобы просто, сурово и фундаментально" http://forum.moex.com/viewtopic.asp?t=28925

By popular demand, need to create simplest examples, including the threading issue WinForms.

Unfortunately, very low priority now.

**Comment by buybackoff** [comment]
@nubick Олег, может у тебя найдется время написать простейший пример использования, в том числе с WinForms, и запостить его в Вики тут и на Смарт-Лабе? Я недавно погуглил, кажется многие просто не знают о существовании проекта, а те, кто находят его случайно, наталкиваются на "простейшие сложности".

Я начал на коленке писать минимальную объектную модель на интерфейсах и абстракных классах. Хочу, чтобы QuikSharp ее имплементировал. Потом под нее, может быть, выложу другие коннекторы. Не хочется изобретать СтокШарп, но они так и не поймут, что такое открытый код, и как в цитате выше: "включает все мыслимые нюансы с документации и чей-то практики". Lean то же самое. Кроме того, я готовлю к релизу библиотеку для анализа данных в реальном времени, на которой написание, тестирование и оптимизация стратегий будет проще и быстрее. Так что не могу причесывать QuikSharp сейчас.

Feel free добавь себя в авторы, если это что-то значит. Коммитов уже скоро будет больше моих :)  Скоро переложу проект в отдельную организацию finsight. Даже странно, что удалось зарегить ее тут сейчас, а у меня этот домен в .ру с 2005-го года без дела лежит.

**Comment by buybackoff** [comment]
@nubick Создал организацию, добавил тебя в коллабораторы с правом на запись. Надеюсь архитектурные изменения будем обсуждать, а по вопросу допилить функционал можно думаю напрямую писать.

**Comment by nubick** [comment]
Времени сделать хорошие примеры пока нет. Я подумаю, может смогу что-то выдрать из моей текущей системы, только она на WPF, а не WinForm, но treading issues там решены, если я правильно понял, что вложено в эту фразу :)

Ты сделал отличную библиотеку, на мой взгляд. Я смотрел стокшарпы всякие и это ад. Наткнулся на твою. Попробовал и все заработало! Это очень здорово! Так что подумай три раза, прежде, чем её усложнять :) Если будешь покрывать её интерфейсами, подумай о том, чтобы она и без них работала. Если мне ничего кроме квика не надо, то я не хочу базовыми интерфейсами заморачиваться. А то будет ненужная сложность, как в стокшарпе и остальных.

**Comment by buybackoff** [comment]
@nubick  Да, там не в формах дело, а в потоках. Что-то не могу найти свой старый пример быстро. Спасибо за такой фидбек! Про интерфейсы - я хочу сделать **минимальную** модель, которая была бы всегда subset, а не superset функциональности любого брокера. Но когда я начал, быстро понял - что задача упростить и найти правильные абстракции - сложнее, чем все усложнить и напихать в одну кучу все возможные случаи. Так что QuikSharp это точно не коснется, и я не собираюсь делать еще одно мозговзрывательное решение как StockSharp. Мне просто не хватает dependency injection для торговой платформы, так чтобы имплементация торговли была спрятана за интерфейсами и в 99% случаев детали имплементации не играли бы роли.

**Comment by eugene20237** [comment]
Подскажите пожалуйста, почему на WPF зависают методы работающие через Tasks (асинхронные)? Графический интерфейс зависает и код не выполняется. Это если использовать инструкции из примеров вида:
quik.Debug.IsQuik().Result;
Как их правильно использовать в WPF приложении?

**Comment by buybackoff** [comment]
http://stackoverflow.com/questions/14526377/why-does-this-async-action-hang
Google и Stackoverflow вам в помощь, это известная тема про async/TLP и GUI

**Comment by eugene20237** [comment]
Спасибо!
