### ISSUE TITLE
как взять последнее значение по IMOEX

### ISSUE THREAD

**Issue by iza88** [finsight/QUIKSharp#290]
прежде всего спасибо еще раз за ваш великолепный проект

не могу понять какой брать `ParamNames` чтобы получить последнее значение инструмента из класса `INDX`, например `IMOEX`. Использую `GetParamEx`

**Comment by Pr0phet1c** [comment]
Вопрос непонятен. Попробуйте переформулировать, описав задачу подробнее.

**Comment by iza88** [comment]
последнюю цену по инструменту беру так
`_quik.Trading.GetParamEx(classCode, secCode, ParamNames.LAST)`
это работает для первого инструмента из скриншота, а для второго надо указать другой `ParamNames`. Я пробовал несколько, но так и не нашел тот, который показывал бы 'Значение'
![image](https://user-images.githubusercontent.com/14890699/110933590-00d37080-833e-11eb-998a-1287eb731ee7.png)

**Comment by Pr0phet1c** [comment]
Интересующий Вас параметр называется CURRENTVALUE. В классе ParamNames такого нет (надо на досуге актуализировать список), но Вы можете указать этот параметр текстом, как это изначально было задумано разработчиками в QLua. ParamNames я реализовал для дополнительного удобства, в качестве альтернативы.
