### ISSUE TITLE
core.dll - не является приложением Win32

### ISSUE THREAD

**Issue by SDANET** [finsight/QUIKSharp#291]
Здравствуйте!
Запускаю проект (QuikPy) на основе Ваших библиотек, получаю ошибку при запуске LUA в квике:
error loading module 'socket.core' from file 'C:\QUIK\socket\core.dll':
	%1 не является приложением Win32.

Версии: Система win-7*64, QUIK 8.11.0.66, LuaForWindows_v5.1.5-52 установлен.
Пробовал 6 разных библиотек из папок clibs, clibs64 - ошибка все та же.
Подскажите что можно сделать?

**Comment by Pr0phet1c** [comment]
1. Не знаю, что такое QuikРу. Тут ничего подсказать не смогу.
2. LuaForWindows ставить не обязательно. Пробовать разные библиотеки из разных попок не надо, правильная библиотека для загрузки выбирается автоматически, на основе определения версии терминала.
3. Могу ошибаться, но рискну предположить, что Вы где-то перемудрили. Попробуйте сделать все "с чистого листа", т.е.:
а) скачать самую свежую версию библиотеки.
б) скомпилировать решение
в) скопировать содержимое папки lua из проекта в отдельное место, из которого будете запускать в терминале "QuikSharp.lua"
г) открыть терминал,  запустить в нам указанный выше скрипт. Предварительно проверьте настройки режима, (если они доступны в той версии) в котором запускаете скрипты. Я пока оставил 5.3.5.
д) если ошибок не будет (а по идее их быть не должно, т.к. я на этой версии терминала работал без проблем), то попробуйте запустить тестовые приложения из данного проекта.

Возможно, Вы в папку с квиком что-нибудь лишнее понапихали. Если это так, то попробуйте и квик заново установить.

**Comment by SDANET** [comment]
Здравствуйте, перезакачал все файлы отсюда, все заменил. Теперь и Quik_2 и QuikSharp запускаются :) Спасибо!
