### ISSUE TITLE
Как получить _все_ открытые позы? плюс описание метода

### ISSUE THREAD

**Issue by kajiev** [finsight/QUIKSharp#293]
Как получить _всё_ из таблицы "позиции по клиентским счетам"?

Я нашёл только этот метод:
` GetFuturesHolding(string firmId, string accId, string secCode, int posType);`
Наверное, ОК передавать **firmId** и **accId**, но если мне неизвестны **secCode** - что делать? 

В нём бы добавить документацию: что ожидается в **posType** ?

**Comment by Pr0phet1c** [comment]
А как Вы это делали на QLua?

**Comment by kajiev** [comment]
Спасибо. Проверил.
