### ISSUE TITLE
ExecutionCondition

### ISSUE THREAD

**Issue by exvion** [finsight/QUIKSharp#295]
Заметил, что в функцию SendLimitOrder нельзя передать параметр ExecutionCondition. С чем связано такое ограничение? Как будет правильнее добавить такую функциональность?

**Comment by Pr0phet1c** [comment]
Вряд ли сейчас кто-то это вспомнит.. Опция не особенно востребованная, судя по отсутствию подобных обращений на протяжении нескольких лет. Если сильно хотите реализовать - добавьте в качестве необязательного параметра, чтобы никому не поломать текущий код.

**Comment by exvion** [comment]
#296
