### ISSUE TITLE
Не стартует QuikSharp.lua

### ISSUE THREAD

**Issue by oops1** [finsight/QUIKSharp#3]
Не стартует QuikSharp.lua. 
Ошибка 
error loading module 'socket.core' from file 'C:\Program Files (x86)\Quik-Zerich\lua\clibs\socket\core.dll':
    Не найден указанный модуль.

**Comment by buybackoff** [comment]
А у Quik-Zerich вообще Луа входит в установку? Мне сложно решить эту проблему удаленно (на моей машине все работает), но Вы второй человек с такой ошибкой, поэтому когда вернусь к этой библиотеке первым делом посмотрю на это.
Т.к. код открытый, pull requests are welcome!

**Comment by buybackoff** [comment]
Вы можете скопировать пакет Луа sockets туда, это единственная зависимость.
Еще вопрос - Вы пользуютесь NuGet пакетом, или клонировали этот репозитарий?

**Comment by oops1** [comment]
Все файлы скопировал , я могу вам дать доступ по тимвьюверу. если есть желание разобраться. И наверное не второй а первый человек, я вас на смартлабе по этой проблеме спрашивал

**Comment by oops1** [comment]
я незнаю LUA

**Comment by buybackoff** [comment]
Быстрое решение - скопируйте из папки packages требуемые файлы туда, куда он просит. 
Судя по [этой срочке](https://github.com/buybackoff/QuikSharp/blob/master/NuGet/QuikSharp.nuspec#L33) я не забыл его добавить, просто проблема с резолюцией путей.

**Comment by oops1** [comment]
Я наверное не понял вас, Но у меня скопированы все файлы. 
В этом сообщении, указан путь 
error loading module 'socket.core' from file 'C:\Program Files (x86)\Quik-Zerich\lua\clibs\socket\core.dll':
по этому пути есть библиотека в наличии.

**Comment by buybackoff** [comment]
Тогда проблема серьезнее и мне надо разбираться.

**Comment by buybackoff** [comment]
Подскажите, какая версия Quik? (Связь - Информационное окно - Версия программы). В одной из недавних версих QLua был сломан, а если сильно новая версия, то там могли быть изменения.

**Comment by oops1** [comment]
Версия Квика 6.15.1.17

**Comment by buybackoff** [comment]
с 6.15 как раз были проблемы, например описано тут http://quik2dde.ru/viewtopic.php?id=30
я тестировал на 6.16

**Comment by oops1** [comment]
Понятно, у цериха пока нету обновлений, буду ждать тогда обновления.

**Comment by buybackoff** [comment]
Любой демо-квик подойдет, я тестровал на своем брокере и на демо

**Comment by oops1** [comment]
Хотя , в ссылке который вы указали выше сказано что версия 6.15.1 уже все исправлено, а у меня

**Comment by buybackoff** [comment]
Хоть на формуе и написано, что проблемы в 6.15.1 были решены по сравнению с 6.15.0, но без дополнительного подтверждения что дело не в Квике я не могу просто так разбираться в чем дело на расстоянии. Если файл dll на нужном месте и скрипт пытается его загрузить, то остальной код - это модуль Lua Sockets, написанный не мной и хорошо работающий много лет.

**Comment by oops1** [comment]
Что мне сделать  ? чтобы помочь вам разобраться  ?

**Comment by buybackoff** [comment]
Попробуйте заменить папку Sockets в C:\Program Files (x86)\Quik-Zerich\lua\ на ту же папку из NuGet пакета (хотя это шаманство). (старую переименуйте а не удаляйте на всякий случай). 

Если это не поможет, то что происходит внутри QLua когда он загружает библиотеку, написанную на C, я не могу понять даже на своей машине.

**Comment by oops1** [comment]
нет не помогло, я все же подозреваю что не хватает зависимостей для библиотеки, что то вы не положили в нугет пакет что есть у вас и чего нету у меня. Может у вас стоит какой нибудь расширенный пак LUA ?

**Comment by buybackoff** [comment]
Sockets единственная зависимость, у которой нет зависимостей. Я тестировал на демо Квике изолированно как если бы я скачал с НюГета.

**Comment by 0a113ef6b61820daa5611c870ed8d5ee** [comment]
cjson.dll требует lua51.dll (на всякий случай, уточняю - в папке квика есть lua5.1.dll - похожее название), квик  пишет "не найден указанный модуль". Нашел в и-нете lua51.dll, теперь при попытке запуска скрипта - квик просто намертво виснет. Квик - самый последний, из того, что лежит на их ftp - 6.16.1.15. Можете что-то порекомендовать?

**Comment by buybackoff** [comment]
Нужно установить это  https://code.google.com/p/luaforwindows/downloads/detail?name=LuaForWindows_v5.1.4-46.exe&can=2&q= и перезапустить Квик

**Comment by buybackoff** [comment]
Корень проблемы описан здесь: http://lua-users.org/lists/lua-l/2008-06/msg00076.html
В Квике в комплекте идет lua5.1.dll, но не идет lu51.dll. В стандартной становке идут оба файла. Я добавлю их оба в NuGet пакет

**Comment by buybackoff** [comment]
https://github.com/buybackoff/QuikSharp/commit/842efb62923835623a9b43da67595ac6f3ee72bf closes this

**Comment by buybackoff** [comment]
Reopen and leave as a question/doc

**Comment by nubick** [comment]
Пытаюсь развернуть систему на выделенном сервере. Получил аналогичную ошибку.
Версия quik 6.17, core.dll в папке присутствует.
Установка LuaForWindows по ссылкы от Mar 19, 2015 не помогла.
Пытаюсь разобраться, но пока не получается.
Если есть идеи, как можно решить, буду признателен. Сам же тоже продолжу разбираться.

**Comment by buybackoff** [comment]
@nubick  "Выделенный сервер" наводит на мысль, что там все с чистого листа и либо нет зависимостей, либо конфликт версий. Я бы прошелся по каждой, их немного.  Также перепроверить lua5.1.dll vs lua51.dll. И не 5.2 ли установилась, не знаю какая сейчас текущая основная.

**Comment by nubick** [comment]
Решил проблему следующим образом:
В папке quik'a файл lua5.1.dll весил 32.832 байт, а аналогичный файл из папки, куда я установил Lua 5.1 (по ссылке выше) весит 161.936 байт. Заменил этот файл в папке quik'a и все заработало.

Не понимаю почему dll'ки отличаются.
Может кому-то моё решение пригодиться.
