### ISSUE TITLE
Проблема с ИИС Сбербанка

### ISSUE THREAD

**Issue by infouss05** [finsight/QUIKSharp#305]
Здравствуйте.
В первую очередь хочется поблагодарить за проделанную работу по написанию данного коннектора.
А во вторых обратиться за помощью.
Есть стандартная функция создания заявки в с# посредством библиотеки QUIKSharp.
long transactionID = (await _quik.Orders.SendMarketOrder(tool.ClassCode, tool.SecurityCode, tool.AccountID, ByOrSell, Lot).ConfigureAwait(false)).TransID
Проверено  через брокера ВТБ и БКС. Все отлично работает.
У меня проблема с созданием алгоритмической заявки на ИИС Сбербанка. Есть брокерский счет открытый в сбербанке и привязанный к нему счет ИИС. При создании заявки через брокерский счет указываю торговый счет "L01-00000F00"  либо tool.AccountID операция проходит без проблем. С операцией через ИИС не понятно что указывать. Использовал разные комбинации:
1. "L01-00000F00/123456"  - покупает с брокерского счета.
2. "123456" - ошибка неверный торговый код.
(123456 - счет ИИС)
Подскажите пожалуйста кто сталкивался и какой код на использовать для создания заявки через ИИС Сбербанка?
Где указать код клиента при создании заявки?
Дополнительно сообщаю, что при работе через Quik, при создании заявки надо выбирать торговый код (он всего один "L01-00000F00") и отдельно код клиента (если ИИС то  их 2).

**Comment by Pr0phet1c** [comment]
Можете сделать скриншот правильно заполненной заявки в терминале QUIK для покупки какой-либо бумаги на счет ИИС?

**Comment by infouss05** [comment]
[](url)
![image](https://user-images.githubusercontent.com/49754444/129515403-cabdf04f-28bb-4091-a994-9589cb682109.png)
![image](https://user-images.githubusercontent.com/49754444/129515460-27be201d-5ae4-43e7-b964-943863f269df.png)
Сам брокерский счет 400SJYJ, а ИИС S00SJYJ

**Comment by infouss05** [comment]
![image](https://user-images.githubusercontent.com/49754444/129515588-deeb1965-39e6-4cd3-9d90-eefa93f27080.png)
![image](https://user-images.githubusercontent.com/49754444/129515599-7303b8fa-8fac-4abe-8a26-f0e2324804df.png)
Еще пару скринов для понимания количества торговых счетов и кодов клиента.

**Comment by Pr0phet1c** [comment]
Никогда не работал в квике с таким большим количеством кодов клиента. К сожалению, на текущий момент у меня есть для Вас только один вариант решения: Вам придется реализовать собственную функцию формирования заявки.  Для начала, посмотрите как реализованы функции формирования заявок, и когда дойдете до метода "SendOrder", модифицируйте его таким образом, чтобы в экземпляр класса "Transaction", кроме текущих передавался параметр "CLIENT_CODE". Ну и протяните его передачу по цепочке вверх. Если будет время и возможность - я попробую модифицировать существующие функции, но не факт, что получится сделать оперативно.

**Comment by Pr0phet1c** [comment]
Еще один вариант: Можете попробовать реализовать отправку заявки через метод "CreateOrder".

**Comment by Pr0phet1c** [comment]
Удалось реализовать функционал оперативно. Как формировать заявку можно посмотреть в демо-приложении. Обновляйтесь и пользуйтесь. Дайте обратную связь после проверки, я тестировал на брокере с одним доступным кодом клиента.

**Comment by infouss05** [comment]
Обновляться через nuget? Там версия до сих пор 2.0.0

**Comment by Pr0phet1c** [comment]
Нет, скачайте свежие исходники. nuget пока не обновлял.

**Comment by infouss05** [comment]
![image](https://user-images.githubusercontent.com/49754444/129567134-66727c8e-92ef-4483-896d-57b4f6d1b1d6.png)
Выдает ошибку.
![image](https://user-images.githubusercontent.com/49754444/129567248-4820bc6f-716a-412a-b825-57c8175c9e17.png)

**Comment by infouss05** [comment]
![image](https://user-images.githubusercontent.com/49754444/129567549-8fc743a9-8ba8-4e2a-8fe3-f055e45e17b6.png)

**Comment by infouss05** [comment]
![image](https://user-images.githubusercontent.com/49754444/129572337-96294373-18a9-46ec-a1c1-a3a19deb32fb.png)

**Comment by infouss05** [comment]
Извиняюсь. Затупил. Не поменял компонент луа в Quik. Поэтому и выдавало ошибку. Загружаются коды клиента корректно. Заявки по счету ИИС тоже выставляются. Огромное спасибо за доработку.

**Comment by infouss05** [comment]
Еще вопрос. Не планируете обновить библиотеку в nuget? Мой проект написан в MS2015 через присоединение пакета QUIKSharp в виде длл.
