### ISSUE TITLE
Обработка ошибок от quik

### ISSUE THREAD

**Issue by serebrennikovvitaly** [finsight/QUIKSharp#316]
Подскажите как обработать ошибку от quik? После любой команды: SendLimitOrder, SendMarketOrder, отправляемых заведомо с ошибкой (например, мало денег или биржа закрыта или другие) - процесс останавливается с ожиданием ответа. 

При этом, quik сразу в сообщениях отдает ошибку, также ошибку вижу в TransReply, в том числе и текст ошибки. Но SendLimitOrder и SendMarketOrder зависают на неопереденный срок. 

Это воспроизводится и в тестовом примере, трассировка не идет дальше команды SendLimitOrder. И не получаю ни сам ордер (так как он не создан) и  исключения не возникает. Также TransID не известен, хотя в TransReply приходит.

Как решить этот вопрос?

![image](https://user-images.githubusercontent.com/16037699/143879868-114df6c3-b8a9-4390-a37f-7d46d0b43389.png)

**Comment by Pr0phet1c** [comment]
При сильном желании экспериментировать с передачей заведомо некорректных данных в терминал, лучше использовать базовый функционал QUIK, а не методы, являющиеся производными, которые созданы для облегчения/упрощения написания кода.
Под "базовым" функционалом, я подразумеваю функцию "SendTransaction". Справку по ее использованию можете подсмотреть в справке по QLua.

**Comment by serebrennikovvitaly** [comment]
Попробовал все-таки штатно решить, прошел дебаггером в движок QuikSharp.
Так вот, ошибка логическая в функции SendOrder!

После получения ошибки от квика, при попытке в строке 134 получить номер ордера через GetOrder_by_transID, order_result оказывается == null.

И далее, в строке 147 такого условия не находится и соответственно, set не становится = true и далее не выходит из бесконечного цикла в строке 128

Надо добавить такое условие в строку 147 

![image](https://user-images.githubusercontent.com/16037699/143904380-692affc1-ac25-4d99-8b08-b8fdea45ecbc.png)

**Comment by Pr0phet1c** [comment]
Если в 147 строке добавить установку set = true, при условии, что order_result  == null, то мы выйдем из цикла, без ошибки, т.е. будем считать, что заявка успешно выставлена.
Но суть проблемы я понял. Подумаю на досуге как лучше обыграть эту ситуацию.

**Comment by serebrennikovvitaly** [comment]
Решил примерно так:

1. Добавил флаг в переменную класса
![image](https://user-images.githubusercontent.com/16037699/143939112-45ff636b-2567-40a8-a316-e6f8d79b7350.png)

2. добавил в функцию GetOrder_by_transID выставление этого флага по окончанию выполнения
![image](https://user-images.githubusercontent.com/16037699/143939326-28b33eb9-69d8-4ccc-a62c-37cdcf001f7c.png)

3. Добавил в функцию SendOrder условие выход из цикла по флагу и возврат order_result, а также до-кучи order_result.TransID = res; перед выводом из SendOrder
![image](https://user-images.githubusercontent.com/16037699/143939929-d596e132-6f91-4440-b20c-e97e8ae59e95.png)

Если нужно, то приложил файл To-Be
[OrderFunctions.zip](https://github.com/finsight/QUIKSharp/files/7621016/OrderFunctions.zip)

**Comment by Pr0phet1c** [comment]
Не самое удачное решение. Цикл появился из-за того, что после отправки транзакции, может пройти некоторое время, прежде чем в терминале появится информация по заявке. Если считать, что при отсутствии информации после первого же запроса заявки нет, то будем сталкиваться с выставлением заявок, думая, что их нет. Помню, как в какой-то момент это привело к выставлению нескольких десятков заявок на покупку какой-то бумаги, в течении буквально нескольких секунд. Адреналина мне тогда хватило по самые уши. Нужно другое решение, но пока у меня нет возможности заняться этим вопросом.

**Comment by serebrennikovvitaly** [comment]
Предлагаю тогда такой вариант. На тесте работает (и выставляет заявки и возвращает ошибки).

1. Подписываемся на событие OnTransReply перед вызовом транзакции

![image](https://user-images.githubusercontent.com/16037699/144320070-f206a06d-a7d1-4e88-a1b7-5e7dc663d4d0.png)

2. В обработчике OnTransReply:
2.1. Получаем транзакцию из словаря
2.2. Если пришла нужная транзакция, то загоняем ошибку квика в transaction.ErrorMessage если код ошибки от квика не 0 (если код 0, то текст содержит что-то типа "заявка создана успешно"
2.3. Записываем обратно в словарь, теперь в словаре содержится текст тразакции

![image](https://user-images.githubusercontent.com/16037699/144320518-c3d92723-0cff-4e24-9d88-7dd2f62378b1.png)

3. Проверяем, если в словаре транзакции содержится текст ошибки, то создаем пустой ордер с текстом ошибки
![image](https://user-images.githubusercontent.com/16037699/144321304-d002cebc-406d-4951-9665-ea06457b7106.png)

4. Перед выходом отписываемся от колбэка, чистим словарь, возвращаем TransID
![image](https://user-images.githubusercontent.com/16037699/144321478-38e38070-10b3-47a9-8791-a6a156c2d2e2.png)

5. в SendTransaction запись в словарь ставим перед вызовом транзакции
![image](https://user-images.githubusercontent.com/16037699/144321846-3aa3163f-6fd5-4327-a560-a9cc6fbb3380.png)


[OrderFunctions.zip](https://github.com/finsight/QUIKSharp/files/7637427/OrderFunctions.zip)

**Comment by Pr0phet1c** [comment]
Приведите, пожалуйста, пример параметров заявки, при которых у Вас функция гарантированно уходила в бесконечный цикл. Я не уверен в оптимальности Вашего решения. По хорошему, ошибку отправки транзакции необходимо отлавливать в методе "SendTransaction", и дальше работать с полученным результатом. Желательно, без дополнительных подписок на события (если это возможно).

**Comment by serebrennikovvitaly** [comment]
например при закрытии биржи в выходные. Квик отдает ошибку - инструмент не торгуется. Или например если баланс с учетом покупки будет отрицательным. Уходит в бесконечный цикл даже на тестовых примерах из quiksharp

**Comment by Pr0phet1c** [comment]
В общем, в SendTransaction обработать эту ошибку не удается, т.к. по сути команда отправки транзакции считается успешно выполненной. Нашел у себя старую реализацию контроля подобных ошибок, в чуть более простом варианте, чем у Вас. 
Предварительное тестирование показало успешный результат.
После боевого тестирования (на реально работающем роботе, выставляющим не единичные заявки), выложу фикс.

**Comment by FocusPo1nt** [comment]
Тоже сталкивался, что иногда из-за некоректных данных от квика (неверное отображение позиции по инструменту или деньгам) после отправки заявки программа виснет. В терминале квика ошибки "превышена позиция по деньгам" и "запрет на операцию шорт". Буду благодарен, если выложите фикс

**Comment by Pr0phet1c** [comment]
Боевое тестирование в процессе. Скорее всего вечером будет фикс.

**Comment by Pr0phet1c** [comment]
Фикс выложил.

**Comment by FocusPo1nt** [comment]
Большое спасибо, буду тестировать

**Comment by serebrennikovvitaly** [comment]
Спасибо за патч, все работает! Можно закрывать тикет
