### ISSUE TITLE
Quik обновление 9.3

### ISSUE THREAD

**Issue by IFetisov** [finsight/QUIKSharp#318]
Если обновить Квик до версии 9.3.
Выскакивает ошибка:
   multiple Lua VMs detected. Expected 5.3 instead of 5.4
Не подскажете как поправить ?

**Comment by serebrennikovvitaly** [comment]
В quik выберете версию 5.3 в меню Сервисы/lua скрипты...

![image](https://user-images.githubusercontent.com/16037699/144319630-05c9a8eb-c34f-42c9-82c9-233dfd0611f5.png)

**Comment by IFetisov** [comment]
Спасибо
