### ISSUE TITLE
Раздвоение заявки

### ISSUE THREAD

**Issue by Gitel3** [finsight/QUIKSharp#322]
Здравствуйте! 
Подписался на событие onQuote, при соблюдении определенных условий по цене отправляю заявку через _quik.Orders.SendLimitOrder(). Сегодня при передаче параметра в 27 контрактов, в терминал в одно и то же время пришло 2 заявки на 26 контракт и на 1 контракт. Все бы ничего, но я дальше отслеживаю поданную заявку по номеру, полученному при ее выставлении, а у выставленных заявок было два разных номера. В первый раз такое, раньше всегда была одна заявка. Подскажите, разделение одной заявки на две это нормальное поведение терминала?

**Comment by Pr0phet1c** [comment]
Да, такая ситуация вполне возможна.
Для того, чтобы избежать подобных ситуаций, при работе с событиями, я обычно применяют примерно такой подход:

private void Events_OnQuote(OrderBook orderBook)
{
    if (i == 1) && !ignoreCall
    {
        ignoreCall = true;
        qt = _quik.Trading.CalcBuySell(tool.ClassCode, secCode, tool.СlientCode, AccountID, (double)(tool.LastPrice + protect), true, false).Result.Qty - 1;
        orderOpenLong1 = _quik.Orders.SendLimitOrder(tool.ClassCode, secCode, AccountID, Operation.Buy, tool.LastPrice + protect, qt).Result.OrderNum;
        i = 0;
        ignoreCall = false;
    }
}

**Comment by Gitel3** [comment]
Ок, интересный подход, спасибо за совет!
