### ISSUE TITLE
Не могу подключиться к удаленному терминалу

### ISSUE THREAD

**Issue by iza88** [finsight/QUIKSharp#323]
Изменил эти 127.0.0.1 на IP компьютера, на котором крутится lua скрипт
![image](https://user-images.githubusercontent.com/14890699/160293709-0ef17c71-93e7-4430-b14e-165bb2d7b815.png)
С удаленной машины telnet с указанием порта проходит, а клиент C# всё равно не коннектится

**Comment by Pr0phet1c** [comment]
Демо-приложение не пытались изучить?
