### ISSUE TITLE
Сбой подтверждения в QuikSharp.Transaction.OnTransReplyCall

### ISSUE THREAD

**Issue by Pr0phet1c** [finsight/QuikSharp#33]
Снова столкнулся с проблемой, решение которой мне не удается найти самостоятельно.
Итак, есть робот (WinForms), который на текущий момент работает в режиме онлайн-теста (т.е. совершает виртуальные сделки, не отправляя реальных заявок на сервер).
Параллельно работает другой робот (на QLua), который торгует в реале совершенно другим инструментом.
Так вот, когда QLua-робот выставляет заявку в квике, то в тестовом QuikSharp-роботе возникает ошибка, которая полностью останавливает работу робота, и в ряде случаев может создавать дополнительные проблемы.
На экране получаю вот  такое окно:
![error ontransreplycall](https://cloud.githubusercontent.com/assets/14761254/11060300/456052c0-87b0-11e5-97e5-9fc56c0c8f41.jpg)
В режиме отладки обратил внимание, что появление таких заявок в QuikSharp распознается как  некий "fakeTrans", но зачем, и что мне с этим делать я так и не понял.
Можно ли узнать как мне избежать появление указанной ошибки?
Ведь этого робота, по идее, не должно волновать что делается в квике с другими инструментами.
Может надо какую-нибудь "заглушку" сделать? Или может быть я не понял заложенного в QuikSharp принципа работы с этими колбэками?
Просьба помочь, если есть такая возможность.

**Comment by buybackoff** [comment]
Робота не может не волновать, по идее, так как любые сделки влияют на состояние денег. Там довольно просто игнорировать любые сделки, совершенные вне QuikSharp, просто убрав нужные Debug.Assert. Сейчас код ищет TransactionId среди тех, которые отправил, и если видит незнакомую транзакцию - ругается.

**Comment by Pr0phet1c** [comment]
Спасибо за разъяснение. Просто привык, что в Qlua я могу тупо игнорировать ненужные мне колбэки.
Не трогая Debug.Assert в коде QuikSharp, могу ли я каким-то образом "обойти" эту ситуацию в коде моего робота, чтобы робот не останавливал из-за этого свою работу?

З.Ы.: Кстати, форк я создал, но видимо как-то криво, и выглядит он сейчас не привязанным к основной ветке разработки. Как результат - не могу слать Pull Raquest. Однако пояснения к своим изменениям я сделал, и если есть желание (и возможность) перенести реализованные функции в проект, то все там.

**Comment by buybackoff** [comment]
Я перенес проект в организацию, может быть поэтому отвязался от ветки
визуально. Debug.Assert - это даже не ошибка, там можно нажать
"игнорировать" и программа продолжит, или запустить в Release mode.
По-другому кроме как убрать эту строку даже не знаю. Ведь если мы не нашли
ИД транзакции и знаем, что такое может быть, то такую ситуации надо просто
игнорировать. Assert был чтобы убедиться, что мы всегда ловим отосланные
транзакции.

2015-11-10 16:16 GMT+03:00 Prophetic <notifications@github.com>:

**Comment by Pr0phet1c** [comment]
По форку: Нет, это не из-за переноса. Я изначально что-то неправильно сделал (первый раз в жизни делал). Надо будет на досуге попробовать форк от последней версии сделать, и заново попытаться прикрутить туда все, что я успел написать.
По роботу: Понял. Спасибо. Попробую действительно Release скомпилить.
Что касается отлова отосланных транзакций, то в целом я конечно согласен с таким подходом, но только если эти транзакции были инициированы данной программой. У меня на фонде часть сделок роботы осуществляют, а часть руками выполняется. Специальный робот на Qlua отслеживает такие трейды, и не ругается, а просто записывает их в общий лог (вместе с трейдами роботов) с пометкой "Hand" (типа сделка осуществленная руками).
Т.е. с одной стороны мы отлавливаем появление  "неизвестных" сделок, а с другой - их появление не нарушает работу десятка других ботов.

**Comment by Pr0phet1c** [comment]
Похоже, без посторонней помощи мне не обойтись :(
Компиляция релиза не помогла. Дальнейшие эксперименты, также ни к чему хорошему не привели.
Последнее, что попытался сделать, это добавил в internal void OnTransReplyCall(TransactionReply reply), в классе QuikEvents, формирование фейковой транзакции:
````
        internal void OnTransReplyCall(TransactionReply reply) {
            if (OnTransReply != null) OnTransReply(reply);
            // invoke event specific for the transaction

            string correlationId = reply.Comment;
            #region Totally untested code or handling manual transactions
            if (!QuikService.Storage.Contains(correlationId))
            {
                correlationId = "manual:" + reply.OrderNum + ":" + correlationId;
                var fakeTrans = new Transaction()
                {
                    Comment = correlationId,
                    IsManual = true,
                    SECCODE = reply.SecCode,
                    CLASSCODE = reply.ClassCode,
                    ACCOUNT = reply.Account,
                    CLIENT_CODE = reply.ClientCode,
                    FIRM_ID = reply.FirmID,
                    PRICE = (decimal)reply.Price,
                    QUANTITY = (int)reply.Quantity,
                    TRANS_ID = reply.TransID,
                    TransactionReply = reply
                    
                    // TODO map order properties back to transaction
                    // ideally, make C# property names consistent (Lua names are set as JSON.NET properties via an attribute)
                };
                QuikService.Storage.Set<Transaction>(correlationId, fakeTrans);
            }
            #endregion

            var tr = QuikService.Storage.Get<Transaction>(reply.Comment);
            if (tr != null)
            {
                lock (tr)
                {
                    tr.OnTransReplyCall(reply);
                    // persist transaction with added reply
                    QuikService.Storage.Set(reply.Comment, tr);
                }
            }
            Trace.Assert(tr != null, "Transaction must exist in persistent storage until it is completed and its reply is recieved");
        }
````
но в процессе работы, как только я вручную отправляю или убиваю заявку в квике, то "выпадаем" вот сюда:
````
        internal void OnTransReplyCall(TransactionReply reply) {
            if (OnTransReply != null) { OnTransReply(reply); }
            // this should happen only once per transaction id
            Trace.Assert(TransactionReply == null);
            TransactionReply = reply;
        }
````
Если после этого продолжить работу, то робот уже никуда не вываливается, но и вообще перестает реагировать на какие-либо события. А в ряде случаев ситуация доходила до зависания квика (с 99% загрузкой процессора), и как следствие нарушение работы "боевых" роботов Qlua. Главное, я не могу понять из-за чего возникает такая проблема.
В общем, получается, что если я хочу использовать для каких-либо целей QuikSharp, то мне запрещается выполнять торговые операции вне QS. IMHO это никуда не годится.

Какие еще есть способы безопасно продолжить работу (включая внесение изменений в QuikSharp), если заявка была сформирована не в QuikSharp`е?
Может я изначально не там копаю?

**Comment by buybackoff** [comment]
Закомментить эту строчку:  Trace.Assert(tr != null, "Transaction must exist
in persistent storage until it is completed and its reply is recieved");
Trace работает в релизе тоже. Я думал там Debug.Assert.

2015-11-12 11:14 GMT+03:00 Prophetic <notifications@github.com>:

**Comment by Pr0phet1c** [comment]
Пробовал закомментить (просто забыл об этом написать). Результат тот же. Робот продолжит работать, но с этого момента не реагирует на события. Если точнее, то по колбэку OnParam, робот обновляет цену последней сделки в форме, но после транзакции обновление больше не выполняется. Возможно, робот (или QuikSharp) уходит в какой-то цикл, но я не могу понять в какой и где.
Заметил такую штуку:
в режиме отладки, вот тут: internal void OnTransReplyCall(TransactionReply reply)
при наведении на reply студия не может вывести значения полей, ссылаясь на то, что код оптимизирован. Это никак не могло повлиять на дальнейшие события?
И на сколько корректно я поступил, попытавшись записать в хранилище фейковую транзакцию? Может мне не стоило этого делать?

**Comment by buybackoff** [comment]
хранилище если сами не используете лучше отключить совсем. сорри, сейчас не
могу глубже в этот вопрос копать. будем пока считать задокументированным
багом, что сторонние транзакции выбивают из нормальной работы QS.

2015-11-12 12:47 GMT+03:00 Prophetic <notifications@github.com>:

**Comment by Pr0phet1c** [comment]
ОК. Принято. Буду ждать (может и сам что-нибудь придумаю)
Я и не знал, что использование хранилища можно отключить.
Если не трудно (и если это не отнимет много времени) - подскажите как это сделать.

**Comment by buybackoff** [comment]
Просто закомментить все с ним связанное.

2015-11-12 14:17 GMT+03:00 Prophetic <notifications@github.com>:

**Comment by Pr0phet1c** [comment]
Понятно. Спасибо.

**Comment by nubick** [comment]
Добавлю, что хранилище и правда работает очень не стабильно. Я просто весь связанный с ним код прячу комментариями. Предлагаю эту часть функционала либо удалить либо вынести и подключать по требованию, чтобы по умолчанию её не было. А то может она много вопросов вызвать у начинающих.

**Comment by buybackoff** [comment]
Надо сделать интерфейс и по умолчанию in-memory, а потом любую реализацию
через dependency injection. Все же иметь удобный доступ ко всем
транзакциям/ордерам/сделкам правильно, учитывая что в Квике только на
сегодня и методы чтобы их достать не были реализованы.


2015-11-12 15:02 GMT+03:00 Oleg Andrushko <notifications@github.com>:

**Comment by SkyN** [comment]
На мой взгляд, по умолчанию должна работать интеграция, и работать стабильно. Т.е. чтобы новичок включил, и у него заработало.
Хранение - дополнительная плюшка, и надо, чтобы пользователь включал её осознанно, понимая, что ещё и файлы будут создаваться. А то может получиться монстр, у которого много всего есть, но чтобы его запустить надо проделать немалый труд.

**Comment by SkyN** [comment]
И по поводу Trace.Assert, я бы предпочёл отказаться от них совсем, заменив на исключения и Trace.WriteLine.
Исключения, можно хоть как-то перехватывать. Trace.Assert остановит всё, рынок скачет, а я в этот момент отошёл от робота за хлебом.

**Comment by buybackoff** [comment]
Assert имеет четкую смысловую нагрузку и равнозначен выкидыванию ошибки.
Просто с ним удобнее дебагить.

Мне изначально хранилище было зачем-то очень нужно, даже для ручных сделок.
Поэтому оно изначально было, хотя очень быстро перестало быть нужным.
Совсем выпиливать его я бы не стал.

Обмен сообщениями, стаканы и котировки, да и даже отслыка заявок, работают
супер надежно и просто. Тут косячок с логикой, сразу вспоминается issue #7
:)


2015-11-12 16:07 GMT+03:00 SkyN <notifications@github.com>:

**Comment by Pr0phet1c** [comment]
Мое мнение, как не профессионала, вряд ли имеет большой вес, но все же я тоже склоняюсь к варианту осознанного подключения хранилища (в случае возникновения такой необходимости у пользователя). У меня эти части кода действительно вызывают массу вопросов, но это еще пол беды.
Дело в том, что я своих роботов храню в DropBox, и запускаю оттуда же. Так вот, когда я запускаю робота на QS, то в папке PersistentStorage происходит постоянная запись в файлы, что в свою очередь приводит к нескончаемой синхронизации DropBox`а, мешая выполнять синхронизацию других важных файлов.
Господа, SkyN и nubick, т.к. buybackoff сейчас не имеет возможности разобраться с возникшей проблемкой, может вы могли бы мне подсказать вариант решения задачки?
Эта беда просто выбила меня из колеи. У меня работают боевые роботы на QLua, и полностью их останавливать на время разработки робота на QS я не могу себе позволить. Я прям расстроился весь... :(

**Comment by buybackoff** [comment]
Без PersistentStorage ничего не будет работать. Но Quik() принимает необязательный параметр - имплементацию этого хранилища. [Ничего не мешает вам сделать свою имплементацию](https://en.wikipedia.org/wiki/Dependency_injection) на основе Dictionary<> в памяти или даже на основе какой-нибудь базы данных типа MySQL.

Я сделал InMemoryStorage и он теперь по умолчанию. Старое хранилище доступно и его можно передать конструктору.

**Comment by buybackoff** [comment]
Хотя нет, я передумал. Слишком резкое изменение. Кому не нужен перманентный сторадж на диске, пусть создают класс Квик так: ` new Quik(port, new InMemoryStorage())`.

Закоментил места, где ручные заявки могли вешать систему. Не тестировал, протестируйте пожалуйста!

**Comment by buybackoff** [comment]
@Pr0phet1c  закройте плиз этот issue, если все заработает

**Comment by buybackoff** [comment]
У старого хранилища можно изменить папку https://github.com/finsight/QuikSharp/blob/master/src/QuikSharp/IPersistentStorage.cs#L35

**Comment by Pr0phet1c** [comment]
Ура! Заработало. Огромное спасибо за то, что смогли выделить время на решение данной проблемки.

**Comment by buybackoff** [comment]
Не за что! Не так уж много времени ушло, чтобы поломать и закомментить. Но логика все равно кривая сейчас.

**Comment by Pr0phet1c** [comment]
Ну, вообще-то Вы не только проблему сбоя решили (хотя, должен признаться, что и в своем роботе обнаружил небольшой косяк, который тоже мог влиять на ситуацию), но еще и реализовали возможность переместить хранилище с диска в оперативную память, что не может не радовать. Так что благодарность весьма уместна  :)

**Comment by manter84** [comment]
Данная ошибка тоже стала вылазить при выставлении сразу двух стоп-ордеров в которых указывал код клиента (если код клиента не указывать, удалив поле Client_Code в StopOrderFunctions, то проблем нет, но ВТБ такие заявки без кода клиента не принимает). Удалось решить ее при установке задержки по времени между первым и вторым ордером (время поставил 300 мс).
