### ISSUE TITLE
quik.Service.IsConnected().Result

### ISSUE THREAD

**Issue by KonstantinReim** [finsight/QUIKSharp#335]
Данную статью читал https://github.com/finsight/QUIKSharp/issues/153?ysclid=l9t0eprxws759249925, рекомендации выполнил, свой вопрос частично закрыл, но все же осталось одно но. Квик работает, QuikSharp работает, соединение есть - запускаю свое приложение C#, проходим вот сюда
private void ConnectedOnOff()
        {
            if (quik != null && quik.Service.IsConnected().Result)
                Connected = true;
        }
выходим все работает - все красиво все хорошо - класс! Отключаю соединение - включаю соединение - все отлично работает! Выключаю QuikSharp - включаю QuikSharp - заходим в if (quik != null && quik.Service.IsConnected().Result)
проходим по дебагеру в библиотеку QuikSharp и из нее больше не выходим. Перезапуск приложения C# - все работает.

**Comment by Pr0phet1c** [comment]
Не знаю, что именно Вы подразумеваете под выключением QuikSharp, но если речь идет об остановке скрипта в терминале, при запущенном приложении C# и установленном соединении (quik != null), то не вижу ничего удивительного. Так делать не надо.
