### ISSUE TITLE
trade.Flags

### ISSUE THREAD

**Issue by KonstantinReim** [finsight/QUIKSharp#337]
`private void Events_OnTrade(Trade trade)
{
    if (trade.Flags == OrderTradeFlags.IsSell) // Сделка Sell // TODO для фьюча не работает
    {
    }
    else // Сделка Buy
    {
    }
}
`
сделка селл на фьюче, а trade.Flags не IsSell

**Comment by KonstantinReim** [comment]
Прежде чем задать вопрос я проверяю и перепроверяю по 100500 раз!
Да я удивлен что библиотека классная, но вот что то пошло не так.
Проверяю на Демо Квик 10.0.1.18
Для акций все работает отлично, для фьючей нет и это факт!!!
Может на реале все будет хорошо - не проверял.

**Comment by Pr0phet1c** [comment]
У меня видимо проблемы с русским языком. Попробую перефразировать:
Посмотрите в демке, как организована работа с этими флагами, и сравните с тем, как это делаете Вы.

**Comment by KonstantinReim** [comment]
trade.Flags.HasFlag(OrderTradeFlags.IsSell)
