### ISSUE TITLE
Примите ли пулриквест? Только актуальное состояние заявки в транзакции.

### ISSUE THREAD

**Issue by SkyN** [finsight/QuikSharp#34]
Планирую изменения, вопрос в том, реализовывать ли их в QuikSharp, и будут ли они приняты в мастер ветку? Или делать локально у себя, и не тревожить QuikSharp?

1) Из Transaction убирается список Orders. Вместо него добавляется два свойства Order и Order2.
Зачем: насколько я понимаю не бывает транзакций, которые сгенерировали бы больше 2х заявок. 99% транзакций генерят 0 или одну заявку, и только MOVE_ORDER может создать две.
Т.е. для доступа к заявке по транзакции будет достаточно получить свойство Transaction.Order.

2) Order начинает реализовать интерфейс INotifyPropertyChanged, т.е. на сообщение из Quik о заявки, находим транзакцию, и если у транзакции Order или Order2 уже заполнен заявкой с таким же номером, то просто меняем свойства у существующей в транзакции заявке, а не добавляем новую.

3) Отмену заявки делаем в классе Order

**Comment by SkyN** [comment]
4) Событие onOrder на Transaction будет вызываться только для новой заявки. Т.е. в случае транзакции NEW_ORDER, оно будет вызывать только один раз.
На изменение заявки, будет вызываться событие интерфейса INotifyPropertyChanged (пункт 2).

**Comment by SkyN** [comment]
в общем, дожидаясь разрешения, начал менять QuikSharp. Остановите меня, если я не прав :)
Предполагается, что OnOrderCall будет выглядеть так:

        internal void OnOrderCall(Order order) {
            // Первое сообщение о заявке, по данной транзакции
            if (Order == null) {
                Order = order;
                if (OnOrder != null)  OnOrder(order);
                return;
            }
            // Повторные сообщения по тойже заявке, похоже, что заявка изменилась
            if (Order.OrderNum == order.OrderNum) {
                Order.Change(order);
                return;
            }            
            // По транзакции пришла вторая заявке
            if (ACTION != TransactionAction.MOVE_ORDERS) 
                Trace.TraceError("Для "+ ACTION + " транзакции пришло более одной заявки");
            // всё, нормально, это была MOVE_ORDERS, можно сохранить информацию о заявке
            if (Order2 == null)
            {
                Order2 = order;
                if (OnOrder != null) { OnOrder(order); }
                return;
            }
            // У меня уже была сохранена заявка с таким номером, т.е. произошло изменение заявки
            if (Order2.OrderNum == order.OrderNum) {
                Order2.Change(order);
                return;
            }
            
            Trace.TraceError("Для MOVE_ORDERS транзакции пришло более двух заявок");
        }
        /// <summary>
        /// Cоздаваемая заявка, например, при транзакции NEW_ORDER
        /// </summary>
        Order Order { get; set; }
        /// <summary>
        /// В транзакции MOVE_ORDER может быть созданно две заявки
        /// Какая из них попадет в Order, а какая в Order2 не гарантируется
        /// </summary>
        Order Order2 { get; set; }

**Comment by SkyN** [comment]
Приблизительно следующее добавиться в класс Order:

        /// <summary>
        /// Свойства, которые проверяются на изменения в методе Change
        /// </summary>
        static readonly string[] propertyForChange = { "Balance", "Datetime", "Flags", "Value", "WithdrawDatetime", "Yield", "RepoValueBalance", "RejectReason", "LuaTimeStamp" };
        /// <summary>
        /// Проверяет, отличаются ли у переданного объекта свойства из списка propertyForChange
        /// И если отличаются, то присваивает значения свойства своему свойству с таким же именем, и вызывает event PropertyChanged
        /// </summary>
        /// <param name="newOrder"></param>
        internal void Change(Order newOrder)
        {
            if (newOrder == null) return;
            if (newOrder == this) return;
            if (newOrder.OrderNum != OrderNum) { Trace.TraceWarning("не могу обновить свойства из заявки с другим номером"); }

            Type type = this.GetType();
            foreach (string prop in propertyForChange)
            {
                object thisValue = type.GetProperty(prop).GetValue(this, null);
                object newOrderValue = type.GetProperty(prop).GetValue(newOrder, null);

                if (thisValue != newOrderValue && (thisValue == null || !thisValue.Equals(newOrderValue)))
                {
                    type.GetProperty(prop).SetValue(this, newOrderValue);
                    PropertyChangedEventHandler handler = PropertyChanged;
                    if (handler != null)
                        handler(this, new PropertyChangedEventArgs(prop));
                }
            }
        }
        /// <summary>
        /// Возникает при изменении значения свойства, вызывается только если изменения зафиксированы в методе Change
        /// </summary>
        public event PropertyChangedEventHandler PropertyChanged;


на следующей неделе потестирую, и если всё ок, и в этом issues реакции не будет, то отправлю пулреквест.

**Comment by buybackoff** [comment]
1,4
нет, потому что в общем случае ордеров может быть N, так как присылаются обновления по ордерам. Например, выставили лимитную заявку на покупку 100 неликвидных опционов. Может быть ситуация, когда нам 100 раз продали по одному опциону в течение дня. Не помню, присылает ли Квик именно обновления ордера в таком случае, вроде бы да. Могут быть и другие случаи. У Транзака такая же модель - присылается обновление Order если там что-то меняется.

Название Order**2** уже говорит, что что-то не так с дизайном. Если вы уверены, что их две, нет ничего сложного получить первую и вторую по `Transaction.Orders[0], Transaction.Orders[1]`, даже печатать не нужно сильно больше, чем в случае `.Order2`

2. Вы можете подключить библиотеку Rx.NET и создать IObservable из события OnOrder. 

3. Пахнет ООП. Я предпочитаю думать о транзакциях и ордерах как сообщениях. Отмена ордера - это еще одно сообщение. Сообщение не может ничего делать само, оно по смыслу DTO (data transfer object). Можно сделать специальную функцию, которая принимает номер заявки и отправляет команду на ее отмену. Эту функцию можно сделать как extension method. Как метод на объекте Order это не нужно, захламляет интерфейс и не добаляет ничего, что нельзя было бы добиться с extension методом.

**Comment by SkyN** [comment]
Ок, значит буду делать дополнительный слой непосредственно в роботе.
Я исходил из предположения, что передается заявка, а дальнейшие сообщения по ней, это её обновление (т.е. как ведет себя таблица заявок). Если же считать, что хранятся все сообщения о заявках, то да, всё правильно. Но сложнее получить текущий срез по заявкам.
