### ISSUE TITLE
Events_OnTransReply и Transaction

### ISSUE THREAD

**Issue by KonstantinReim** [finsight/QUIKSharp#341]
Здравствуйте.
private void Events_OnTransReply(TransactionReply transReply)
{
   ...
   id == transReply.TransID
   ...
}
private static async Task Transaction(...)
{
   ...
   decimal res = await quik!.Trading.SendTransaction(newOrderTransaction).ConfigureAwait(false); // Отправляет транзакцию
   ...
}
Вопрос - может ли случиться так, что в Events_OnTransReply(...) ответ на транзакцию уже поступил, а в res = await quik!.Trading.SendTransaction(newOrderTransaction).ConfigureAwait(false); ответ ЕЩЕ не поступил?

**Comment by Pr0phet1c** [comment]
Конкретно по данной ситуации сейчас не смогу дать однозначного ответа, но раньше неоднократно обсуждались случаи рассинхронизации событий в Квике.
Вывод: Я не сильно удивлюсь, если описанная Вами ситуация окажется реальностью. Однако, я уже очень дано не сталкивался с проблемами размещения и идентификации заявок. Странно, что Вы копаете так глубоко, когда есть отлаженная функция, которая исправно работает уже не один год.
В демках есть примеры выставления заявок, которые прекрасно работают. Вам точно необходимо изобрести свой велосипед?
