### ISSUE TITLE
как получить размер плеча по инструменту (DLong) через QuikSharp?

### ISSUE THREAD

**Issue by ildarskii** [finsight/QUIKSharp#344]
Согласно документации [Quik Lua](https://luaq.ru/getBuySellInfo.html) значение плеча можно получить с помощью функции getBuySellInfo() через поле long_coef. 

В реализации QuikSharp в классе [TradingFunctions](https://github.com/finsight/QUIKSharp/blob/master/src/QuikSharp/TradingFunctions/TradingFunctions.cs) функция getBuySellInfo() отсутствует (она закомментирована).

Подскажите, как можно получить значение плеча по инструменту в библиотеке QuikSharp?

**Comment by Pr0phet1c** [comment]
Эта функция на данный момент действительно не реализована. ЕСли будет время - постараюсь реализовать.
Как сейчас можно получить эту информацию в Q# к сожалению не знаю.

**Comment by Pr0phet1c** [comment]
Готово. Пользуйтесь

**Comment by ildarskii** [comment]
Функции GetBuySellInfo и GetBuySellInfoEx появились в библиотеке, спасибо.
Но при их вызове ничего не возвращается и код зависает в бесконечном ожидании. 
Остальные функции вроде GetParamEx работают хорошо...

**Comment by bak19** [comment]
Попробуйте перезагрузиться, чтоб изменение qsfunctions.lua прошло
У меня все работает. Спасибо

**Comment by ildarskii** [comment]
А попробуйте запустить для акций ВТБ функцию GetBuySellInfo(Firmid, clientCode, "TQBR", "VTBR", 0). 
У меня возвращает пустые значения (отсутствие плеча):
DLong = null, DShort = null, LongCoef = "1.000000"
Тогда как в таблице Квик вижу DLong = 0.4, DShort = 0.37


При этом если вызвать с другими параметрами GetBuySellInfo(Firmid, clientCode, "INSTR", "RUR_2", 0).  (такой инструмент и класс тоже есть в справочнике квик, что бы он ни значил), то программа зависает. 
А функция GetBuySellInfoEx(..) зависает даже если запросить по ВТБ.
Было бы разумным возвращать управление назад с кодом ошибки, без зависания.

**Comment by bak19** [comment]
GetBuySellInfo не возвращает DLong, DShort. Тут все правильно

DLong, DShort возвращает функция GetBuySellInfoEx(..)
Чтобы она заработала, нужно слегка подкорректировать файл src/QuikSharp/DataStructures/BuySellInfo.cs

` /// <summary>
        /// Срок расчётов. Возможные значения: положительные целые числа, начиная с «0», соответствующие срокам расчётов из таблицы «Позиции по инструментам»: «0» – T0, «1» – T1, «2» – T2 и т.д.
        /// </summary>
        [JsonProperty("limit_kind")]
        public int LimitKind { get; set; }
`
public int LimitKind { get; set; } поменяйте на public string LimitKind { get; set; } 
После этого должно заработать

**Comment by ildarskii** [comment]
Да, так заработало. Включите исправление в master версию?

И по второй технической проблеме зависания. 
Если запрашиваемый инструмент отсутствует в таблице "Купить/Продать" (у меня там всего 150 инструментов, тогда как в Квик их около 37 тыс.шт.), тогда функции GetBuySellInfo и GetBuySellInfoEx зависают. Так как заранее неизвестно, входит ли инструмент в таблицу, то приложение всегда будет зависать. 
Было бы правильно завершить работу функции с возвратом соотв. статуса или значениями по умолчанию. 
Подскажите где и что исправить?

**Comment by bak19** [comment]
Внести сам правки не смогу, т.к. не разработчик библиотеки.

По второму вопросу, попробуйте отредактировать таблицу "купить/продать" средствами самого quikа. Добавьте в нее все инструменты с которыми работаете или планируете работать. Возможно это и будет решением.

**Comment by ildarskii** [comment]
Добавление в таблицу квик инструментов не помогло, все равно зависает на них. 
Плюс нужно системное решение, т.к. набор инструментов и значение плеча по ним динамически меняются. 

Проблему с зависанием решил через асинхронные запросы. Вложенный Task нужен, чтобы не было блокирующего ожидания. 

`
                    var t = new Task(() =>
                    {
                        // этот запрос может привести к зависанию приложения если не асинхронный запрос
                        var task = Task.Run(() => QuikLua.Trading.GetBuySellInfoEx(Firmid, clientCode, classCode, secCode, 0)); 

                        if (task.Wait(100)) // если не завис запрос
                        {
                            DLong = task.Result.DLong;

                            Console.WriteLine($"{DLong}");
                        }
                    });
                    t.Start();

`

**Comment by ildarskii** [comment]
Кстати, столкнулся с неожиданным поведением библиотеки QuikSharp - она не совместима с официальной последней версией пакета Newton.Json 13.0.3, хотя в настройках QuikSharp это не указано. 
Было бы правильным прописать в настройках несовместимость.

**Comment by ildarskii** [comment]
С учетом вышесказанного, изначальная проблема решена. Спасибо.
