### ISSUE TITLE
NET6, NET7

### ISSUE THREAD

**Issue by BizzzziB** [finsight/QUIKSharp#345]
При попытке подключить библиотеку к проекту разрабатываемому для NET6 или 7, при создании объекта Quik происходит зависание в QuikService на строке 904:  response = await tcs.Task.ConfigureAwait(false); 

try
{
    **response = await tcs.Task.ConfigureAwait(false);**
}

Пробовал брать из NuGet, перекомпилировать библиотеку под net6-windows, net7-windows. Не помогает. Подскажите что можно сделать?

**Comment by atlazar** [comment]
У меня была такая проблема, насколько я помню помогло собрать библиотеку именно под .NET Framework и использовать в .NET Framework проекте. .NET core не работало, вроде как из-за того, что либы не копировались внутрь библиотеки.
