### ISSUE TITLE
Замена Newtonsoft.Json на System.Text.Json

### ISSUE THREAD

**Issue by dnmsk** [finsight/QUIKSharp#348]
Добрый день.
Есть возможность заменить json сериалайзер на стандартный .net core. Соответственно изменится фреймворк с net461;netstandard2.0 на .net6+.
Это даст 2х+ прирост к производительности в парсинге сообщений из луа.

Создам PR если одобрите идею.

**Comment by Pr0phet1c** [comment]
@buybackoff , спасибо за комментарий. Тогда не будем рисковать. Стабильность, на мой взгляд важнее, в данном случае.
@dnmsk , за предложение спасибо, но пока воздержимся.

**Comment by buybackoff** [comment]
В добавок, классно если что-то может работать на допотопной версии винды и .NET 4.x. Многие пользователи даже наверное не задумываются о версиях .NET. 

Форсировать предпоследние версии не стоит. Через полтора месяца будет .NET v8 LTS и тоже сильно быстрее во многих аспектах. Но Квик такой медленный сам и latency через интернет, все микро-оптиммзации не имеют смысла. Все и так в десятки раз быстрее, чем если бы это всё было на Питоне например.

**Comment by Pr0phet1c** [comment]
@buybackoff , согласен.
