### ISSUE TITLE
не понятно, зачем нужна Transaction.IsComepleted

### ISSUE THREAD

**Issue by SkyN** [finsight/QuikSharp#35]
она возвращает true, если последнее сообщение о заявках по транзакции было о том, что заявка не активна и не отменена. Т.е., видимо, предполагается, что заявка исполнилась полностью.

Но если транзакция была MOVE_ORDER с двумя заявками, и исполнилась только одна?
А если исполнилась только частично?
А если транзакция было об отмене заявки, то текущий метод "Транзакция исполнена" не вернет True никогда.

Да и вообще, какое дело транзакции, о заявке созданной по ней. Предлагаю удалить эту функцию, чтобы некого не смущать. На заявке есть свойство State. А вообще я предпочитаю сравнивать значения Balance и Quantity :), так проще, т.к. одинаковый алгоритм для частично и полностью исполнившихся заявок.

**Comment by Pr0phet1c** [comment]
Мне это конечно не мешает (просто не использую), но я тоже дожидаюсь когда заявка теряет статус "Active", после чего сравниваю Balance и Quantity.

**Comment by buybackoff** [comment]
я уже не помню зачем. она вам мешает?

**Comment by SkyN** [comment]
ну кроме того, что у неё не правильная логика, больше никак не мешает. Пользоваться ей нельзя.
