### ISSUE TITLE
не завершается задача GetOrder_by_transID

### ISSUE THREAD

**Issue by Olddead91** [finsight/QUIKSharp#356]
function qsfunctions.getOrder_by_ID(msg)
	if msg.data ~= "" then
		local spl = split(msg.data, "|")
		class_code, sec_code, trans_id = spl[1], spl[2], spl[3]
	end

	local order_num = 0
	local res
	for i = 0, getNumberOf("orders") - 1 do
		local order = getItem("orders", i)
		if order.class_code == class_code and order.sec_code == sec_code and order.trans_id == tonumber(trans_id) and order.order_num > order_num then
			order_num = order.order_num
			res = order
		end
	end
	msg.data = res
	return msg
end

В случае, если передается не существующий  transID (например id по вчерашней заявке) - local res так и остается в неопределенном состоянии и задача висит и не возвращает результат.  
Возможно такое или причина в чем-то другом?

**Comment by Olddead91** [comment]
Аналогичная проблема и с GetOrder_by_Number. Сталкиваюсь с ней на Демо-Квике, во время проверки вчерашних неучтеных сделок. Ниже представлен код, который нормально обрабатывает отсутствие заявок в таблице

//if (_mode != "TransID") ord = quikInstance.Orders.GetOrder_by_Number(_id).Result; // TODO висит если не может найти ордер
 //else ord = quikInstance.Orders.GetOrder_by_transID(strSecParam.Class, strSecParam.Sec, _id).Result; 
               
                Order? ord = null;
                List<Order> orders = quikInstance.Orders.GetOrders(strSecParam.Class, strSecParam.Sec).Result;
                if (orders != null && orders.Count > 0)
                {
                    foreach (Order order in orders)
                    {
                        if (_mode != "TransID")
                        {
                            if (order.OrderNum == _id) ord = order; // обязательно пройти весь список иначе глючит, что не находит заявку
                        }
                        else
                        {
                            if (order.TransID == _id) ord = order; 
                        }
                    }
                }
                else return null;
                return ord;

**Comment by Pr0phet1c** [comment]
1. Несколько странно, что с этой ошибкой сталкиваетесь только Вы. Но могу предположить, что никто больше не пытается получить данные по заявкам предыдущих дней, т.к. по понятным причинам их там не будет.
2. Указанный Вами код Lua по сути читается так: Перебираем в квике всю таллицу заявок, и каждую заявку в ней сравниваем по трем параметрам, с переданными значениями. Если удалось найти заявку, в которой все три параметра совпали - записываем заявку в переменную и возвращаем в качестве результата. Если НЕ нашли - мы просто дойдем до конца цикла и вернем null.  "order.order_num > order_num" - эт о какая-то заглушка, на сколько я понимаю. Как тут может что-то зависнуть - не представляю. 
3. GetOrder_by_Number, если помотреть на код lua, еще проще

`unction qsfunctions.getOrder_by_Number(msg)
	for i=0,getNumberOf("orders")-1 do
		local order = getItem("orders",i)
		if order.order_num == tonumber(msg.data) then
			msg.data = order
			return msg
		end
	end
	return msg
end`

Мы также перебираем ВСЮ таблицу заявок, и в случае совпадения номера заявки возвращаем в составе параметра эту заявку. То, что Вы показываете в своем коде - это по сути тоже самое. Единственное отличие в том, что вы решили свалить в одну кучю номера заявок и ID транзакций. Зачем - непонятно, но это пусть будет на Вашей совести.

Будет время - я попробую проверить как работает функция, при передаче несуществующего номера.

**Comment by Pr0phet1c** [comment]
Проверил. Зависание действительно имело место. Видимо, до Вас никому не приходило в голову запрашивать заявки прошлых периодов (мне в том числе).
Исправлено. Можете забирать.

**Comment by Olddead91** [comment]
Классно, спс!
Иногда бывают ситуации, когда падает Квик или приложение с активными заявками, и чтобы не лезть руками в учёт, чекаешь заявки на старте. Очень редко, но бывает, что чек происходит только на следующий день.
