### ISSUE TITLE
Падение скрипта: qsutils.lua:155: attempt to index upvalue 'callback_client' (a nil value)

### ISSUE THREAD

**Issue by SkyN** [finsight/QuikSharp#37]
Если быстро создать и удалить объект Quik, то lua скрипт остановиться с ошибкой 
QuikSharp\src\QuikSharp\lua\qsutils.lua:155: attempt to index upvalue 'callback_client' (a nil value)

воспроизводиться на коде:

        using QuikSharp;
        namespace QuickQuit
        {
            class Program
            {
                static void Main(string[] args)
                {
                    Quik Q = new Quik();
                }
            }
        }

воспроизводиться не всегда. Причём, я смог воспроизвести только когда в Quik список скриптов закрыт. Если же список скриптов открыт, то получаю просто:
Loading values that a client missed during disconnect

**Comment by buybackoff** [comment]
Объект Quik расчитан на долгую счастиливую жизнь в течение дня, тут он даже соединиться наверное не успевает.
