### ISSUE TITLE
Запуск нескольких роботов одновременно

### ISSUE THREAD

**Issue by Pr0phet1c** [finsight/QuikSharp#39]
Собственно вопрос в том есть ли способ запустить одновременно несколько роботов (на данный момент у меня не получилось), или придется писать что-то вроде платформы, которая будет общаться с терминалом, а уже внутри нее реализовывать работу множества роботов?

**Comment by buybackoff** [comment]
Наверное правильный вопрос - запуск нескольких процессов с QuikSharp. Сейчас поддреживается только одно соединение, сколько из одного процесса им воспользуются роботов - на ваше усмотрение. Несколько процессов в теории можно подключить, изменив номер порта (задается параметром для Quik() и прописано в скрипте Луа) и запустив второй скрипт с измененным портом внутри Квика. Где-то тут было обсуждение на тему.

QuikSharp изначально создавался асинхронным с поддрежкой доступа из разных потоков, поэтому ничего дополнительно с портами и процессами я не буду делать.

**Comment by Pr0phet1c** [comment]
Понял. попробую покопаться в луа-скрипте. До этого пробовал другой порт указывать только в самом роботе, при инициализации quik.
Спасибо.

**Comment by Pr0phet1c** [comment]
Посмотрел, но легче не стало.
мы биндим по одному порту для response_server и callback_server, и задать перечень портов, как я понимаю, низя.
Боюсь ошибиться, но правильно ли я понимаю, что если мне надо запустить например 15 роботов, то надо создать 15 комплектов файлов Lua и в каждом таком комплекте в файле qsutils.lua задать различные порты в строке "local port = 34130"?
Ну и конечно в каждом роботе на C# также надо будет указать один из портов комплекта?

**Comment by buybackoff** [comment]
Да, наверное так. Второй порт рассчитывается как основной +offset (наверное 1), поэтому порты должны идти с шагом +2

**Comment by Pr0phet1c** [comment]
Да, это уже понял.
Наверное, в моем случае, логичнее будет сделать платформу, внутри которой будет крутиться пакет "готовых" роботов, а для разработки и отладки "новых" можно парочку отдельных комплектов файлов состряпать.
В любом случае, спасибо.
