### ISSUE TITLE
Spreads integration

### ISSUE THREAD

**Issue by buybackoff** [finsight/QuikSharp#40]
В [Spreads](https://github.com/Spreads/Spreads) уже есть [пример примитивной торговой стратегии](http://hotforknowledge.com/2015/12/29/how-to-write-the-simplest-trading-strategy-using-spreads/). Нужно добавить в КШ API для получения всех данных как IAsyncEnumerable или IObservable, что дуально. Также нужно сделать пример атомарного трейдера, Квик поддерживает режим 2 (но не 3) на ФОРТС. Интересно, поддерживает ло он режим 2 на акциях и споте валюты? В принципе, потом можно писать стратегии настолько гибкие и сложные, насколько люди разберутся в Spreads, которые не будут зависеть от Квика и смогут работать с любом месте.

**Comment by sergshabal** [comment]
@buybackoff, а что за режимы такие 2 и 3?

**Comment by buybackoff** [comment]
атомарная перестановка заявок

**Comment by sergshabal** [comment]
а это чья вощможность? квика, плазы или quiksharp?

**Comment by buybackoff** [comment]
@nubick Spreads под GPL - нужно твое согласие поменять лицензию, или совет почему не стоит это делать. Работает это так, что все твои коммиты остаются твоими и любой форк может продолжать как Апаче. Так как они были Апаче, можно изменить на GPL в любой момент без явного разрешения, только имя в авторах оставить... С другой стороны, КШ создавался как зеркало функций Луа без дополнительных фич, и пожалуй должен им остаться, но тогда нужно будет создавать новый проект с фичами. Последний коммит Spreads (0.3.5) может многим показаться интересным, он решает все проблемы хранения данных. Тут раньше для хранения данных использовался Esent, который работал через жопу, - Spreads выводит хранение на новый универсальный уровень.

Я раньше не любил GPL, но сейчас понял в чем фишка - для конечных пользователей, которые сами не пишут софт для третьих лиц, а только используют КШ для торговли, разницы нет. А все остальные лицензии позволяют людям брать куски кода, изменять и улучшать его, и не постить назад. У КШ форков в какой-то момент было больше звезд - и где все пулл реквесты!?

Понимаю, что в нашей великой и могучей стране всем положить на лицензии, так что вопрос скорее риторический. Просто любая ссылка на Спрэдс автоматически сделает этот проект GPL.

**Comment by nubick** [comment]
Меняй как считаешь нужным. Главное, чтобы на хорошее дело! :)

**Comment by buybackoff** [comment]
может быть позже
