### ISSUE TITLE
CallBacks и стандартизация

### ISSUE THREAD

**Issue by sergshabal** [finsight/QUIKSharp#46]
Вопрос1: пишет ли кто-то колбэки луа?(OnAccountBalance, OnAccountPosition, OnAllTrade, ...) И соответствующие им обработчики и QuikSharp?
Если да то прошу запушить чтоб не повторятся. 

Вопрос2(предложение): Давайте стандартизируем структуры данных. А то где-то SecCode, где-то sec_code.

**Comment by buybackoff** [comment]
Все sec_code должны быть заменены на SecCode + JSON.NET attribute, как [тут например](https://github.com/finsight/QuikSharp/blob/master/src/QuikSharp/DataStructures/DepoLimitEx.cs#L16). Просто изначально я не использовал этот аттрибут и делал имя свойств как в Квике. Руки не долшли, все работало. Выглядит плохо конечно, надо поменять.

Вряд ли кто-то пишет, смело шлите pull request! :)

**Comment by buybackoff** [comment]
@sergshabal  Кстати в корне есть файл Эксель, через который я генерировал код. Помогает когда много полей просто скопировать из документации Квика таблицу и обработать в Экселе, вместо того, чтобы руками писать структуры целиком.

**Comment by buybackoff** [comment]
@sergshabal  смотрите #195 если что-то пропустили за три года :)
