### ISSUE TITLE
Борьба с последствиями дисконнекта

### ISSUE THREAD

**Issue by Pr0phet1c** [finsight/QuikSharp#47]
Не знаю как у других, а у меня после восстановления коннекта с сервером (если перед этим был дисконнект) Квик некоторое время "висит" (около минуты), прежде чем вновь оказывается в состоянии отдавать какие-либо данные. За это время, робот успевает вывалиться с ошибкой. Причем, ошибка может возникнуть где угодно.
Собственно задача, после восстановления связи определить, что Квик уже начал стабильно отдавать данные. Кто-нибудь уже решал такую задачку, или это только у меня такая проблема??

**Comment by COBRAprogDAV** [comment]
могу проверить, если выложите пример как выставлять заявки.

**Comment by Pr0phet1c** [comment]
Да, пожалуйста.
Мне не жалко.

        long _transactionID = 0;
        QuikSharp.DataStructures.Transaction.Order order_new = new QuikSharp.DataStructures.Transaction.Order();
        order_new.ClassCode = “SPBFUT”;
        order_new.SecCode = “SiM6”;
        order_new.Operation = Operation.Buy;
        order_new.Price = price;
        order_new.Quantity = qty;
        order_new.Account = AccountID;
        order_new.ClientCode = ClientCode;
        _transactionID = _quik.Orders.CreateOrder(order_new);

В упрощенном виде как-то так...

**Comment by COBRAprogDAV** [comment]
нет у меня не висит QUIK 7.1.0.381
-подал заявку
-сделал дисконнект
-авто коннект
-через 10 сек подал еще завку встала сразу
20:07:11,Connecting...
20:07:15,Connected!
20:07:16,(161) Заявка N 2383767684 зарегистрирована
20:08:58,Net error: Удаленный хост принудительно разорвал существующее подключение.
20:09:58,Соединение установить не удалось
20:10:03,Соединение установить не удалось
20:10:14,Соединение установлено
20:10:22,(161) Заявка N 2383773615 зарегистрирована

**Comment by COBRAprogDAV** [comment]
isconnected отрабатывает сразу
[Test]
        public void IsConencted() {
            Console.WriteLine("IsConnected? : " + _q.Service.IsConnected().Result);
        }

**Comment by Pr0phet1c** [comment]
isConnected у меня тоже сразу отрабатывает. Но буквально через 1-2 секунды квик "засыпает". Длительность этой спячки разная. Вечером может секунд на 5-10, а днем на 1-1,5 минуты может зависнуть. Я этот процесс по часам квика вижу, когда секунды сразу после коннекта сначала идут, потом висят, а потом снова начинают идти. Потом все идет нормально, но за это время робот успевает "отвалиться". Я уж думаю, может счетчик какой-нибудь по сигналам квика запускать после реконнекта, но пока кроме OnParam из сигналов ничего в голову не приходит. А этот колбэк не самый подходящий параметр для анализа (за одно и тоже время может пройти сильно разное количество сигналов)

**Comment by buybackoff** [comment]
По умолчанию после дисконнекта все пропущенные данные записываются в файл и после реконнекта пересылаются клиенту. Все собирался отключить это, т.к. опасная штука, но кажется это все еще в основном коде. Если много данных, может в этом дело.

**Comment by Pr0phet1c** [comment]
В том то и дело, что я уже давно отключил эту запись в файл пропущенных данных (закомментил одну строку), т.к. у меня из-за нее тоже возникали некоторые трудности. Но даже эти записи никак мне не помогут.
Попробую объяснить почему:
Я запрашиваю наборы свечек по разным инструментам и храню их в памяти робота (это одновременно не менее 40 наборов). Пополняются эти наборы по колбэкам, с поступлением каждой новой свечки.
Соответственно, если я например собираю "минтуки", а дисконнект длился минут 5, то мне необходимо очистить хранилище и перезаказать данные, после того как соединение восстановлено. И все бы ничего, но вся система работает только до того момента как я получил подтверждение isConnected. Ведь сразу после этого робот отправляет запросы на подписку по всем инструментам и всем тайм-фреймам, но из-за того, что квик уже успевает "зависнуть", но в течение длительного времени ответов роботу от него не приходит. И то ли потоки успевают завершиться, то ли еще что-то. но в какой-то момент робот вылетает с ошибкой, в произвольном месте.

**Comment by COBRAprogDAV** [comment]
так зависание не в результате дисконнекта, а в результате запроса на подписку по всем инструментам и всем тайм-фреймам?  понять не могу?

**Comment by COBRAprogDAV** [comment]
ждите подтверждения isConnected  пару минут до "устаканивания" потом шлите подписки - почему бы не так сделать?

**Comment by Pr0phet1c** [comment]
Я не знаю, как правильно объяснить. В общем как я это понимаю, пока квик не "устаканился", и не начал равномерно отдавать данные - нельзя слать никакие запросы к нему, т.к. с большой вероятностью, они не вернуться в отведенное время, и возникнет сбой.
Конечно, можно тупо приостановить робота после дисконнекта на какое-то время, но:
- хотелось бы вернуться к рабочему состоянию робота как можно быстрее, после восстановления связи (промедление может дорого стоить);
- останавливая робота на какое-то фиксированное время, нет гарантии, что по его истечению, квик уже "разморозится", а устанавливать слишком долгий период перерыва - это значительно увеличивать вероятность больших потерь.

Другими словами, задача отловить момент, когда квик пришел в норму, и сразу после этого продолжить работу.

**Comment by COBRAprogDAV** [comment]
это вам к разработчикам QUIK или поменять брокера.
Я тестил  с одним роботом ничего не зависает.
Если у вас много роботов  ищите с какого количества роботов начинаются
зависания. Я бы так начал искать. 
А насчет гарантий "равномерно отдавать данные" тоже сами можете все узнать.
сначала делаете 10 минут, если ничего не зависает уменьшаете время и т.д.
мне кажется у вас "тупит" брокер
Я думаю это не проблема QUIKSHARP
