### ISSUE TITLE
Не работают тесты.

### ISSUE THREAD

**Issue by johndob** [finsight/QuikSharp#48]
Скачал solution КШ c github. Обновил References в Profiler на проекты QuikSharp и QuikSharpTest (изначально видимо были ссылки на старую dll в которой нет Transaction). Запускаю QuikSharp.lua в Квике, запускаю Profiler с тестами. Quik выдает сообщение Connected, а когда закрывю profiler - переключается на Connecting...
Но! Никакие тесты не работают, даже IsQuik, ответа не приходит. 
Где может быть проблема?

p.s. Еще заметил с непорядок нэймспэйсами. Например в папке QuikSharp.DataStructures.Transaction часть классов имеет такой namespace, а часть - просто QuikSharp.

**Comment by johndob** [comment]
Я помню, что полгода назад пробовал КШ и он работал. Поэтому создал новую ветку от последнего комита  9/9/2015, и о чудо! Тесты заработали.  Надо разбираться, почему не работает последняя версия...

**Comment by buybackoff** [comment]
Какая ошибка? StackTrace? Шлите pull request, когда пофиксите!

**Comment by johndob** [comment]
Вопрос снимаю. С последней версией тоже заработало, только не сразу. Из-за чего - неясно.
