### ISSUE TITLE
Прошу пример использования вашей библиотекой

### ISSUE THREAD

**Issue by sadersa** [finsight/QUIKSharp#52]
Виктор привет
прошу пример на пару строк кода по использованию вашей библиотекой
В тестах что вы выложили все работает замечательно - но 
я создал новый проект
добавил вашу библиотеку в референсах
создал кнопку и в ней разместил ваш код
            Quik quik = new Quik();       -ок создается
            long orderId = 123456789; 
            Order order = quik.Orders.GetOrder("TQBR", orderId).Result;
**вот сюда а никогда не прихожу - программа зависает**
            Assert.IsNull(order);
Прошу помощи

**Comment by buybackoff** [comment]
Это особенности использования из WPF/WebForms:
https://github.com/finsight/QuikSharp/issues/26

**Comment by buybackoff** [comment]
И с какой стати ордер с фейк номером  123456789 должен вернуться!? По идее должна быть ошибка, ни разу не думал об этом.

**Comment by nubick** [comment]
`private async Task<Order> GetOrder()
{
  Quik quik = new Quik(); -ок создается
  long orderId = 123456789; 
  Order order = await quik.Orders.GetOrder("TQBR", orderId);
  return order
}`

Советы простые. Не использовать нигде в WPF приложениях Result. Использовать функционал работы с асинхронными методами (async и await). Разобраться как работают потоки в WFP приложении, когда используете асинхронные вызовы.

**Comment by khataev** [comment]
>  Разобраться как работают потоки в WFP приложении, когда используете асинхронные вызовы.

А можете хотя бы подсказать, в каком направлении разбираться? Разве в WPF потоки особенные какие-то, не такие как в WinForms?

**Comment by PavelSVL** [comment]
Сделайте, пожалуйста, пример реализации на **WinForm**.
Ничего не получается, quik = new Quik() создаю в отдельном от формы потоке, а дальше не понимаю.
quik.Service.GetScriptPath().Result  -  не работает.
private async void GetPath()
        {      ---
                path = await quik.Service.GetScriptPath();
        } - зависает
Пробовал разные варианты, которые тут нашлись, но результат всегда один и тот же.
Помогите кто нибудь.

**Comment by FoKycHuK** [comment]
На самом деле, тут проблема не в WPF и не в формах, кажется.
Пытаюсь сейчас разобраться в библиотеке (опыт на c# есть), и тоже сталкиваюсь с этой проблемой:
Создал новый проект, подгрузил через NuGet эту библиотеку, затем пробую сделать так: 
`static void Main(string[] args)
        {
            var quik = new Quik();
            Console.WriteLine("quik created");
            var result = quik.Service.IsConnected().Result;
            Console.WriteLine(result);
        }`
Проблема та же самая, как и выше: таск никогда не завершается.
В квике при каждом запуске пишет "Connected".

**Comment by sm00vik** [comment]
Добрый день. 
Подскажите пож. можно ли оставить в программе один экземпляр класса Quik или можно их сделать некоторое кол-во под определенные задачи. К примеру экземпляр под отправку транзакций и один под получение справочной информации из quika. Вопрос касается производительности приложения. Какой подход является более эффективным? Спасибо.

**Comment by buybackoff** [comment]
В проекте используется мультиплексинг, можно забыть о производительности на уровне QuikSharp - она всегда будет ограничена самим Квиков и скоростью сети. Получение данных никак не влияет на отправку транзакций, если обе вещи происходят с одним и тем же терминалом Квик.

**Comment by sm00vik** [comment]
Еще раз большое спасибо за ответ. Проект замечательный.

**Comment by webhive** [comment]
@FoKycHuK
> Попробовал такой расклад: взял проект src/QuikSharp из мастера, создал новый солюшн, добавив туда этот проект в студии, и из другого проекта смог добиться того, чтоб пример выше работал.
> 
> Гипотеза -- в нюгете лежит старая, нерабочая версия?

Точно такая же фигня. Версия из NuGet-а - таск не завершается. Версия из мастера, собранная вручную - работает.

**Comment by buybackoff** [comment]
В НюГете версия без configureawait(false), формально она рабочая, но нужно
знать как работать с формами/wpf

**Comment by webhive** [comment]
В консоли не работало. Т.е. формы/wpf не должны влиять.

**Comment by let4be** [comment]
в нугете нерабочая версия, см. https://github.com/finsight/QuikSharp/issues/83
master сломан также

**Comment by Pr0phet1c** [comment]
Думаю, эту ветку тоже можно закрыть
