### ISSUE TITLE
А можно ли подписаться на получение обезличенных сделок без открытия таблиц?

### ISSUE THREAD

**Issue by sadersa** [finsight/QUIKSharp#53]
привет
А можно ли подписаться на получение обезличенных сделок без открытия таблиц?
нашел метод OrderBook.Subscribe 
может есть что то подобное для сделок
а то складывается впечатление что данные идет с задержкой
например я в МТ5 получаю подтверждение постановки ордера на 150 мсек раньше чем в квике

**Comment by Pr0phet1c** [comment]
Подписываться на получение колбэка OnAllTrade пробовали?

**Comment by sadersa** [comment]
да пробывал - все работает
но только когда открыта таблица обезличенных сделок в квике
и такое впечатление что данные идут не когда они в квик приходят а когда таблица рефрешится. (
и из за этого задержка.
вот и подумал если можно получать данные без таблиц то может они пойдут быстрее.

**Comment by Pr0phet1c** [comment]
Я сам не использую таблицу всех сделок, поэтому мне сложно сделать однозначно правильный вывод. Пока, учитывая реализованный код данного колбэка в QuikSharp, склоняюсь к предположению, что это именно квик так работает, т.е. (опять же, предположительно), если в квике открыта таблица всех сделок, то колбэки идут и данные получаются с сервера. Если таблица закрыта, то квик, для экономии ресурсов не обрабатывает таблицу всех сделок. Звучит бредово, но если вдруг оно действительно так, что я не особенно удивлюсь.
К сожалению, в Lua я не видел функции подписки к таблице всех сделок (может конечно плохо смотрел), а значит и в QuikSharp такую подписку организовать скорее всего не получится.

**Comment by buybackoff** [comment]
QuikSarp добавляет почти нулевую задержку, но в Квике длинный путь от биржи к брокеру, от брокера в Квик, процессинг в Квике... Надо читать доки Квика, как там работает.

**Comment by sergshabal** [comment]
в квике меню связь -> заказ всех сделок. Там добавляйте инструменты которые хотите получать, потом пробуйте подписаться на OnAllTrade. В теории должно работать

**Comment by Pr0phet1c** [comment]
sergshabal, позволю себе с Вами не согласиться. Если я правильно понял описание, предоставленное sadersa, то сделки в открытой таблице обезличенных сделок у него есть, а значит "заказ всех сделок" у него уже включен.

**Comment by ch5oh** [comment]
Надо вызывать предварительно _quik.Candles.Subscribe("SPBFUT", "RIM6", CandleInterval.TICK)
При этом наличие таблицы "Все сделки" в Квике не требуется.
