### ISSUE TITLE
Методы типа Subscribe для свечей и стаканов сделать синхронными

### ISSUE THREAD

**Issue by ch5oh** [finsight/QuikSharp#54]
Это мгновенные операции. Нет никакой необходимости делать их "асинхронно". Зачем?

**Comment by buybackoff** [comment]
Нет. Все, что касается IO, должно быть асинхронно.

**Comment by ch5oh** [comment]
Вы не уловили.
Метод QuikService.Send<T> -- сколько угодно асинхронный.

Но методы Subscribe / Unsubscribe вообще не требуют возвращения ответа и делать их как async нет смысла. Ради острых ощущений?..

Вот так отлично работает и потом использовать проще:
        public void Subscribe(string classCode, string securityCode, CandleInterval interval)
        {
            var message = new Message<string>(classCode + "|" + securityCode + "|" + (int)interval, "subscribe_to_candles");            
#pragma warning disable 4014
            QuikService.Send<Message<string>>(message);
#pragma warning restore 4014
        }

**Comment by buybackoff** [comment]
Вы не поняли про IO: QuikSharp посылает сообщение в Quik, ответ показывает,
что Квик получил сообщение. Вы всегда можете не ждать ответа, никто не
заставляет исопльзовать await/Task.Result.

2016-04-15 13:08 GMT+03:00 ch5oh <notifications@github.com>:

**Comment by ch5oh** [comment]
Я к тому, что нет смысла писать провокационный код если в этом нет реальной необходимости.
Юзер дёргает Subscribe -- и его не волнуют подробности. Если исключение не выброшено, значит всё в порядке.

Кстати, как корректно обработать исключение в Subscribe?
Или оформить этот вопрос отдельным тикетом?

**Comment by buybackoff** [comment]
Давайте не будем обсуждать дизайн... Тем более, когда есть причина, чтобы
он был такой. Добавьте overload, но не пытайтесь менять то, что до вас
делали и уже пользуются.

2016-04-15 13:15 GMT+03:00 ch5oh <notifications@github.com>:

**Comment by ch5oh** [comment]
Имхо, это OpenSource. Здесь всё обсуждается.
В случае разногласий делают форк и расходятся.
Тем более, я человек новый. У меня возникают вопросы.
Если трудно объяснить в двух словах зачем **там** кровь из носу необходим async-await...
Что ж... поехали дальше.

**Comment by buybackoff** [comment]
Я объяснил. Вы предлагаете изменение, которое потребует изменения
существующего кода у пользователей и добавляет абсолютно ноль ценности.
Если вам удобнее без тасков и вы не можете просто не ждать его, добавьте
новый метод. Это open source, вы не можете просто так менять существующую
API...

2016-04-15 13:31 GMT+03:00 ch5oh <notifications@github.com>:

**Comment by buybackoff** [comment]
Это обсуждение похоже на троллинг. Давайте обсуждать только код в формате pull request, или баги. Есть другие более важные дела, чем переписываться тут на подобные темы.
