### ISSUE TITLE
Как корректно обработать исключение в Subscribe?

### ISSUE THREAD

**Issue by ch5oh** [finsight/QUIKSharp#55]
В случае ошибочной подписки (например, указание секции которой в Квике нет) получаю LuaException, который не перехватывается обычным try-catch и, кажется, валит программу.

Как его корретно принять и обработать?

**Comment by buybackoff** [comment]
Покажите код, где именно падает?

**Comment by ch5oh** [comment]
1. Подключиться к Квику
2. Попытаться подписаться
_quik.Candles.Subscribe("ЧУШЬ", "ЕРЕСЬ", CandleInterval.TICK);

**Comment by ch5oh** [comment]
Вот полностью фрагмент:
```
try
{
    Console.WriteLine("A mistake, sorry...");
    _quik.Candles.Subscribe("WRONG", "SECURITY", CandleInterval.TICK);
}
catch (LuaException lex)
{
    Console.WriteLine("Try-catch works!");
}
```

Кеч не срабатывает.
Выскакивает стандартное окно AppCrash.
В консоли пишут стек-трейс:

> 
> A mistake, sorry...
> 
> Unhandled Exception: QuikSharp.LuaException: WRONG - unknown class code.
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at QuikSharp.QuikService.<Send>d__1b`1.MoveNext() in w:\git\QuikSharp\src\QuikSharp\QuikService.cs:line 502
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at QuikSharp.CandleFunctions.<Subscribe>d__10.MoveNext() in w:\git\QuikSharp\src\QuikSharp\CandleFunctions.cs:line 92
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
>

**Comment by buybackoff** [comment]
В Луа нужно поймать исключение и задать свойтсво `msg.lua_error` с описанием и оправить сообщение назад. Дакже должно быть дазадо поле `msg.cmd = 'lua_error'` Только наличие этого поля в сообщении позволить C# поймать ошибку. В [этом файле](https://github.com/finsight/QuikSharp/blob/master/src/QuikSharp/lua/qsfunctions.lua) поле cmd в одном месте (cnhjrf 352) задается на `lua_create_data_source_error`, при этом на стороне C# нету обработчика, который бы понимал эту команду специальным образом. Надо изменить на `msg.cmd = 'lua_error'` или добавить отдельную логику для этой команды на стороне C#.

**Comment by buybackoff** [comment]
Вообзе в функциях Луа не нужно ловить ошибки, они все ловятся в `function qsfunctions.dispatch_and_process(msg)` на восьмой строке. Только в SendTransaction своя логика или кривости Квика.

**Comment by ch5oh** [comment]
Видимо, был план сделать отдельный обработчик?..
Сейчас попробую пулл-реквест сделать.

**Comment by buybackoff** [comment]
Не знаю, эти функции добавлял @nubick

**Comment by nubick** [comment]
Нет, не было такого плана. :)
Походу, я не правильно понял смысл msg.cmd и решил, что это просто строковое описание ошибки и присвоил другую строку, описывающую контекст ошибки, чтобы было понятно где упало.
Спасибо за исправление!
