### ISSUE TITLE
Вопрос по скорости обмена с Квиком

### ISSUE THREAD

**Issue by PavelSVL** [finsight/QUIKSharp#57]
Добрый день.

Начал изучать Ваш коннектор QuikSharp, уже почти дописал платформу для робота и решил измерить скорость исполнения запросов, по сравнению с таким же роботом на Lua.

Вы пишете, что скорость около 60 МИКРОсекунд.
Я в своем роботе на C#, получая все свечи по инструменту через "get_candles_from_data_source", делаю замер в двух местах: 
   в Lua (получается меньше 1 МИЛИсекунды) от входа до выхода функции. 
   в C# (получается 400 МИЛИсекунд), это с момента вызова quik.Candles.GetLastCandles("SPBFUT", "RIM6", CandleInterval.M1, 0).Result и до получения обратно данных о свечах.
Получается C# за секунду успевает исполнить 2-3 функции или циклов, а тот же самый робот на луа, без C# успевает выполнить гораздо больше 100 функций или циклов расчета и обмена с квиком.

Основная задержка идет от 
internal async Task<TResponse> Send<TResponse>(IMessage request, int timeout = 0)
            ...
            ...
            var response = await tcs.Task;  >200 МИЛИсекунд.

Как перейти в МИКРОсекунды, я что то не так делаю, или что то не так понимаю?

Подскажите, пожалуйста.

**Comment by buybackoff** [comment]
Есть тесты, где показывается, что я имею в виду: 60 микросекунд - это скорость обмена данными по TCP между C#/Lua. В это не входит вызов функций Луа. Идея была в том, что сам QuikSharp практически не добавляет задержки - она пренебрежимо мала. Разницы в 400 раз не может быть, наеврное вызовы в Луа отличаются и вы не ждете ответа в Луа.

**Comment by buybackoff** [comment]
Недавно было обсуждение, что этот метод можно не ждать. Можете не вызывать .Result, подписка произойдет все равно в бэкграунде.

**Comment by PavelSVL** [comment]
А какой ответ мы ждем? С# отправляет запрос вызова функции (60 микросекунд), луа получает запрос, находит в памяти функцию, соответствующую запросу, исполняет ее (1-5 милисекунд) и отдает результат... дальше на сколько я понял луа уже ничего и не далает, а идет уже обмен через сокет, который почемуто занимает много времени... Только что он делает, результат то уже есть...

**Comment by buybackoff** [comment]
Покажите свой код (оба)... Я много тестил, чтобы быть уверенным в своих цифрах. Может слона в лавке не заметили или что-то еще. TCP via loopback очень быстрый, а я по сути ничего к этому особо не добавляю, кроме сериализации, которая тоже быстрая и тут одно маленькое сообщение только.

**Comment by buybackoff** [comment]
Вообще, 400 милли - это нужно бить в бубен и кричать, что что-то сломалось... Или дело в чем-то другом :)

**Comment by PavelSVL** [comment]
`C#
	public void StartConnector()
        {
            LoadFormStartSettings();
            Quik trader = new Quik();
            BeginInvoke(new doLabelQuik(LabelQuik), "NO");
            if (Set.OpenQuik) OpenQuik(Set.QuikPath);
            
            while (working)
            {
                    bool isQuik = trader.Debug.IsQuik().Result;
                    if (isQuik)
                    {
                        BeginInvoke(new doLabelQuik(LabelQuik), "OK");
                        string Time = trader.Service.GetInfoParam(InfoParams.SERVERTIME).Result;
                        if (Time == "") Time = trader.Service.GetInfoParam(InfoParams.LOCALTIME).Result;
                        BeginInvoke(new doLabelTime(LabelTime), Time);
                        
                        bool isConnect = trader.Service.IsConnected().Result;
                        if (isConnect)
                        {
                            BeginInvoke(new doLabelConnect(LabelConnect), "OK");
                            DateTime one = DateTime.Now;
                            var candle = trader.Candles.GetLastCandles("SPBFUT", "RIM6", CandleInterval.M1, 0).Result;
                            DateTime two = DateTime.Now;
                            TimeSpan Timer = two - one;
                            Log("Candle Close =  " + candle[1].Close + "    Timer = " + Timer.Milliseconds + " ms.");
                    }
                    else
                        {
                            if(Set.AutoConnect && WeekDay() && Convert.ToDateTime(Time) >= Convert.ToDateTime(Set.TimeConnect) && Convert.ToDateTime(Time) < Convert.ToDateTime(Set.TimeDisconnect)) Connect(Set.QuikLogin, Set.QuikPassword);
                            BeginInvoke(new doLabelConnect(LabelConnect), "NO");
                        }
                    }
                    else
                    {
                        BeginInvoke(new doLabelQuik(LabelQuik), "NO");
                    }
                Thread.Sleep((int)Set.SleepTime);
            }
        }

 	private void StartThread()
        {
            mainThread = new Thread(StartConnector) { IsBackground = true };
            mainThread.Start();
        }

        private void ReStartThread()
        {
            mainThread.Abort();
            mainThread = new Thread(StartConnector) { IsBackground = true };
            mainThread.Start();
        }

        private void Form1_Shown(object sender, EventArgs e)
        {
            StartThread();
        }`

**Comment by PavelSVL** [comment]
Я правда прошу его всю историю (~3000 свечей). Если грузить 10 свечей, то выполнит за 4 милисекунды.

**Comment by buybackoff** [comment]
Ну дак! А что Луа все это делает за 1 мсек!?

**Comment by buybackoff** [comment]
https://github.com/finsight/QuikSharp/blob/master/src/QuikSharp/lua/qsfunctions.lua#L385  В C# мы вызывает функцию CreateDataSource, она возвращает все данные. В Луа очевидно вы не ждете возврата или данных меньше. Код в Луа не вижу.

Кстате, бросьте это дело с BeginInvoke и Thread... Все давно построено на async/await и Tasks...

**Comment by PavelSVL** [comment]
`function qsfunctions.get_candles_from_data_source(msg)
	local ttime = os.clock()
	local ds, is_error = create_data_source(msg)
	if not is_error then
		--- датасорс изначально приходит пустой, нужно некоторое время подождать пока он заполниться данными
		repeat sleep(1) until ds:Size() > 0

		local count = tonumber(split(msg.data, "|")[4]) --- возвращаем последние count свечей. Если равен 0, то возвращаем все доступные свечи.
		local class, sec, interval = get_candles_param(msg)
		local candles = {}
		local start_i = count == 0 and 1 or math.max(1, ds:Size() - count + 1)
		for i = start_i, ds:Size() do
			local candle = fetch_candle(ds, i)
			candle.sec = sec
			candle.class = class
			candle.interval = interval
			table.insert(candles, candle)
		end
		ds:Close()
		msg.data = candles
	end
	return msg, log(round((os.clock()-ttime)*1000)..' ms',1)
end
`

**Comment by PavelSVL** [comment]
Функция Lua осталась Ваша, я только таймер воткнул

**Comment by PavelSVL** [comment]
Если ее немного модифицировать, то будет исполняться менее чем за 1 мс. Ну по крайней мере на моих компьютерах.

**Comment by buybackoff** [comment]
Возможно QS в C# не возвращает результат до первой свечи: https://github.com/finsight/QuikSharp/blob/1a112e5c3dfe038c88b93e034b78099c396d64a3/src/QuikSharp/QuikService.cs#L435

**Comment by PavelSVL** [comment]
Так я на событие и не подписываюсь же. Функция же просто загружает сразу все что есть и отдает.

**Comment by buybackoff** [comment]
Не я писал эту часть, надо разбираться. 400 мсек очень похожи на ожидание ответа от сервера Квика.

**Comment by buybackoff** [comment]
Если в Квике не открыт график, ей нужно обратиться к серверу. А может всегда нужно.

**Comment by PavelSVL** [comment]
Почему не использовать BeginInvoke и Thread?
По другому не получилось запуститься на WinForm.

**Comment by PavelSVL** [comment]
График открыт, данные уже подгружены в квике, поэтому обращения на сервер нет, и поэтому быстро выдается результат того что уже есть

**Comment by buybackoff** [comment]
Тут несколько топиков про WinForms - все возможно.
Возможно @nubick может подсказать про свечи. Я историческими свечками не пользовался, только сделки и котировки и стаканы.

**Comment by PavelSVL** [comment]
Получается что задержка идет из за большого размера таблицы, которую возвращает луа, уменьшая эту таблицу уменьшается и время. Если уменьшить до одного значения, то отработает моментально, так же как и isConnected например, которая возвращает одну переменную.

**Comment by buybackoff** [comment]
3000 * (8 * 5) = 129 Kb / 400 msec = 375 Kb/sec - очень мало, если данные уже в памяти. Надо разбираться.

**Comment by buybackoff** [comment]
Но абсолютно логично, если данные идут с сервера по интернету. Я понятия не имею, как именно работает эта подписка...

**Comment by PavelSVL** [comment]
Без подключения к серверу работает точно так же, спокойно грузит все свечи. Он их грузит из памяти квика

**Comment by PavelSVL** [comment]
Для примера можно взять `var candle = trader.Candles.GetAllCandles("chart").Result;`.
То есть просто читаем с открытого графика по идентификатору.
И результат будет тот же

**Comment by buybackoff** [comment]
Мне не нравится этот цикл:

```
for i = start_i, ds:Size() do
			local candle = fetch_candle(ds, i)
			candle.sec = sec
			candle.class = class
			candle.interval = interval
			table.insert(candles, candle)
		end
```

и эта функция:
```
function fetch_candle(data_source, index)
	local candle = {}
	candle.low   = data_source:L(index)
	candle.close = data_source:C(index)
	candle.high = data_source:H(index)
	candle.open = data_source:O(index)
	candle.volume = data_source:V(index)
	candle.datetime = data_source:T(index)
	return candle
end
```
Возможно это и есть слон в лавке... Надо ds целиком сериализировать о отправлять, потом распаковывать автоматически в C#. Возможно там случайно complexity O(n^2) или еще хуже.

**Comment by PavelSVL** [comment]
Ну опять же тут `var candle = trader.Candles.GetAllCandles("chart").Result;` не используются эти функции

**Comment by buybackoff** [comment]
Замерьте плиз не вызов встроенной функции Квика, а именно ту функцию, которую вызывает Шарп... Короче, явно где-то тут что-то простое на видном месте, но не сразу очевидное... Я пока разбираться с этим не могу. Подпишитесь на Плазу - там коннектор не нужен, там все работает из коробки... :)
