### ISSUE TITLE
Transactions callbacks

### ISSUE THREAD

**Issue by sergshabal** [finsight/QUIKSharp#58]
Продублирую тут, вдруг кто не видел. https://github.com/finsight/QuikSharp/issues/7#issuecomment-215014468 

Наверное стоит мне сюда написать. Вопрос: создал я новую транзакцию, и хочу обработать ее OnOrder, как это сделать?

Пишу тест:

``` c#
        [Test]
        public void SendOrderTest()
        {
            Quik q = new Quik(Quik.DefaultPort, new InMemoryStorage());

            var t = new Transaction()
            {
                ACCOUNT = "NL0011100043",
                CLASSCODE = "QJSIM",
                SECCODE = "SBER",
                ACTION = TransactionAction.NEW_ORDER,
                OPERATION = TransactionOperation.B,
                PRICE = 120M,
                QUANTITY = 1,
                CLIENT_CODE = "101942",
                Comment = "",
            };

            t.OnOrder += (Order o) => {
                Console.WriteLine(
                    "New order regs with num = {0} on transaction {1}",
                    o.OrderNum, t.TRANS_ID);
                rised = true;
                mre.Set();
            };

            q.Events.OnOrder += (Order o) =>
            {
                Console.WriteLine(
                    "New order in QuikEvents regs with num = {0} on transaction {1}",
                    o.OrderNum, t.TRANS_ID);
            };

            var tRes = q.Trading.SendTransaction(t).Result;
            Console.WriteLine("Transaction Id = {0}", tRes);
            Assert.True(tRes != -1);

            mre.WaitOne(10000);
            Assert.IsTrue(rised, "Event OnOrder was not rised!");
            AfterTest();
        }
```

так вот, обработчик `t.OnOrder` никогда не будет вызван, потому что это не тот объект который вытягивается из `QuikEvents.cs`:

``` c#
        internal void OnOrderCall(Order order) {
            ......
            var tr = QuikService.Storage.Get<Transaction>(correlationId);
            if (tr != null) {
                lock (tr) {
                    tr.OnOrderCall(order);
                }
            }
```

Может так все и задумано. Тогда как при создании транзакции реагировать на ее события?
Возможно у меня неправильный подход. Кто как тут реализует такие вещи и нужны ли они?

**Comment by Pr0phet1c** [comment]
Возможно, для Вас важно именно колбэки обрабатывать в Вашем алгоритме, но я просто отправляю новую заявку, получая в ответ transactionID этого ордера. По ID - нахожу саму заявку в книге заявок, и далее по мере поступления колбэков, проверяю изменения интересующих меня параметров в этой заявке.

**Comment by sergshabal** [comment]
да можно конечно и так, но раз можно подписаться на событие почему бы не подписаться. видимо это фича которую еще нужно допилить.

**Comment by Pr0phet1c** [comment]
Кстати, обратил внимание, что Вы пытаетесь подписаться на колбэк с привязкой к вашей заявке.
Сильно сомневаюсь, что такое вообще возможно. Работа таких колбэков сводится к тому, что отслеживаются ВСЕ изменения в книге заявок, и каждый вызов колбэка передают информацию о том в какой конкретно заявке произошли изменения. Ваша задача определить произошли ли эти изменения по интересующей Вас заявке (в рамках конкретного робота), или изменения был по другой заявке, и тогда их можно проигнорировать.
Отсюда вывод: Вы в принципе неправильно пытаетесь подписаться на это событие.
В Вашем случае это может выглядеть примерно так:
```
Quik q = new Quik(Quik.DefaultPort, new InMemoryStorage());
q.Events.OnOrder += OnOrderDo;

    void OnOrderDo(QuikSharp.DataStructures.Transaction.Order order)
    {
            .............................
    }
```

**Comment by sm00vik** [comment]
Добрый день. Подскажите пож. как лучше обрабатывать события по стоп-заявке. Самому запрашивать quik или как-то можно через callback. Спасибо. PS Правильно я понял, что данное событие по умолчанию не реализовано здесь?!

**Comment by Pr0phet1c** [comment]
Да, Вы правильно поняли, обработка колбэка OnStopOrder сейчас не реализована (точнее, его реализация не завершена). Я в роботах ими не пользуюсь, т.к. для меня стоп-ордер - это невозможность отреагировать на событие роботом (т.е. ручная торговля). Что именно делать в Вашем случае мне пока трудно сказать. Возможно, есть способ как-то иначе решить задачу.
Если будет время - попробую все же реализовать данный колбэк.

**Comment by buybackoff** [comment]
Я закрываю, но вынес комментом в #195, нужна дополнительная инфа актуально ли это и проблема ли это.
