### ISSUE TITLE
Вывод данных на форму Wpf

### ISSUE THREAD

**Issue by spvik** [finsight/QUIKSharp#60]
подскажите как вывести данные стакана на форму wpf,
как преобразовать данные в itemsource?
_quik.Events.OnQuote += (orderBook) => {
                if (orderBook.sec_code == securityCode)
                {

```
                bestBidPrice = orderBook.bid.OrderByDescending(o => o.price).First().price;
                bestOfferPrice = orderBook.offer.OrderByDescending(o => o.price).Last().price;

                this.Dispatcher.BeginInvoke(new Action(() => Quotes.ItemsSource = ...));


            }
```

**Comment by nubick** [comment]
Создай ObservableCollection<PriceQuantity> collection  и сделай Binding в Quotes.ItemsSource на эту collection.

При каждом событии OnQuote:
collection.Clear();
collection.AddRange(orderBook.bid);
collection.AddRange(orderBook.offer);

Ну или в другом порядке. Как тебе нужно. Решение на вскидку, в редакторе не проверял.

**Comment by spvik** [comment]
Странно, но не получается, 
объявил:  public ObservableCollection<OrderBook.PriceQuantity> collection { get; private set; } 
1) у коллекции нет метода AddRsnge
 collection.Add(orderBook.bid);
в этом случае пишет: Argument type QuikSharp.OrderBook.PriceQuanity[] is not assignable to parameter type QuikSharp.OrderBook.PriceQuanity
 collection.Add(orderBook);
в этом случае: тоже самое

подскажите что не так делаю

**Comment by nubick** [comment]
Я думаю, нужно начать с изучения C#, а потом WPF.
По смыслу же понятно что делает AddRange. Если у тебя нет расширений, реализующих AddRange, то пробегись в цикле и добавь каждый элемент по отдельности.

Но все эти моменты не имеют ни какого отношения к QuikSharp.
