### ISSUE TITLE
Не создается ордер по CreateOrder

### ISSUE THREAD

**Issue by sadersa** [finsight/QUIKSharp#63]
привет
на счете нехватает денег на новую заявку
создаю  через CreateOrder - ожидаю ответа что нет денег а в Events.OnOrder пусто

куда приходят неторговые ответы - типа идет клиринг - нет денег и так далее?

**Comment by buybackoff** [comment]
Можно легко отдебагить ответ от Квика до того, как он обработался QuikSharp.

**Comment by sadersa** [comment]
подскажи плиз как - что гуглить в какую сторону смотреть - про дебаг в квике пока не слышал

**Comment by nubick** [comment]
Попробуй посмотреть событие Quik.Events.OnTransReply.
Ты пытаешься отправить транзакцию на покупку через CreateOrder. Но терминал не принимает эту транзакцию, так как денег нет (но вы держитесь там). И ни каких заявок не создается и OnOrder не вызывается, но должно быть сообщение об этом в OnTransReply. Проверь.

**Comment by sadersa** [comment]
во как - а разве терминал обладает мозгами чтоыб принять решение стоит ему отправлять заявку или нет ? я не думал что даже сервер квик это должен рассматривать - только биржа.
инфа точная?

**Comment by nubick** [comment]
OnTransReply помог?
