### ISSUE TITLE
ссылка в описании функции ведет в никуда

### ISSUE THREAD

**Issue by sadersa** [finsight/QuikSharp#64]
ссылка ведет на ошибочную страничку

        /// <summary>
        /// Возвращает заявку из хранилища терминала по её номеру.
        /// На основе: http://help.qlua.org/ch4_5_1_1.htm
        /// </summary>
        /// <param name="classCode">Класс инструмента.</param>
        /// <param name="orderId">Номер заявки.</param>

**Comment by buybackoff** [comment]
Шлите PR пожалуйста, такое не глядя будем принимать.
