### ISSUE TITLE
Работает ли библиотека с несколькими клиентами?

### ISSUE THREAD

**Issue by sadersa** [finsight/QUIKSharp#65]
привет
будет ли работать ваша разработка при работе с несколькими клиентами
тоесть 1 скрипт луа - и 3-5 клиентов
например написал свой стакан - каждый запускается как отдельое приложение
могут ли они работать с 1м скриптом луи и при этом совершать сделки - предусмотрена ли такая возможность и есть ли потенциальные проблемы - например нумерация внутренних ордеро и так далее

**Comment by buybackoff** [comment]
Нет, скрипт - клиент должны быть 1 к 1, можно запустить несколько скриптов на разных портах, но как они будут вместе работать - не определено.

**Comment by Pr0phet1c** [comment]
Я использую в работе одновременно несколько клиентов. Как и написал buybackoff - делаются копии скриптов Lua и в каждой копии прописываются свои порты. Соответственно, в каждом клиенте, при инициализации подключаемся к "своему" порту. На текущий момент, максимальное количество одновременно запущенных клиентов достигает трех (больше пока не требовалось). Проблем не наблюдал.

**Comment by buybackoff** [comment]
@Pr0phet1c В вашей ветке есть некоторые полезные фиксы. Не могли бы вы слать PR? Напрмер, пробел после open_interest, новое поле ISIN...

**Comment by Pr0phet1c** [comment]
С PR у меня проблемы. До сих пор не научился нормально работать с GitHub. Пока могу только через Issues, как и договаривались ранее.
Вот кстати один фикс, который с делал у себя после последнего слияния с вашей веткой, но я не уверен, что это именно ошибка, а не какая-нибудь особенность:

TradingFunctionsTest.cs:

В оригинале:
`		private void PrintDepoLimits (List<DepoLimitEx> depoLimits)
		{
			Console.WriteLine ("Количество стро: {depoLimits.Count}");
			foreach (var depo in depoLimits)
			{
				Console.WriteLine ($"Код бумаги: {depo.SecCode}");
				Console.WriteLine ($"Счет депо: {depo.TrdAccId}");
				Console.WriteLine ($"Идентификатор фирмы: {depo.FirmId}");
				Console.WriteLine ($"Код клиента: {depo.ClientCode}");
				Console.WriteLine ($"Входящий остаток по бумагам: {depo.OpenBalance}");
				Console.WriteLine ($"Входящий лимит по бумагам: {depo.OpenLimit}");
				Console.WriteLine ($"Текущий остаток по бумагам: {depo.CurrentBalance}");
				Console.WriteLine ($"Текущий лимит по бумагам: {depo.CurrentLimit}");
				Console.WriteLine ($"Заблокировано на продажу количества лотов: {depo.LockedSell}");
				Console.WriteLine ($"Заблокированного на покупку количества лотов: {depo.LockedBuy}");
				Console.WriteLine ($"Стоимость ценных бумаг, заблокированных под покупку: {depo.LockedBuyValue}");
				Console.WriteLine ($"Стоимость ценных бумаг, заблокированных под продажу: {depo.LockedSellValue}");
				Console.WriteLine ($"Цена приобретения: {depo.AweragePositionPrice}");
				Console.WriteLine ($"Тип лимита.  = «0» обычные лимиты, <> «0» – технологические лимиты: {depo.LimitKindInt}");
				Console.WriteLine ($"Тип лимита бумаги (Т0, Т1 или Т2): {depo.LimitKind}");
				Console.WriteLine ($"------------------------------------------------------------------------");
			}
		}
`

у меня в таком виде проект не компилируется.
мой вариант:
`		private void PrintDepoLimits (List<DepoLimitEx> depoLimits)
		{
			Console.WriteLine ("Количество строк: {depoLimits.Count}");
			foreach (var depo in depoLimits)
			{
				Console.WriteLine (@"Код бумаги: {depo.SecCode}");
				Console.WriteLine (@"Счет депо: {depo.TrdAccId}");
				Console.WriteLine (@"Идентификатор фирмы: {depo.FirmId}");
				Console.WriteLine (@"Код клиента: {depo.ClientCode}");
				Console.WriteLine (@"Входящий остаток по бумагам: {depo.OpenBalance}");
				Console.WriteLine (@"Входящий лимит по бумагам: {depo.OpenLimit}");
				Console.WriteLine (@"Текущий остаток по бумагам: {depo.CurrentBalance}");
				Console.WriteLine (@"Текущий лимит по бумагам: {depo.CurrentLimit}");
				Console.WriteLine (@"Заблокировано на продажу количества лотов: {depo.LockedSell}");
				Console.WriteLine (@"Заблокированного на покупку количества лотов: {depo.LockedBuy}");
				Console.WriteLine (@"Стоимость ценных бумаг, заблокированных под покупку: {depo.LockedBuyValue}");
				Console.WriteLine (@"Стоимость ценных бумаг, заблокированных под продажу: {depo.LockedSellValue}");
				Console.WriteLine (@"Цена приобретения: {depo.AweragePositionPrice}");
				Console.WriteLine (@"Тип лимита.  = «0» обычные лимиты, <> «0» – технологические лимиты: {depo.LimitKindInt}");
				Console.WriteLine (@"Тип лимита бумаги (Т0, Т1 или Т2): {depo.LimitKind}");
				Console.WriteLine (@"------------------------------------------------------------------------");
			}
		}
`

Но я не проверял этот кусок кода (не было необходимости), и не уверен что мой вариант правильный, а времени разобраться пока не было.

**Comment by Pr0phet1c** [comment]
Не пора ли закрыть данную ветку?
