### ISSUE TITLE
Transaction callback hell

### ISSUE THREAD

**Issue by buybackoff** [finsight/QUIKSharp#7]
Сдесь будут собираться мысли, как жить и что делать с асинхронными OnTransReply, OnTrade, OnOrder. Самое неприятное место во всем квике.

**Comment by sergshabal** [comment]
Наверное стоит мне сюда написать. Вопрос: создал я новую транзакцию, и хочу обработать ее OnOrder, как это сделать?

Пишу тест:

```c#
        [Test]
        public void SendOrderTest()
        {
            Quik q = new Quik(Quik.DefaultPort, new InMemoryStorage());

            var t = new Transaction()
            {
                ACCOUNT = "NL0011100043",
                CLASSCODE = "QJSIM",
                SECCODE = "SBER",
                ACTION = TransactionAction.NEW_ORDER,
                OPERATION = TransactionOperation.B,
                PRICE = 120M,
                QUANTITY = 1,
                CLIENT_CODE = "101942",
                Comment = "",
            };

            t.OnOrder += (Order o) => {
                Console.WriteLine(
                    "New order regs with num = {0} on transaction {1}",
                    o.OrderNum, t.TRANS_ID);
                rised = true;
                mre.Set();
            };

            q.Events.OnOrder += (Order o) =>
            {
                Console.WriteLine(
                    "New order in QuikEvents regs with num = {0} on transaction {1}",
                    o.OrderNum, t.TRANS_ID);
            };

            var tRes = q.Trading.SendTransaction(t).Result;
            Console.WriteLine("Transaction Id = {0}", tRes);
            Assert.True(tRes != -1);

            mre.WaitOne(10000);
            Assert.IsTrue(rised, "Event OnOrder was not rised!");
            AfterTest();
        }
```

так вот, обработчик `t.OnOrder` никогда не будет вызван, потому что это не тот объект который вытягивается из `QuikEvents.cs`:
```c#
        internal void OnOrderCall(Order order) {
            ......
            var tr = QuikService.Storage.Get<Transaction>(correlationId);
            if (tr != null) {
                lock (tr) {
                    tr.OnOrderCall(order);
                }
            }
```

Может так все и задумано. Тогда как при создании транзакции реагировать на ее события?
Возможно у меня неправильный подход. Кто как тут реализует такие вещи и нужны ли они?

**Comment by buybackoff** [comment]
Нужно ревью логики

**Comment by buybackoff** [comment]
@sergshabal это еще актуально?  [Тут](https://github.com/finsight/QUIKSharp/blob/9edebdc57e40b13b6a4e7d887cce7d48398d2fbe/src/QuikSharp/TradingFunctions/TradingFunctions.cs#L346) мы сохраняем транзакию по CLIENT_CODE, а [тут](https://github.com/finsight/QUIKSharp/blob/9edebdc57e40b13b6a4e7d887cce7d48398d2fbe/src/QuikSharp/QuikEvents.cs#L252) используем `order.TransID`, чтобы найти транзакцию. Возможно это разные поля, иначе должно работать. "Потому что это не тот объект который вытягивается из QuikEvents.cs" Вы не разобрались тогда почему?

**Comment by Agremond** [comment]
Добрый день.
Виктор, Вы говорите что нужно ревью логики. Что именно Вы ожидаете от ревью?

QS позиционируется Вами как набор функций QLUA на языке C#, если так, то логика обработки асинхронных событий OnOrder, OnTransReplay, OnTrade и др. ложится на плечи конечного пользователя QS.
Ежели Вы хотите, получить что то более "умное", надстройку над обозначенными функциями, сняв бремя асинхронной обработки с конечного пользователя, то по идее нужно реализовать механизм обработки обозначенных выше событий.

**Comment by buybackoff** [comment]
Я пытался следать "умно" изначально, и в нескольких issue (выше их видно, часто ссылался на этот issue) поднимался вопрос. Пока видение, что мы просто повторяем то, как ведет себя QLUA. К такому поведению все привыкли и оно задокументировано. Делать умную надстройку пока нет времени. И если её делать, то в общем виде как отдельную библиоеку - чтобы работало с любой системой выставления ордеров. Может кто-то уже сделал подобное.

**Comment by Agremond** [comment]
По части работы с другими системами не скажу, нет опыта.
Почему как отдельную библиотеку.
Вероятно под более "умно" Вы подразумваете, работу на уровне ордеров и их интерфейсов(создать, получить текущий статус и т.д., удалить, заменить)?

 Для себя я делаю обработку асинхронных On... ,  на основе общих рекомендаций, найденных на форуме QUIK [здесь](https://forum.quik.ru/messages/forum10/message11805/topic1302/#message11805). Могу рассказать подробнее, если интересно.

**Comment by buybackoff** [comment]
Под "умно" - линковать все связянные с транзакцией последующие события, которые со стороны Квика могут приходить в совершенно произвольном порядке. PR на эту тему welcome :)

**Comment by Agremond** [comment]
Связывание событий у меня сейчас происходит и служит для отслеживания текущего сотояния заявки, ее цикла жизни. Для этого хранятся все события исключая дубляжи и посредством нехитрой логики их разбираю. В процессе разбора меняется состояние заявки. Вот и все.
Преждем чем отправлять PR, мне нужно понимать что Вы ожидаете, так как сейчас логика реализована(она еще не закончена) вне библиотеке, а на базе примера QuikSharpDemo.

По большому счету, заявки можно отслеживать и через _quik.Orders.GetOrders().Result;, но я решил что это нерационально и медленно.

**Comment by buybackoff** [comment]
Это за пределами цели проекта "повторить QLUA API". Если у кого есть идеи как решить это в общем виде - пишите в #195
