### ISSUE TITLE
Реализовал колбэк OnStopOrder

### ISSUE THREAD

**Issue by Pr0phet1c** [finsight/QuikSharp#70]
Не уверен, что с точки зрения автора проекта моя реализация данного колбэка достаточно корректна, но работает (проверил).

З.Ы.: Попытался создать PR, но там ТАКОЕ вылезло, что я испугался и резко передумал.

**Comment by sm00vik** [comment]
Я попробовал по аналогии с onOrder, но пока не получилось. Еще надо малость поразбираться.

**Comment by Pr0phet1c** [comment]
Я обработал этот колбэк по аналогии с OnOrder, получив и выведя в сообщение номер стоп-заявки. Все сработало, на этом остановился.

Отправлено с моего Windows Phone

-----Исходное сообщение-----
От: "sm00vik" <notifications@github.com>
Отправлено: ‎15.‎07.‎2016 17:25
Кому: "finsight/QuikSharp" <QuikSharp@noreply.github.com>
Копия: "Prophetic" <prodeaner@gmail.com>; "Author" <author@noreply.github.com>
Тема: Re: [finsight/QuikSharp] Реализовал колбэк OnStopOrder (#70)

Я попробовал по аналогии с onOrder, но пока не получилось. Еще надо малость поразбираться.
