### ISSUE TITLE
Ряд вопросов

### ISSUE THREAD

**Issue by alphagenerator** [finsight/QuikSharp#72]
Здравствуйте Виктор! Очень благодарю Вас за проделанную работу и публикацию! На мой взгляд проект вполне может стать трендовым у Quik юзеров, для этого есть ряд веских причин. 

Хочу протестить библиотеку, попробовать перенести свои сетапы с ДДЕ на Вашу разработку сделав по ходу дела парочку примеров имплементации вашей либы на практике, которые Вы если захотите, затем можете включить в проект. Наверняка возникнет ряд вопросов и если Вы не против то я хотел бы здесь их обсудить. Свечки приходят стаканы, лента, шлются заявки, супер! https://i.gyazo.com/1b94c9f76f396625cde69a6e120dc34b.gif 

Но как ни странно не удалось получить данные по счету маржу лимиты net по фьючевым позам(((
Не понял что писать в 
quik.Trading.GetFuturesHolding();
quik.Trading.GetDepo();
или прочеех

чтобы получить это:

https://i.gyazo.com/64b2a36fb3a801320edbb63ac208696b.png

Заранее спасибо!

**Comment by buybackoff** [comment]
Вероятно эти функции еще не написаны, шлите pull request!

**Comment by alphagenerator** [comment]
Сорри протупил
await quik.Trading.GetFuturesHolding("MC0000200000", "SPBFUT00646", sec, 0); работает

но как счет получить общий() пока не нашел((

**Comment by alphagenerator** [comment]
хотел комитнуть пример нет доступа, если откроете добавлю пример со стаканом лентой и графиками

**Comment by buybackoff** [comment]
Если оставить все церемонии, я так и не понял, в чем проблема? И какой доступ вам нужен? Если Вы видите, что некоторая функция реализована, но не работает, покажите пример, и мы исправим. Если она не реализована и нужна Вам, мы тоже поможем ее реализовать и тут есть куча примеров как добавить функционал. В коде все просто понять что уже работает, и до чего не дошли руки.

**Comment by alphagenerator** [comment]
Как получить дату из таблицы «Портфель по бумагам»( Стоимость портфеля, ВходСредства, ТекСредства, Прибыль/убытки, ПроцИзмен, Вариац. маржа, Шорты, Лонги, На покупку, На продажу, Плечо, Тек.плечо)? Приведите пожалуйста пример строки кода.
Пробовал: GetDepo(),GetDepoLimits() либо неверно что то ввел либо что то не работает
В GetMoney непонятны некоторые поля такие как tag например, тоже лучше пример чтобы долго не писать

Я не разбираюсь в луа к сожалению и какие есть в ней функции, могу только сказать какие таблицы с квика нужно получать. В идеале сделать универсальную функцию получения любой таблицы как по дде, если конечно это возможно. Или разъяснить как это делать самому, так как если для каждой таблицы нужно писать функцию то Вы от меня утомитесь быстро.

Доступ я имел в виду чтобы примеры кидать в проект, комитить

**Comment by Pr0phet1c** [comment]
alphagenerator, как раз вчера мне потребовалось получить таблицу лимитов по бумагам.
Вот Вам рабочий пример:
`
List<DepoLimitEx> depoLimitsTable;
depoLimitsTable = new List<DepoLimitEx>();
depoLimitsTable = quik.Trading.GetDepoLimits().Result;
`
