### ISSUE TITLE
Как установить соединение

### ISSUE THREAD

**Issue by Yorkst** [finsight/QUIKSharp#73]
Использую архив с гитхаба и Finam Junior (Quik 7.0.0.289).

После переустановки всех nuget пакетов проект компилируется.

Запустил QuikSharp.lua через Сервисы/Lua скриты/Добавить/Запустить. Последнее его сообщение - "Connecting...".
Запускаю Console Application с таким кодом:

```
using System;
using QuikSharp;

namespace QuikTest
{
    class Program
    {
        static async void TestQuik()
        {
            Console.WriteLine("Creating Quik");
            var quick = new Quik();
            Console.WriteLine("Created Quik");
            var isQuik = await quick.Debug.IsQuik();
            Console.WriteLine(isQuik);
        }
        static void Main(string[] args)
        {
            TestQuik();
            Console.ReadLine();
        }
    }
}

```

Падает с InvalidOperationException "Please, start QUIK first and run the lua script "

Т.е. мне надо дождаться сообщения connected от quik? Но оно не появляется. Надо что-то еще сделать?

**Comment by Pr0phet1c** [comment]
Попробуйте вот так:

_quik = new Quik(Quik.DefaultPort, new InMemoryStorage());

**Comment by Yorkst** [comment]
Результат тот же.
Внутри qsutils.lua , в методе getResponseServer(), вот этот вызов никогда не завершается:
`local status, client, err = pcall(response_server.accept, response_server )`
В документации по accept сказано, что эта функция ждет подключения:
http://w3.impa.br/~diego/software/luasocket/tcp.html
Но судя по ошибке C#, это он ждет подключение:
QuikService.EnsureConnectedClient в этом месте
`while (!connected) {
    try {
        _responseClient = new TcpClient {
            ExclusiveAddressUse = true,
            NoDelay = true
        };
        _responseClient.Connect(_host, _responsePort);
        connected = true;
    } catch {
        //Trace.WriteLine("Trying to connect...");
    }
}`
Съедает исключение "No connection could be made because the target machine actively refused it"

**Comment by buybackoff** [comment]
Проверьте, что порты совпадают и что firewall не блокирует соединение. Lua - это tcp-сервер, к нему подключается c# клиент. 

"No connection could be made because the target machine actively refused it" - такая ошибка обычно возникает, когда на порте никто не слушает соединения, или кто-то их активно рубит.

**Comment by Yorkst** [comment]
Я добавил правило в inbound rules, и outbound rules, но дело не в firewall-е.
Если создать TCP сервер таким образом, код который выше не падает с исключением. (Но и ничего не делает, естественно)
```
using System;
using System.Net.Sockets;
using System.Net;
using System.Threading.Tasks;

namespace Tcp
{
    class Program
    {
        static void WaitForClients(IPAddress ip, int port, string serverName)
        {
            var server = new TcpListener(ip,port);
            server.Start();
            while (true)
            {
                Console.WriteLine("Waiting for a connection to a " + serverName + " server");
                var client = server.AcceptTcpClient();
                Console.WriteLine("Accepted a client of " + serverName + " server");
            }
        }
        static void Main(string[] args)
        {
            Task.Run(()=> WaitForClients(IPAddress.Parse("127.0.0.1"), 34130, "response"));
            WaitForClients(IPAddress.Parse("127.0.0.1"), 34131, "callback");
        }
    }
}
```
А с lua проблема.

В `qsutils.lua` getResponseServer виснет на этой строке:
`local status, client, err = pcall(response_server.accept, response_server )`

Я думал, может быть поблеа с версией quik, но если запускать lua через командную строку, то же самое. Отладочный вывод доходит до этой строки и больше ничего не присходит.

Если кто-то готов помочь с teamviewer-а, пишите на Dandrag@mail.ru

**Comment by buybackoff** [comment]
Как вы запускаете Луа из командной строки? Может проблемы с версией Луа на
машине, по ходу дела Луа даже не может создать сервер или не может принять
соединение.

Так как у большинства работает "из коробки", я бы смотрел в сторону системы
- зависимости, битность, версии Луа. Проект работает с версией Луа 5.1,
может быть у вас новее?

Там был интересный случай, что разные библиотеки работают с lua5.1.dll и
lua51.dll (без точки), поэтому в комплекте идет обертка, которая форвардит
вызовы из одной в другую. Не утверждаю, что в этом дело, но может подобная
алхимия...

**Comment by Yorkst** [comment]
Запуск делаю так. Файл из репозитория, только добавил отладочный вывод:

```
C:\Program Files\QUIK-Junior\QuikSharp>lua QuikSharp.lua
A subdirectory or file logs already exists.
LOG 0: Hello, QuikSharp! Running outside Quik.
LOG 0: Entered main function
LOG 0: > start
LOG 1: Connecting...
LOG 0: > getting server
LOG 0: Waiting for a server
LOG 0: > entering pcall
```
Сам метод, который виснет:
```
local function getResponseServer()
    log('Waiting for a server')
    local i = 0
    while true do
        log("> entering pcall")
        local status, client, err = pcall(response_server.accept, response_server )
        log("> left pcall")
        if status and client then
            return client
        else
            log("> server error")
            log(err, 3)
        end
    end
end
```

У меня lua51.dll без точки. Весит 166 кб, в отличие от той, которая идет с quik sharp. Номер на ней не указан
Получил компиляцией кода 5.1.5, как показано здесь: http://www.thijsschreijer.nl/blog/?p=863

Попробую 5.1.0

**Comment by buybackoff** [comment]
То есть вы запускаете Луа используя те же самые бинарники, что идут с
Квиком? Попробуйте установить отдельно Lua for Windows, скорее всего дело в
этих бинарниках, если в обоих случаях они одни и те же.

**Comment by buybackoff** [comment]
Если в QuikSharp без точки, то какие-то модули будут вызывать ее, и
ожидать, что в системной папке есть библиотека с точкой (с телефона пишу,
не помню что в комплекте идет как обертка, там вроде около 5 кб всего).
Помню, что в системной папке должна быть Луа противоположная той, которая в
КвикШарп - с точкой или без.

**Comment by buybackoff** [comment]
И не пойму, вы скопировали QuikSharp.lua туда, где Луа, или опустили
рабочую папку, когда показывали, как вызываете скрипт из строки? Там есть
зависимости, вы точно вызываете скрипт из оригинальной папки?

**Comment by Yorkst** [comment]
Помогает замена
```
local response_server = socket.bind('localhost', port, 1)
local callback_server = socket.bind('localhost', callback_port, 1)
```
На 
```
local response_server = socket.bind('127.0.0.1', port, 1)
local callback_server = socket.bind('127.0.0.1', callback_port, 1)
```
Я не представляю, чем это может быть вызвано

**Comment by buybackoff** [comment]
может в файлом hosts что-то делали и убрали эту стандартную строку...

**Comment by webhive** [comment]
В общем словил похожую проблему. Вот тут https://github.com/finsight/QuikSharp/issues/52#issuecomment-252502654 уже писал по этому поводу, но порыл чуть глубже и в конце-концов дошёл до этой ветки.

Как писал @FoKycHuK таск никогда не завершается. А не завершается он по причине которую описал чуть выше @Yorkst. А именно - Lua сервер не отвечает. Т.е. эти 2 проблемы - на самом деле одна и та-же проблема.

Но всё ещё интереснее. Если перезагрузить машину, то волшебным образом всё начинает работать. Но не более 1-2 запусков программы - потом всё опять встаёт.  Если заменить версию QuikSharp (как писал @FoKycHuK) всё работает но опять же - только 1-2 запуска программы, потом опять сервер перестаёт отвечать. Причём работает и в обратную сторону - т.е. сначала используешь версию из мастера - 1-2 запуска, всё встало -> откат на версию из nuGet - опять 1-2 успешных запуска и теперь всё не работает с обеими версиями. Помогает только перезагрузка. 

Пробовал закрывать Quik, закрывать программу (даже прибивал процессы и вручную закрывал все открытые сокеты) - ничего не помогает - только перезапуск. Потом опять 1-2 раза всё работает отлично и опять висим. 

Замена localhost на 127.0.0.1 в моём случае ничего не дала. 

Ну и насчёт 1-2 запусков. Вообще-то как правило 1 запуска достаточно - следующий уже не работает, но когда решил окончательно всё проверить почему-то запустилось 2 раза успешно, а уже начиная с 3-го работать перестало.

Вот такой вот квест получился. Звучит довольно бредово, но всё именно так как я описал. Куда рыть дальше ума не приложу.  Может у кого-то будут какие-то ещё идеи.

**Comment by FoKycHuK** [comment]
@webhive отличное расследование! :) 
У меня почему-то с версией из мастера все работает вообще без пререканий, хоть 100 раз.
Правда, я брал версию где-то пол года назад и с тех пор не обновлял. Выкачал проект один раз, залил в свой репозиторий и добавил в референсы, Если нужна старая версия -- дай знать, залью куда-нибудь отдельный проект, или возьми мастер за январь с какого-нибудь коммита.

А версия из нюгета у меня так и не работала вообще. Перезагрузки и прочее не помогало.

**Comment by webhive** [comment]
> Если нужна старая версия -- дай знать, залью куда-нибудь отдельный проект, или возьми мастер за январь с какого-нибудь коммита.

Может глянешь тогда версию коммита чтоб уж наверняка? 
```
$ git log --oneline -n 1
``` 
Я бы проверил.

**Comment by FoKycHuK** [comment]
@webhive
У меня не сабрепозиторий и не форк, так что это не поможет ( я просто все файлы залил в чистый репо.

**Comment by webhive** [comment]
Ещё на заметку. Попробовал сегодня поконнектиться telnet-ом к lua серверу. Ну это чтобы исключить влияние c# кода и проверить как себя ведёт только сам quik. Ну так вот поведение точно такое же - 1-2 раза телнетом можно к серверу присоединиться, а потом ошибка "Сбой подключения". 

Делаю это так

``
$ telnet localhost 34131
`` 

Плюс такая ещё странность. После того как telnet на localhost перестаёт работать я могу ещё 1-2 раза законнектиться на 127.0.0.1 (ну и наоборот тоже работает сначала на 127.0.0.1 - потом на localhost). 

А вот когда оба уже отказываются принимать соединение - то тогда уже всё  только перезагрузка. 

Т.е. судя по всему проблема именно где-то на стороне Lua-сервера.

**Comment by webhive** [comment]
Аааааа! Заработало! Хотя и через жопу :( 
Взял Lua сервер от версии из NuGet-а, а клиент из master-а git-a.

**Comment by webhive** [comment]
Блин - опять перестало работать. Но зато я наконец разобрался со всей этой историей. Проблема как оказалось описана тут #65. Т.е. 2 клиента одновременно не могут коннектиться на один и тот-же порт. В этом случае первый клиент получает данные, а остальные висят. В моей конкретно ситуации при определённых условиях создавалось дополнительное подключение на тот же порт, которое и блокировало дальнейшие попытки.

**Comment by buybackoff** [comment]
В Lua у нас параметр backlog в [socket.bind/listen](http://w3.impa.br/~diego/software/luasocket/tcp.html#listen) установен как 1. Любая попытка коннекта после первого соединения заполнит эту очередь. По идее получается, что если была вторая попытка коннекта, то Lua брала соединение из очереди (которое к тому моменту могло быть мертвое, тогда Луа могла выкидывать ошибку, которую нигде не было видно), а активное соединение из C# или разрывалось, так как не было места в очереди, либо помещалось в очередь, но никогда не бралось Луой в текущем сеансе связи. Это мои фантазии, не знаю как это именно работает ОС (http://stackoverflow.com/a/4254062/801189).

Наверное можно сделать возможность иметь нескольких клиентов на один порт, или принимать всех outstading клиентов и оставлять только последнего (по таймауту - если акцепт вернул таймаут, берем последнего клиента). Но это все сильно усложняет код, и не понятно для чего нужно, если 1-1 соединение задокументирвано, и логику нескольких соединений можно реализовать как несколько логических потоков через одно TCP соединение. У нас мультиплексинг, можно слать сообщения независимо, мы не ждем ответа синхронно, а собираем запрос-ответ по id. В Квике все равно есть мютекс какой-нибудь, и пока не придет ответ на заявку, вторую не получится поставить на исполнение.

**Comment by webhive** [comment]
Тут вот ещё какой момент есть. В VisualStudio рисую wpf форму. Добавляю DataContext - в дизайнере автоматически появляются все поля для биндинга. НО! Вот тут-то и появляется проблема - студия-то сама по себе держит один коннект (для дизайнера). И когда запускаю программу - создаётся фактически-то второй коннект. 

Да - можно сказать - визуальный дизайнер для слабаков и создавай биндинги в рантайме. Но хочется всё-таки, чтоб работало и в дизайнере тоже, чтоб заниматься кодингом именно "мяса", а формочки и списки накидывать мышкой.

**Comment by buybackoff** [comment]
Вообще QuikSharp должен быть singleton static service per port. Все другие сценарии не поддерживаются. Приложение должно использовать одно и то же соединение во всех местах.

**Comment by webhive** [comment]
Ну да - но это справедливо только в контексте одного приложения. Если приложения разные - то в каждом из них свой singleton instance.

**Comment by webhive** [comment]
Вообще сценарий когда к серверу подключено несколько разных приложений не выглядит какой-то фантастикой. Вместо того, чтобы городить одно мега-приложение "всё в одном" вполне логично сделать несколько более простых. 

И в этом случае ограничение на одновременное число подключений это конечно жестокий облом. 

Погуглил тут на досуге - есть вот такая штука http://keplerproject.github.io/copas - с виду похоже, что малой кровью можно сделать вполне себе многопоточный сервер. Не знаю как quik к этому отнесётся, но с учётом того, что в lua многопоточность не настоящая вполне может прокатить - всё равно физически-то запросы в quik будут идти последовательно.

**Comment by buybackoff** [comment]
Можно и в текущей версии принимать больше 1-го, хранить всех клиентов в таблицу и делать импровизированный pubsub. В main() периодически проверять, нет ли желающих еще подлючится. Но это кодинг ради кодинга, когда проблему можно просто решить более простым дизайном с заданными ограничениями. Шлите PR, если сделаете :)

Но тогда уже проще сделать один сервис с IPC. Я что-то похожее неспеша делаю - QuickSharp крутится в отдельном процессе, и получает команда/отсылает ответы другим процессам. Вся философия проекта в том, что это обертка/shim над Lua в Квик, а не дополнитльный фунционал. То есть если Квик у вас один - то и работать нужно с одним его представлением в C#.

В текущей версии несколько приложений могут работать на разных портах.

**Comment by webhive** [comment]
Хммм - попробовал ``copas``. Ммда - "не выходит каменный цветок". Всё походу упирается в неспособности Lua поддерживать нормальную мультипотоковость. Короче ``copas`` каждое соединение рвёт после выполнения обработчика коннекта. Попробовал в лоб - зациклить каждый обработчик, но тогда текущий "thread" монопольно занимает всё время, а Lua переключать потоки не умеет. 

В общем на Lua можно сделать "многопотоковым" только что-то типа http без keep-alive. Ну либо дописывать ещё и клиентскую часть, но это уже действительно перебор.  

> Но тогда уже проще сделать один сервис с IPC.

У меня родилась идея сделать прокси. Многопоточный со стороны c#, чтобы  принимать коннекты от разных клиентов QuikSharp и однопоточный к quick. Сделать такую штуку можно вполне себе малой кровью. Логика там получится простая как валенок, накладных расходов каких-то оно в принципе тоже не должно создавать. На досуге пожалуй даже и попробую.  

> В текущей версии несколько приложений могут работать на разных портах.

На самом деле вот эта проблем с одним коннектом довольно критичная. В частности насколько я понял проблемы с wpf это не вопрос непонимания людьми нюансов async/await - это тут не при чём (я проверил :)). Это именно проблема когда при использовании DataContext в дизайнере у нас неявно создаётся дополнительный экземпляр QuickSharp, который всё и портит. 

Т.е. если пишешь на wpf но все биндинги прописываешь в коде руками то оно будет работать в любом случае - главное обеспечить условие, чтоб был гарантированно один коннект. 

Если же биндинги делать через дизайнер то тут как раз и начинаются проблемы, т.к. предугадать когда IDE запросит данные невозможно. Дизайнер форм довольно неплохо данные кэширует, поэтому обращения к quik происходят не так уж и часто. Но этот как раз делает работу ещё более непредсказуемой.

**Comment by buybackoff** [comment]
Это хороший пример, когда использование дизайнера усложняет жизнь, хотя на
первый взгляд упрощает... Я только недавно освоил WPF и MVVM pattern, и
вообще не понимаю, откуда берутся у вас магическим еще один экземпляр
соединения!? Делайте байндинги вручную, это довольно просто, тем более со
всякими фреймворками типа Caliburn.Micro.

Насколько я помню, у меня там есть статический метод, который обеспечивает
"сингтон на порт", то есть не дает создать два инстанса на один порт и
переиспользует уже созданный, используйте его или такую же логику.

2016-10-12 10:00 GMT+03:00 Roman Tataurov <notifications@github.com>:

**Comment by webhive** [comment]
> Это хороший пример, когда использование дизайнера усложняет жизнь, хотя на
первый взгляд упрощает...

Ну тут на любителя. Попробуйте руками боле-менее сложный грид забиндить, а потом этот биндинг поддерживать в рабочем состоянии :)

> не понимаю, откуда берутся у вас магическим еще один экземпляр соединения!?

Ну например. Кидаем на форму DataGrid. Дальше можно руками набивать ему данные в коде, но концептуально более правильно создать отдельный класс, который и занимается загрузкой данных. Этот класс назначается полю DataContext DataGrid-а. Сделать это можно опять же либо в коде руками, либо просто в свойства DataGrid-a выбрать из списка. Во втором случае насколько я понимаю механику работы - дальше уже дизайнер сам создаёт экземпляр этого класса (у себя внутри - в адресном пространстве VisualStudio) и с его помощью подгружает данные (в дизайнере). 

Ну а дальше можно прям в дизайнере рисовать колонки, биндить к ним поля и тут же видеть прям в дизайнере результат, оформлять их, форматировать и т.п.  Огромное количество времени экономится на разработку UI. И результат видно прям сразу. Нет процесса - поменял цвет - скомпилил - не понравилось - опять поменял скомпилил и т.д. Фактически рисуешь UI с живыми данными. 

> Насколько я помню, у меня там есть статический метод, который обеспечивает "сингтон на порт",

Сдаётся мне, что как ни верти синглтон будет один в контексте приложения. В случае с дизайнером у нас 2 приложения. Первое это VisualStudio с дизайнером который создал экземпляр этого класса у себя. Второе это разрабатываемая программа. В каждом из этих приложений да - будет один экземпляр. Но фактически будет 2 приложения и в каждом из них синглтон экземпляр QuikSharp лезущий в quik на один и тот же порт.

**Comment by buybackoff** [comment]
Выложите свой пример ;) Я как раз последнюю неделю вожусь с WPF и мне уже
тошно от него по сравнению с Angular2. Я бы сделал локальный вэб-сервер на
основе QS и Angular2 module, чтобы можно было торговать из браузера через
вэб-интерфейс... Через Эксель я уже делал, можно еще поизвращаться :)

2016-10-12 12:43 GMT+03:00 Roman Tataurov <notifications@github.com>:

**Comment by webhive** [comment]
> Выложите свой пример

Да смысла большого не вижу куда-то выкладывать. Там кода-то с гулькин нос - просто тестовый пример. Могу зипануть да на почту выслать. 

> Я как раз последнюю неделю вожусь с WPF и мне уже
тошно от него по сравнению с Angular2. Я бы сделал локальный вэб-сервер на
основе QS и Angular2 module, чтобы можно было торговать из браузера через
вэб-интерфейс... 

Ааааа! Бьюсь в истерике :) Точно такая-же фигня. 

> Через Эксель я уже делал, можно еще поизвращаться :)

Да-да-да - с этим наигрался - возможностей уже не хватает - захотелось копнуть глубже и вот я тут.
