### ISSUE TITLE
Когда будут реализованы GetMoney, GetMoneyEx, GetPortfolioInfo, GetPortfolioInfoEx?

### ISSUE THREAD

**Issue by smihus** [finsight/QUIKSharp#75]
Хотел узнать когда вы планируете реализовать эти функции.

**Comment by buybackoff** [comment]
Когда кто-нибудь пришлет pull request ;)

**Comment by smihus** [comment]
Понятно :)
Придется разбираться глубже, а ведь хотел воспользоваться библиотекой, чтоб с lua не разбираться.

**Comment by buybackoff** [comment]
Там по шаблону других функций можете скопировать, все очень просто. В процессе за одно и с Луа освоитесь - на мой взгляд это самый простой язык, проще Питона и JavaScript

**Comment by smihus** [comment]
Отправил Pull Request с реализацией функции GetMoney

**Comment by buybackoff** [comment]
Проверили работоспособность? (сегодня вск) Хорошо бы добавить тест с примером вызова функции.

**Comment by smihus** [comment]
У себя проверил, получил закешированные в Quik данные по лимиту. Тест хотел добавить, но не удалось заставить работать проект с тестами :(.
Завтра вечером еще попробую. 
Это мой первый пул реквест и у меня есть несколько вопросов:
1. У меня форматирование несколько отличается от вашего, соответственно оно все попало в git. Вряд ли вам мое форматирование интересно. Как этого избежать. Чтобы каждый раз свое форматирование не отменять перед коммитом.
2. Несколько nuget пакетов имеют более новые версии и у меня работает только с ними. А с теми версиями, что клонировались отсюда не работают. Должна ли информация об обновленных пакетах попадать в пул реквест?
3. Если у меня не получится заставить работать проект с тестами, сможете помочь?

**Comment by buybackoff** [comment]
1. У меня нестандартное форматирование, потому что маленький ноутбук, большой шрифт и я поэтому не терплю лишние строки с `{`, `}`, которые отнимают целую строку (и еще привык к F# 😄) ). Это отличается от стандартного форматирования для C#, но мне все равно в каком виде вы засабмитите, сочетание клавиш Ctrl + E + D все форматирует назад под меня (и под вас на вашей стороне). Шум в истории Гит переживу, пока мало людей работают с исходниками.
2. Обновляйте пакеты, это всегда хорошо. А с какими не работает?
3. Пишите, чем можем поможем.

**Comment by smihus** [comment]
Понятно :). Вечером еще раз попробую запустить проект с тестами, если не заработает, напишу.16.10.2016, 20:27, "Victor Baybekov" <notifications@github.com>:
У меня нестандартное форматирование, потому что маленький ноутбук, большой шрифт и я поэтому не терплю лишние строки с {, }, которые отнимают целую строку (и еще привык к F# <g-emoji alias="smile" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f604.png" ios-version="6.0">😄) ). Это отличается от стандартного форматирования для C#, но мне все равно в каком виде вы засабмитите, сочетание клавиш Ctrl + E + D все форматирует назад под меня (и под вас на вашей стороне). Шум в истории Гит переживу, пока мало людей работают с исходниками.
Обновляйте пакеты, это всегда хорошо. А с какими не работает?
Пишите, чем можем поможем.

**Comment by buybackoff** [comment]
Уже реализовано
