### ISSUE TITLE
примеры работы с квик

### ISSUE THREAD

**Issue by dasmeer** [finsight/QUIKSharp#77]
привет, может кто-нибудь дать мне примеры:

1 загрузки исторических данных из квика (вх параметр - интсрумент, напр. srz6)
2 подачи заявки, выставление stop-loss и take-profit (инструмент, out номер заявки)
3 отмена заявки (номер заявки)

?

**Comment by buybackoff** [comment]
а что в тестах не хватает? или в хелпе в QLUA?

**Comment by dasmeer** [comment]
мб понятности? вы сделали надстройку над ЛУА, работает и круто, зачем мне лезть в дерби винды, если я хочу ей пользоваться для работы? можете помочь с конкретными вопросами 1,2,3 или сказать хотя бы метод как называется в тестах, напр, загрузки данных не нашел...

**Comment by Pr0phet1c** [comment]
Попробуем начать с простого.
Правильно ли я понимаю, что с QLua (этот тот интерпретатор языка, который используется в Квике, для написания скриптов) Вы не знакомы?
Если мое первое предположение верно, то удалось ли Вам хотя бы просто подключиться своим приложением, использующем библиотеку QuikSharp, к квику и получить например статус коннекта к серверу?

**Comment by dasmeer** [comment]
QLua не знаком, пока устатанавливаю студию 2015, так как 2012 не работает с C# 6, как получится соединиться отпишу, спасибо

**Comment by Pr0phet1c** [comment]
ОК. Как будете готовы - попробуем двинуться дальше. Однако, справку по QLua из квика я все равно настоятельно рекомендую изучить, т.к. большинство команд в QS по сути представляют из себя такие же команды (функции/методы) как и в QLua. Плюс к этому, в той справке есть описания и структура различных параметров, которые возвращаются такими командами. Я, например, просто скопировал себе отдельно файл QLUA.chm из папки квика, и периодически использую его для поиска необходимой информации.

**Comment by dasmeer** [comment]
вчера пытался запустить тест 

class Program
    {
        static async void TestQuik()
        {
            Console.WriteLine("Creating Quik");
            var quick = new Quik();
            Console.WriteLine("Created Quik");
            var isQuik = await quick.Debug.IsQuik();
            Console.WriteLine(isQuik);
        }
        static void Main(string[] args)
        {
            TestQuik();
            Console.ReadLine();
        }
    }

упало с ошибкой _responseClient.Connect(_host, _responsePort);

Exception: Exception thrown: 'System.Net.Sockets.SocketException' in System.dll ("Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение"). Exception thrown: 'System.Net.Sockets.SocketException' in System.dll ("Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение")

может ли это быть вызванно версией квика или тем что торговля в это время не велась (это было в час ночи по мск)?

**Comment by buybackoff** [comment]
надо запустить скрипт внутри Квика перед тем, как пытаться соединяться

**Comment by dasmeer** [comment]
проверил сейчас,  нет, с торговлей это не связанно

**Comment by dasmeer** [comment]
какой скрипт нужно запустить?

**Comment by buybackoff** [comment]
QuikSharp.lua из папки lua

**Comment by dasmeer** [comment]
запустил, все работает, Спасибо! этот скрипт нужно постоянно запускать или он автоматом будет подключаться?

**Comment by buybackoff** [comment]
нужно, чтобы он всегда работал внутри Квика. Не помню на 100%, но вроде бы если его не останавливать, то при следующем запуске Квика он вроде автоматически запустится.

**Comment by Pr0phet1c** [comment]
1. Скрипт стартует автоматически, при запуске Квика (если перед этим не был остановлен принудительно или из-за ошибки/сбоя)
2. вот пример создания заявки (странно, что не смог найти его здесь, ведь раньше я уже давал такой пример):
`
        QuikSharp.DataStructures.Transaction.Order order_new = new QuikSharp.DataStructures.Transaction.Order();
        order_new.ClassCode = "EQBR";
        order_new.SecCode = "SBER";
        order_new.Operation = Operation.Buy;
        order_new.Price = 300;
        order_new.Quantity = 1;
        order_new.Account = ""; // подставить свой Account ID
        order_new.ClientCode = ""; // подставить свой код клиента
        long res = await _quik.Orders.CreateOrder(order_new).ConfigureAwait(false); // в качестве результата получим номер транзакции
`
Попробуйте, и сообщите о результатах. после этого двинемся дальше.

**Comment by dasmeer** [comment]
да, спасибо за пример, я уже написал что-то подобное:

var buyOrderId = quik.Orders.CreateOrder(new Order()
            {
                ClassCode = "TQBR",
                SecCode = "SBER",
                Operation = Operation.Buy,
                Price = 100,
                Quantity = 10, //in lots
                Account = "L01-00000F00",
                ClientCode = "ХХХХХ"
            }).Result;// .ConfigureAwait(false);

возвращает 4, ошибка "Неверный код клиента" хотя код клиента я беру из квика из таблицы лимитов, кит финанс... еще по количеству можете сориентировать, это то что мы пишем в завяке, когда создаем ее в квике напр 1 (кол-во лот (10)) пишем в коде 1 или 10 для одной заявки?

**Comment by dasmeer** [comment]
есть какие-то логи того, что приходит в квик?

**Comment by Pr0phet1c** [comment]
1. Странно, что у Вас это не работает. Я уже давно "зашил" этот код в метод и пользуюсь без проблем. Возможно Вас сможет натолкнуть на какие-то мысли то, что кроме указанных очевидных наименований в квике есть также FirmID.
я вообще не указываю эти параметры вручную, а определяю их автоматически:

                clientCode = await quik.Class.GetClientCode().ConfigureAwait(false);
                accountID = await quik.Class.GetTradeAccount(classCode).ConfigureAwait(false);
                firmID = (await quik.Class.GetClassInfo(classCode).ConfigureAwait(false)).firmid;


При этом, в коде формирования заявки и меня подставляются именно accountID и clientCode.

2. Количество в заявках указываем в лотах, т.е. для Вашего примера, пишем "1". Причем, когда вы вытаскиваете и квика остаток по бумаге, то получаете значение уже в количестве акций, т.е. для рассматриваемого примера будет 10.
3. Про логи того, что приходит в квик не слышал. Когда мне нужно было проверить что туда пришло, а в Qlua-скрипт добавлял вывод сообщения с интересующей меня информацией, но поверьте: тот пример, который я Вам дал работает, т.к. его проверили уже несколько человек.

**Comment by dasmeer** [comment]
может ли это быть связанно с тем что у меня два счета на основном рынке? (один ИИС) 
что у вас делает quik.Class.GetClientCode() можно пример?

**Comment by dasmeer** [comment]
написал в поддержку брокера, может они что подскажут..

**Comment by Pr0phet1c** [comment]
1. Теоретически, из-за наличия двух счетов на одной секции рынка, такое возможно. НО: Из той же теории следует, что раз мы указываем и код клиента и AccountID, где один из параметров это и есть номер счета с которым работаем, то предположение о проблеме двух счетов скорее всего неверное. Возможно, Вам имеет смысл попытаться создать заявку с помощью отдельного скрипта на QLua, чтобы найти работоспособную комбинацию (если надо - могу помочь в написании такого скрипта).
2. Я же привел пример реальной строки для quik.Class.GetClientCode(). Что конкретно Вам показалось непонятным в нем? Хотя, проверьте доступен ли у Вас вообще такой метод (я точно не помню, но есть вероятность, что это моя личная доработка библиотеки, и этого метода может не быть в распространяемой версии)
3. Я бы не рассчитывал на помощь брокера в этом вопросе.

**Comment by dasmeer** [comment]
1 был бы признателен вам за скрипт, но попытался сам, глянете? (это в принципе мой первый)) 

[scritp to git.zip](https://github.com/finsight/QuikSharp/files/569197/scritp.to.git.zip)

2 метод недоступен (иначе бы не спрашивал)

**Comment by dasmeer** [comment]
ответ поддержки "Попробуйте указать код клиента без кавычек"

**Comment by Pr0phet1c** [comment]
Дайте свою почту, у меня не вставляется файл сюда.
Отправлю Вам несколько скорректированный скрипт. Скрипт рабочий, проверил только что.
Но лучше воспользуйтесь файлом "Test_open_position" (из того же вложения). Его гораздо проще читать. Для использования этого файла не забудьте в папку с этим скриптом также разархивировать библиотеку QL.lua

**Comment by dasmeer** [comment]
можете помочь с ошибкой "неверный код клиента"?

**Comment by dasmeer** [comment]
о, спасибо! присылайте на ss-ko@bk.ru

**Comment by dasmeer** [comment]
не сразу понял что скрипт нужно было поместить в папку, которая содержит папку socket, но результат исполнения тот же - "неверный код клиента", пробовал и без кавычек код использовать - не помогает. написал брокеру, не знаю даже, что еще посоветуете?

**Comment by buybackoff** [comment]
А номер счета верный?

**Comment by buybackoff** [comment]
https://forum.quik.ru/forum10/topic1218/

**Comment by dasmeer** [comment]
через луа действительно помогло использование "код//код".

в библиотеке нашел косяк из-за которого заявки не уходили:

transaction.CLIENT_CODE = transaction.TRANS_ID.Value.ToString();

код клиента зачем-то заменятся на ид, ид всегда = 4, если это закоментарить - заявки уходят, теперь проблема получить нормальный transaction_id, иначе он всегда 4...

**Comment by Pr0phet1c** [comment]
Прикольно. Я даже не замечал отсутствие CLIENT_CODE в методе CreateOrder, но что самое интересное - у меня все работает, без дополнительных доработок этого метода.  :)
Однако, не смотря на тот факт, что у меня проблем с заявками нет, выглядит реализованное решение как-то непонятно (для меня). 
ИД вроде как должен генерироваться случайно вот этой строкой:
            transaction.TRANS_ID = QuikService.GetNewUniqueId();

Попробуйте отдельно несколько раз вызвать указанный метод и посмотреть на возвращаемый результат.

**Comment by buybackoff** [comment]
Это написано в документации, с разделе "Формат tri файла".

> CLIENT_CODE 20-ти символьное составное поле, может содержать код клиента и текстовый комментарий с тем же разделителем, что и при вводе заявки вручную. Параметр используется только для групповых транзакций. Необязательный параметр 

Это поле, по которому можно отследить транзацию -> ордер -> сделку. Хотя по идее для этого больше подходит `brokerref`.

**Comment by buybackoff** [comment]
В первый раз слышу, что CLIENT_CODE на что-то реально влияет. Я думал, что если это необязательный параметр, который при этом всегда возвращается обратно в ордерах и сделках, то его удобно использовать для их объединения.

**Comment by dasmeer** [comment]
повторюсь, у меня два счета, поэтому влияет

**Comment by buybackoff** [comment]
два счета на одной площадке?

**Comment by dasmeer** [comment]
да, 2 на одной площадке: основной и ИИС

**Comment by dasmeer** [comment]
ид транзакции действительно = QuikService.GetNewUniqueId(); 
но это уникальный int в рамках сессии не знаю зачем он может пригодиться
мне важна ид заявки в квике, для этого переделал 

public async Task<**Transaction**> CreateOrder(Order order)
        {
            Transaction newOrderTransaction = new Transaction
            {
                ACTION = TransactionAction.NEW_ORDER,
                ACCOUNT = order.Account,
                CLIENT_CODE = order.ClientCode,
                CLASSCODE = order.ClassCode,
                SECCODE = order.SecCode,
                QUANTITY = order.Quantity,
                OPERATION = order.Operation == Operation.Buy ? TransactionOperation.B : TransactionOperation.S,
                PRICE = order.Price
            };

            await Quik.Trading.SendTransaction(newOrderTransaction).ConfigureAwait(false);

            **return newOrderTransaction;**
        }

вызываю 
var trans = await quik.Orders.CreateOrder(new Order()
            {
                ClassCode = "SPBFUT",
                SecCode = "SRZ6",
                Operation = Operation.Sell,
                Price = 15000,
                Quantity = 1, //in lots
                Account = "ХХХ",
                //ClientCode = "0000" - не нужен на forts
            }).ConfigureAwait(false);

//подписываюсь
            trans.OnOrder += Trans_OnOrder;

//получаю коррекный ИД

private static void Trans_OnOrder(Order order)
        {
            Console.WriteLine($"new order {order.**OrderNum**} {order.State}");
        }

**Comment by Pr0phet1c** [comment]
Я конечно не знаю, как оно работает с субсчетами, но я получаю ИД транзакции вот в этой строке:
res = await _quik.Orders.CreateOrder(order_new).ConfigureAwait(false);
Ну, а дальше (в моем случае) все значительно сложнее.
Т.к. мне приходится иметь дело с одновременной работой пары десятков роботов, то я храню в своем приложении всю таблицу ордеров и таблицу сделок, которые обновляются по своим колбэкам.
А сам ордер вытаскиваю уже из этой таблицы, и делаю с ним все что мне необходимо.

Правда, есть еще один нюанс: Я достаточно много самостоятельных изменений вносил в основную библиотеку, и возможно, делал что-то еще, что сейчас позволяет мне работать уже не задумываясь о подобных вопросах. Но сейчас я просто не вспомню всего, что делал больше полугода назад.

Кстати, работая с колбэком OnOrder (равно как и OnTrade) - помните, что на одно событие он приходит ТРИЖДЫ. Из-за этого некоторые Ваши решения могут срабатывать не совсем так как Вам виделось раньше.

**Comment by dasmeer** [comment]
ок, понял вас, спасибо за помощь, мне тоже не нравится то, что на CreateOrder у меня дважды срабатывает OnOrder, но объекты полученные в нем отличаются только 	
<LuaTimeStamp>1478596673662</LuaTimeStamp>
<LuaTimeStamp>1478596673663</LuaTimeStamp>
так что идентифицировать результат одного ордера небольшая проблема

1 не подскажете как создавать заявки SL, TP, SL+TP ?

2 еще бы как-то решить проблему того, чтобы отвалившийся коннект квика к серверу брокера автоматом восстанавливался, возможно это? (при подключении ввожу пароль сертификата)

**Comment by Pr0phet1c** [comment]
1. Сам такие заявки никогда не использовал (в роботах), но предполагаю, что с помощью параметра ACTION - в транзакции. Значение берем из перечисления TransactionAction, т.е. там где раньше использовали TransactionAction.NEW_ORDER, используем TransactionAction.NEW_STOP_ORDER. Плюс заполняем дополнительные параметры транзакции, участвующие в процессе оформления соответствующей заявки (STOPPRICE, STOP_ORDER_KIND, STOPPRICE2  и т.п.).
2. У меня такой проблемы нет, т.к. ввод пароля у моего брокера не используется. В моем случае, соединение восстанавливается автоматически (через настройки Квика). При потере коннекта у меня возникают проблемы другого характера, но в данном контексте это уже не важно.

**Comment by dasmeer** [comment]
есть ли у вас пример кода, как из квика получить открытый интерес (кол-во открытых позиций)? (данные для каждой свечи)

**Comment by Pr0phet1c** [comment]
у меня нет. И даже не представляю как эти данные оттуда достать.

**Comment by buybackoff** [comment]
@dasmeer  https://github.com/finsight/QuikSharp/blob/f42f4eb8b8223031dda7e5ce69d71d2ea39a743c/src/QuikSharp/DataStructures/AllTrade.cs#L101

**Comment by dasmeer** [comment]
ок, спасибо - попробую

**Comment by dasmeer** [comment]
1 OpenInteres получаю в реальном времени, а можно исторический как-то выцеплять с целью тестирования стратегий? на графиках в квике у меня он есть на фортс

2 как предотвратить любые сообщения библиотеки вроде "Conecting", "Conected", "Loading values that a client missed during disconnect" все закоментарил, но в квике они то и дело появляются!? (при запуске и остановке моей консоли тестирования) отключать все сообщения в квике впринципе пока бы не хотелось..

**Comment by dasmeer** [comment]
1 OpenInteres получаю в реальном времени, а можно исторический как-то выцеплять с целью тестирования стратегий? на графиках в квике у меня он есть на фортс

2 как предотвратить любые сообщения библиотеки вроде "Conecting", "Conected", "Loading values that a client missed during disconnect" все закоментарил, но в квике они то и дело появляются!? (при запуске и остановке моей консоли тестирования) отключать все сообщения в квике впринципе пока бы не хотелось..

**Comment by dasmeer** [comment]
1 есть ли пример того, как получить доску опционов?
2 по предыдущему посту ответов нет у экспертов?

**Comment by buybackoff** [comment]
Доску опционов недавно добавили, последний пулл реквест

**Comment by dasmeer** [comment]
есть ли способ корректной обработки отсутсвия данных?

получаю свечи по опциону, свечей по которому нет
quik.Candles.GetAllCandles(classCode, inst, interval).Result;

в итоге код и соединение виснет, даже если закрыть мою консоль, помогает только спот-старт луа скрипта в квике

пробовал прерывать таск по таймеру и получать свечи по следующему опциону, но даже если свечи есть, данные не возвращаются

как это обойти? есть ли какой-то метод сначала проверить наличие свечей для инструмента?

**Comment by buybackoff** [comment]
@Pr0phet1c  добавил пример. Оставлю открытым, чтобы было видно.

**Comment by buybackoff** [comment]
#196

**Comment by manter84** [comment]
Такая же проблема. Неверный код клиента при выставлении стоп, лимитных и рыночных ордеров. Брокер ВТБ. Сделал все что написано выше в C# (в lua не нашел где надо поставить //), но не помогло. Код клиента роботом определяется верно.  Куда копать уже не знаю. У меня есть два кода клиента у брокера для фонды и срочного рынка. Хочу съездить закрыть доступ на срочный рынок, так как не торгую на нем. Может кто подскажет куда  копать еще?
