### ISSUE TITLE
Вопрос по добавлению функционала

### ISSUE THREAD

**Issue by spvik** [finsight/QUIKSharp#78]
Добрый день, помогите разобраться, требуется вставить функцию в луа для формирование доски опционов, если я добавлю в qsfunctions.lua следующий код 
```
function qsfunctions.getOptionBoard(msg)
    local spl = split(msg.data, "|")
    local class_code, secCode = spl[1], spl[2]
	local result, err = Функция получения доски опционов
	if result then
		msg.data = result
	else
		log("OptionBoard returns nil", 3)
		msg.data = nil
	end
    return msg
end
```

Создам структуру в DataStructures , и к примеру в файл Tradingfunction.cs вставлю 
```
public async Task<Своя структура> GetOptionBoard(string classCode, string secCode)
        {
            var response = await QuikService.Send<Message<Своя структура>>(
                    (new Message<string>(classCode + "|" + secCode, "getGetOptionBoard"))).ConfigureAwait (false);
            
            return response.Data;
        }
```
Будет ли такой код работать, или еще где то надо, что то править

**Comment by buybackoff** [comment]
Для функций по идее этого должно хватить, сериализация там автоматическая, так как мы храним тип `Message<Своя структура>` для каждого запроса и при получении ответа можем десериализировать без дополнительных подсказок.

Для событий (callbacks) нужно довабить логику в двух местах:
https://github.com/finsight/QuikSharp/blob/master/src/QuikSharp/QuikService.cs#L402
и
https://github.com/finsight/QuikSharp/blob/f42f4eb8b8223031dda7e5ce69d71d2ea39a743c/src/QuikSharp/Serialization.cs#L225

**Comment by spvik** [comment]
Еще вопрос, в c# несилен, делаю по аналогии FuturesClientHolding он наследует интерфейс  IWithLuaTimeStamp, для чего он нужен, и нужен ли в моей функции, и если мне СаllBackи не нужны, можно не добавлять события, правильно ли я понял?

**Comment by buybackoff** [comment]
Точно не помню, для чего, мы задаем TimeStamp с миллисекундным разрешением
на стороне Луа, у Квика вроде где-то разрешение только секунда была. Для
функций события не нужны.



2016-11-07 9:41 GMT+03:00 spvik <notifications@github.com>:

**Comment by spvik** [comment]
Виктор, еще вопрос: Создал вот такую структуру:
`using Newtonsoft.Json;

namespace QuikSharp.DataStructures
{
    /// <summary>
    /// OptionBoard structure
    /// </summary>
    public class OptionBoard
    {
        /// <summary>
        /// Strike
        /// </summary>
        [JsonProperty("Strike")]
        public int Strike { get; set; }

        /// <summary>
        /// Code
        /// </summary>
        [JsonProperty("code")]
        public string Code { get; set; }

        /// <summary>
        /// Volatility
        /// </summary>
        [JsonProperty("Volatility")]
        public double Volatility { get; set; }

        /// <summary>
        /// OptionBase
        /// </summary>
        [JsonProperty("OPTIONBASE")]
        public string OPTIONBASE { get; set; }

        /// <summary>
        /// Offer
        /// </summary>
        [JsonProperty("OFFER")]
        public int OFFER { get; set; }

        /// <summary>
        /// Longname
        /// </summary>
        [JsonProperty("Longname")]
        public string Longname { get; set; }

        /// <summary>
        /// Name
        /// </summary>
        [JsonProperty("Name")]
        public string Name { get; set; }

        /// <summary>
        /// OptionType
        /// </summary>
        [JsonProperty("OPTIONTYPE")]
        public string OPTIONTYPE { get; set; }

        /// <summary>
        /// ShortName
        /// </summary>
        [JsonProperty("shortname")]
        public string Shortname { get; set; }

        /// <summary>
        /// Bid
        /// </summary>
        [JsonProperty("BID")]
        public int BID { get; set; }

        /// <summary>
        /// DaysToMatDate
        /// </summary>
        [JsonProperty("DAYS_TO_MAT_DATE")]
        public int DAYSTOMATDATE { get; set; }
    }
}
`
добавил в функцию 
`  public async Task<List<OptionBoard>> GetOptionBoard(string classCode,  string secCode)
        {
            var message = new Message<string>(classCode + "|" + secCode, "getOptionBoard");
            Message<List<OptionBoard>> response =
                await QuikService.Send<Message<List<OptionBoard>>>(message).ConfigureAwait(false);
            return response.Data;`
в луа добавил:
`--Моя Функция
function qsfunctions.getOptionBoard(msg)
    local spl = split(msg.data, "|")
    local classCode, secCode = spl[1], spl[2]
	local result, err = getOptions(classCode, secCode)
	if result then
		msg.data = result
	else
		log("Option board returns nil", 3)
		msg.data = nil
	end
    return msg
end

function getOptions(classCode,secCode)
	--classCode = "SPBOPT"
--BaseSecList="RIZ6"
local SecList = getClassSecurities(classCode) --все сразу
local t={}
local p={}
for sec in string.gmatch(SecList, "([^,]+)") do --перебираем опционы по очереди.
            local Optionbase=getParamEx(classCode,sec,"optionbase").param_image
            local Optiontype=getParamEx(classCode,sec,"optiontype").param_image
            if (string.find(secCode,Optionbase)~=nil) then
--				t[getParamEx(classCode,sec,"code").param_image]={}
                
                p={
                    ["code"]=getParamEx(classCode,sec,"code").param_image,
					["Name"]=getSecurityInfo(classCode,sec).name,
					["DAYS_TO_MAT_DATE"]=getParamEx(classCode,sec,"DAYS_TO_MAT_DATE").param_value+0,
					["BID"]=getParamEx(classCode,sec,"BID").param_value+0,
					["OFFER"]=getParamEx(classCode,sec,"OFFER").param_value+0,
					["OPTIONBASE"]=getParamEx(classCode,sec,"optionbase").param_image,
					["OPTIONTYPE"]=getParamEx(classCode,sec,"optiontype").param_image,
					["Longname"]=getParamEx(classCode,sec,"longname").param_image,
					["shortname"]=getParamEx(classCode,sec,"shortname").param_image,
					
					["Volatility"]=getParamEx(classCode,sec,"volatility").param_value+0,
					["Strike"]=getParamEx(classCode,sec,"strike").param_value+0
                    }

				

                        table.insert( t, p ) 
            end
              
end
return t
end`
Все нормально скомпилировалось, создаю новый проект, подключаю скомпилированую библиотеку; выдает ошибку 'OptionBoard' is a type, which is not valid in the given context. Class name is not valid at this point.

Можете посмотреть, что не так сделал, или подсказать где ошибся, заранее благодарен

**Comment by spvik** [comment]
странно часть кода пропадает
 public async Task<List<OptionBoard>> GetOptionBoard(string classCode,  string secCode)
        {
            var message = new Message<string>(classCode + "|" + secCode, "getOptionBoard");
            Message<List<OptionBoard>> response =
                await QuikService.Send<Message<List<OptionBoard>>>(message).ConfigureAwait(false);
            return response.Data;

**Comment by buybackoff** [comment]
Создайте PR. Функционал полезен, с PR смогу подробнее вникнуть. Так удаленно вслепую дебагить неудобно.

**Comment by buybackoff** [comment]
Наример вот: http://stackoverflow.com/questions/2278931/how-to-solve-is-a-type-which-is-not-valid-in-the-given-context-c

**Comment by spvik** [comment]
Первый раз у меня с PR, посмотрите все ли получилось

**Comment by buybackoff** [comment]
Спасибо! Все ОК. На какой строке выходит ошибка, есть ли StackTrace? Получается ли сериализовать в строку и обратно без отправки команды в Квик? (методы ToJSON/FromJSON)

**Comment by spvik** [comment]
Ошибка выходит когда пытаюсь написать простой код, еще даже до компиляции
```
static void Main(string[] args)
        {
            Quik q = new Quik();

            Console.WriteLine("isconn: "+q.Service.IsConnected().Result );

            
            List <OptionBoard> = q.Trading.GetOptionBoard("SPBOPT", "RIZ6");

            Console.ReadLine();
        }
```
 List <OptionBoard>  - подсвечивается и пишет ошибку, о которой ранее писал

**Comment by buybackoff** [comment]
Ну так это в той ссылке на SO и решено: List<OptionBoard> **myVariable** =
...

**Comment by spvik** [comment]
ну да, что то немного не доглядел. глупо получилось

**Comment by spvik** [comment]
Да, все работает, спасибо за помощь, думаю такой функционал, может еще кому пригодиться в вашей библиотеке

**Comment by spvik** [comment]
Еще было бы здорово CallBack прикрутить (аппетит приходит во время еды), но боюсь сам не смогу осилить такое (с событиями и делагами, туго), или вы более детально укажите, что и где подкрутить

**Comment by buybackoff** [comment]
Там же все copy-paste, по примеру того, что есть - все очень просто! Я
показал, где нужно добавить дополнительную логику. На стороне Луа колбеки
отличаются наличием поля `cmd`, по которому мы различаем их на стороне C#.

2016-11-07 16:59 GMT+03:00 spvik <notifications@github.com>:

**Comment by spvik** [comment]
Значит, я еще не могу понял логику исполнения.
Опишу как я это вижу: 
Все данные по опционом мы берем текущей таблицы параметров, 
при изменение данной таблицы на данные виды опционов, не на все, а только которые относятся к базовому активу, который мы задаем в функционале который я написал выше.
Должны отсылаться данные в c#, но на сколько я понимаю луа, там для этого есть CallBack OnParam,
Он у вас реализован, как к нему подключить мою функцию, пока не понимаю, если быть конкретнее в луа какой код написать, пока не могу придумать

**Comment by buybackoff** [comment]
#91
