### ISSUE TITLE
Ошибки после слияния

### ISSUE THREAD

**Issue by Pr0phet1c** [finsight/QuikSharp#80]
Попытался слить текущую основную ветку со своей, и получил ряд непонятных для меня ошибок в файле "QuikEvents.cs":

Студия ругается вот на этот кусок кода:

        /// <summary>
        /// Событие вызывается когда библиотека QuikSharp успешно подключилась к Quik'у
        /// </summary>
        public event InitHandler OnConnectedToQuik;
        internal void OnConnectedToQuikCall(int port) {
            OnConnectedToQuik?.Invoke(port);
            OnInit?.Invoke(port);
        }

        /// <summary>
		/// Событие вызывается когда библиотека QuikSharp была отключена от Quik'а
		/// </summary>
		public event VoidHandler OnDisconnectedFromQuik;
        internal void OnDisconnectedFromQuikCall() {
            OnDisconnectedFromQuik?.Invoke();
        }

        public event InitHandler OnInit;

        public event EventHandler OnAccountBalance;
        public event EventHandler OnAccountPosition;

        /// <summary>
        /// Функция вызывается терминалом QUIK при получении обезличенной сделки.
        /// </summary>
        public event AllTradeHandler OnAllTrade;
        internal void OnAllTradeCall(AllTrade allTrade) => OnAllTrade?.Invoke(allTrade);

        public event VoidHandler OnCleanUp;
        internal void OnCleanUpCall()
        {
            OnCleanUp?.Invoke();
        }

Подчеркнуты оказываются все части, где присутствует "?.Invoke".

В пояснениях к ошибке написано: Синтаксическая ошибка, требуется ":"

Не могу понять в чем конкретно проблема, и как ее исправить. Не поможете?

**Comment by buybackoff** [comment]
у вас наверное старая версия Visual Studio. Нужна поддержка C# 6

**Comment by Pr0phet1c** [comment]
Да, похоже на то. Обновил студию - проблема ушла. Спасибо.
