### ISSUE TITLE
OnParam?.Invoke(par) и другие...

### ISSUE THREAD

**Issue by Pr0phet1c** [finsight/QuikSharp#81]
После того, как я разобрался с изменением конструкции некоторых колбэков, то обратил внимание что в ряде случаев изменения типа "?.Invoke" были внесены, а в другом ряде - нет, хотя студия предлагает выполнить такие же изменения (например для: if (OnStopOrder != null) OnStopOrder(stopOrder);, if (OnTrade != null) OnTrade(trade);, if (OnTransReply != null) OnTransReply(reply); и т.п.)

Собственно, вопрос: Почему  такие изменения не были сделаны в других местах? Это связано с какими-то проблемами или банальная нехватка времени?

**Comment by buybackoff** [comment]
Последнее. Это только синтаксический сахар, где видел, там заменил. Возможно есть функция заменить везде.

**Comment by Pr0phet1c** [comment]
Понятно. Спасибо.
