### ISSUE TITLE
По поводу Pull Request

### ISSUE THREAD

**Issue by Pr0phet1c** [finsight/QUIKSharp#82]
В виду того, что раньше я никогда не работал над совместными проектами, у меня накопилось немалое количество дополнений, которые я вносил в базовый проект. PR не слал, а потому многие вещи остаются пока только в моей ветке. В последнее время попытки выполнить merge с основной веткой проекта, часто вызывают у меня массу сложностей (возможно, в силу недостатка знаний), в результате, слияние по факту приходится делать вручную, чтобы не "сломались" мои модификации. Хочется уже избавиться от этой проблемы максимально сократив количество различий между моей веткой и основной.

По сему ряд вопросов:
1. Правильно ли я понимаю, что если я сейчас попытаюсь прислать PR, то Вы увидите ВСЕ  дополнения, которые я внес в проект, за все время работы с ним?

2. Если мое предположение из первого вопроса верно, то возникает такая проблемка - Я могу попытаться вспомнить что именно я добавлял от себя, но скорее всего что-нибудь наверняка упущу (или забуду, что что-то добавил, или напишу, что добавил, а по факту окажется, что уже давно отменил свое добавление, заменив его "базовой" реализацией из вашей ветки). Отсюда два дополнительных вопроса:
   а) Стоит ли мне в при таком раскладе вообще посылать PR?
   б) Есть ли необходимость вспоминать максимальное количество изменений, которые я вносил, и вписывать их в описание? Или Вы и так увидите все, что я реализовал?

**Comment by buybackoff** [comment]
Если коммиты были более-менее гранулярными, то поможет cherry pick.
* Создаете новый бранч для каждого PR (или один большой мега бранч)
* Делаете cherry pick нужных коммитов из своего мастера в новый бранч
* Шлете PR из нового бранча (никогда не шлите PR из мастера)

Тогда получится разбить дополнения на отдельные куски. Я по старой привычке пользуюсь https://gitextensions.github.io/ и там все довольно просто.

**Comment by buybackoff** [comment]
По поводу 2-б: после каждого cherry pick можно отредактировать лишние изменения или добавить вручную дополнительные. Я предпочитаю затем каждый "черрипикнутый" коммит сразу коммитить в новую ветку, тогда будет видна история с оригинальным описанием коммита. Если сделать черри пик нескольких коммитов, то они объединяться в один.

**Comment by Pr0phet1c** [comment]
Спасибо. Буду осмысливать.

**Comment by Pr0phet1c** [comment]
В общем, не смог я разобраться с cherry pick и с тем как из отдельного бранча слать PR.
Что я сделал:
1. Скачал последнюю версию мастера с Вашей ветки (https://github.com/finsight/QuikSharp)
2. Исправил обнаруженные ошибки, чтобы проект компилировался. (см.: https://github.com/finsight/QuikSharp/issues/84)
3. Путем сравнения своего мастера с вашей веткой, через процедуру подготовки PR, добавил все свои доработки в скачанную версию проекта.
4. Записал все значимые изменения, которые были мной добавлены, и вписал их в описание.
5. Отправил PR из того, что у меня выгружено на GitHub.

Принимать или нет это PR - решайте сами. Все изменения пришлось сделать скопом. 
При формиро вании PR вылезли отличия, которые я не заводил (в основном это lua-файлы). Причина возникновения этих отличий мне неизвестна.
Честно говоря, я вообще не уверен, что правильно создал этот самый PR, т.к. делал его первый раз в жизни.

**Comment by buybackoff** [comment]
У меня предложение добавить Вас в котрибьютеры (право на запись напрямую),
чтобы проще было поддерживать одну версию в дальнейшем. PR ближе к вечеру
посмотрю и солью.

On Dec 20, 2016 3:18 PM, "Prophetic" <notifications@github.com> wrote:

В общем, не смог я разобраться с cherry pick и с тем как из отдельного
бранча слать PR.
Что я сделал:

   1. Скачал последнюю версию мастера с Вашей ветки (
   https://github.com/finsight/QuikSharp
   <https://github.com/finsight/QuikSharp>)
   2. Исправил обнаруженные ошибки, чтобы проект компилировался. (см.: #84
   <https://github.com/finsight/QuikSharp/issues/84>)
   3. Путем сравнения своего мастера с вашей веткой, через процедуру
   подготовки PR, добавил все свои доработки в скачанную версию проекта.
   4. Записал все значимые изменения, которые были мной добавлены, и вписал
   их в описание.
   5. Отправил PR из того, что у меня выгружено на GitHub.

Принимать или нет это PR - решайте сами. Все изменения пришлось сделать
скопом.
При формиро вании PR вылезли отличия, которые я не заводил (в основном это
lua-файлы). Причина возникновения этих отличий мне неизвестна.
Честно говоря, я вообще не уверен, что правильно создал этот самый PR, т.к.
делал его первый раз в жизни.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/finsight/QuikSharp/issues/82#issuecomment-268229542>,
or mute the thread

**Comment by Pr0phet1c** [comment]
Страшное какое-то слово (контрибьютер). Я даже и не знаю стоит ли это делать. На всякий случай напомню, что я не являюсь профессиональным программистом, и C# изучаю немногим больше года. Как бы я чего не напортачил в роли контрибьютера.

**Comment by buybackoff** [comment]
Это же Гит, вся история сохраняется, все можно исправить :)

**Comment by buybackoff** [comment]
Вообще правильное слово коллаборатор (или коллаборационист:) ), Вы уже
контрибьютер.

**Comment by Pr0phet1c** [comment]
Что ж, спасибо за доверие. Надеюсь, это пойдет на пользу проекту.

**Comment by buybackoff** [comment]
Добавил в коллабораторы. Предлагаю в дальнейшем сделать ветку dev и в ней творить что угодно, а мастер поддерживать в рабочем стабильном виде, чтобы компилировалось с чистого клона и тесты запускались. Перидически сливать из dev проверенный новый функционал, если там еще есть что добавлять после Вашего PR.

**Comment by Pr0phet1c** [comment]
Увидел Ваши вопросы в почтовом уведомлении, но не могу найти их на GitHub, поэтому отвечу в этой ветке.
1. По поводу файлов Lua в папке Profiler. Эти файлы лежат в указанной папке в скачиваемом архиве. Он у меня сохранился со вчерашнего дня и я только что проверил этот факт.
2. Если речь о лишних отступах типа "ConfigureAwait (false)", то эти отступы сделаны не мной, а исправлять я их не стал чтобы сократить количество изменений для своего первого PR. Плюс к этому, когда я начинаю "причесывать" какие-то куски кода, то студия автоматом меняет компоновку текста, что сбивает используемый Вами стиль компоновки, и как следствие увеличивает количество сравнительных отличий. Для меня конечно привычней форматирование, которое предлагает студия, но "ломать" чужое не люблю.
3. По идее следов слияния быть вообще не должно. Как я уже писал выше, я взял "чистый" дистрибутив проекта и добавил туда свои доработки. Однако, когда я заново собранный проект переносил в локальную папку, которая у меня считается репозиторием, то в этой папке я не стал трогать такие вещи как ".git", ".gitattributes" и ".gitignore" опасаясь, что удаление этих папок/файлов сделает невозможным нормальную синхронизацию и отправку PR. Возможно данные в этих файлах и папках как-то повлияли на появления так называемых следов слияния.

И "да", у меня идет реальная торговля с использованием этой библиотеки. Правда, сейчас на срочке роботы отключены (до нового года), а на фондовой секции сделки среднесрочные и реальные движения редки. Однако, в своем алго-приводе, я специально вчера проверил работу с заявками на всякий случай.

4. Про "JsonProperty" - постараюсь посмотреть и внести необходимые изменения.
5. Каюсь, описание функции делал самостоятельно, а не использовал ее описание из Lua
6. Про изменения в QuikSharp.lua - опять же, это не мои изменения вот так выглядит этот кусок кода в скачиваемом архиве:
function is_quik()
    if getScriptPath then return true else return false end
end
script_path = "."
if is_quik() then
    script_path = getScriptPath()
	package.loadlib(getScriptPath()  .. "\\clibs\\lua51.dll", "main")
end
package.path = package.path .. ";" .. script_path .. "\\?.lua;" .. script_path .. "\\?.luac"..";"..".\\?.lua;"..".\\?.luac"
package.cpath = package.cpath .. ";" .. script_path .. '\\clibs\\?.dll'..";"..'.\\clibs\\?.dll'

7. Где-то еще был вопрос по работоспособность тестов: Скажем так - тесты я запускал всего пару раз, когда только учился пользоваться библиотекой. после того, как я написал своего первого полноценного робота на основе QS, к тестам я больше не возвращался. Но, как я уже писал - функционал, реализованный не мной я не ломал. Другое дело, что часть этого функционала мной не используется и на сколько он работоспособен я могу не знать (как пример - доска опционов).

**Comment by Pr0phet1c** [comment]
Раз уж так случилось, что мой PR был принят, то у меня есть еще кое что.
Как Вы наверное заметили, с завидной периодичностью тут появляются просьбы предоставить какие-нибудь примеры использования библиотеки. Тестами пользоваться умеют не все, да и не самый наглядный инструмент на мой взгляд. Поэтому, я написал специальное демонстрационное приложение на WinForm. Но т.к. нормально работать оно могло только с учетом "моих" доработок библиотеки, раньше я его выложить не мог. Собственно вопрос: Как лучше поступить с проектом этой демки? Высылать по запросу потенциальных пользователей, в виде отдельного проекта, или подключить его к проекту QuikSharp? 
Могу предварительно выслать его Вам куда-нибудь для ознакомления.

**Comment by buybackoff** [comment]
Примеры всегда хорошо! Если у Вас есть время выложить, думаю все будут
довольны!

2016-12-21 9:52 GMT+03:00 Prophetic <notifications@github.com>:

**Comment by Pr0phet1c** [comment]
Вопрос в том, куда выложить?

**Comment by buybackoff** [comment]
Папка Examples в корне, например.

**Comment by Pr0phet1c** [comment]
Вы имеете в виду папку в корне "решения" (в обозревателе решений), или речь просто о создании подпапки в проводнике?
Прошу прощения, просто пока не очень понимаю, как правильно все сделать.

**Comment by buybackoff** [comment]
Например так: https://github.com/aspnet/SignalR
Там папка samples на уровне папки src, в самом решении примеры тоже
присутствуют в папке решения.

2016-12-21 13:25 GMT+03:00 Prophetic <notifications@github.com>:

**Comment by Pr0phet1c** [comment]
Спасибо. Вроде сделал. Выгрузил и отправил PR, но мне теперь сразу предлагаю выполнить слияние, а я боюсь :)

Может посмотрите на досуге, все ли я правильно сделал?

**Comment by buybackoff** [comment]
Спасибо за пример! Все ОК.

**Comment by buybackoff** [comment]
Моих коммитов уже только 35%, проект стал действительно общественным. Если бы еще кто-нибудь пост на Смарт-Лабе написал с новым появившимся примером, и с рассказом, что тут действительно все открыто и всех пускают с любыми идеями и измененими, думаю еще больше людей бы стало пользоваться, добавлять фунционал и исправлять ошибки 😄

Я уже два раза писал, в принципе 35% - частично результат как раз этого. Но если кто-то другой напишет, доверия будет еще больше.  @nubick написал в трех частях тут: https://nubick.ru/2016/06/30/trading-robots-step1/

@Pr0phet1c  нет случайно желания и времени рассказать о своем опыте использования?

**Comment by Pr0phet1c** [comment]
Да, хорошо. Постараюсь в ближайшее время разместить пост о недавнем обновлении.

**Comment by sm00vik** [comment]
Добрый день. Можно слать PR на reflector или на dev? Спасибо.

**Comment by buybackoff** [comment]
@sm00vik  у нас мастер основная ветка
