### ISSUE TITLE
Не могу подключиться к quik

### ISSUE THREAD

**Issue by let4be** [finsight/QUIKSharp#83]
An unhandled exception of type 'System.TypeInitializationException' occurred in mscorlib.dll
Additional information: The type initializer for 'QuikSharp.EsentStorage' threw an exception.

какая то ошибка на стадии инициализации... луа скрипт работает
net 4.5, visual studio 2015 community

**Comment by pantov** [comment]
Пример зависает на Подключаемся к терминалу Quik...
запущен или нет QuikSharp.lua  значения не имеет.
Чтото-не так с дллками, трудно понять.
Может подскажете, что где проверить?
Спасибо.

**Comment by Pr0phet1c** [comment]
Попробуйте перезапустить Lua-скрипт в терминале, и убедитесь, что кроме этой демки больше никакое приложение, с использованием этой библиотеки, не подключается к терминалу.

И еще, когда запускаете скрипт в квике, должны всплыть три сообщения:
 - о том что скрипт запущен из такой-то папки
- о том, что стартовала функция Main
- и "Connecting..."

В тот момент, когда приложение конектится к квику, должно появится еще одно сообщение: "Connected!" 
Вы наблюдаете эти сообщения?

**Comment by Tolstij** [comment]
Доброго времени суток!
Я начинающий программист и трейдер. Пробую запустить QuikSharpDemo с GitHub'а.
1. В проекте пришлось делать ссылку на класс QuikSharp из этого решения, а не на поставляемую библиотеку из NuGet, т.к. отсутствует класс QuikSharp.DataStructures.PortfolioInfoEx.
2. Коннекта нет. В Quik'е скрипт запущен и сообщения :
 о том что скрипт запущен из такой-то папки
о том, что стартовала функция Main
и "Connecting..."
выдает. 
В чем может быть проблема?

**Comment by Pr0phet1c** [comment]
Если демка зависает на этапе подключения, то один человек давал вот такой совет:
------------
Если у Вас к библиотеке квикшарп подключена Newtonsoft.Json версии 9.01, то скорее всего из за нее, откатите на 8.03. У квик шарпа есть проблемы с более новыми версиями Json.
------------
Я с такой проблемой не сталкивался (у меня например стоит 9.0.0.0)

**Comment by Tolstij** [comment]
Она не зависает. Она просто не подключается. 
пишет "Ошибка инициализации объекта Quik." 
Возможно я не правильно описал ошибку

**Comment by Pr0phet1c** [comment]
Значит ошибка проявляется вот на этом участке кода:
            try
            {
                textBoxLogsWindow.AppendText("Подключаемся к терминалу Quik..." + Environment.NewLine);
                _quik = new Quik(Quik.DefaultPort, new InMemoryStorage());    // инициализируем объект Quik
                //_quik = new Quik(34136, new InMemoryStorage());    // отладочное подключение
            }
            catch
            {
                textBoxLogsWindow.AppendText("Ошибка инициализации объекта Quik..." + Environment.NewLine);
            }

Что по факту означает, что у Вас возникает ошибка на строке:
                _quik = new Quik(Quik.DefaultPort, new InMemoryStorage());    // инициализируем объект Quik

Это очень странно. У вас точно все процессы компиляции без ошибок прошли?
Можете попробовать эту строку вот таком виде реализовать:
_quik = new Quik();

**Comment by buybackoff** [comment]
А порт правильный? Тут указан 34136, в проекте по умолчанию 34130

**Comment by Tolstij** [comment]
Проблема решена. Заработало. Спасибо!
