### ISSUE TITLE
Не могу скомпиллировать после git clone

### ISSUE THREAD

**Issue by let4be** [finsight/QuikSharp#84]
Error	CS0246	The type or namespace name 'OptionBoard' could not be found (are you missing a using directive or an assembly reference?)	QuikSharp	C:\stock\QuikSharp\src\QuikSharp\TradingFunctions\TradingFunctions.cs	71	Active

**Comment by let4be** [comment]
master ветка сломана, d5f313fe4868f191171c3f16d374f07ef1682a4c компиллится

**Comment by Pr0phet1c** [comment]
Кажется, у меня было нечто похожее после слияния, но я грешил на проблемы со своей стороны.
Попробуйте проверить два момента:
1. Есть ли у вас в наличии файл OptionBoard.cs?
2. Добавлен ли (подключен) этот класс в сам проект?

**Comment by Pr0phet1c** [comment]
Если все еще не получилось скомпилировать проект:
1. OptionBoard.cs - не подключен к проекту. Необходимо подключить (в папку DataStructures)
2. Необходимо зайти в  "Управление пакетами NuGet для решения..." и выполнить обновление пакетов: Esent.Collections, Esent.Interop, Esent.Isam, Newtonsoft.Json

После этих действий у меня проект полностью скомпилировался без ошибок.

**Comment by buybackoff** [comment]
OMG, разве Esent не выпилили из проекта!?

**Comment by Pr0phet1c** [comment]
Не мне об этом судить. Сборки, что у меня, что в вашей ветке остались подключены к проекту (или это только я так вижу), я и не трогаю их.

**Comment by buybackoff** [comment]
После недавних изменеий от @Pr0phet1c  должно все работать.
