### ISSUE TITLE
Паузы в OnTransReply

### ISSUE THREAD

**Issue by buybackoff** [finsight/QuikSharp#89]
http://smart-lab.ru/blog/371302.php#comment6662037
* [x] Добавить ArrayPool к JSON.NET
* [x] Изменить настройки GC на server concurrent в app.config
* [x] ~~(?) Входить в no gc region во время ожидания ответа на транзакции~~ SustainedLowLatency option instead

**Comment by buybackoff** [comment]
Этот коммит не протестирован, @Pr0phet1c можете пожалуйста проверить, что он работает? У меня сейчас нету рабочего Квика под рукой.

**Comment by buybackoff** [comment]
Ping/Pong тесты работают OK

**Comment by buybackoff** [comment]
Еще можно использовать RecyclableMemyrStream, читать сообщения как байты и десериализовать напрямую из потока, но в ближайшее время я это делать не буду. Пример есть [тут](https://github.com/buybackoff/SignalW/blob/master/src/SignalW.Client/Serialization.cs#L90). 

GC статистика показывает, что основной мусорщик - JSON.NET, с этим ничего не поделать. Добавление ArrayPool должно были сильно снизить объем мусора.

![image](https://cloud.githubusercontent.com/assets/489852/21545356/26eec81a-cde8-11e6-930d-1d9e2ad9044d.png)

![image](https://cloud.githubusercontent.com/assets/489852/21545346/0ef6df90-cde8-11e6-928f-14c385f350a4.png)

**Comment by buybackoff** [comment]
Третья строчка - сильно много некешированных лямбд. Но это мелочи и gen0.

**Comment by Pr0phet1c** [comment]
Попытка провести тест "на скорую руку" (скачал в отдельную папку и скомпилил, а потом обновленные длл-ки тупо подсунул своему роботу) ошибок не выявила. Более того, чисто визуально показалось, что инициализация параметров по списку инструментов (19 наименований) прошла раза в два быстрее, чем это происходило обычно. Позже буду мержить со своей рабочей веткой и запускать все с полным перекомпилированием проектов.

**Comment by Pr0phet1c** [comment]
В общем, перекомпилил все свои проекты - работает.

**Comment by buybackoff** [comment]
Супер, спасибо!
