### ISSUE TITLE
Нереализованный функционал

### ISSUE THREAD

**Issue by Pr0phet1c** [finsight/QUIKSharp#91]
А кто-нибудь знает, остались ли какие-либо функции, доступные в QLua, и нереализованные в QS?

**Comment by buybackoff** [comment]
Везде, где `break`, нет реализованного колбэка: https://github.com/finsight/QuikSharp/blob/ff44c25705afc5c1bfb1917557cee544a3cd315b/src/QuikSharp/Serialization.cs#L258

**Comment by Pr0phet1c** [comment]
ОК. Попробуем реализовать.

**Comment by sm00vik** [comment]
Никак не получается подружиться с гитом :) Выложу сюда. Если будет кому интересно, то можно использовать.
=================================================================
-- Выводит на график метку
function qsfunctions.addLabel(msg)
	local spl = split(msg.data, "|")
    local price, curdate, curtime, qty, path, id, algmnt, bgnd = spl[1], spl[2], spl[3], spl[4], spl[5], spl[6], spl[7], spl[8]
 label = {
    TEXT = "",
    IMAGE_PATH = path,
    ALIGNMENT = algmnt,
    YVALUE = tostring(price),
    DATE = tostring(curdate),
    TIME = tostring(curtime),
    R = 255,
    G = 255,
    B = 255,
    TRANSPARENCY = 0,
    TRANSPARENT_BACKGROUND = bgnd,
    FONT_FACE_NAME = "Arial",
    FONT_HEIGHT = "15",
    HINT = " " .. tostring(price) .. "  " .. tostring(qty)
  }
	local res = AddLabel(id, label)
	msg.data = res
    return msg
end

-- Удаляем выбранную метку
function qsfunctions.delLabel(msg)
	local spl = split(msg.data, "|")
    local tag, id = spl[1], spl[2] 
 	DelLabel(tag, tonumber(id))
	msg.data = ""
    return msg
end

-- Удаляем все метки с графика
function qsfunctions.delAllLabels(msg)
	local spl = split(msg.data, "|")
	local id = spl[1]
	DelAllLabels(id)
	msg.data = ""
    return msg
end

================================================================
/// <summary>
        /// Выводит метку на график
        /// </summary>
        /// <param name="price"></param>
        /// <param name="curDate"></param>
        /// <param name="curTime"></param>
        /// <param name="hint"></param>
        /// <param name="path"></param>
        /// <param name="tag"></param>
        /// <param name="alignment">LEFT, RIGHT, TOP, BOTTOM</param>
        /// <param name="backgnd"> On = 1, Off = 0</param>
        /// <returns>Возвращает Id метки</returns>
        Task<double> AddLabel(double price, string curDate, string curTime, string hint, string path, string tag, string alignment, double backgnd);

        /// <summary>
        /// Удаляет метку по ее Id
        /// </summary>
        /// <param name="tag"></param>
        /// <param name="id">Id метки</param>
        /// <returns></returns>
        Task<bool> DelLabel(string tag, double id);

        /// <summary>
        /// Удаляет все метки с графика
        /// </summary>
        /// <param name="tag"></param>
        /// <returns></returns>
        Task<bool> DelAllLabels(string tag);

public async Task<double> AddLabel(double price, string curDate, string curTime, string hint, string path, string tag, string alignment, double backgnd)
        {
            var response = await QuikService.Send<Message<double>>(
                (new Message<string>(price + "|" + curDate + "|" + curTime + "|" + hint + "|" + path + "|" + tag + "|" + alignment + "|" + backgnd, "addLabel"))).ConfigureAwait(false);
            return response.Data;
        }

        public async Task<bool> DelLabel(string tag, double id)
        {
            await QuikService.Send<Message<string>>(
                (new Message<string>(tag + "|" + id, "delLabel"))).ConfigureAwait(false);
            return true;
        }

        public async Task<bool> DelAllLabels(string tag)
        {
            await QuikService.Send<Message<string>>(
                (new Message<string>(tag, "delAllLabels"))).ConfigureAwait(false);
            return true;
        }
==================================================================
         [Test]
        public void addLabel()
        {
            var res = _q.Service.AddLabel(61000, "20170105", "100000", "1", "C:\\ClassesC\\Labels\\buy.bmp", "si", "BOTTOM", 0);
            Console.WriteLine("AddLabel: "
                    + String.Join(",", Convert.ToString(res.Result)));
        }

        [Test]
        public void delLabel()
        {
           double tagId = 13;
            var res = _q.Service.DelLabel("si", tagId);

            Console.WriteLine("delLabel: "
                    + String.Join(",", Convert.ToString(res.Result)));
        }

        [Test]
        public void delAllLabels()
        {
            var res = _q.Service.DelAllLabels("si").Result;

            Console.WriteLine("delAllLabels: "
                  + String.Join(",", Convert.ToString(res)));
        }

**Comment by Pr0phet1c** [comment]
sm00vik, Думаю эти функции могут быть полезными для кого-то. Если автор проекта не против - то я постараюсь их добавить, как только руки дойдут. Только мне бы еще этот bmp-файлик как-то заполучить...

**Comment by buybackoff** [comment]
Это встроенные функции для работы с графиками, я только за.

**Comment by Pr0phet1c** [comment]
Добавил:
(https://github.com/Pr0phet1c/QuikSharp/commit/d9c213f408764eee48b3e0dc1ea517a65201007a)
Но пока не тестировал.
sm00vik, можете скачать "мою" ветку и протестировать у себя? Если у Вас все заработает, то солью с мастером.

**Comment by sm00vik** [comment]
Хорошо, попробую.

**Comment by sm00vik** [comment]
Все нормально, работает. Я последнее время добавляю к тестам остановку сервиса _q.StopService(); Без этой команды nunit выдает ошибку (хотя сам тест проходит исправно).
Ссылка на картинки -
https://cloud.mail.ru/public/5TQ6/QtKb7hKRh
Спасибо.

**Comment by sm00vik** [comment]
Набросал примерчик с AutoLogin в Quik. Делаю PR. Выбрасывает с ошибкой идентификацией. У меня прав нет?

**Comment by buybackoff** [comment]
@sm00vik  для PR не нужны права, но нужно коммитить в свой форк и потом создавать PR. Вы как делаете?

**Comment by sm00vik** [comment]
Сделал new branch. Далее  Commit в свой branch. Далее PR to master. -> validation faild. Нет прав.

**Comment by buybackoff** [comment]
Вы наверное делаете Push со своего компьютера, а не Pull Request - я не вижу никаких свежих коммитов тут: https://github.com/sm00vik/QuikSharp/tree/master

**Comment by sm00vik** [comment]
Да, с компьютера - Github. Там есть PR.

**Comment by buybackoff** [comment]
Попробуйте запушить к себе в репо и сделать PR через сайт. Я не пользовался
клиентом ГХ и не могу дельно посоветовать в чем причина.

**Comment by sm00vik** [comment]
Хорошо. Спасибо.
