### ISSUE TITLE
Изменения в QLUA

### ISSUE THREAD

**Issue by buybackoff** [finsight/QUIKSharp#94]
На этой странице https://arqatech.com/ru/support/files/quik-workstation/ есть история изменения всех версий. Стоит пройтись по всем упоминаниям Lua и проверить, все ли правильно тут.

Я писал эту библиотеку на основе 6.17, потом кто-то что-то добавлял/фиксил, но выборочно.

**Comment by Pr0phet1c** [comment]
Пока добрался только до выписки изменений, которые стоит проверить:

Версия 7.0, 07.10.2015
В Таблицу заявок добавлены параметры: 
«Стоп-заявка» с номером стоп-заявки, «породившей» эту заявку, 
«Средневзвешенная цена приобретения», 
«Средняя цена исполнения заявки», 
«UID снявшего заявку»,
«Время окончания срока» со временем действия заявок типа «До времени».

В Таблицу сделок добавлены: 
«Валюта расчетов» с валютой расчетов сделки на Московской Бирже;
«ID транзакции» — TRANS_ID заявки, породившей сделку.

В Таблицу лимитов по бумагам добавлен параметр «Заблокировано на покупку», отображающий сумму денег, заблокированную под исполнение всех заявок на покупку по данной бумаге.
В Таблицу транзакций добавлен параметр «Биржевой номер» с биржевым номером заявки.
Для инструментов Срочного рынка Московской Биржи в «Таблице обезличенных сделок» добавлена трансляция открытого интереса (столбец «Открытый интерес»).
Версия 7.1, 12.02.2016
В Lua добавлены функции ParamRequest, CancelParamRequest и getParamEx2. Они позволяют управлять получением биржевых параметров без добавления этих параметров в открытую Таблицу текущих торгов. Описание приведено в пп. 3.12.2, 3.18 Руководства пользователя Интерпретатора языка Lua.
Версия 7.2, 11.04.2016
Средствами QLUA с помощью параметра «visible» в функциях «getItem», 4. «SearchItems» и «OnOrder» добавлена возможность получить из таблицы «Orders» видимое количество лотов айсберг-заявок.
Версия 7.4, 02.09.2016
Получение параметров таблицы «Обязательства и требования по активам»: 
«planned_covered» – «Плановая Т+», 
«firm_use» – «Тип раздела». 
См. п. 5.5 Руководства пользователя Интерпретатора языка Lua.

Доступ к таблице «Обязательства и требования по активам» для валютного рынка. См. п. 5.6 Руководства пользователя Интерпретатора языка Lua.
Версия 7.5, 05.10.2016
В Таблице котировок появилась возможность отображать дополнительную информацию об инструменте:
Цена последней сделки;
К закрытию пред.дня;
К закрытию пред.дня, в %;
К оценке пред.дня;
К оценке пред.дня, в %;
Расчетная цена;
Средневзвешенная цена;
Спред;
Суммарный спрос/предложение;
Заявки на покупку/продажу;
Свои заявки/стоп-заявки.
Более подробно см. в п. 3.4 Раздела 3 Руководства пользователя QUIK.
Версия 7.6, 05.12.2016
Поддержана работа с дополнительными ограничениями для контроля параметров подаваемых заявок, настроенными на стороне серверной части QUIK. Пользователи, обладающие специальным правом, будут предупреждены о нарушении ограничений, но смогут их проигнорировать и выставить заявку. При нарушении дополнительного ограничения в Рабочем месте появляется предупреждающее сообщение, содержащее список нарушенных ограничений с предложением отклонить подаваемую заявку, проигнорировать нарушение ограничений и подать заявку или отложить решение по данной заявке с возможностью вернуться к подаче заявки позже.

В результате поддержки данного функционала изменения коснулись Таблицы транзакций.
В таблицу добавлен параметр «Исходный номер» с числовым идентификатором нарушившей ограничение транзакции. 
Добавлены новые значения параметра «Статус»:
«14» — транзакция не прошла контроль дополнительных ограничений»;
«15» — транзакция принята после нарушения дополнительных ограничений;
«16» — транзакция отменена пользователем в ходе проверки дополнительных ограничений».

Дальше двинуться в данное время не получается.
