### ISSUE TITLE
Недостающие колбэки

### ISSUE THREAD

**Issue by Pr0phet1c** [finsight/QuikSharp#96]
Добавил реализацию недостающих колбэков, за исключением OnNegDeal и OnNegTrade (боюсь, моих знаний для их реализации может не хватить).
Однако, тестирование в реальной работе пока провести не могу, и не знаю когда получится.
Сливать с мастер-веткой, или будем ждать тестирования?

**Comment by buybackoff** [comment]
Шлите PR, но без хотя бы ручного тестирования ("на моей машине работает") пока не сливайте.

**Comment by buybackoff** [comment]
Хотя, если без них жили, они наверное не настолько важны... Думаю можно запросто слить, вряд ли там может быть какая-либо проблема.

**Comment by Pr0phet1c** [comment]
Да, в общем-то они все оказались однообразны. При вызове передают таблицу с параметрами. Все недостающие таблицы под них я заводил вручную (из справочника по QLua). Там теоретически могут быть потенциальные орфографические ошибки, но на работоспособность других функций не повлияет. Тогда сливаю.

**Comment by buybackoff** [comment]
Уже наверное можно версию 1.0-beta публиковать в NuGet, практически все методы реализованы 😄 Нужно разобраться с #7 и логикой объединения транзакций/заявок/сделок по ID и/или группам. Не уверен, что сейчас это реализвано как следует, скорее костыль. Хотя тут недавно поднимали issue и что-то фиксили.

**Comment by Pr0phet1c** [comment]
По поводу https://github.com/finsight/QuikSharp/issues/7 ничего не могу сказать, я в таком виде никогда даже не пытался использовать колбэки. Для меня, отправка заявки и обработка изменений в журнале заявок - совершенно не связанные между собой задачи. Звучит это конечно странно, но я не ошибся, все так и есть (сейчас работаю над демо-роботом, там OnOrder вообще не используется например).
А вот с объединением я что-то не улавливаю суть задачи. Если для сделок это можно применить (объединив сделки по номеру заявки, с расчетом средней цены исполнения заявки), что тоже не всем нужно, то зачем объединять остальное я не понимаю. Может попробуете пояснить подробнее?

**Comment by buybackoff** [comment]
Надо просто сделать ревью того, как работает сейчас. У меня уже на горизонте маячит реализация #40, когда подберусь к этому буду смотреть (не раньше, чем через месяц). NuGet в текущем виде пораньше обновлю.
